/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: ModuleUICategoryDescription.idl,v $
 *
 *  $Revision: 1.5 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 08:22:12 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/

#ifndef __com_sun_star_ui_ModuleUICommandDescription_idl__
#define __com_sun_star_ui_ModuleUICommandDescription_idl__

#ifndef __com_sun_star_container_XNameAccess_idl__
#include <com/sun/star/container/XNameAccess.idl>
#endif

//=============================================================================

module com { module sun { module star { module ui {

//=============================================================================

/** a service which provides information about the user interface command
    categories of a single module.

    <p>
    Every OpenOffice.org module has an amount of commands that can be used by
    user interface elements. This service provides access to the user interface
    commands that are part of a single OpenOffice.org module, like Writer
    or Calc.
    </p>

    @since OOo 2.0.0
*/

service ModuleUICategoryDescription
{
    /** provides access to user interface command categories of an installed
        module.

        <p>
        An implementation must provide a language dependent string which
        can be used by a UI to display the category name.
        The key to a user interface command category depends on the specific
        implementation. OpenOffice.org uses a pre-defined number of
        identifiers defined in <type scope="::com::sun:star::frame">
        CommandGroup</type>.
        </p>

        @see ::com::sun::star::frame::ModuleManager
        @see ::com::sun::star::frame::CommandGroup
    */

    interface com::sun::star::container::XNameAccess;
};

}; }; }; };

#endif
