
 /*
  * copyright text to see as text in the soffice binary
  *
  */



extern const char copyright_text_1[] = "Copyright © 2002 Sun Microsystems, Inc., 901 San Antonio Road, Palo Alto, California 94303, U.S.A. All rights reserved.";
extern const char copyright_text_2[] = "Sun Microsystems, Inc. has intellectual property rights relating to technology embodied in the product that is described in this document. In particular, and without limitation, these intellectual property rights may include one or more of the U.S. patents listed at http://www.sun.com/patents and one or more additional patents or pending patent applications in the U.S. and in other countries.";
extern const char copyright_text_3[] = "This document and the product to which it pertains are distributed under licenses restricting their use, copying, distribution, and decompilation. No part of the product or of this document may be reproduced in any form by any means without prior written authorization of Sun and its licensors, if any.";
extern const char copyright_text_4[] = "Third-party software, including font technology, is copyrighted and licensed from Sun suppliers.";
extern const char copyright_text_5[] = "This product is based in part on the work of the Independent JPEG Group, The FreeType Project and the Catharon Typography Project.";
extern const char copyright_text_6[] = "Portions Copyright 2000 SuSE, Inc. Word for Word Copyright © 1996 Inso Corp. International CorrectSpell spelling correction system Copyright © 1995 by Lernout & Hauspie Speech Products N.V. All rights reserved.";
extern const char copyright_text_7[] = "Source code for portions of this product are available under the Mozilla Public License at the following sites: http://www.mozilla.org/, http://www.jclark.com/, and http://www.gingerall.com.";
extern const char copyright_text_8[] = "Sun, Sun Microsystems, the Sun logo, Java, Solaris, StarOffice, the Butterfly logo, the Solaris logo, and the StarOffice logo are trademarks or registered trademarks of Sun Microsystems, Inc. in the U.S. and other countries.";
extern const char copyright_text_9[] = "UNIX is a registered trademark in the U.S. and in other countries, exclusively licensed through X/Open Company, Ltd. Screen Beans and Screen Beans clipart characters are registered trademarks of A Bit Better Corporation. International CorrectSpell is a trademark of Lernout & Hauspie Speech Products N.V.";
extern const char copyright_text_10[] = "International CorrectSpell Swedish, Russian, Norwegian, English, Dutch, and Danish correction systems Copyright © 1995 by Lernout & Hauspie Speech Products N.V. All rights reserved. Reproduction or disassembly of embodied algorithms or database prohibited.";
extern const char copyright_text_11[] = "International CorrectSpell Spanish and French correction systems Copyright © 1995 by Lernout & Hauspie Speech Products N.V. All rights reserved. Adapted from word list supplied by Librairie Larousse. Reproduction or disassembly of embodied algorithms or database prohibited.";
extern const char copyright_text_12[] = "International CorrectSpell Australian English correction system Copyright © 1995 by Lernout & Hauspie Speech Products N.V. All rights reserved. Based upon The Macquarie Dictionary, Second Revised Edition Copyright © Macquarie University NSW. Reproduction or disassembly of embodied algorithms or database prohibited.";
extern const char copyright_text_13[] = "International CorrectSpell Catalan correction system Copyright © 1995 by Lernout & Hauspie Speech Products N.V. All rights reserved. Adapted from Catalan word list Copyright © 1992 Universitat de Barcelona. Reproduction or disassembly of embodied algorithms or database prohibited.";
extern const char copyright_text_14[] = "International CorrectSpell Czech correction system Copyright © 1995 by Lernout & Hauspie Speech Products N.V. All rights reserved. Adapted from word list supplied by Jan Hajic. Reproduction or disassembly of embodied algorithms or database prohibited.";
extern const char copyright_text_15[] = "International CorrectSpell Finnish correction system Copyright © 1995 by Lernout & Hauspie Speech Products N.V. All rights reserved. Adapted from word list supplied by University of Helsinki Institute for Finnish Language and Dr. Kolbjorn Heggstad. Reproduction or disassembly of embodied algorithms or database prohibited.";
extern const char copyright_text_16[] = "International CorrectSpell German correction system Copyright © 1995 by Lernout & Hauspie Speech Products N.V. All rights reserved. Adapted from word list supplied by Langenscheidt K.G. Reproduction or disassembly of embodied algorithms or database prohibited.";
extern const char copyright_text_17[] = "International CorrectSpell Italian correction system Copyright © 1995 by Lernout & Hauspie Speech Products N.V. All rights reserved. Adapted from word list supplied by Zanichelli S.p.A. Reproduction or disassembly of embodied algorithms or database prohibited.";
extern const char copyright_text_18[] = "International CorrectSpell Portuguese correction system Copyright © 1995 by Lernout & Hauspie Speech Products N.V. All rights reserved. Portions adapted from the Dicionario Academico da Lingua Portuguesa Copyright © 1992 by Porto Editora. Reproduction or disassembly of embodied algorithms or database prohibited.";
extern const char copyright_text_19[] = "Federal Acquisitions: Commercial Software - Government Users Subject to Standard License Terms and Conditions.";
extern const char copyright_text_20[] = "DOCUMENTATION IS PROVIDED \"AS IS\" AND ALL EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND WARRANTIES, INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, ARE DISCLAIMED, EXCEPT TO THE EXTENT THAT SUCH DISCLAIMERS ARE HELD TO BE LEGALLY INVALID.";
extern const char copyright_text_21[] = "Copyright © 2002 Sun Microsystems, Inc., 901 San Antonio Road, Palo Alto, California 94303, États-Unis. Tous droits réservés.";
extern const char copyright_text_22[] = "Sun Microsystems, Inc. a les droits de propriété intellectuels relatants à la technologie incorporée dans ce produit. En particulier, et sans la limitation, ces droits de propriété intellectuels peuvent inclure un ou plus des brevets américains énumérés à http://www.sun.com/patents et un ou les brevets plus supplémentaires ou les applications de brevet en attente dans les États - Unis et les autres pays.";
extern const char copyright_text_23[] = "Ce produit ou document est protégé par un copyright et distribué avec des licences qui en restreignent l'utilisation, la copie, la distribution, et la décompilation. Aucune partie de ce produit ou document ne peut être reproduite sous aucune forme, par quelque moyen que ce soit, sans l'autorisation préalable et écrite de Sun et de ses bailleurs de licence, s'il y ena.";
extern const char copyright_text_24[] = "Le logiciel détenu par des tiers, et qui comprend la technologie relative aux polices de caractères, est protégé par un copyright et licencié par des fournisseurs de Sun.";
extern const char copyright_text_25[] = "Ce produit repose en partie sur le travail de l'Independent JPEG Group, de The FreeType Project et de Catharon Typography Project.";
extern const char copyright_text_26[] = "Portions Copyright 2000 SuSE, Inc. Word for Word Copyright © 1996 Inso Corp. Système de correction orthographique International CorrectSpell Copyright © 1995 de Lernout & Hauspie Speech Products N.V. Tous droits réservés.";
extern const char copyright_text_27[] = "Le code source de certaines parties de ce produit est disponible sous licence publique Mozilla sur les sites suivants : http://www.mozilla.org/, http://www.jclark.com/ et http://www.gingerall.com.";
extern const char copyright_text_28[] = "Sun, Sun Microsystems, le logo Sun, Java, Solaris, StarOffice, le logo Butterfly, le logo Solaris et le logo StarOffice sont des marques de fabrique ou des marques déposées de Sun Microsystems, Inc. aux États-Unis et dans d'autres pays.";
extern const char copyright_text_29[] = "UNIX est une marque déposée aux États-Unis et dans d'autres pays et licenciée exclusivement par X/Open Company, Ltd.";
extern const char copyright_text_30[] = "Les Screen Beans et les objets graphiques prédessinés Screen Beans sont des marques déposées de A Bit Better Corporation. International CorrectSpell est une marque déposée de Lernout & Hauspie Speech Products N.V.";
extern const char copyright_text_31[] = "Systèmes de correction orthographique suédois, russe, norvégien, anglais, néerlandais et danois International CorrectSpell Copyright © 1995 de Lernout & Hauspie Speech Products N.V. Tous droits réservés. Il est interdit de reproduire ou de désassembler les algorithmes ou les bases de données incorporés.";
extern const char copyright_text_32[] = "Systèmes de correction orthographique espagnol et français International CorrectSpell Copyright © 1995 de Lernout & Hauspie Speech Products N.V. Tous droits réservés. Adapté à partir de la liste de mots fournie par la Librairie Larousse. Il est interdit de reproduire ou de désassembler les algorithmes ou les bases de données incorporés.";
extern const char copyright_text_33[] = "Système de correction orthographique anglais australien International CorrectSpell Copyright © 1995 de Lernout & Hauspie Speech Products N.V. Tous droits réservés. élaboré à partir de The Macquarie Dictionary, deuxième édition mise à jour. Copyright © Macquarie University NSW. Il est interdit de reproduire ou de désassembler les algorithmes ou les bases de données incorporés.";
extern const char copyright_text_34[] = "Système de correction orthographique catalan International CorrectSpell Copyright © 1995 de Lernout & Hauspie Speech Products N.V. Tous droits réservés. Adapté à partir de la liste de mots catalans Copyright © 1992 Universitat de Barcelona. Il est interdit de reproduire ou de désassembler les algorithmes ou les bases de données incorporés.";
extern const char copyright_text_35[] = "Système de correction orthographique tchèque International CorrectSpell Copyright © 1995 de Lernout & Hauspie Speech Products N.V. Tous droits réservés. Adapté à partir de la liste de mots fournie par Jan Hajic. Il est interdit de reproduire ou de désassembler les algorithmes ou les bases de données incorporés.";
extern const char copyright_text_36[] = "Système de correction orthographique finlandais International CorrectSpell Copyright © 1995 de Lernout & Hauspie Speech Products N.V. Tous droits réservés. Adapté à partir de la liste de mots fournie par le University of Helsinki Institute pour la langue finlandaise et par le Dr Kolbjorn Heggstad. Il est interdit de reproduire ou de désassembler les algorithmes ou les bases de données incorporés.";
extern const char copyright_text_37[] = "Système de correction orthographique allemand International CorrectSpell Copyright © 1995 de Lernout & Hauspie Speech Products N.V. Tous droits réservés. Adapté à partir de la liste de mots fournie par Langenscheidt K.G. Il est interdit de reproduire ou de désassembler les algorithmes ou les bases de données incorporés.";
extern const char copyright_text_38[] = "Système de correction orthographique italien International CorrectSpell Copyright © 1995 de Lernout & Hauspie Speech Products N.V. Tous droits réservés. Adapté à partir de la liste de mots fournie par Zanichelli S.p.A. Il est interdit de reproduire ou de désassembler les algorithmes ou les bases de données incorporés.";
extern const char copyright_text_39[] = "Système de correction orthographique portugais International CorrectSpell Copyright © 1995 de Lernout & Hauspie Speech Products N.V. Tous droits réservés. Certaines parties ont été adaptées à partir du Dicionario Academico da Lingua Portuguesa Copyright © 1992 de Porto Editora. Il est interdit de reproduire ou de désassembler les algorithmes ou les bases de données incorporés.";
extern const char copyright_text_40[] = "Acquisitions fédérales : logiciel commercial ; les utilisateurs gouvernementaux sont soumis aux conditions générales standard de la licence.";
extern const char copyright_text_41[] = "LA DOCUMENTATION est fournie « TELLE QUELLE » et TOUTES LES CONDITIONS, REPRÉSENTATIONS ET GARANTIES EXPRESSES OU TACITES, Y COMPRIS TOUTE GARANTIE TACITE CONCERNANT LA QUALITÉ MARCHANDE, L'APTITUDE À UN USAGE PARTICULIER OU LA NON-VIOLATION DE DROITS DE TIERS SERONT REJETÉES, EXCEPTÉ DANS LE CAS OÙ L'EXCLUSION OU LA LIMITATION DE TELLES GARANTIES NE SERAIT PAS AUTORISÉE PAR LA LÉGISLATION EN VIGUEUR.";

