/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_datatransfer_XTransferDataInfo_idl__
#define __com_sun_star_datatransfer_XTransferDataInfo_idl__

#include <com/sun/star/datatransfer/DataFlavor.idl>
#include <com/sun/star/uno/XInterface.idl>


module com { module sun { module star { module datatransfer {

/** This interface provides direct access to the data in all data flavors. It can
    be used by the clipboard implementation to optimize data transport on
    flush operations.

    @see com::sun::star::datatransfer::XTransferable
*/

published interface XTransferDataAccess: com::sun::star::uno::XInterface
{
    /** To query for the summarized data size in bytes of a sequence of <type>DataFlavor</type>.

        @param aFlavorList
        A sequence of requested <type>DataFlavor</type>.
        <p>An unsupported <type>DataFlavor</type> will be ignored.</p>

        @returns
        The number of bytes of the transfer data in the specified sequence of <type>DataFlavor</type>.
    */
    hyper queryDataSize( [in] sequence < DataFlavor > aFlavorList );

    /** To get all the data of a sequence of <type>DataFlavor</type>.

        @param aFlavorList
        The sequence of requested <type>DataFlavor</type>.
        <p>An unsupported <type>DataFlavor</type> will be ignored.</p>

        @returns
        The data in the requested <type>DataFlavor</type>.
        <p>For unsupported <type>DataFlavor</type> an
        empty any will be returned.</p>
     */
    sequence < any > getData( [in] sequence < DataFlavor > aFlavorList );
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
