/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: ConversionDictionaryList.idl,v $
 *
 *  $Revision: 1.6 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 02:04:02 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_linguistic2_ConversionDictionaryList_idl__
#define __com_sun_star_linguistic2_ConversionDictionaryList_idl__

#ifndef __com_sun_star_linguistic2_XConversionDictionaryList_idl__
#include <com/sun/star/linguistic2/XConversionDictionaryList.idl>
#endif

#ifndef __com_sun_star_lang_XComponent_idl__
#include <com/sun/star/lang/XComponent.idl>
#endif

//=============================================================================

module com { module sun { module star { module linguistic2 {

//=============================================================================
/** represents a list of available conversion dictionaries.

    <p>There will be only one list that may hold different types of
    conversion dictionaries. That is e.g. it may hold dictionaries
    for Korean Hangul/Hanja conversion along with ones for
    Chinese traditional/simplified conversion or conversion between
    different Indic script types.</p>

    <p>The list will be used by the text conversion service to
    check for user supplied text conversions.</p>

    @see com::sun::star::linguistic2::ConversionDictionary
    @see com::sun::star::linguistic2::HangulHanjaConversionDictionary
    @see com::sun::star::i18n::TextConversion

     @since OOo 1.1.2
*/
published service ConversionDictionaryList
{
    interface com::sun::star::linguistic2::XConversionDictionaryList;
    interface com::sun::star::lang::XComponent;
};

//=============================================================================

}; }; }; };

#endif
