/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_linguistic2_ConversionDictionaryList_idl__
#define __com_sun_star_linguistic2_ConversionDictionaryList_idl__

#ifndef __com_sun_star_linguistic2_XConversionDictionaryList_idl__
#include <com/sun/star/linguistic2/XConversionDictionaryList.idl>
#endif

#ifndef __com_sun_star_lang_XComponent_idl__
#include <com/sun/star/lang/XComponent.idl>
#endif

//=============================================================================

module com { module sun { module star { module linguistic2 {

//=============================================================================
/** represents a list of available conversion dictionaries.

    <p>There will be only one list that may hold different types of
    conversion dictionaries. That is e.g. it may hold dictionaries
    for Korean Hangul/Hanja conversion along with ones for
    Chinese traditional/simplified conversion or conversion between
    different Indic script types.</p>

    <p>The list will be used by the text conversion service to
    check for user supplied text conversions.</p>

    @see com::sun::star::linguistic2::ConversionDictionary
    @see com::sun::star::linguistic2::HangulHanjaConversionDictionary
    @see com::sun::star::i18n::TextConversion

     @since OpenOffice 1.1.2
*/
published service ConversionDictionaryList
{
    interface com::sun::star::linguistic2::XConversionDictionaryList;
    interface com::sun::star::lang::XComponent;
};

//=============================================================================

}; }; }; };

#endif
