/*************************************************************************
 *
 *  $RCSfile: DictionaryListEventFlags.idl,v $
 *
 *  $Revision: 1.5 $
 *
 *  last change: $Author: arellano $ $Date: 2001-04-03 18:48:37 $
 *
 *  The Contents of this file are made available subject to the terms of
 *  either of the following licenses
 *
 *         - GNU Lesser General Public License Version 2.1
 *         - Sun Industry Standards Source License Version 1.1
 *
 *  Sun Microsystems Inc., October, 2000
 *
 *  GNU Lesser General Public License Version 2.1
 *  =============================================
 *  Copyright 2000 by Sun Microsystems, Inc.
 *  901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License version 2.1, as published by the Free Software Foundation.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *  MA  02111-1307  USA
 *
 *
 *  Sun Industry Standards Source License Version 1.1
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.1 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://www.openoffice.org/license.html.
 *
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 *
 *  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 *
 *  Copyright: 2000 by Sun Microsystems, Inc.
 *
 *  All Rights Reserved.
 *
 *  Contributor(s): _______________________________________
 *
 *
 ************************************************************************/
#ifndef __com_sun_star_linguistic2_DictionaryListEventFlags_idl__
#define __com_sun_star_linguistic2_DictionaryListEventFlags_idl__


//=============================================================================

module com { module sun { module star { module linguistic2 {

//=============================================================================
/** constants representing a single dictionary-list event.

    <P>These flags define the possible types for a
    dictionary-list event.</P>

    @see    com::sun::star::linguistic2::DictionaryListEvent
    @see    com::sun::star::linguistic2::XDictionaryListEventListener
    @see    com::sun::star::linguistic2::XDictionaryList
*/
constants DictionaryListEventFlags
{
    //-------------------------------------------------------------------------
    /** A positive entry was added to a dictionary from the
        dictionary list.
    */
    const short ADD_POS_ENTRY = 1;

    //-------------------------------------------------------------------------
    /** A positive entry was deleted from a dictionary of the
        dictionary list or a dictionary with positive entries
        was cleared.

    <!-- Dennis: Should "dictionary list" be hyphenated? -->
    */
    const short DEL_POS_ENTRY = 2;

    //-------------------------------------------------------------------------
    /** A negative entry was added to a dictionary from the
        dictionary list.

    <!-- Dennis: Should "dictionary list" be hyphenated? -->*/
    const short ADD_NEG_ENTRY = 4;

    //-------------------------------------------------------------------------
    /** A negative entry was deleted from a dictionary of the
        dictionary list or a dictionary with negative entries
        was cleared.

    <!-- Dennis: Should "dictionary list" be hyphenated? -->
    */
    const short DEL_NEG_ENTRY = 8;

    //-------------------------------------------------------------------------
    /** A dictionary with positive entries was activated or
        has changed its language.
    */
    const short ACTIVATE_POS_DIC = 16;

    //-------------------------------------------------------------------------
    /** A dictionary with positive entries was deactivated or
        has changed its language.
    */
    const short DEACTIVATE_POS_DIC = 32;

    //-------------------------------------------------------------------------
    /** A dictionary with negative entries was activated or
        has changed its language.
    */
    const short ACTIVATE_NEG_DIC = 64;

    //-------------------------------------------------------------------------
    /** A dictionary with negative entries was deactivated or
        has changed its language.
    */
    const short DEACTIVATE_NEG_DIC = 128;
};

//=============================================================================

}; }; }; };

#endif
