/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_linguistic2_Proofreader_idl__
#define __com_sun_star_linguistic2_Proofreader_idl__


module com { module sun { module star { module linguistic2 {
        interface XProofreader; };
}; }; };


module com { module sun { module star { module linguistic2 {


/** provides a proofreader (often known as grammar checker) for text

    <p>An implementation of this service will receive text and has to identify
    the sentence end and report all errors found.</p>

    <p>An implementation of this service is not limited to grammar checking at all.
    It might also check style, used terms etc. Basically it can check every
    aspect of a single sentence. Since the text provided is always the complete
    paragraph it can also choose to analyze the context of the sentence currently
    required to be checked. However error reports need to be limited to the
    current sentence.</p>

    @since OOo 3.0.1
 */

service Proofreader : XProofreader {};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
