/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_linguistic2_XDictionaryEventListener_idl__
#define __com_sun_star_linguistic2_XDictionaryEventListener_idl__

#ifndef __com_sun_star_lang_XEventListener_idl__
#include <com/sun/star/lang/XEventListener.idl>
#endif

#ifndef __com_sun_star_linguistic2_DictionaryEvent_idl__
#include <com/sun/star/linguistic2/DictionaryEvent.idl>
#endif


//=============================================================================

module com { module sun { module star { module linguistic2 {

//=============================================================================
/** This interfaces allows the object to act according to dictionary events.

    <P>The single method is used by a dictionary to notify its
    listeners about
    <type scope="com::sun::star::linguistic2">DictionaryEvent</type>s.</P>

    @see    <type scope="com::sun::star::linguistic2">XDictionary</type>
    @see    <type scope="com::sun::star::lang">XEventListener</type>
*/
published interface XDictionaryEventListener : com::sun::star::lang::XEventListener
{
    //-------------------------------------------------------------------------
    /** is used to get notification of dictionary events.

        @param  aDicEvent
            the event to be notified of.

    @see    <type scope="com::sun::star::lang">DictionaryEvent</type>
    */
    void processDictionaryEvent(
            [in] com::sun::star::linguistic2::DictionaryEvent aDicEvent );

};

//=============================================================================

}; }; }; };

#endif
