/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_linguistic2_XLinguServiceEventListener_idl__
#define __com_sun_star_linguistic2_XLinguServiceEventListener_idl__


#include <com/sun/star/lang/XEventListener.idl>
#include <com/sun/star/linguistic2/LinguServiceEvent.idl>


module com { module sun { module star { module linguistic2 {

/** is used to inform listeners about LinguServiceEvents.

    <P>The function of this interface is used by the
    <type scope="com::sun::star::linguistic2">XLinguServiceEventBroadcaster</type>
    to inform its listeners about the
    <type scope="com::sun::star::linguistic2">LinguServiceEvent</type>s.
    </P>

    @see    <type scope="com::sun::star::linguistic2">XLinguServiceManager</type>
*/
published interface XLinguServiceEventListener : com::sun::star::lang::XEventListener
{
    /**
        @param aLngSvcEvent
            the event the listener will be informed about.
     */
    void    processLinguServiceEvent(
        [in] com::sun::star::linguistic2::LinguServiceEvent aLngSvcEvent );

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
