/*************************************************************************
 *
 *  $RCSfile: XSearchableDictionaryList.idl,v $
 *
 *  $Revision: 1.6 $
 *
 *  last change: $Author: jsc $ $Date: 2001-03-16 16:41:27 $
 *
 *  The Contents of this file are made available subject to the terms of
 *  either of the following licenses
 *
 *         - GNU Lesser General Public License Version 2.1
 *         - Sun Industry Standards Source License Version 1.1
 *
 *  Sun Microsystems Inc., October, 2000
 *
 *  GNU Lesser General Public License Version 2.1
 *  =============================================
 *  Copyright 2000 by Sun Microsystems, Inc.
 *  901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License version 2.1, as published by the Free Software Foundation.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *  MA  02111-1307  USA
 *
 *
 *  Sun Industry Standards Source License Version 1.1
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.1 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://www.openoffice.org/license.html.
 *
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 *
 *  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 *
 *  Copyright: 2000 by Sun Microsystems, Inc.
 *
 *  All Rights Reserved.
 *
 *  Contributor(s): _______________________________________
 *
 *
 ************************************************************************/
#ifndef __com_sun_star_linguistic2_XSearchableDictionaryList_idl__
#define __com_sun_star_linguistic2_XSearchableDictionaryList_idl__


#ifndef __com_sun_star_linguistic2_XDictionaryList_idl__
#include <com/sun/star/linguistic2/XDictionaryList.idl>
#endif

#ifndef __com_sun_star_linguistic2_XDictionaryEntry_idl__
#include <com/sun/star/linguistic2/XDictionaryEntry.idl>
#endif

#ifndef __com_sun_star_lang_Locale_idl__
#include <com/sun/star/lang/Locale.idl>
#endif


//=============================================================================

module com { module sun { module star { module linguistic2 {

//=============================================================================
/** allows searching for an entry in all dictionaries of the dictionary-list.

    <P> Only active dictionaries of a suitable language will be searched
    for the entry.
    The language is suitable if it is the same as the dictionaries language or
    the dictionary may hold entries of all langauges.
    <P>

    @see com::sun::star::linguistic2::XDictionaryList
*/
interface XSearchableDictionaryList : com::sun::star::linguistic2::XDictionaryList
{
    //-------------------------------------------------------------------------
    /** looks for an entry for a given word in the list of dictionaries.

        @returns
            the dictionary entry that was found, </NULL> otherwise.

        @param aWord
            the word (entry) to be looked for.

        @param aLocale
            the language of the word to be looked for.

        @param bSearchPosDic
            </TRUE> if only postive dictionaries should be searched.
            </FALSE> of only negative dictionaries should be searched.

        @param bSpellEntry
            </TRUE> if entries for purposes of spellchecking are required.
            </FALSE> if only entries for hyphenation purposes are required.

    */
    com::sun::star::linguistic2::XDictionaryEntry   queryDictionaryEntry(
        [in] string  aWord ,
        [in] com::sun::star::lang::Locale  aLocale,
        [in] boolean bSearchPosDics,
        [in] boolean bSpellEntry );

};

//=============================================================================

}; }; }; };

#endif


