/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: FillRule.idl,v $
 *
 *  $Revision: 1.4 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 02:47:49 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_rendering_FillRule_idl__
#define __com_sun_star_rendering_FillRule_idl__

module com { module sun { module star { module rendering {

/** Determines which algorithm to use when determining inside and
    outside of filled poly-polygons.

    @since OOo 2.0.0
 */
enum FillRule
{
    /** Fill every area, which is within one or more of the
        poly-polygons polygons.<p>

        For example, a poly-polygon consisting of two concentric
        circles is filled the same way as if only the outer circle
        would exist.<p>
     */
    NON_ZERO,

    //-------------------------------------------------------------------------

    /** Fill every area, where, when travelling along a line, an
        uneven number of intersections with polygon edges have
        happened.<p>
     */
    EVEN_ODD
};

}; }; }; };

#endif
