/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_rendering_StringContext_idl__
#define __com_sun_star_rendering_StringContext_idl__

module com { module sun { module star { module rendering {

/** Collection of string-related arguments used on all canvas text
    interfaces.<p>

    A possibly much larger string than later rendered is necessary
    here, because in several languages, glyph selection is context
    dependent.<p>

    @since OpenOffice 2.0
 */
published struct StringContext
{
    /** The complete text, from which a subset is selected by the
        parameters below.
     */
    string      Text;

    //-------------------------------------------------------------------------

    /** Start position within the string.<p>

        The first character has index 0.<p>
     */
    long    StartPosition;

    //-------------------------------------------------------------------------

    /** Length of the substring to actually use.<p>

        Must be within the range [0,INTMAX].<p>
    */
    long    Length;

};

}; }; }; };

#endif
