/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: MenuSingleChange.idl,v $
 *
 *  $Revision: 1.6 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 02:22:17 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/


#ifndef __com_sun_star_mozilla_MenuSingleChange_idl__
#define __com_sun_star_mozilla_MenuSingleChange_idl__

#ifndef __com_sun_star_lang_XComponent_idl__
#include <com/sun/star/lang/XComponent.idl>
#endif

//=============================================================================

 module com {  module sun {  module star {  module mozilla {

//=============================================================================


// DocMerge from idl: struct com::sun::star::mozilla::MenuSingleChange
/** Explains a change for a menu item
 */
published struct MenuSingleChange
{
    // DocMerge from xml: field com::sun::star::mozilla::MenuSingleChange::ID
    /** unique ID of this menu item
     */
    short   ID;

    //-------------------------------------------------------------------------

    // DocMerge from xml: field com::sun::star::mozilla::MenuSingleChange::ChangeID
    /** ID identifying the type of change in the any type change
     */
    short   ChangeID;

    //-------------------------------------------------------------------------

    // DocMerge from xml: field com::sun::star::mozilla::MenuSingleChange::Change
    /** value of change
     */
    any     Change;
};

//=============================================================================

}; }; }; };



#endif
