/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

module ooo { module vba { module word {
    constants WdColorIndex {
        const long wdAuto = 0;
        const long wdBlack = 1;
        const long wdBlue = 2;
        const long wdBrightGreen = 4;
        const long wdByAuthor = -1;
        const long wdDarkBlue = 9;
        const long wdDarkRed = 13;
        const long wdDarkYellow = 14;
        const long wdGray25 = 16;
        const long wdGray50 = 15;
        const long wdGreen = 11;
        const long wdNoHighlight = 0;
        const long wdPink = 5;
        const long wdRed = 6;
        const long wdTeal = 10;
        const long wdTurquoise = 3;
        const long wdViolet = 12;
        const long wdWhite = 8;
        const long wdYellow = 7;
    };
}; }; };

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
