/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

module ooo { module vba { module word {
    constants WdDefaultFilePath {
        const long wdAutoRecoverPath = 5;
        const long wdBorderArtPath = 19;
        const long wdCurrentFolderPath = 14;
        const long wdDocumentsPath = 0;
        const long wdGraphicsFiltersPath = 10;
        const long wdPicturesPath = 1;
        const long wdProgramPath = 9;
        const long wdProofingToolsPath = 12;
        const long wdStartupPath = 8;
        const long wdStyleGalleryPath = 15;
        const long wdTempFilePath = 13;
        const long wdTextConvertersPath = 11;
        const long wdToolsPath = 6;
        const long wdTutorialPath = 7;
        const long wdUserOptionsPath = 4;
        const long wdUserTemplatesPath = 2;
        const long wdWorkgroupTemplatesPath = 3;
    };
}; }; };

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
