module ooo { module vba { module word {
    constants WdVerticalAlignment {
        const long wdAlignVerticalBottom = 3;
        const long wdAlignVerticalCenter = 1;
        const long wdAlignVerticalJustify = 2;
        const long wdAlignVerticalTop = 0;
    };
}; }; };
