/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http:
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http:
 */

#include "op.h"
#include "optab.h"



OPCODE_FKT pOpFkt[ FKT_LIMIT ] =
{                       
    OP_BOF,             
    OP_EOF,             
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    OP_Window1,         
    OP_ColumnWidth,     
    NI,                 
    NI,                 
    OP_NamedRange,      
    OP_Blank,           
    OP_Integer,         
    OP_Number,          
    OP_Label,           
    OP_Formula,         
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    OP_Footer,          
    OP_Header,          
    NI,                 
    OP_Margins,         
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    OP_SymphNamedRange, 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    OP_HiddenCols,      
};


OPCODE_FKT pOpFkt123[ FKT_LIMIT123 ] =
{                       
    OP_BOF123,              
    OP_EOF123,              
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,         
    NI,     
    NI,                 
    NI,                 
    NI,     
    NI,         
    NI,         
    NI,         
    NI,         
    NI,         
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    OP_Label123,                
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    OP_CreatePattern123,            
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    OP_SheetName123,    
    NI,                 
    OP_Number123,                   
    OP_Note123,         
    OP_IEEENumber123,                   
    OP_Formula123,          
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI, 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI,                 
    NI      
};


/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
