/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_chart_ChartDataArray_idl__
#define __com_sun_star_chart_ChartDataArray_idl__

#ifndef __com_sun_star_chart_ChartData_idl__
#include <com/sun/star/chart/ChartData.idl>
#endif

#ifndef __com_sun_star_chart_XChartDataArray_idl__
#include <com/sun/star/chart/XChartDataArray.idl>
#endif

#ifndef __com_sun_star_chart_XChartData_idl__
#include <com/sun/star/chart/XChartData.idl>
#endif


//=============================================================================

 module com {  module sun {  module star {  module chart {

//=============================================================================

/** must be supported by each data source for charts, where you want
    to access the values directly.

    <p>It contains the data values as well as the descriptions for
    each row and column.</p>
 */
published service ChartDataArray
{
    service com::sun::star::chart::ChartData;
    interface com::sun::star::chart::XChartDataArray;
};

//=============================================================================

}; }; }; };

#endif
