/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_chart_ChartLegendPosition_idl__
#define __com_sun_star_chart_ChartLegendPosition_idl__


//=============================================================================

 module com {  module sun {  module star {  module chart {

//=============================================================================

/** specifies one of the default positions of the legend in relation
    to the diagram.
 */
published enum ChartLegendPosition
{
    //-------------------------------------------------------------------------

    /** no chart legend is displayed.

        <p>To disable the legend you should set the property
        <member>ChartDocument::HasLegend</member> to <FALSE/> instead
        of setting this value.</p>
     */
    NONE,

    //-------------------------------------------------------------------------

    /** displays the chart legend on the left side of the diagram.

        <p>The second entry in the legend is placed below the first
        one.</p>
     */
    LEFT,

    //-------------------------------------------------------------------------

    /** displays the chart legend above the diagram.

        <p>The second entry in the legend is placed an the right hand
        side of the first one.</p>
     */
    TOP,

    //-------------------------------------------------------------------------

    /** displays the chart legend on the right side of the diagram.

        <p>The second entry in the legend is placed below the first
        one.</p>
     */
    RIGHT,

    //-------------------------------------------------------------------------

    /** displays the chart legend beneath the diagram.

        <p>The second entry in the legend is placed an the right hand
        side of the first one.</p>
     */
    BOTTOM
};

//=============================================================================

}; }; }; };

#endif
