/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: ChartAxisArrangeOrderType.idl,v $
 *
 *  $Revision: 1.10 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-07 22:03:17 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_chart_ChartAxisArrangeOrderType_idl__
#define __com_sun_star_chart_ChartAxisArrangeOrderType_idl__


//=============================================================================

 module com {  module sun {  module star {  module chart {

//=============================================================================

/** Values specify the arrangement of the axes descriptions.
 */
published enum ChartAxisArrangeOrderType
{
    //-------------------------------------------------------------------------

    /** The descriptions are arranged automatically.

        <p>If there is enough space to put them side by side, this
        arrangement is preferred. If the descriptions would overlap
        when arranged side by side, they are staggered.</p>
     */
    AUTO,

    //-------------------------------------------------------------------------

    /** The descriptions are arranged side by side.
     */
    SIDE_BY_SIDE,

    //-------------------------------------------------------------------------

    /** The descriptions are alternately put on two lines with the even
        values out of the normal line.
     */
    STAGGER_EVEN,

    //-------------------------------------------------------------------------

    /** The descriptions are alternately put on two lines with the odd
        values out of the normal line.
     */
    STAGGER_ODD
};

//=============================================================================

}; }; }; };

#endif
