/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_chart_LineDiagram_idl__
#define __com_sun_star_chart_LineDiagram_idl__

#include <com/sun/star/chart/Diagram.idl>

#include <com/sun/star/chart/ChartStatistics.idl>

#include <com/sun/star/chart/ChartAxisXSupplier.idl>

#include <com/sun/star/chart/ChartTwoAxisYSupplier.idl>

#include <com/sun/star/chart/ChartAxisZSupplier.idl>

#include <com/sun/star/chart/Dim3DDiagram.idl>

#include <com/sun/star/chart/StackableDiagram.idl>
#include <com/sun/star/awt/Size.idl>


 module com {  module sun {  module star {  module chart {


/** specifies line, spline and symbol diagrams.
 */
published service LineDiagram
{
    service com::sun::star::chart::Diagram;
    service com::sun::star::chart::ChartStatistics;
    service com::sun::star::chart::ChartAxisXSupplier;
    service com::sun::star::chart::ChartTwoAxisYSupplier;
    service com::sun::star::chart::ChartAxisZSupplier;
    service com::sun::star::chart::Dim3DDiagram;
    service com::sun::star::chart::StackableDiagram;


    /** determines which type of symbols are displayed.

        <p>In this interface, only the two values
        ChartSymbolType::NONE and
        ChartSymbolType::AUTO are supported. Later
        versions may support the selection of the symbols shape.</p>

        <p>If you set this property to
        ChartSymbolType::AUTO, you can change the
        symbol shape for objects supporting the service
        ChartDataPointProperties or
        ChartDataRowProperties.</p>

        @see ChartDataPointProperties
        @see ChartDataRowProperties
     */
    [property] long SymbolType;


    /** specifies the size of symbols in 1/100th of a millimeter.
     */
    [optional, property] com::sun::star::awt::Size SymbolSize;


    /** Set this property to any valid URL that points to a graphic
        file.  This graphic is then used as symbol for all series.

        <p>When you query this value you get an internal URL of the
        embedded graphic.</p>

        @deprecated
        @see ChartSymbolType
     */
    [optional, property] string SymbolBitmapURL;


    /** determines if the chart type has lines connecting the data
        points or contains just symbols.
     */
    [property] boolean Lines;


    /** determines if the chart is a spline-chart type and specifies
        the type of splines.

        @see CurveStyle
        <p>You can set the following values:
        <table border>
        <tr><td>0</td><td>lines are used instead of splines</td></tr>
        <tr><td>1</td><td>use cubic splines</td></tr>
        <tr><td>2</td><td>use B-splines</td></tr>
        <tr><td>3</td><td>use stepped line with step start</td></tr>
        <tr><td>4</td><td>use stepped line with step end</td></tr>
        <tr><td>5</td><td>use stepped line with step center x</td></tr>
        <tr><td>6</td><td>use stepped line with step center y</td></tr>
        </table>
        </p>
     */
    [property] long SplineType;


    /** specifies the power of the polynomials used for spline
        calculation

        This property is only valid for B-splines
     */
    [optional, property] long SplineOrder;


    /** determines the number of sampling points of a spline
     */
    [optional, property] long SplineResolution;

    /** Set this property to a graphic object which is then used as
        symbol for all series.

        @since LibreOffice 6.1

        @deprecated - added for backwards compatibility
        @see ChartSymbolType
     */
    [optional, property] com::sun::star::graphic::XGraphic SymbolBitmap;
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
