/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_form_component_CurrencyField_idl__
#define __com_sun_star_form_component_CurrencyField_idl__

#ifndef __com_sun_star_awt_UnoControlCurrencyFieldModel_idl__
#include <com/sun/star/awt/UnoControlCurrencyFieldModel.idl>
#endif

#ifndef __com_sun_star_form_FormControlModel_idl__
#include <com/sun/star/form/FormControlModel.idl>
#endif

#ifndef __com_sun_star_form_XReset_idl__
#include <com/sun/star/form/XReset.idl>
#endif


//=============================================================================

 module com {  module sun {  module star {  module form {  module component {

//=============================================================================

/** This service specifies the ControlModel for an edit field which
    contains a currency value.
 */
published service CurrencyField
{
    service com::sun::star::awt::UnoControlCurrencyFieldModel;

    service com::sun::star::form::FormControlModel;

    /** can be used to reset the control to it's default state.

        @see CurrencyField::DefaultValue
    */
    interface com::sun::star::form::XReset;

    /** contains a default value for the control.

        @see com::sun::star::awt::UnoControlCurrencyFieldModel::Value
        @see com::sun::star::form::XReset
     */
    [property] double DefaultValue;

};

//=============================================================================

}; }; }; }; };

#endif
