/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_form_component_FileControl_idl__
#define __com_sun_star_form_component_FileControl_idl__

#include <com/sun/star/awt/UnoControlFileControlModel.idl>

#include <com/sun/star/form/FormControlModel.idl>

#include <com/sun/star/form/XReset.idl>


 module com {  module sun {  module star {  module form {  module component {


/** This service specifies the control model of an edit field for a
    file name.
 */
published service FileControl
{
    service com::sun::star::awt::UnoControlFileControlModel;

    service com::sun::star::form::FormControlModel;

    /** can be used to reset the control to its default text.

        @see FileControl::DefaultText
    */
    interface com::sun::star::form::XReset;

    /** contains a default value for the control.

        <p>This value is used when the control is initially displayed, and for resetting it.</p>

        @see com::sun::star::awt::UnoControlFileControlModel::Text
        @see com::sun::star::form::XReset
     */
    [property] string DefaultText;

};


}; }; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
