/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_form_component_TextField_idl__
#define __com_sun_star_form_component_TextField_idl__

#include <com/sun/star/awt/UnoControlEditModel.idl>

#include <com/sun/star/form/FormControlModel.idl>
#include <com/sun/star/form/component/RichTextControl.idl>
#include <com/sun/star/form/XReset.idl>



 module com {  module sun {  module star {  module form {  module component {


/** specifies a component which allows the input of text, either single- or multi-line.
 */
published service TextField
{
    service com::sun::star::awt::UnoControlEditModel;

    service com::sun::star::form::FormControlModel;

    /** specifies optional capabilities for displaying and inputting formatted text.

        <p>If the <member>RichTextControl::RichText</member> property is set to <TRUE/>,
        then the <type>TextField</type> component will disable it's reset capabilities. This means
        that all calls to <member scope="com::sun::star::form">XReset::reset</member> will be ignored.</p>
    */
    [optional] service RichTextControl;

    /** can be used to reset the control to it's default text.

        @see TextField::DefaultText
    */
    interface com::sun::star::form::XReset;

    /** contains a default value for the control.

        <p>This value is used when the control is initially displayed, and for resetting it.</p>

        @see com::sun::star::awt::UnoControlEditModel::Text
        @see com::sun::star::form::XReset
     */
    [property] string DefaultText;
};


}; }; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
