/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: Pump.idl,v $
 *
 *  $Revision: 1.11 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-09 15:27:00 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_io_Pipe_idl__
#define __com_sun_star_io_Pipe_idl__

#ifndef __com_sun_star_io_XActiveDataSource_idl__
#include <com/sun/star/io/XActiveDataSource.idl>
#endif

#ifndef __com_sun_star_io_XActiveDataSink_idl__
#include <com/sun/star/io/XActiveDataSink.idl>
#endif

#ifndef __com_sun_star_io_XActiveDataControl_idl__
#include <com/sun/star/io/XActiveDataControl.idl>
#endif


//=============================================================================

 module com {  module sun {  module star {  module io {

//=============================================================================

// DocMerge from xml: service com::sun::star::io::Pump
/** the implementation of a data source and a data sink.
    <p>A thread will be created that reads from the input stream and writes
    the data to the connected output stream. Data will not be buffered by
    this service. </p>

 */
published service Pump
{
    /** allows to set the outputstream
     */
    interface com::sun::star::io::XActiveDataSource;

    /** allows to set the inputstream
     */
    interface com::sun::star::io::XActiveDataSink;

    /** allows listener administration and starting/stopping the pump */
    interface com::sun::star::io::XActiveDataControl;

};

//=============================================================================

}; }; }; };

/*=============================================================================

=============================================================================*/
#endif
