/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#ifndef __com_sun_star_util_SearchOptions2_idl__
#define __com_sun_star_util_SearchOptions2_idl__


#include <com/sun/star/util/SearchOptions.idl>


module com { module sun { module star { module util {

/** This augments com::sun::star::util::SearchOptions to be able to
    specify additional search algorithms for use with
    com::sun::star::util::XTextSearch2

    @since LibreOffice 5.2
 */
struct SearchOptions2 : com::sun::star::util::SearchOptions {

    /** Search type, one of com::sun::star::util::SearchAlgorithms2
        constants. This is preferred over the content of the
        SearchAlgorithms SearchOptions::algorithmType enum field.
     */
    short   AlgorithmType2;

    /** The escape character to be used with a
        com::sun::star::util::SearchAlgorithms2::WILDCARD search.

        <p> A Unicode character, if not 0 escapes the special meaning of
        a question mark, asterisk or escape character that follows
        immediately after the escape character. If 0 defines no escape
        character is used. </p>

        <p> Common values are '\' (U+005C REVERSE SOLIDUS) aka backslash
        in text processing context, or '~' (U+007E TILDE) in spreadsheet
        processing context. </p>
     */
    long    WildcardEscapeCharacter;
};

}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
