/*************************************************************************
 *
 *  $RCSfile: SortDescriptor.idl,v $
 *
 *  $Revision: 1.12 $
 *
 *  last change: $Author: vg $ $Date: 2003-04-01 15:16:07 $
 *
 *  The Contents of this file are made available subject to the terms of
 *  either of the following licenses
 *
 *         - GNU Lesser General Public License Version 2.1
 *         - Sun Industry Standards Source License Version 1.1
 *
 *  Sun Microsystems Inc., October, 2000
 *
 *  GNU Lesser General Public License Version 2.1
 *  =============================================
 *  Copyright 2000 by Sun Microsystems, Inc.
 *  901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License version 2.1, as published by the Free Software Foundation.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *  MA  02111-1307  USA
 *
 *
 *  Sun Industry Standards Source License Version 1.1
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.1 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://www.openoffice.org/license.html.
 *
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 *
 *  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 *
 *  Copyright: 2000 by Sun Microsystems, Inc.
 *
 *  All Rights Reserved.
 *
 *  Contributor(s): _______________________________________
 *
 *
 ************************************************************************/
#ifndef __com_sun_star_util_SortDescriptor_idl__
#define __com_sun_star_util_SortDescriptor_idl__

#ifndef __com_sun_star_beans_XPropertySet_idl__
#include <com/sun/star/beans/XPropertySet.idl>
#endif

#ifndef __com_sun_star_lang_Locale_idl__
#include <com/sun/star/lang/Locale.idl>
#endif

//=============================================================================

module com {  module sun {  module star {  module util {

//=============================================================================

/** specifies the properties which can be used to describe
    a sort order applied to an XSortable.

    @see XSortable

    @deprecated
 */
service SortDescriptor
{
     interface com::sun::star::beans::XPropertySet;

    //-------------------------------------------------------------------------
    /** specifies if the case of letters is important when comparing entries.
     */
        [property] boolean IsCaseSensitive;

     //-------------------------------------------------------------------------
    /** specifies the sorting order.

            The sorting order may be defined for sepearte keys in specific
            implementations. For those this property may not need to be set.

            @see <type scope"com::sun::star::text">TextSortDescriptor</type>
     */
        [optional, property] boolean SortAscending;

     //-------------------------------------------------------------------------
    /** specifies if the columns are sorted.

        <dl>
        <dt>
        <TRUE/>
        </dt>
        <dd>The columns are sorted.

        </dd>
        <dt>
        <FALSE/>
        </dt>
        <dd>The rows are sorted.
        </dd>
        </dl>
     */
    [property] boolean SortColumns;

     //-------------------------------------------------------------------------
    /** specifies the locale for the compare operator (collator).
     */
    [property] com::sun::star::lang::Locale CollatorLocale;

     //-------------------------------------------------------------------------
    /** specifies the algorithm for the compare operator (collator).

            The collator algorithm may be defined for sepearte keys in specific
            implementations. For those this property may not need to be set.

            @see <type scope"com::sun::star::text">TextSortDescriptor</type>

            @see com::sun::star::i18n::XCollator
     */
        [optional, property] string CollatorAlgorithm;
};

//=============================================================================

}; }; }; };

#endif
