/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_task_DocumentMSPasswordRequest2_idl__
#define __com_sun_star_task_DocumentMSPasswordRequest2_idl__

#include <com/sun/star/task/DocumentMSPasswordRequest.idl>



module com { module sun { module star { module task {

/** this request specifies if a password for opening or modifying of an encrypted Microsoft Office document is requested.

    <P>
    It is supported by <type>InteractionHandler</type> service, and can
    be used to interact for a document password. Continuations for using with
    the mentioned service are Abort and Approve.
    </P>

    @see com::sun::star::task::PasswordRequest
    @see com::sun::star::task::DocumentMSPasswordRequest

    @since OOo 3.3
*/
exception DocumentMSPasswordRequest2 : DocumentMSPasswordRequest
{
    /** specifies if the requested password is for opening a document or for modifying it.
    */
    boolean     IsRequestPasswordToModify;

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
