/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_configuration_backend_CopyImporter_idl__
#define __com_sun_star_configuration_backend_CopyImporter_idl__

#include <com/sun/star/configuration/backend/Importer.idl>
#include <com/sun/star/lang/XInitialization.idl>


module com { module sun { module star { module configuration { module backend {


/**
    imports data into a configuration layer by copying over existing data.


    @since OOo 1.1.2
*/
published service CopyImporter
{

    /** allows importing configuration data into a backend.

        <p> In this implementation, the changes are copied over any
            <type>XLayer</type> data that already exists in the <type>Backend</type>,
            replacing it completely.
        </p>
      */
    service Importer ;


    /** allows initializing the implementation with settings that control
        its behavior .

        <p> This interface, which is optional in <type>Importer</type>
            is mandatory in this service and supports the following arguments
            which must be provided as
            <type scope="com::sun::star::beans">NamedValue</type>:
        <dl>
            <dt><code>Overwrite</code> : <atom>boolean</atom></dt>
            <dd>If <FALSE/>, specifies that the data should be applied
                only if the existing layer is empty.
            </dd>
        </dl>
        </p>
      */
    interface com::sun::star::lang::XInitialization ;

} ;


} ; } ; } ; } ; } ;

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
