/*************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Copyright 2000, 2010 Oracle and/or its affiliates.
 *
 * OpenOffice.org - a multi-platform office productivity suite
 *
 * This file is part of OpenOffice.org.
 *
 * OpenOffice.org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License version 3
 * only, as published by the Free Software Foundation.
 *
 * OpenOffice.org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License version 3 for more details
 * (a copy is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3 along with OpenOffice.org.  If not, see
 * <http://www.openoffice.org/license.html>
 * for a copy of the LGPLv3 License.
 *
 ************************************************************************/
#ifndef __com_sun_star_configuration_backend_LocalHierarchyBrowser_idl__
#define __com_sun_star_configuration_backend_LocalHierarchyBrowser_idl__

#include <com/sun/star/configuration/backend/HierarchyBrowser.idl>

//=============================================================================

module com { module sun { module star { module configuration { module backend {

//=============================================================================

/**
    is a <type>HierarchyBrowser</type>, that browses a configuration database
    stored in the local file system.

    @see com::sun::star::configuration::backend::LocalSingleBackend

    @since OOo 1.1.2
*/
published service LocalHierarchyBrowser
{
    //-------------------------------------------------------------------------

    /** allows browsing a configuration hierarchy for components.

        <p> Either a schema repository or a layer directory can be browsed.
            Components can be retrieved either as component names or as
            file URLs.
        </p>

        <p> The following additional arguments are supported for
            <member scope="com::sun::star::task">XJob::execute()</member>:<BR/>

        <dl>
            <dt><code>SchemaDataUrl</code> : <atom>string</atom></dt>
            <dd>Base directory to search for schema files.
                If this is specified, schema files will be browsed,
                so argument <code>LayerDataUrl</code> should not be specified.
            </dd>
            <dt><code>LayerDataUrl</code> : <atom>string</atom></dt>
            <dd>Base directory to search for layer files.
                If this is specified, layer files will be browsed,
                so argument <code>SchemaDataUrl</code> should not be specified.
            </dd>
            <dt><code>FetchComponentNames</code> : <atom>boolean</atom></dt>
            <dd><ul><li>if <TRUE/> components will be returned as component names,</li>
                    <li>if <FALSE/> components will be returned as fileURLs,</li>
                    <li>if this argument is not provided, the default is to
                        retrieve names when browsing schemas and URLs when
                        browsing layers.</li>
            </dd>
        </dl>
        </p>
      */
    service HierarchyBrowser ;

    //-------------------------------------------------------------------------
} ;

//=============================================================================

} ; } ; } ; } ; } ;

#endif
