 # config variable for LibreOffice
 # this file is intended to be able to be included in a Makefile
 # and not to be sourced in a shell session
 #

# Horrible hack to prepend spaces to expansions
# Spaces are usually eaten by make parser but not if variable expands to space.
# Space prefix is desirable because system CFLAGS may be completely empty,
# which means that the variables defined here would need extra twiddling
# to get them into invoked external configures and override pkg-config there.
gb_SPACE:=$(gb_SPACE) $(gb_SPACE)
export SRC_ROOT=/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice
export BUILDDIR=/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice

# export AFLAGS=
export ABW_CFLAGS=$(gb_SPACE)
export ABW_LIBS=$(gb_SPACE)
export ANDROID_NDK_HOME=
export ANDROID_APP_ABI=
export ANDROID_SDK_HOME=
export ANDROID_PACKAGE_NAME=
export ANDROID_BINUTILS_PREBUILT_ROOT=
export ANDROID_GCC_TOOLCHAIN_VERSION=
export ANT=/usr/share/ant/bin/ant
export ANT_HOME=/usr/share/ant
export ANT_LIB=/usr/share/ant/lib
export APR_CFLAGS=$(gb_SPACE)
export APR_LIBS=$(gb_SPACE)
export AR=ar
export ASSERT_ALWAYS_ABORT=FALSE
export ATL_INCLUDE=
export ATL_LIB=
export ATOMIC_LIB=
export AVAHI_CFLAGS=$(gb_SPACE)
export AVAHI_LIBS=$(gb_SPACE)
export LIBATOMIC_OPS_CFLAGS=$(gb_SPACE)
export LIBATOMIC_OPS_LIBS=$(gb_SPACE)
export BINDIR=/usr/local/bin
export BISON=/usr/bin/bison
export BOOST_CPPFLAGS=-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/external/boost/include -I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/boost
export BOOST_CXXFLAGS=-D_GLIBCXX_HAS_GTHREADS
export BOOST_LOCALE_LIB=
export BOOST_DATE_TIME_LIB=
export BOOST_FILESYSTEM_LIB=
export BOOST_IOSTREAMS_LIB=
export BOOST_LDFLAGS=
export BOOST_SYSTEM_LIB=
export BOX2D_CFLAGS=
export BOX2D_LIBS=
export BRAND_INTRO_IMAGES=intro.png intro-highres.png
export BREAKPAD_SYMBOL_CONFIG=
export BSH_JAR=
export BUILD_PLATFORM=x86_64-pc-linux-gnu
export BUILD_POSTGRESQL_SDBC=TRUE
export BUILD_TYPE=LibO DESKTOP AVMEDIA DBCONNECTIVITY EXTENSIONS SCRIPTING DYNLOADING NATIVE LIBCMIS ODFVALIDATOR OFFICEOTRON UCPP ODK LIBJPEG_TURBO CLUCENE EXPAT XMLSEC REVENGE ODFGEN EPUBGEN WPD WPG WPS VISIO CDR MSPUB MWAW ETONYEK FREEHAND EBOOK ABW PAGEMAKER QXP ZMF STAROFFICE LCMS2 CPPUNIT PYUNO LIBRELOGO MARIADBC MARIADB_CONNECTOR_C HSQLDB POSTGRESQL LIBTOMMATH FIREBIRD CURL BOOST MDDS GLM OPENLDAP NSS SANE ICU ORCUS GRAPHITE HARFBUZZ NEON OPENSSL REDLAND HUNSPELL QRCODEGEN ZXING BOX2D HYPHEN MYTHES COINMP LPSOLVE LIBEXTTEXTCAT LIBNUMBERTEXT EPOXY OPENCL PDFIUM POPPLER SKIA LIBGPGERROR LIBASSUAN GPGMEPP JFREEREPORT APACHE_COMMONS BSH RHINO OPENSYMBOL MORE_FONTS LIBLANGTAG LIBPNG QADEVOOO
export BUILD_X64=
export BUILD_X86=
export BUILDING_PCH_WITH_OBJ=
export BZIP2_CFLAGS=$(gb_SPACE)
export BZIP2_LIBS=$(gb_SPACE)
export CAIRO_CFLAGS=$(gb_SPACE)-isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/uuid -isystem /usr/include/freetype2 -isystem /usr/include/libpng16
export CAIRO_LIBS=$(gb_SPACE) -lcairo
export CC=/usr/bin/ccache gcc
export CC_FOR_BUILD=/usr/bin/ccache gcc
export CCACHE_DEPEND_MODE=1
export CDR_CFLAGS=$(gb_SPACE)
export CDR_LIBS=$(gb_SPACE)
# export CFLAGS=
export CLANG_USE_LD=
export CLANGDIR=
export CLANGLIBDIR=
export CLANGSYSINCLUDE=
export CLANGTOOLLIBS=
export CLUCENE_CFLAGS=$(gb_SPACE)
export CLUCENE_LIBS=$(gb_SPACE)
export LIBCMIS_CFLAGS=$(gb_SPACE)
export LIBCMIS_LIBS=$(gb_SPACE)
export COM=GCC
export COMMONS_LOGGING_JAR=
export COMMONS_LOGGING_VERSION=1.2
export COMPATH=/usr
export COMPILER_PLUGINS=
export COMPILER_PLUGINS_ANALYZER_PCH=TRUE
export COMPILER_PLUGINS_COM_IS_CLANG=
export COMPILER_PLUGINS_CXX=
export COMPILER_PLUGINS_CXXFLAGS=
export COMPILER_PLUGINS_CXX_LINKFLAGS=
export COMPILER_PLUGINS_DEBUG=
export COMPILER_PLUGINS_TOOLING_ARGS=
export COM_IS_CLANG=
export CPPUNIT_CFLAGS=$(gb_SPACE)
export CPPUNIT_LIBS=$(gb_SPACE)
export CPUNAME=X86_64
export CROSS_COMPILING=
export CURL=/home/homeboy445/anaconda3/bin/curl
export CURL_CFLAGS=$(gb_SPACE)
export CURL_LIBS=$(gb_SPACE)
export CUSTOM_BRAND_DIR=
export CUSTOM_BRAND_IMAGES=
export CXX=/usr/bin/ccache g++
export CXX_FOR_BUILD=
export CXX_X64_BINARY=
export CXX_X86_BINARY=
# export CXXFLAGS=
export CXXFLAGS_CXX11=-std=c++17
export CXXFLAGS_INTRINSICS_SSE2=-msse2
export CXXFLAGS_INTRINSICS_SSSE3=-mssse3
export CXXFLAGS_INTRINSICS_SSE41=-msse4.1
export CXXFLAGS_INTRINSICS_SSE42=-msse4.2
export CXXFLAGS_INTRINSICS_AVX=-mavx
export CXXFLAGS_INTRINSICS_AVX2=-mavx2
export CXXFLAGS_INTRINSICS_F16C=-mf16c
export CXXFLAGS_INTRINSICS_FMA=-mfma
export DATADIR=/usr/local/share
export DBUS_CFLAGS=$(gb_SPACE)-isystem /usr/include/dbus-1.0 -isystem /usr/lib/x86_64-linux-gnu/dbus-1.0/include
export DBUS_LIBS=$(gb_SPACE) -ldbus-1
export DBUS_GLIB_CFLAGS=$(gb_SPACE)-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
export DBUS_GLIB_LIBS=$(gb_SPACE)-lglib-2.0
export DBUS_HAVE_GLIB=TRUE
export DCONF_CFLAGS=
export DCONF_LIBS=
export DEFAULT_BRAND_IMAGES=intro.png intro-highres.png logo.svg logo_inverted.svg logo-sc.svg logo-sc_inverted.svg about.svg
export DICT_SYSTEM_DIR=file:///usr/share/hunspell
export DISABLE_CVE_TESTS=
export DISABLE_DYNLOADING=
export DISABLE_OPENSSL=
export DISABLE_PYTHON=
export DLOPEN_LIBS=-ldl
export DLLTOOL=
export DOCDIR=/usr/local/share/doc/libreoffice
export DOXYGEN=/usr/bin/doxygen
export DO_FETCH_TARBALLS=TRUE
export DPKG=
export EBOOK_CFLAGS=$(gb_SPACE)
export EBOOK_LIBS=$(gb_SPACE)
export ENABLE_ANDROID_LOK=
export ENABLE_ANDROID_EDITING=
export ENABLE_AVAHI=
export ENABLE_BREAKPAD=
export DEFAULT_CRASHDUMP_VALUE=true
export ENABLE_CAIRO_CANVAS=TRUE
export ENABLE_CHART_TESTS=
export ENABLE_CIPHER_OPENSSL_BACKEND=
export ENABLE_LIBCMIS=TRUE
export ENABLE_COINMP=TRUE
export SYSTEM_COINMP=
export COINMP_CFLAGS=
export COINMP_LIBS=
export ENABLE_CUPS=TRUE
export ENABLE_CURL=TRUE
export ENABLE_FUZZERS=
export ENABLE_DBGUTIL=
export ENABLE_DBUS=TRUE
export ENABLE_DCONF=
export ENABLE_DEBUG=
export ENABLE_EOT=
export ENABLE_EVOAB2=
export ENABLE_FIREBIRD_SDBC=TRUE
export ENABLE_FORMULA_LOGGER=
export ENABLE_GDB_INDEX=
export ENABLE_GIO=TRUE
export ENABLE_GPGMEPP=TRUE
export ENABLE_GSTREAMER_1_0=TRUE
export ENABLE_GTK3=TRUE
export DISABLE_GUI=
export ENABLE_HTMLHELP=
export ENABLE_JAVA=TRUE
export ENABLE_LDAP=TRUE
export ENABLE_LPSOLVE=TRUE
export ENABLE_LTO=
export ENABLE_LWP=TRUE
export ENABLE_MACOSX_SANDBOX=
export ENABLE_MEDIAWIKI=
export ENABLE_MARIADBC=TRUE
export ENABLE_NSS=TRUE
export ENABLE_ONLINE_UPDATE=
export ENABLE_ONLINE_UPDATE_MAR=
export ENABLE_EXTENSION_UPDATE=TRUE
export ENABLE_OOENV=TRUE
export ENABLE_OPENGL_TRANSITIONS=TRUE
export ENABLE_OPENGL_CANVAS=TRUE
export ENABLE_OPTIMIZED=TRUE
export ENABLE_OPTIMIZED_DEBUG=
export ENABLE_PCH=
export ENABLE_PDFIMPORT=TRUE
export ENABLE_PDFIUM=TRUE
export ENABLE_POPPLER=TRUE
export ENABLE_QT5=
export ENABLE_KF5=
export ENABLE_GTK3_KDE5=
export ENABLE_RANDR=TRUE
export ENABLE_RELEASE_BUILD=
export ENABLE_REPORTBUILDER=TRUE
export ENABLE_RUNTIME_OPTIMIZATIONS=TRUE
export ENABLE_SAL_LOG=
export ENABLE_SCRIPTING_BEANSHELL=TRUE
export ENABLE_SCRIPTING_JAVASCRIPT=TRUE
export ENABLE_SDREMOTE=TRUE
export ENABLE_SDREMOTE_BLUETOOTH=TRUE
export ENABLE_SILENT_MSI=
export ENABLE_SKIA=TRUE
export ENABLE_SKIA_DEBUG=
export ENABLE_SYMBOLS_FOR=
export ENABLE_VALGRIND=
export ENABLE_WERROR=
export ENDIANNESS=little
export EPM=NO
export EPM_FLAGS=
export EPUBGEN_CFLAGS=$(gb_SPACE)
export EPUBGEN_LIBS=$(gb_SPACE)
export ETONYEK_CFLAGS=$(gb_SPACE)
export ETONYEK_LIBS=$(gb_SPACE)
export debug=
export FIND=find
export FIREBIRD_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/firebird/gen/Release/firebird/include
export FIREBIRD_LIBS=$(gb_SPACE)-lfbclient
export FLEX=/usr/bin/flex
export FLUTE_JAR=
export FONTCONFIG_CFLAGS=$(gb_SPACE)-I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16
export FONTCONFIG_LIBS=$(gb_SPACE) -lfontconfig -lfreetype
export FONTFORGE=
export FREEHAND_CFLAGS=$(gb_SPACE)
export FREEHAND_LIBS=$(gb_SPACE)
export FREETYPE_CFLAGS=$(gb_SPACE)-isystem /usr/include/freetype2 -isystem /usr/include/libpng16
export FREETYPE_LIBS=$(gb_SPACE) -lfreetype
export GCC_VERSION=900
export GIO_CFLAGS=$(gb_SPACE)-pthread -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include
export GIO_LIBS=$(gb_SPACE) -lgio-2.0 -lgobject-2.0 -lglib-2.0
export GIT_REFERENCE_SRC=
export GIT_LINK_SRC=
export GIT_NEEDED_SUBMODULES=
export EPOXY_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/epoxy/include
export EPOXY_LIBS=$(gb_SPACE)
export GLM_CFLAGS=$(gb_SPACE)-isystem /home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/glm
export GPG_ERROR_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/libgpg-error/src
export GPG_ERROR_LIBS=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/libgpg-error/src/.libs -lgpg-error
export GPGMEPP_CFLAGS=$(gb_SPACE)
export GPGMEPP_LIBS=$(gb_SPACE)
export GNUTLS_CFLAGS=$(gb_SPACE)
export GNUTLS_LIBS=$(gb_SPACE)
export PARALLELISM?=4
 export GNUCOPY=/usr/bin/cp
export GNUMAKE_WIN_NATIVE=
export GNUPATCH=/usr/bin/patch
export GNUTAR=bsdtar
export GOBJECT_CFLAGS=$(gb_SPACE)
export GOBJECT_LIBS=$(gb_SPACE)
export GPERF=/usr/bin/gperf
export GRAPHITE_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/graphite/include -DGRAPHITE2_STATIC
export GRAPHITE_LIBS=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/LinkTarget/StaticLibrary -lgraphite
export HARFBUZZ_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/harfbuzz/src
export HARFBUZZ_LIBS=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/harfbuzz/src/.libs -lharfbuzz
# export GREP=
export GSSAPI_LIBS=-lgssapi_krb5 
export GSTREAMER_1_0_CFLAGS=$(gb_SPACE)-pthread -isystem /usr/include/gstreamer-1.0 -isystem /usr/include/orc-0.4 -isystem /usr/include/gstreamer-1.0 -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include
export GSTREAMER_1_0_LIBS=$(gb_SPACE) -lgstpbutils-1.0 -lgstaudio-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0
export GTK3_CFLAGS=$(gb_SPACE)-pthread -isystem /usr/include/gtk-3.0/unix-print -isystem /usr/include/gtk-3.0 -isystem /usr/include/at-spi2-atk/2.0 -isystem /usr/include/at-spi-2.0 -isystem /usr/include/dbus-1.0 -isystem /usr/lib/x86_64-linux-gnu/dbus-1.0/include -isystem /usr/include/gtk-3.0 -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/cairo -isystem /usr/include/pango-1.0 -isystem /usr/include/fribidi -isystem /usr/include/harfbuzz -isystem /usr/include/atk-1.0 -isystem /usr/include/cairo -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/uuid -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED
export GTK3_LIBS=$(gb_SPACE) -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -pthread -lglib-2.0 -lcairo
export USING_X11=TRUE
export HAMCREST_JAR=
export HAVE_BROKEN_GCC_WMAYBE_UNINITIALIZED=TRUE
export HAVE_CLANG_DEBUG_INFO_KIND_CONSTRUCTOR=
export HAVE_GCC_AVX=TRUE
export HAVE_GCC_BUILTIN_ATOMIC=TRUE
export HAVE_GCC_FNO_ENFORCE_EH_SPECS=TRUE
export HAVE_GCC_FNO_SIZED_DEALLOCATION=TRUE
export HAVE_GCC_GGDB2=TRUE
export HAVE_GCC_SPLIT_DWARF=
export HAVE_GCC_STACK_CLASH_PROTECTION=TRUE
export HAVE_GNUMAKE_FILE_FUNC=TRUE
export HAVE_LD_BSYMBOLIC_FUNCTIONS=TRUE
export HAVE_LD_HASH_STYLE=TRUE
export HAVE_POSIX_FALLOCATE=YES
export HAVE_WDEPRECATED_COPY_DTOR=TRUE
export HELP_ONLINE=
export HELP_OMINDEX_PAGE=FALSE
export HOST_PLATFORM=x86_64-pc-linux-gnu
export HSQLDB_JAR=
export HSQLDB_USE_JDBC_4_1=TRUE
export HUNSPELL_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/hunspell/src/hunspell
export HUNSPELL_LIBS=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/hunspell/src/hunspell/.libs -lhunspell-1.7
export HYPHEN_LIB=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/hyphen/.libs -lhyphen
export HYPH_SYSTEM_DIR=file:///usr/share/hyphen
export ICECREAM_RUN=
# export ICECC_VERSION=
export ICU_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/icu/source/i18n -I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/icu/source/common
export ICU_LIBS=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/icu/source/lib
export ICU_MAJOR=68
export ICU_MINOR=1
export ICU_RECLASSIFIED_CONDITIONAL_JAPANESE_STARTER=TRUE
export ICU_RECLASSIFIED_HEBREW_LETTER=TRUE
export ICU_RECLASSIFIED_PREPEND_SET_EMPTY=TRUE
export ICU_UCHAR_TYPE=-DUCHAR_TYPE=uint16_t
export INTROSPECTION_SCANNER=
export ILIB=
export ILIB_FOR_BUILD=
export INSTALLDIR=/usr/local/lib/libreoffice
export INSTALLDIRNAME=libreoffice
export INSTALL_NAME_TOOL=
export INSTDIR=/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/instdir
export INSTDIR_FOR_BUILD=/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/instdir
export INSTROOT=/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/instdir
export INSTROOTBASE=/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/instdir
export INSTROOT_FOR_BUILD=/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/instdir
export IWYU_PATH=
export JAVACOMPILER=/usr/bin/javac
export JAVADOC=/usr/bin/javadoc
export JAVADOCISGJDOC=
export JAVACFLAGS=-J-Xmx128M
export JAVAIFLAGS=-Xmx64M
export JAVAIFLAGS_FOR_BUILD=-Xmx64M
export JAVA_CLASSPATH_NOT_SET=TRUE
export JAVAINTERPRETER=/usr/bin/java
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export JAVA_HOME_FOR_BUILD=/usr/lib/jvm/java-11-openjdk-amd64
export JAVA_SOURCE_VER=8
export JAVA_TARGET_VER=8
export JAWTLIB=-L/usr/lib/jvm/java-11-openjdk-amd64/lib/ -ljawt
export JDK=sun
export JDK_FOR_BUILD=sun
export JFREEREPORT_JAR=
export JITC_PROCESSOR_TYPE=
export JVM_ONE_PATH_CHECK=
export KF5_CFLAGS=$(gb_SPACE)
export KF5_LIBS=$(gb_SPACE)
export KRB5_LIBS=-lcom_err  -lkrb5 
export LCMS2_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/lcms2/include -Wno-long-long
export LCMS2_LIBS=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/lcms2/src/.libs -llcms2
export LD_GC_SECTIONS=-Wl,--gc-sections
export LD_PLUGIN=
# export LDFLAGS=  
export LFS_CFLAGS=
export LIBASSUAN_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/libassuan/src
export LIBASSUAN_LIBS=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/libassuan/src/.libs -lassuan
export LIBBASE_JAR=
export LIBDIR=/usr/local/lib
export LIBEOT_CFLAGS=$(gb_SPACE)
export LIBEOT_LIBS=$(gb_SPACE)
export LIBEXSLT_CFLAGS=$(gb_SPACE)-isystem /usr/include/libxml2
export LIBEXSLT_LIBS=$(gb_SPACE) -lexslt -lxslt -lxml2
export LIBEXTTEXTCAT_CFLAGS=$(gb_SPACE)
export LIBEXTTEXTCAT_LIBS=$(gb_SPACE)
export LIBFONTS_JAR=
export LIBFORMULA_JAR=
export LIBGCRYPT_CFLAGS=
export LIBGCRYPT_LIBS=
export LIBJPEG_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/libjpeg-turbo
export LIBJPEG_LIBS=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/libjpeg-turbo/.libs -ljpeg
export LIBLANGTAG_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/liblangtag
export LIBLANGTAG_LIBS=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/liblangtag/liblangtag/.libs -llangtag
export LIBLAYOUT_JAR=
export LIBLOADER_JAR=
export LIBNUMBERTEXT_CFLAGS=$(gb_SPACE)
export LIBNUMBERTEXT_LIBS=$(gb_SPACE)
export LIBO_BIN_FOLDER=program
export LIBO_BIN_FOLDER_FOR_BUILD=program
export LIBO_ETC_FOLDER=program
export LIBO_LIB_FOLDER=program
export LIBO_LIB_FOLDER_FOR_BUILD=program
export LIBO_LIB_PYUNO_FOLDER=program
export LIBO_SHARE_FOLDER=share
export LIBO_SHARE_HELP_FOLDER=help
export LIBO_SHARE_JAVA_FOLDER=program/classes
export LIBO_SHARE_PRESETS_FOLDER=presets
export LIBO_SHARE_READMES_FOLDER=readmes
export LIBO_SHARE_RESOURCE_FOLDER=program/resource
export LIBO_URE_BIN_FOLDER=program
export LIBO_URE_ETC_FOLDER=program
export LIBO_URE_LIB_FOLDER=program
export LIBO_URE_LIB_FOLDER_FOR_BUILD=program
export LIBO_URE_MISC_FOLDER=program
export LIBO_URE_MISC_FOLDER_FOR_BUILD=program
export LIBO_URE_SHARE_JAVA_FOLDER=program/classes
export LIBO_VERSION_MAJOR=7
export LIBO_VERSION_MICRO=0
export LIBO_VERSION_MINOR=2
export LIBO_VERSION_PATCH=0
export LIBO_VERSION_SUFFIX=.alpha0
export LIBO_VERSION_SUFFIX_SUFFIX=+
export LIBPNG_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/libpng
export LIBPNG_LIBS=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/LinkTarget/StaticLibrary -llibpng
export LIBREPOSITORY_JAR=
export LIBSERIALIZER_JAR=
export LIBTOMMATH_CFLAGS=-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/libtommath
export LIBTOMMATH_LIBS=-ltommath
export LIBTOOL=
export LIBXML_CFLAGS=$(gb_SPACE)-isystem /usr/include/libxml2
export LIBXML_JAR=
export LIBXML_LIBS=$(gb_SPACE) -lxml2
export LIBXSLT_CFLAGS=$(gb_SPACE)-isystem /usr/include/libxml2
export LIBXSLT_LIBS=$(gb_SPACE) -lxslt -lxml2
export LO_CLANG_CC=
export LO_CLANG_CXX=
export LO_CLANG_CXXFLAGS_INTRINSICS_SSE2=
export LO_CLANG_CXXFLAGS_INTRINSICS_SSSE3=
export LO_CLANG_CXXFLAGS_INTRINSICS_SSE41=
export LO_CLANG_CXXFLAGS_INTRINSICS_SSE42=
export LO_CLANG_CXXFLAGS_INTRINSICS_AVX=
export LO_CLANG_CXXFLAGS_INTRINSICS_AVX2=
export LO_CLANG_CXXFLAGS_INTRINSICS_F16C=
export LO_CLANG_CXXFLAGS_INTRINSICS_FMA=
# export LO_ELFCHECK_ALLOWLIST=
# export LS=
export MACOSX_BUNDLE_IDENTIFIER=
export MACOSX_CODESIGNING_IDENTITY=
export MACOSX_DEPLOYMENT_TARGET=
export MACOSX_PACKAGE_SIGNING_IDENTITY=
export MACOSX_SDK_PATH=
export MAC_OS_X_VERSION_MAX_ALLOWED=
export MAC_OS_X_VERSION_MIN_REQUIRED=
export MANDIR=/usr/local/share/man
export MARIADBC_MAJOR=1
export MARIADBC_MICRO=2
export MARIADBC_MINOR=0
export MARIADB_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/mariadb-connector-c/include
export MARIADB_LIBS=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/LinkTarget/StaticLibrary -lmariadb-connector-c
export LIBMARIADB=
export LIBMARIADB_PATH=
export BUNDLE_MARIADB_CONNECTOR_C=
export MDDS_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/mdds/include
export MDDS_LIBS=$(gb_SPACE)
export MERGELIBS=
export ML_EXE=
export MOC5=moc
export MPL_SUBSET=
export MSGFMT=
export MSGUNIQ=
export MSM_PATH=
export MSPUB_CFLAGS=$(gb_SPACE)
export MSPUB_LIBS=$(gb_SPACE)
export MSVC_CXX=
export MSVC_DLLS=
export MSVC_DLL_PATH=
export MSVC_USE_DEBUG_RUNTIME=
export MWAW_CFLAGS=$(gb_SPACE)
export MWAW_LIBS=$(gb_SPACE)
export MYTHES_CFLAGS=$(gb_SPACE)
export MYTHES_LIBS=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/mythes/.libs -lmythes-1.2
export NASM=nasm
export NEON_CFLAGS=$(gb_SPACE)
export NEON_LIBS=$(gb_SPACE)
export NEON_VERSION=0311
export NM=nm
export NSS_CFLAGS=$(gb_SPACE)
export NSS_LIBS=$(gb_SPACE)
export NUMBERTEXT_EXTENSION_PACK=
export nodep=
# export OBJCFLAGS=
# export OBJCXXFLAGS=
export OBJDUMP=objdump
export ODFGEN_CFLAGS=$(gb_SPACE)
export ODFGEN_LIBS=$(gb_SPACE)
export ODFVALIDATOR=sh /home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/bin/odfvalidator.sh
export OFFICEOTRON=sh /home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/bin/officeotron.sh
export BFFVALIDATOR=
export OOO_JUNIT_JAR=/usr/share/java/junit4.jar
export OOO_VENDOR=homeboy445
export OPENSSL_CFLAGS=$(gb_SPACE)
export OPENSSL_LIBS=$(gb_SPACE)
export OPENSYMBOL_TTF=f543e6e2d7275557a839a164941c0a86e5f2c3f2a0042bfc434c88c6dde9e140-opens___.ttf
export ORCUS_CFLAGS=$(gb_SPACE)
export ORCUS_LIBS=$(gb_SPACE)
export OS=LINUX
export OS_FOR_BUILD=LINUX
export PATH=/home/homeboy445/anaconda3/bin:/home/homeboy445/anaconda3/condabin:/home/homeboy445/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-11-openjdk-amd64/bin
export LIBO_PATH_SEPARATOR=:
export PAGEMAKER_CFLAGS=$(gb_SPACE)
export PAGEMAKER_LIBS=$(gb_SPACE)
export PCH_INSTANTIATE_TEMPLATES=
export PCH_CODEGEN=
export PCH_DEBUGINFO=
export PCH_NO_CODEGEN=
export PERL=/usr/bin/perl
export PKGFORMAT=
export PKGMK=
export PKG_CONFIG=/usr/bin/pkg-config
export PLATFORMID=linux_x86_64
export POPPLER_CFLAGS=$(gb_SPACE)
export POPPLER_LIBS=$(gb_SPACE)
export POSTGRESQL_INC=%OVERRIDE_ME%
export POSTGRESQL_LIB=
export PREFIXDIR=/usr/local
export PRODUCTNAME=LibreOfficeDev
export PRODUCTNAME_WITHOUT_SPACES=LibreOfficeDev
export PRODUCTVERSION=7.2
export PROGRESSBARCOLOR=
export PROGRESSFRAMECOLOR=
export PROGRESSPOSITION=
export PROGRESSSIZE=
export PROGRESSTEXTBASELINE=
export PROGRESSTEXTCOLOR=
export PTHREAD_CFLAGS=
export PTHREAD_LIBS=
export PYTHON_CFLAGS=$(gb_SPACE)-I/usr/include/python3.8
export PYTHON_FOR_BUILD=/home/homeboy445/anaconda3/bin/python
export PYTHON_LIBS=$(gb_SPACE) -lpython3.8 -lpthread -ldl -lutil -lrt
export PYTHON_VERSION=3.8
export PYTHON_VERSION_MAJOR=
export PYTHON_VERSION_MINOR=
export PYTHONWARNINGS=
export ENABLE_QRCODEGEN=TRUE
export QRCODEGEN_CFLAGS=$(gb_SPACE)
export QRCODEGEN_LIBS=$(gb_SPACE)
export ENABLE_ZXING=TRUE
export ZXING_CFLAGS=$(gb_SPACE)
export ZXING_LIBS=$(gb_SPACE)
export QT5_CFLAGS=$(gb_SPACE)
export QT5_LIBS=$(gb_SPACE)
export QT5_GOBJECT_CFLAGS=$(gb_SPACE)
export QT5_GOBJECT_LIBS=$(gb_SPACE)
export QT5_HAVE_GOBJECT=
export QXP_CFLAGS=$(gb_SPACE)
export QXP_LIBS=$(gb_SPACE)
export RANLIB=ranlib
export RAPTOR_MAJOR=0
export RASQAL_MAJOR=3
export READELF=readelf
export REDLAND_CFLAGS=$(gb_SPACE)
export REDLAND_LIBS=$(gb_SPACE)
export REDLAND_MAJOR=0
export REVENGE_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/librevenge/inc
export REVENGE_LIBS=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/librevenge/src/lib/.libs -lrevenge-0.0
export RHINO_JAR=
export RPM=
export RTL_ARCH=X86_64
export RTL_OS=Linux
export SAC_JAR=
export SAL_ENABLE_FILE_LOCKING=1
export SCPDEFS= -DWITH_POSTGRESQL_SDBC -DWITH_FIREBIRD_SDBC -DWITHOUT_EXTENSION_MEDIAWIKI -DWITH_HELPPACK_INTEGRATION -DWITH_EXTENSION_INTEGRATION -DENABLE_EXTENSION_UPDATE
export SDKDIRNAME=sdk
export SDKDIRNAME_FOR_BUILD=sdk
export SERF_CFLAGS=$(gb_SPACE)
export SERF_LIBS=$(gb_SPACE)
export SHA256SUM=shasum -a 256
export SHOWINCLUDES_PREFIX=
export SOLARINC=-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/include  -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux
export SORT=sort
export SPLIT_APP_MODULES=
export SPLIT_OPT_FEATURES=
export SRCDIR=/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice
export STAROFFICE_CFLAGS=$(gb_SPACE)
export STAROFFICE_LIBS=$(gb_SPACE)
export STRIP=strip
export STRIP_COMPONENTS=--strip-components
export SYSBASE=
export SYSTEM_ABW=
export SYSTEM_APACHE_COMMONS=
export SYSTEM_APR=
export SYSTEM_BLUEZ=
export SYSTEM_BOOST=
export SYSTEM_BSH=
export SYSTEM_BOX2D=
export SYSTEM_BZIP2=
export SYSTEM_CAIRO=TRUE
export SYSTEM_CLUCENE=
export SYSTEM_CPPUNIT=
export SYSTEM_CURL=
export SYSTEM_DICTS=TRUE
export SYSTEM_EXPAT=
export SYSTEM_FONTCONFIG=TRUE
export SYSTEM_FREETYPE=TRUE
export SYSTEM_FIREBIRD=
export SYSTEM_GENBRK=
export SYSTEM_GENCCODE=
export SYSTEM_GENCMN=
export SYSTEM_EPOXY=
export SYSTEM_GLM=
export SYSTEM_GPGMEPP=
export SYSTEM_GRAPHITE=
export SYSTEM_HARFBUZZ=
export SYSTEM_HSQLDB=
export SYSTEM_HUNSPELL=
export SYSTEM_HYPH=
export SYSTEM_ICU=
export SYSTEM_JFREEREPORT=
export SYSTEM_LIBJPEG=
export SYSTEM_LCMS2=
export SYSTEM_CDR=
export SYSTEM_LIBCMIS=
export SYSTEM_EBOOK=
export SYSTEM_ETONYEK=
export SYSTEM_EPUBGEN=
export SYSTEM_FREEHAND=
export SYSTEM_LIBATOMIC_OPS=
export SYSTEM_LIBEOT=
export SYSTEM_LIBEXTTEXTCAT=
export SYSTEM_LIBEXTTEXTCAT_DATA=
export SYSTEM_LIBLANGTAG=
export SYSTEM_LIBNUMBERTEXT=
export SYSTEM_LIBNUMBERTEXT_DATA=
export SYSTEM_LIBORCUS=
export SYSTEM_LIBPNG=
export SYSTEM_LIBTOMMATH=
export SYSTEM_LIBXML=TRUE
export SYSTEM_LIBXML_FOR_BUILD=TRUE
export SYSTEM_LIBXSLT=TRUE
export SYSTEM_LIBXSLT_FOR_BUILD=TRUE
export SYSTEM_LPSOLVE=
export SYSTEM_MDDS=
export SYSTEM_MARIADB_CONNECTOR_C=
export SYSTEM_MSPUB=
export SYSTEM_MWAW=
export SYSTEM_MYTHES=
export SYSTEM_NEON=
export SYSTEM_NSS=
export SYSTEM_ODBC_HEADERS=
export SYSTEM_ODFGEN=
export SYSTEM_OPENLDAP=
export SYSTEM_OPENSSL=
export SYSTEM_PAGEMAKER=
export SYSTEM_POPPLER=
export SYSTEM_POSTGRESQL=
export SYSTEM_PYTHON=TRUE
export SYSTEM_QRCODEGEN=
export SYSTEM_ZXING=
export SYSTEM_QXP=
export SYSTEM_REDLAND=
export SYSTEM_REVENGE=
export SYSTEM_RHINO=
export SYSTEM_SERF=
export SYSTEM_STAROFFICE=
export SYSTEM_UCPP=
export SYSTEM_VISIO=
export SYSTEM_WPD=
export SYSTEM_WPG=
export SYSTEM_WPS=
export SYSTEM_XMLSEC=
export SYSTEM_ZLIB=TRUE
export SYSTEM_ZMF=
export TARFILE_LOCATION=/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/external/tarballs
export TESTINSTALLDIR=/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/test-install
export THES_SYSTEM_DIR=file:///usr/share/mythes
export TLS=NSS
export TMPDIR=/tmp
export TOUCH=/usr/bin/touch
export UCRTSDKDIR=
export UCRTVERSION=
export UCRT_REDISTDIR=
export USE_LD=
export USE_LIBRARY_BIN_TAR=
export USE_XINERAMA=TRUE
export UPDATE_CONFIG=
export UUIDGEN=/usr/bin/uuidgen
export VALGRIND_CFLAGS=$(gb_SPACE)
export VCVER=
export DEVENV=
export VISIO_CFLAGS=$(gb_SPACE)
export VISIO_LIBS=$(gb_SPACE)
export WGET=wget
export WINDOWS_BUILD_SIGNING=FALSE
export WINDOWS_SDK_HOME=
export WINDOWS_SDK_LIB_SUBDIR=
export WINDOWS_SDK_VERSION=
export WINDOWS_SDK_WILANGID=
export WINDOWS_X64=
export WINDRES=
export WITH_COMPAT_OOWRAPPERS=
export WITH_EXTENSION_INTEGRATION=TRUE
export WITH_EXTRA_EXTENSIONS=
export WITH_FONTS=TRUE
export WITH_GALLERY_BUILD=TRUE
export WITH_GSSAPI=TRUE
export WITH_KRB5=TRUE
export WITH_LINKER_HASH_STYLE=gnu
export WITH_LOCALES=
export WITH_MYSPELL_DICTS=
export WITH_POOR_HELP_LOCALIZATIONS=
export WITH_THEMES= breeze breeze_dark breeze_dark_svg breeze_svg colibre colibre_svg elementary elementary_svg karasa_jaga karasa_jaga_svg sifr sifr_dark sifr_dark_svg sifr_svg sukapura sukapura_svg 
export WITH_WEBDAV=neon
export WORKDIR=/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir
export WORKDIR_FOR_BUILD=/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir
export WPD_CFLAGS=$(gb_SPACE)-I/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/libwpd/inc
export WPD_LIBS=$(gb_SPACE)-L/home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/workdir/UnpackedTarball/libwpd/src/lib/.libs -lwpd-0.10
export WPG_CFLAGS=$(gb_SPACE)
export WPG_LIBS=$(gb_SPACE)
export WPS_CFLAGS=$(gb_SPACE)
export WPS_LIBS=$(gb_SPACE)
export XINERAMA_LINK=dynamic
export XMLLINT=/home/homeboy445/anaconda3/bin/xmllint
export XMLSEC_CFLAGS=$(gb_SPACE)
export XMLSEC_LIBS=$(gb_SPACE)
export XRANDR_CFLAGS=$(gb_SPACE)
export XRANDR_LIBS=$(gb_SPACE) -lXrandr
export XRENDER_CFLAGS=$(gb_SPACE)
export XRENDER_LIBS=$(gb_SPACE) -lXrender -lX11
export XSLTPROC=/home/homeboy445/anaconda3/bin/xsltproc
export ZLIB_CFLAGS=$(gb_SPACE)
export ZLIB_LIBS=$(gb_SPACE)-lz
export ZMF_CFLAGS=$(gb_SPACE)
export ZMF_LIBS=$(gb_SPACE)
export USE_AVMEDIA_DUMMY=

# lang-related stuff
include $(BUILDDIR)/config_$(gb_Side)_lang.mk

# tarball names
# does use some of the variables defined above
include /home/homeboy445/DevFolder/OpenSource/LibreOffice/libreoffice/download.lst
