# -*- Mode: makefile-gmake; tab-width: 4; indent-tabs-mode: t -*-

ifeq ($(strip $(SOLARENV)),)
include $(dir $(realpath $(firstword $(MAKEFILE_LIST))))config_host.mk
endif

include $(SOLARENV)/gbuild/gbuild.mk

$(eval $(call gb_Module_make_global_targets,$(wildcard $(SRCDIR)/RepositoryModule_*.mk)))

# vim: set noet sw=4 ts=4:
