#ifndef INCLUDED_SWDLLAPI_H
#define INCLUDED_SWDLLAPI_H

#ifndef _SAL_TYPES_H_
#include "sal/types.h"
#endif

#if defined(SW_DLLIMPLEMENTATION)
#define SW_DLLPUBLIC  SAL_DLLPUBLIC_EXPORT
#else
#define SW_DLLPUBLIC  SAL_DLLPUBLIC_IMPORT
#endif
#define SW_DLLPRIVATE SAL_DLLPRIVATE

#endif /* INCLUDED_SWDLLAPI_H */
