
# mak file fuer unxfbsdi

ASM=
AFLAGS=

SOLAR_JAVA=TRUE
JAVAFLAGSDEBUG=-g

LINKOUTPUT_FILTER=" |& $(SOLARENV)$/bin$/msg_filter"


cc=				gcc
CC=				g++
CDEFS+=			-D_USE_NAMESPACE=1 -DX86 -DNEW_SOLAR -DSTLPORT_VERSION=400
CDEFS+=			-D_REENTRANT -D_PTHREADS -D_THREAD_SAFE
CFLAGS+= -w -c $(INCLUDE)
CFLAGS+= -I/usr/X11R6/include
CFLAGSCC= -pipe
CFLAGSCXX= -pipe -fno-for-scope -fpermissive
CFLAGSEXCEPTIONS= -fexceptions
CFLAGS_NO_EXCEPTIONS= -fno-exceptions
CFLAGSOBJGUIST= -fPIC
CFLAGSOBJCUIST= -fPIC
CFLAGSOBJGUIMT= -fPIC
CFLAGSOBJCUIMT= -fPIC
CFLAGSSLOGUIMT=	-fPIC
CFLAGSSLOCUIMT=	-fPIC
CFLAGSPROF=     -pg
CFLAGSDEBUG=	-g
CFLAGSDBGUTIL=
CFLAGSOPT= -O2
CFLAGSNOOPT= -O
CFLAGSOUTOBJ= -o

STATIC=	-Wl,-Bstatic
DYNAMIC= -Wl,-Bdynamic

#THREADLIB= -pthread
LINK= gcc
# -v -nostdlib
LINKFLAGS=
LINKFLAGSAPPGUI= -Wl,-export-dynamic
LINKFLAGSAPPCUI= -Wl,-export-dynamic
LINKFLAGSSHLGUI= -shared
LINKFLAGSSHLCUI= -shared
LINKFLAGSTACK=
LINKFLAGSPROF=
LINKFLAGSDEBUG=-g
LINKFLAGSOPT=

.IF "$(NO_BSYMBOLIC)"==""
.IF "$(PRJNAME)" != "envtest"
LINKFLAGSSHLGUI+= -Wl,-Bsymbolic
LINKFLAGSSHLCUI+= -Wl,-Bsymbolic
.ENDIF
.ENDIF

LINKVERSIONMAPFLAG=-Wl,--version-script

STDLIBCPP=-lstdc++

# _SYSLIBS= -L/usr/lib -lm
# _X11LIBS= -L/usr/X11R6/lib -lXext -lXt -lX11
# _CXXLIBS= -L/usr/lib -lstdc++ -L/usr/local/lib

STDOBJGUI=
STDSLOGUI=
STDOBJCUI=
STDSLOCUI=

STDLIBCUIST=-lm
STDLIBGUIST==-lXaw -lXt -lX11 -lm
STDLIBGUIMT=-pthread -lm -lstlport_gcc
STDLIBCUIMT=-pthread -lm -lstlport_gcc
STDSHLGUIMT=-lXaw -lXt -lX11 -lXext -pthread -lm -lstlport_gcc
STDSHLCUIMT=-pthread -lm -lstlport_gcc

LIBMGR=			ar
LIBFLAGS=		-r
LIBEXT=			.a

IMPLIB=
IMPLIBFLAGS=

MAPSYM=
MAPSYMFLAGS=

RC=irc
RCFLAGS=		-fo$@ $(RCFILES)
RCLINK=
RCLINKFLAGS=
RCSETVERSION=

DLLPOSTFIX=		fi
DLLPRE=			lib
DLLPOST=		.so
LDUMP=
