# mk file fuer unxsogs
ASM=
AFLAGS=

SOLAR_JAVA=TRUE
JAVAFLAGSDEBUG=-g

# _PTHREADS is needed for the stl
CDEFS+=-D_PTHREADS -D_REENTRANT -DSYSV -DSUN -DSUN4 -D_POSIX_PTHREAD_SEMANTICS -DSTLPORT_VERSION=400
 
CVER=C295
CDEFS+=-DCVER=$(CVER)
CDEFS+=-D_USE_NAMESPACE=1

.IF "$(SOLAR_JAVA)"!=""
JAVADEF=-DSOLAR_JAVA
.IF "$(debug)"==""
JAVA_RUNTIME=-ljava
.ELSE
JAVA_RUNTIME=-ljava_g
.ENDIF
.ENDIF 

CC=g++
cc=gcc
CFLAGS=-w -c $(INCLUDE)
CFLAGSCC= -pipe

CFLAGSEXCEPTIONS=-fexceptions
CFLAGS_NO_EXCEPTIONS=-fno-exceptions

CFLAGSCXX= -pipe -fno-for-scope -fpermissive

#STDOBJVCL=$(L)$/salmain.o
CFLAGSOBJGUIST=
CFLAGSOBJCUIST=
CFLAGSOBJGUIMT=
CFLAGSOBJCUIMT=
CFLAGSSLOGUIMT=-fPIC
CFLAGSSLOCUIMT=-fPIC
CFLAGSPROF=
CFLAGSDEBUG=-g
CFLAGSDBGUTIL=
CFLAGSOPT=-O2
CFLAGSNOOPT=-O
CFLAGSOUTOBJ=-o

STATIC		= -Wl,-Bstatic
DYNAMIC		= -Wl,-Bdynamic

LINK=gcc
LINKFLAGS=
LINKFLAGSAPPGUI=-Wl,-export-dynamic
LINKFLAGSSHLGUI=-shared
LINKFLAGSAPPCUI=-Wl,-export-dynamic
LINKFLAGSSHLCUI=-shared
LINKFLAGSTACK=
LINKFLAGSPROF=
LINKFLAGSDEBUG=-g
LINKFLAGSOPT=

LINKVERSIONMAPFLAG=-Wl,--version-script

# Reihenfolge der libs NICHT egal!

STDLIBCPP=-lstdc++

STDOBJGUI=
STDSLOGUI=
STDOBJCUI=
STDSLOCUI=

STDLIBGUIST=-lnsl -lsocket -ldl -lm -lstlport_gcc
STDLIBCUIST=-lnsl -lsocket -ldl -lm -lstlport_gcc
STDLIBGUIMT=-lpthread -ldl -lm -lstlport_gcc
STDLIBCUIMT=-lpthread -ldl -lm -lstlport_gcc
# libraries for linking shared libraries
STDSHLGUIMT=-lpthread -lnsl -lsocket -ldl -lm -lstlport_gcc
STDSHLCUIMT=-lpthread -ldl -lm -lstlport_gcc

STDLIBGUIST+=-lXm -lXt -lX11
STDLIBGUIMT+=-lXm -lXt -lX11

LIBMGR=ar
LIBFLAGS=-r
# LIBEXT=.so

IMPLIB=
IMPLIBFLAGS=

MAPSYM=
MAPSYMFLAGS=

RC=irc
RCFLAGS=-fo$@ $(RCFILES)
RCLINK=
RCLINKFLAGS=
RCSETVERSION=

DLLPOSTFIX=ss
DLLPRE=lib
DLLPOST=.so
