/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_awt_grid_XSortableMutableGridDataModel_idl__
#define __com_sun_star_awt_grid_XSortableMutableGridDataModel_idl__

#include <com/sun/star/awt/grid/XMutableGridDataModel.idl>
#include <com/sun/star/awt/grid/XSortableGridData.idl>


module com { module sun { module star { module awt { module grid {


/** describes a grid control data model whose data can be modified and sorted.
 */
interface XSortableMutableGridDataModel
{
    /** provides access to the basic functionality of a grid data model, plus functions to modify it.
    */
    interface XMutableGridDataModel;

    /** provides means to sort the data represented by the model.

        <p>If you set a new column sort order, the implementation will notify the registered <type>XGridDataListener</type>s
        via a call to its <member>XGridDataListener::dataChanged</member> method.</p>
    */
    interface XSortableGridData;
};


}; }; }; }; };


#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
