/*************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Copyright 2000, 2010 Oracle and/or its affiliates.
 *
 * OpenOffice.org - a multi-platform office productivity suite
 *
 * This file is part of OpenOffice.org.
 *
 * OpenOffice.org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License version 3
 * only, as published by the Free Software Foundation.
 *
 * OpenOffice.org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License version 3 for more details
 * (a copy is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3 along with OpenOffice.org.  If not, see
 * <http://www.openoffice.org/license.html>
 * for a copy of the LGPLv3 License.
 *
 ************************************************************************/
#ifndef __com_sun_star_accessibility_AccessibleRelation_idl__
#define __com_sun_star_accessibility_AccessibleRelation_idl__

#include <com/sun/star/uno/XInterface.idl>

module com { module sun { module star { module accessibility {

/** An <type>AccessibleRelation</type> object defines a one-to-many
    relation.

    <p>The represented relation points from the implementing object to a set
    of target objects.</p>

    @since OOo 1.1.2
*/
published struct AccessibleRelation
{
    /** Type of the relation.

        <p>Its value has to be one of the constants defined by
        <type>AccessibleRelationType</type>.  If that value is INVALID then
        the whole relation is regarded as invalid.  The content of the
        TargetSet is then undefined.</p>

        @see AccessibleRelationType
    */
    short RelationType;

    /** Set of objects that are the relation's targets.

        <p>The content of this set is undefined if the relation's type is
        INVALID.  The set must not contain references to one object more
        than once.</p>
    */
    sequence< ::com::sun::star::uno::XInterface> TargetSet;
};

}; }; }; };

#endif
