/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_accessibility_Accessible_idl__
#define __com_sun_star_accessibility_Accessible_idl__

module com { module sun { module star { module accessibility {

 interface    XAccessible;

/** Every class has to support this service in order to be accessible.

    <p>It provides the means to derive a XAccessibleContext
    object--which may but usually is not the same object as the object that
    supports the XAccessible interface--that provides the
    actual information that is needed to make it accessible.</p>

    <p>Service <code>Accessible</code> is just a wrapper for the interface
    <code>XAccessible</code>.  See the interface's documentation for more
    information.</p>

    @see XAccessible

    @since OOo 1.1.2
*/
service Accessible
{
    interface XAccessible;
};

}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
