/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: CannotActivateFactoryException.idl,v $
 *
 *  $Revision: 1.11 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-09 15:51:34 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_loader_CannotActivateFactoryException_idl__
#define __com_sun_star_loader_CannotActivateFactoryException_idl__

#ifndef __com_sun_star_uno_Exception_idl__
#include <com/sun/star/uno/Exception.idl>
#endif

//=============================================================================

 module com {  module sun {  module star {  module loader {

//=============================================================================

/** indicates an error during component activation
    <p> This exception is thrown when an application tries to
    activate a component factory using the
    <member>XImplementationLoader::activate()</member>
    method, but the component factory can not be activated.
    <p>
    Possible reasons for this error is a missing shared library or .jar file,
    a badly linked library, a wrong LD_LIBRARY_PATH or PATH, an incomplete
    classpath, or a missing java installation. The Message should
    contain some more detailed explanations.
 */
published exception CannotActivateFactoryException: com::sun::star::uno::Exception
{
};

//=============================================================================

}; }; }; };

/*=============================================================================

=============================================================================*/
#endif
