/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_lang_MultiServiceFactory_idl__
#define __com_sun_star_lang_MultiServiceFactory_idl__

#ifndef __com_sun_star_lang_XMultiServiceFactory_idl__
#include <com/sun/star/lang/XMultiServiceFactory.idl>
#endif
#ifndef __com_sun_star_lang_XMultiComponentFactory_idl__
#include <com/sun/star/lang/XMultiComponentFactory.idl>
#endif

#ifndef __com_sun_star_lang_XServiceInfo_idl__
#include <com/sun/star/lang/XServiceInfo.idl>
#endif


//=============================================================================

module com {  module sun {  module star {  module lang {

//=============================================================================

/** Provides a collection of implementations of services.

    <p>The factories for instantiating objects of implemetations
    are accessed via a service name.</p>

    <p>The <type scope="com::sun::star::container">XContentEnumerationAccess</type>
    interface can be supported optionally.
    If it is suported, it is possible to  enumerate all implementations that
    support the service specified with the argument of
    <member scope="com::sun::star::container">XContentEnumerationAccess::createContentEnumeration</member>.
    The enumerator returns interfaces. The type of the interface is not specified.
    Commonly this is <type>XSingleComponentFactory</type>.</p>
*/
published service MultiServiceFactory
{
    /** This interface uses a service name to instantiate a component
        which supports the specified service.
    */
    interface com::sun::star::lang::XMultiServiceFactory;

    /** This interface uses a service name and a component context to instantiate
        a component which supports the specified service.
    */
    interface com::sun::star::lang::XMultiComponentFactory;

    /** Factories, as well as all other services, should always support
        this interface.
    */
    interface com::sun::star::lang::XServiceInfo;
};

//=============================================================================

}; }; }; };

/*=============================================================================

=============================================================================*/
#endif
