/*************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Copyright 2000, 2010 Oracle and/or its affiliates.
 *
 * OpenOffice.org - a multi-platform office productivity suite
 *
 * This file is part of OpenOffice.org.
 *
 * OpenOffice.org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License version 3
 * only, as published by the Free Software Foundation.
 *
 * OpenOffice.org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License version 3 for more details
 * (a copy is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3 along with OpenOffice.org.  If not, see
 * <http://www.openoffice.org/license.html>
 * for a copy of the LGPLv3 License.
 *
 ************************************************************************/
#ifndef __com_sun_star_lang_XInitialization_idl__
#define __com_sun_star_lang_XInitialization_idl__

#include <com/sun/star/uno/XInterface.idl>

#include <com/sun/star/uno/Exception.idl>


//=============================================================================

module com {  module sun {  module star {  module lang {

//=============================================================================

// DocMerge from xml: interface com::sun::star::lang::XInitialization
/** initializes an object directly after its creation.

    <p>This interface works together with factories. If you want to
    initialize the object after creation, you should
    support this interface and you may support other interfaces
    which offer type-safe initialization methods.  </p>

    <p>Instead of calling <member>XSingleComponentFactory::createInstanceWithContext</member>
    and later initialize(), you should call
    <member>XSingleComponentFactory::createInstanceWithArgumentsAndContext</member>
    to pass the arguments to the instance. The reason is, that a component may want to
    return the same instance for the same set of parameters, and it can do so by implementing
    the factory itself.
    </p>

 */
published interface XInitialization: com::sun::star::uno::XInterface
{
    //-------------------------------------------------------------------------

    // DocMerge from xml: method com::sun::star::lang::XInitialization::initialize
    /** initializes the object.

        <p>It should be called directly after the object is created.
     */
    void initialize( [in] sequence<any> aArguments )
            raises( com::sun::star::uno::Exception );

};

//=============================================================================

}; }; }; };

/*=============================================================================

=============================================================================*/
#endif
