/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: EffectCommands.idl,v $
 *
 *  $Revision: 1.3 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 02:36:31 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_presentation_EffectCommands_idl__
#define __com_sun_star_presentation_EffectCommands_idl__

//=============================================================================

 module com {  module sun {  module star {  module presentation {

//=============================================================================

/**
    @see ::com::sun::star::animations::XCommand
*/
constants EffectCommands
{
    /** the command is user defined
    */
    const short CUSTOM = 0;

    /** the command is an ole verb.
        Required parameters are
            "Verb" of type long that specifies the verb to execute.
    */
    const short VERB = 1;

    /** the command starts playing on a media object.
        Optional parameters are
            "MediaTime" of type double that specifies the start
            time in mili seconds. If not given, play continues at
            last position known.
    */
    const short PLAY = 2;

    /** the command toggles the pause status on a media object.
    */
    const short TOGGLEPAUSE = 3;

    /** the command stops the animation on a media object
    */
    const short STOP = 4;

    /** the command stops all currently running sound effects.
    */
    const short STOPAUDIO = 5;
};

//=============================================================================

}; }; }; };

#endif
