/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: Presentation.idl,v $
 *
 *  $Revision: 1.12 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 02:40:22 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_presentation_Presentation_idl__
#define __com_sun_star_presentation_Presentation_idl__

#ifndef __com_sun_star_presentation_XPresentation_idl__
#include <com/sun/star/presentation/XPresentation.idl>
#endif

#ifndef __com_sun_star_beans_XPropertySet_idl__
#include <com/sun/star/beans/XPropertySet.idl>
#endif


//=============================================================================

 module com {  module sun {  module star {  module presentation {

//=============================================================================

/** This service is a presentation that is available from a
    <type>PresentationDocument</type> via the
    <type>XPresentationSupplier</type> interface.
 */
published service Presentation
{
    /** lets you start and stop a presentation.

        <p>It also gives you access to the more advanced features, like
        rehearse timing and the live modes.
     */
    interface com::sun::star::presentation::XPresentation;

    //-------------------------------------------------------------------------

    /** This is the standard interface for access to the properties from this
        service.
     */
    interface com::sun::star::beans::XPropertySet;

    //-------------------------------------------------------------------------

    /** enables/disables the shape animations.
     */
    [property] boolean AllowAnimations;

    //-------------------------------------------------------------------------

    /** If this string is not empty, it contains the name of a customized
        show that is used for the presentation.
     */
    [property] string CustomShow;

    //-------------------------------------------------------------------------

    /** If this string is not empty, it contains the name of the page where
        the presentation is started.
     */
    [property] string FirstPage;

    //-------------------------------------------------------------------------

    /** If this property is set to <TRUE/>, the window of the presentation is
        always on top of all other windows.
     */
    [property] boolean IsAlwaysOnTop;

    //-------------------------------------------------------------------------

    /** If this property is <TRUE/>, all pages are changed automatically.

        <p>This overrides the properties of the pages.</p>
     */
    [property] boolean IsAutomatic;

    //-------------------------------------------------------------------------

    /** If this property is set to <TRUE/>, the presentation is repeated
        endlessly.
     */
    [property] boolean IsEndless;

    //-------------------------------------------------------------------------

    /** If this property is set to <TRUE/>, the presentation runs in
        full-screen mode.
     */
    [property] boolean IsFullScreen;

    //-------------------------------------------------------------------------

    /** With this property, you can set the presentation to live mode.
        <p>Implementations that have no live mode capability may ignore this
        property and always return false.
     */
    [property] boolean IsLivePresentation;

    //-------------------------------------------------------------------------

    /** If this property is <TRUE/>, the mouse is visible during the
        presentation.
     */
    [property] boolean IsMouseVisible;

    //-------------------------------------------------------------------------

    /** is the duration of the black screen after the
        presentation has finished.

        <p>If this is set to <literal>0</literal>, no black screen is shown.</p>
     */
    [property] long Pause;

    //-------------------------------------------------------------------------

    /** If this is set to <TRUE/>, the Navigator is opened at the start of the
        presentation.
     */
    [property] boolean StartWithNavigator;

    //-------------------------------------------------------------------------

    /** If this is <TRUE/>, a pen is shown during presentation.

        <p>You can draw on the presentation with this pen.</p>
     */
    [property] boolean UsePen;

};

//=============================================================================

}; }; }; };

#endif
