/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_presentation_XShapeEventListener_idl__
#define __com_sun_star_presentation_XShapeEventListener_idl__

#ifndef __com_sun_star_lang_XEventListener_idl__
#include <com/sun/star/lang/XEventListener.idl>
#endif
#ifndef __com_sun_star_awt_XMouseListener_idl__
#include <com/sun/star/awt/XMouseListener.idl>
#endif
#ifndef __com_sun_star_drawing_XShape_idl__
#include <com/sun/star/drawing/XShape.idl>
#endif

module com {  module sun {  module star {  module presentation {

/** Listener interface to receive shape-specific events.<p>

    @since OpenOffice 2.4
 */
interface XShapeEventListener : ::com::sun::star::lang::XEventListener
{
    /** Notify a clicked shape.<p>

        This method notifies the listener that a shape was
        clicked.<p>

        @param xShape
        The shape that was clicked upon.

        @param aOriginalEvent
        The original mouse click event that generated this notification.
     */
    void click( [in] ::com::sun::star::drawing::XShape  xShape,
                [in] ::com::sun::star::awt::MouseEvent  aOriginalEvent );
};

}; }; }; };


#endif
