/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_script_ScriptEvent_idl__
#define __com_sun_star_script_ScriptEvent_idl__

#include <com/sun/star/script/AllEventObject.idl>



 module com {  module sun {  module star {  module script {

/** script event that gets delivered whenever a script event takes place.
    <p>For that to happen, a "ScriptEventDescriptor" must be registered at
    and attached to an object by an <type>XEventAttacherManager</type>.</p>
 */
published struct ScriptEvent: com::sun::star::script::AllEventObject
{
    /** type of the script language as string; for example, "Basic" or "StarScript".
     */
    string ScriptType;

    /** script code as string.

        <p>The code has to correspond with the language
        defined by ScriptType.</p>
     */
    string ScriptCode;

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
