/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_script_XAllListener_idl__
#define __com_sun_star_script_XAllListener_idl__

#include <com/sun/star/lang/XEventListener.idl>

#include <com/sun/star/script/AllEventObject.idl>

#include <com/sun/star/reflection/InvocationTargetException.idl>



 module com {  module sun {  module star {  module script {

/** specifies a listener combining all methods
    of a listener interface in a single generic call.

    <p>Without any output parameters, it is possible to adapt any interface
    if the XAllListenerAdapterService can generate an adapter.</p>
 */
published interface XAllListener: com::sun::star::lang::XEventListener
{
    /** gets called when an event occurs at the object.
     */
    void firing( [in] com::sun::star::script::AllEventObject iaEvent );

    /** gets called when a "vetoable event" occurs at the object.

        <p>That happens when the listener method raises an exception,
        or has a return value declared.</p>
     */
    any approveFiring( [in] com::sun::star::script::AllEventObject aEvent )
            raises( com::sun::star::reflection::InvocationTargetException );
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
