/*************************************************************************
 *
 *  $RCSfile: XInvocation.idl,v $
 *
 *  $Revision: 1.1 $
 *
 *  last change: $Author: mi $ $Date: 2000-11-06 12:21:53 $
 *
 *  The Contents of this file are made available subject to the terms of
 *  either of the following licenses
 *
 *         - GNU Lesser General Public License Version 2.1
 *         - Sun Industry Standards Source License Version 1.1
 *
 *  Sun Microsystems Inc., October, 2000
 *
 *  GNU Lesser General Public License Version 2.1
 *  =============================================
 *  Copyright 2000 by Sun Microsystems, Inc.
 *  901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License version 2.1, as published by the Free Software Foundation.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *  MA  02111-1307  USA
 *
 *
 *  Sun Industry Standards Source License Version 1.1
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.1 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://www.openoffice.org/license.html.
 *
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 *
 *  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 *
 *  Copyright: 2000 by Sun Microsystems, Inc.
 *
 *  All Rights Reserved.
 *
 *  Contributor(s): _______________________________________
 *
 *
 ************************************************************************/
#ifndef __com_sun_star_script_XInvocation_idl__
#define __com_sun_star_script_XInvocation_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __com_sun_star_beans_XIntrospectionAccess_idl__
#include <com/sun/star/beans/XIntrospectionAccess.idl>
#endif

#ifndef __com_sun_star_lang_IllegalArgumentException_idl__
#include <com/sun/star/lang/IllegalArgumentException.idl>
#endif

#ifndef __com_sun_star_script_CannotConvertException_idl__
#include <com/sun/star/script/CannotConvertException.idl>
#endif

#ifndef __com_sun_star_reflection_InvocationTargetException_idl__
#include <com/sun/star/reflection/InvocationTargetException.idl>
#endif

#ifndef __com_sun_star_beans_UnknownPropertyException_idl__
#include <com/sun/star/beans/UnknownPropertyException.idl>
#endif


//=============================================================================

 module com {  module sun {  module star {  module script {

//=============================================================================

// DocMerge from xml: interface com::sun::star::script::XInvocation
/** makes it possible to invoke methods and set/get properties at an object
    which corresponds with the object which implements this interface.

    Container access is available through <type scope="com::sun::star::container">XIndexContainer</type>,
    <type scope="com::sun::star::container">XNameContainer</type> and
    <type scope="com::sun::star::container">XEnumerationAccess</type>.
    </p>
 */
[ uik(E227A3C2-33D6-11D1-AABE00A0-249D5590), ident( "XInvocation", 1.0 ) ]
interface XInvocation: com::sun::star::uno::XInterface
{
    //-------------------------------------------------------------------------

    // DocMerge from idl: method com::sun::star::script::XInvocation::getIntrospection
    /** @returns
                the introspection from this object or <NULL/> if the object
                does not provide this information.
     */
    [const] com::sun::star::beans::XIntrospectionAccess getIntrospection();

    //-------------------------------------------------------------------------

    // DocMerge from xml: method com::sun::star::script::XInvocation::invoke
    /** provides access to properties and methods exposed by an object.

        @param aParams all parameters; pure out params are undefined in sequence,
                       i.e. the value has to be ignored by the callee
        @param aOutParamIndex out indices
        @param aOutParam out parameters
     */
    any invoke( [in] string aFunctionName,
             [in] sequence<any> aParams,
             [out] sequence<short> aOutParamIndex,
             [out] sequence<any> aOutParam )
            raises( com::sun::star::lang::IllegalArgumentException,
                    com::sun::star::script::CannotConvertException,
                    com::sun::star::reflection::InvocationTargetException );

    //-------------------------------------------------------------------------

    // DocMerge from xml: method com::sun::star::script::XInvocation::setValue
    /** sets a value to the property with the specified name.

        <p> If the underlying object implements an
        <type scope="com::sun::star::container">XNameContainer</type>, then this method will insert the
        value if there is no such <var>aPropertyName</var>.

        </p>
     */
    void setValue( [in] string aPropertyName,
             [in] any aValue )
            raises( com::sun::star::beans::UnknownPropertyException,
                    com::sun::star::script::CannotConvertException,
                    com::sun::star::reflection::InvocationTargetException );

    //-------------------------------------------------------------------------

    // DocMerge from idl: method com::sun::star::script::XInvocation::getValue
    /** @returns
                the value of the property with the specified name.

                @param aPropertyName
                specifies the name of the property.
     */
    any getValue( [in] string aPropertyName )
            raises( com::sun::star::beans::UnknownPropertyException );

    //-------------------------------------------------------------------------

    // DocMerge from idl: method com::sun::star::script::XInvocation::hasMethod
    /** @returns
                <TRUE/> if the method with the specified name exists.

                <p>This optimizes the calling sequence
                ( <method>XInvocation::hasMethod</method>, <method>XInvocation::invoke</method> )!

                @param aName
                specifies the name of the method.
     */
    [const] boolean hasMethod( [in] string aName );

    //-------------------------------------------------------------------------

    // DocMerge from idl: method com::sun::star::script::XInvocation::hasProperty
    /** @returns
                <TRUE/> if the property with the specified name exists.

                <p>This optimizes the calling sequence
                ( <method>XInvocation::hasProperty</method>,
                <method>XInvocation::getValue</method> ) or

                ( <method>XInvocation::hasProperty</method>,
                <method>XInvocation::setValue</method> )!

                @param aName
                specifies the name of the property.
     */
    [const] boolean hasProperty( [in] string aName );

};

//=============================================================================

}; }; }; };

/*=============================================================================

    $Log: not supported by cvs2svn $
    Revision 1.1  2000/11/03 15:07:34  mi
    moved from api module

    Revision 1.2  2000/10/06 14:43:29  dbo
    added doc for XInvocation::invoke()

    Revision 1.1.1.1  2000/09/18 23:35:36  hjs
    initial import

    Revision 1.4  2000/09/11 11:52:38  mi
    documentation merged from XML

    Revision 1.2  2000/02/07 11:24:51  mi
    zu #70728# missing documentation marked

    Revision 1.1  1999/12/06 12:47:55  ab
    #70472# Invokation -> Invocation

    Revision 1.3  1999/11/24 17:48:18  mi
    documentation welformed

    Revision 1.2  1999/11/11 13:35:24  dbo
    doc

    Revision 1.1.1.1  1999/11/11 09:48:45  jsc
    new


=============================================================================*/
#endif
