# Auto-generated by pythonmaker - DO NOT EDIT.
from __future__ import annotations

from test.codemaker.pythonmaker.Enum2 import Enum2 as test_codemaker_pythonmaker_Enum2_

Enum = test_codemaker_pythonmaker_Enum2_
