# Auto-generated by pythonmaker - DO NOT EDIT.
from __future__ import annotations

from com.sun.star.uno.XComponentContext import XComponentContext as com_sun_star_uno_XComponentContext_
from test.codemaker.pythonmaker.XTest import XTest as test_codemaker_pythonmaker_XTest_

class S2:
    @staticmethod
    def create(ctx: com_sun_star_uno_XComponentContext_) -> test_codemaker_pythonmaker_XTest_:
        ...

