/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: BindableDatabaseComboBox.idl,v $
 *
 *  $Revision: 1.3 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 00:31:35 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/

#ifndef __com_sun_star_form_binding_BindableDatabaseComboBox_idl__
#define __com_sun_star_form_binding_BindableDatabaseComboBox_idl__

#ifndef __com_sun_star_form_component_DatabaseComboBox_idl__
#include <com/sun/star/form/component/DatabaseComboBox.idl>
#endif

#ifndef __com_sun_star_form_binding_BindableDataAwareControlModel_idl__
#include <com/sun/star/form/binding/BindableDataAwareControlModel.idl>
#endif

//=============================================================================

module com {  module sun {  module star {  module form {  module binding {

//=============================================================================

/** This service specifies a model of a combo box (a list box combined with a text
    input field) which is data-aware and thus can be bound to a database field,
    and additionally supports binding to arbitrary external values.

    <p>If an <type scope="com::sun::star::form::binding">ValueBinding</type> instance is
    set at the field, it will exchange it's text with the binding as <em>string</em>, thus only
    bindings supporting string exchange will be accepted in
    <member scope="com::sun::star::form::binding">XValueBinding::setValueBinding</member>.
    </p>

    @see com::sun::star::form::binding::XValueBinding::supportsType
    @see com::sun::star::awt::UnoControlComboBoxModel::Text
 */
service BindableDatabaseComboBox
{
    service com::sun::star::form::component::DatabaseComboBox;

    /** specifies the interaction between an internal binding to a database column,
        and an external value binding.</p>
    */
    service com::sun::star::form::binding::BindableDataAwareControlModel;

};

//=============================================================================

}; }; }; }; };

#endif
