/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#ifndef __com_sun_star_form_binding_XListEntryTypedSource_idl__
#define __com_sun_star_form_binding_XListEntryTypedSource_idl__

#include <com/sun/star/form/binding/XListEntrySource.idl>


module com {  module sun {  module star {  module form { module binding {


/** specifies a source of string list entries with corresponding underlying data values

    @see XListEntrySource

    @since LibreOffice 5.4
*/
interface XListEntryTypedSource : com::sun::star::form::binding::XListEntrySource
{
    /** provides access to the entirety of all list entries, along with
        the corresponding underlying data values.

        @param  DataValues
                The sequence is used by
                com::sun::star::form::component::ListBox for external
                sources such as spreadsheets to return the resulting
                data value if a listbox entry was selected, e.g. set it
                at the specified bound cell using
                com::sun::star::form::binding::XValueBinding::setValue().
     */
    sequence< string > getAllListEntriesTyped( [out] sequence< any > DataValues );

};


}; }; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
