/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_form_binding_XListEntrySink_idl__
#define __com_sun_star_form_binding_XListEntrySink_idl__

#include <com/sun/star/uno/XInterface.idl>


module com {  module sun {  module star {  module form { module binding {

interface XListEntrySource;


/** specifies support for indirect manipulation of a string list
*/
interface XListEntrySink : com::sun::star::uno::XInterface
{
    /** sets the new source for the list entries of the component

        <p>The list represented by this component will be cleared, and initially
        filled with the entries from the new list source.</p>

        @param Source
            the new source for the list entries. May be `NULL`, in this
            case, the current source is revoked.
    */
    void    setListEntrySource( [in] XListEntrySource Source );

    /** retrieves the current source for the list entries of the component.
    */
    XListEntrySource
            getListEntrySource( );
};


}; }; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
