/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/



#ifndef __com_sun_star_xsd_Time_idl__
#define __com_sun_star_xsd_Time_idl__

#ifndef __com_sun_star_xsd_XDataType_idl__
#include <com/sun/star/xsd/XDataType.idl>
#endif
#ifndef __com_sun_star_util_Time_idl__
#include <com/sun/star/util/Time.idl>
#endif

//=============================================================================
module com {  module sun {  module star {  module xsd {

//-----------------------------------------------------------------------------
/** specifies an <a href="http://www.w3.org/TR/xmlschema-2/#time">XSD compliant time type</a>
*/
service Time
{
    /** provides access to common data type functionality
    */
    interface XDataType;

    /** specifies the inclusive upper bound for the value
        @see http://www.w3.org/TR/xmlschema-2/#rf-maxInclusive
    */
    [property, maybevoid] com::sun::star::util::Time MaxInclusiveTime;

    /** specifies the exclusive upper bound for the value
        @see http://www.w3.org/TR/xmlschema-2/#rf-maxExclusive
    */
    [property, maybevoid] com::sun::star::util::Time MaxExclusiveTime;

    /** specifies the inclusive lower bound for the value
        @see http://www.w3.org/TR/xmlschema-2/#rf-minInclusive
    */
    [property, maybevoid] com::sun::star::util::Time MinInclusiveTime;

    /** specifies the exclusive lower bound for the value
        @see http://www.w3.org/TR/xmlschema-2/#rf-minExclusive
    */
    [property, maybevoid] com::sun::star::util::Time MinExclusiveTime;
};

//=============================================================================

}; }; }; };

#endif
