/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_container_XIdentifierAccess_idl__
#define __com_sun_star_container_XIdentifierAccess_idl__

#ifndef __com_sun_star_container_XElementAccess_idl__
#include <com/sun/star/container/XElementAccess.idl>
#endif

#ifndef __com_sun_star_container_NoSuchElementException_idl__
#include <com/sun/star/container/NoSuchElementException.idl>
#endif

#ifndef __com_sun_star_lang_WrappedTargetException_idl__
#include <com/sun/star/lang/WrappedTargetException.idl>
#endif

//=============================================================================

module com {  module sun {  module star {  module container {

//=============================================================================

/** provides access to the elements of a collection through a unique identifier.
 */
published interface XIdentifierAccess: com::sun::star::container::XElementAccess
{
    /** @returns
            the element with the specified identifier

        @param Identifier
            specifies the identifier of the element that should be retrieved.

        @throws com::sun::star::lang::NoSuchElementException
            If the identifier is not existing.

        @throws  com::sun::star::lang::WrappedTargetException
            If the implementation has internal reasons for exceptions,
            then wrap these in a <typee scope="com::sun::star::lang">WrappedTargetException</type>
            exception.
     */
    any getByIdentifier( [in] long Identifierr )
            raises( com::sun::star::container::NoSuchElementException,
                    com::sun::star::lang::WrappedTargetException );

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    /** @returns
            a sequence of all identifiers in this container.

        <p>The order of the identifiers is not specified. </p>
     */
    sequence<long> getIdentifiers();
}
;

//=============================================================================

}; }; }; };

#endif
