/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __ooo_vba_access_AcColorIndex_idl__
#define __ooo_vba_access_AcColorIndex_idl__

module ooo { module vba { module access {
    constants AcColorIndex {
        const long acColorIndexAqua = 14;
        const long acColorIndexBlack = 0;
        const long acColorIndexBlue = 12;
        const long acColorIndexBrightGreen = 10;
        const long acColorIndexDarkBlue = 4;
        const long acColorIndexFuschia = 13;
        const long acColorIndexGray = 7;
        const long acColorIndexGreen = 2;
        const long acColorIndexMaroon = 1;
        const long acColorIndexOlive = 3;
        const long acColorIndexRed = 9;
        const long acColorIndexSilver = 8;
        const long acColorIndexTeal = 6;
        const long acColorIndexViolet = 5;
        const long acColorIndexWhite = 15;
        const long acColorIndexYellow = 11;
    };
}; }; };

#endif
