/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_embed_EmbedMisc_idl__
#define __com_sun_star_embed_EmbedMisc_idl__



module com { module sun { module star { module embed {

/** The constant set contains flags describing miscellaneous characteristics
    of embedded objects.

    <p>
    The constant values can be combined with "or" operation.
    The first 32 bits are reserved for MS values, they are added because
    this API is going to be used to embed MS OLE objects into OOo documents,
    so there should be a possibility to transfer all the possible MS flags
    to container. In case own specific values should be added those bits can
    not be used.
    </p>

    @see XEmbeddedObject
*/
published constants EmbedMisc
{
    // analog of the MS OLEMISC enum

    /** means that the object wish to regenerate view representation if it's
        view in the container is resized.
     */
    const hyper MS_EMBED_RECOMPOSEONRESIZE = 1;

    /** The object has no view representation except icon.
     */
    const hyper MS_EMBED_ONLYICONIC = 2;

    /** If the object is generated from a selection, the selection should not
        be removed, the object should be inserted beside the selection.
     */
    const hyper MS_EMBED_INSERTNOTREPLACE = 4;

    /** The object is a static object that contains only representation.
     */
    const hyper MS_EMBED_STATIC = 8;

    /**
     */
    const hyper MS_EMBED_CANTLINKINSIDE = 16;

    /**
     */
    const hyper MS_EMBED_CANLINKBYOLE1 = 32;

    /**
     */
    const hyper MS_EMBED_ISLINKOBJECT = 64;

    /**
     */
    const hyper MS_EMBED_INSIDEOUT = 128;

    /**
     */
    const hyper MS_EMBED_ACTIVATEWHENVISIBLE = 256;

    /**
     */
    const hyper MS_EMBED_RENDERINGISDEVICEINDEPENDENT = 512;

    /**
     */
    const hyper MS_EMBED_INVISIBLEATRUNTIME = 1024;

    /**
     */
    const hyper MS_EMBED_ALWAYSRUN = 2048;

    /**
     */
    const hyper MS_EMBED_ACTSLIKEBUTTON = 4096;

    /**
     */
    const hyper MS_EMBED_ACTSLIKELABEL = 8192;

    /**
     */
    const hyper MS_EMBED_NOUIACTIVATE = 16384;

    /**
     */
    const hyper MS_EMBED_ALIGNABLE = 32768;

    /**
     */
    const hyper MS_EMBED_SIMPLEFRAME = 65536;

    /**
     */
    const hyper MS_EMBED_SETCLIENTSITEFIRST = 131072;

    /**
     */
    const hyper MS_EMBED_IMEMODE = 262144;

    /**
     */
    const hyper MS_EMBED_IGNOREACTIVATEWHENVISIBLE = 524288;

    /**
     */
    const hyper MS_EMBED_WANTSTOMENUMERGE = 1048576;

    /**
     */
    const hyper MS_EMBED_SUPPORTSMULTILEVELUNDO = 2097152;

    /**
     */
    const hyper EMBED_ACTIVATEIMMEDIATELY = 0x100000000;

    /**
     */
    const hyper EMBED_NEVERRESIZE = 0x200000000;

    /** The object needs the size to be provided from the container after
        it is loaded to function in optimal way.
     */
    const hyper EMBED_NEEDSSIZEONLOAD = 0x400000000;

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
