/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_embed_OLESimpleStorage_idl__
#define __com_sun_star_embed_OLESimpleStorage_idl__

#include <com/sun/star/embed/XOLESimpleStorage.idl>
#include <com/sun/star/io/XInputStream.idl>
#include <com/sun/star/io/XStream.idl>

module com { module sun { module star { module embed {
/** This service provides a simple functionality to allow
    read/write the storages in OLE storage format.
*/
published service OLESimpleStorage: XOLESimpleStorage
{
    // CONSTRUCTORS ----------------------------------------------------------
    /** is used to initialize the object on it's creation.

        @param xInputStream
                [in] the InputStream that contains data in OLE storage format.

        @param bNoTempCopy
                [in] specifies whether a temporary copy should be created during
                substreams opening. If the copy is not created the storage must
                stay alive while the opened substreams are used.

     */
    createFromInputStream ([in] ::com::sun::star::io::XInputStream xInputStream, [in] boolean bNoTempCopy);

    /** is used to initialize the object on it's creation.

        @param xStream
                [in] the Stream that contains data in OLE storage format.

        @param bNoTempCopy
                [in] specifies whether a temporary copy should be created during
                substreams opening. If the copy is not created the storage must
                stay alive while the opened substreams are used.

     */
    createFromStream ([in] ::com::sun::star::io::XStream xStream, [in] boolean bNoTempCopy);
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
