/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XCommonEmbedPersist.idl,v $
 *
 *  $Revision: 1.3 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 00:09:23 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_embed_XCommonEmbedPersist_idl__
#define __com_sun_star_embed_XCommonEmbedPersist_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __com_sun_star_embed_XStorage_idl__
#include <com/sun/star/embed/XStorage.idl>
#endif

#ifndef __com_sun_star_io_IOException_idl__
#include <com/sun/star/io/IOException.idl>
#endif

#ifndef __com_sun_star_embed_WrongStateException_idl__
#include <com/sun/star/embed/WrongStateException.idl>
#endif

#ifndef __com_sun_star_lang_IllegalArgumentException_idl__
#include <com/sun/star/lang/IllegalArgumentException.idl>
#endif

#ifndef __com_sun_star_beans_PropertyValue_idl__
#include <com/sun/star/beans/PropertyValue.idl>
#endif

//============================================================================

 module com {  module sun {  module star {  module embed {

//============================================================================
/** specifies common implementation for embedded objects and links
    persistence.
 */
interface XCommonEmbedPersist: com::sun::star::uno::XInterface
{
     //------------------------------------------------------------------------
    /** lets the object or the link store itself.

        @throws com::sun::star::embed::WrongStateException
            the object is in wrong state

        @throws com::sun::star::io::IOException
            in case of io problems during saving

        @throws com::sun::star::uno::Exception
            in case of other problems
     */
    void storeOwn()
        raises( ::com::sun::star::embed::WrongStateException,
                ::com::sun::star::io::IOException,
                ::com::sun::star::uno::Exception );

    //------------------------------------------------------------------------
    /** allows to detect if the data store is read-only.

        @returns
            <TRUE/> if the data store is readonly or opened readonly
            <FALSE/> otherwise

        @throws com::sun::star::embed::WrongStateException
            the object is in wrong state ( has no entry )
     */
    boolean isReadonly()
        raises( ::com::sun::star::embed::WrongStateException );

    //------------------------------------------------------------------------
    /** lets the object or the link reload itself.

        <p>
        If the object has persistance it will be reloaded from it's persistant
        entry.
        </p>

        @param aMediaArgs
            optional parameters for document reloading, see also
            <type scope="com::sun::star::document">MediaDescriptor</type>

        @param aObjectArgs
            optional parameters for object reloading, see also
            <type scope="com::sun::star::embed">EmbeddedObjectDescriptor</type>

        @thrown ::com::sun::star::lang::IllegalArgumentException
            one of arguments is illegal

        @throws com::sun::star::embed::WrongStateException
            the object is in wrong state

        @throws com::sun::star::io::IOException
            in case of io problems during opening\creation

        @throws com::sun::star::uno::Exception
            in case of other problems
     */
    void reload(
            [in] sequence< ::com::sun::star::beans::PropertyValue > aMediaArgs,
            [in] sequence< ::com::sun::star::beans::PropertyValue > aObjectArgs )
        raises( ::com::sun::star::lang::IllegalArgumentException,
                ::com::sun::star::embed::WrongStateException,
                ::com::sun::star::io::IOException,
                ::com::sun::star::uno::Exception );
};

//============================================================================

}; }; }; };

#endif

