/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Copyright 2000, 2010 Oracle and/or its affiliates.
 *
 * OpenOffice.org - a multi-platform office productivity suite
 *
 * This file is part of OpenOffice.org.
 *
 * OpenOffice.org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License version 3
 * only, as published by the Free Software Foundation.
 *
 * OpenOffice.org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License version 3 for more details
 * (a copy is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3 along with OpenOffice.org.  If not, see
 * <http://www.openoffice.org/license.html>
 * for a copy of the LGPLv3 License.
 *
 ************************************************************************/
#ifndef __com_sun_star_embed_XInsertObjectDialog_idl__
#define __com_sun_star_embed_XInsertObjectDialog_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/embed/XStorage.idl>
#include <com/sun/star/embed/InsertedObjectInfo.idl>
#include <com/sun/star/io/IOException.idl>
#include <com/sun/star/embed/WrongStateException.idl>
#include <com/sun/star/lang/IllegalArgumentException.idl>
#include <com/sun/star/beans/PropertyValue.idl>


 module com {  module sun {  module star {  module embed {

/** allows to create and initialize a new embedded object using GUI dialog.
 */
published interface XInsertObjectDialog: com::sun::star::uno::XInterface
{
    /** creates a new object using GUI dialog.

        <p>
        The dialog allows for user to do a number of choices that are container
        related. This information will be returned in the
        <type>InsertedObjectInfo</type> object.
        <p>

        @param xStorage
            a parent storage the entry should be created/opened in

        @param sEntName
            a name for the entry

        @param lObjArgs
            optional parameters for the object persistence initialization
            see also <type scope="com::sun::star::embed">EmbeddedObjectDescriptor</type>

        @returns
            the structure containing the object and container related options

        @thrown ::com::sun::star::lang::IllegalArgumentException
            one of arguments is illegal

        @throws com::sun::star::io::IOException
            in case of io problems during opening\creation

        @throws com::sun::star::uno::Exception
            in case of other problems
     */
    InsertedObjectInfo createInstanceByDialog(
                            [in] ::com::sun::star::embed::XStorage xStorage,
                            [in] string sEntName,
                            [in] sequence< ::com::sun::star::beans::PropertyValue > lObjArgs )
        raises( ::com::sun::star::lang::IllegalArgumentException,
                ::com::sun::star::io::IOException,
                ::com::sun::star::uno::Exception );
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
