/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/



#ifndef __com_sun_star_datatransfer_dnd_DragSourceEvent_idl__
#define __com_sun_star_datatransfer_dnd_DragSourceEvent_idl__

#ifndef __com_sun_star_lang_EventObject_idl__
#include <com/sun/star/lang/EventObject.idl>
#endif

//=============================================================================

module com { module sun { module star { module datatransfer { module dnd {

 published interface XDragSource;
 published interface XDragSourceContext;

//=============================================================================
/** This class is the base class for <type>DragSourceDragEvent</type> and <type>DragSourceDropEvent</type>.

    <p>To access the <type>XDragSource</type> that originated this event, use the
    <member scope="com::sun::star::lang">EventObject::Source</member> member of
    this object.</p>
*/

published struct DragSourceEvent: com::sun::star::lang::EventObject
{
    //-------------------------------------------------------------------------
    /** The drag source context of the current drag operation.

        @see com::sun::star::datatransfer::dnd::XDragSourceContext
     */

    XDragSourceContext DragSourceContext;

    //-------------------------------------------------------------------------
    /** The drag source on which the Drag and Drop operation was initiated.

        @see com::sun::star::datatransfer::dnd::XDragSource
     */

    XDragSource DragSource;
};

//=============================================================================

}; }; }; }; };

#endif
