/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_i18n_CalendarDisplayIndex_idl__
#define __com_sun_star_i18n_CalendarDisplayIndex_idl__


module com { module sun { module star { module i18n {



/**
    Values to be passed to <member>XCalendar::getDisplayName()</member>.
 */
published constants CalendarDisplayIndex
{
    /// name of an AM/PM value
    const short AM_PM            = 0;
    /// name of a day of week
    const short DAY              = 1;
    /// name of a month
    const short MONTH            = 2;
    /// name of a year (if used for a specific calendar)
    const short YEAR             = 3;
    /// name of an era, like BC/AD
    const short ERA              = 4;

    /** name of a possessive genitive case month
        @since LibreOffice 3.5
     */
    const short GENITIVE_MONTH   = 5;

    /** name of a partitive case month
        @since LibreOffice 3.5
     */
    const short PARTITIVE_MONTH  = 6;
};

}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
