/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/



#ifndef __com_sun_star_i18n_TextConversionType_idl__
#define __com_sun_star_i18n_TextConversionType_idl__


//=============================================================================

module com {  module sun {  module star {  module i18n {

//=============================================================================

//--------------------------------------------------------------------------
/** These constansts specifiy the conversion type to be used with
    <type>XTextConversion</type>.

     @since OpenOffice 1.1.2
*/

published constants TextConversionType
{
    /// Conversion from Hanja to Hangul
    const short TO_HANGUL       = 1;

    /// Conversion from Hangul to Hanja
    const short TO_HANJA        = 2;

    /// Conversion from Traditional to Simplified Chinese
    const short TO_SCHINESE     = 3;

    /// Conversion from Simplified to Traditional Chinese
    const short TO_TCHINESE     = 4;
};

//=============================================================================

}; }; }; };

#endif
