#!/bin/sh

# 16.06.2006 Volker Quetschke
# A comparison with the empty string crashes dmake - equality test with empty
# string must work too.
# (issue 65281)

: ${DMAKEPROG:=dmake}
file1="mfile1.mk"
tmpfiles="$file1"

trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15

# Remove files from prior failed run
rm -rf $tmpfiles

# Remember to quote variables in generated makefiles( $ -> \$ ).
cat > $file1 <<EOT
SHELL*:=/bin/sh 
SHELLFLAGS*:=-ce

RHS=

all:
.IF \$(LHS) == \$(RHS)
	+@echo "true"
.ELSE
	+@echo "false"
.ENDIF

EOT

output=`eval ${DMAKEPROG} -r -f $file1`
result=$?

if test "$output" != "true"; then
  result=1
fi 
 
test $result -eq 0 && echo "Success - Cleaning up" && rm -f ${tmpfiles}
test $result -ne 0 && echo "Failure!"
exit $result
