#!/bin/sh

# 06.02.2006 Volker Quetschke
# Verify that the .SETDIR attribute works separately from the target
# definition. (issue 61714)

: ${DMAKEPROG:=dmake}
file1="mfile1.mk"
file2="subdir"
tmpfiles="$file1 $file2"

trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15

# Remove files from prior failed run
rm -rf $tmpfiles

# Remember to quote variables in generated makefiles( $ -> \$ ).
cat > $file1 <<EOT
SHELL*:=/bin/sh 
SHELLFLAGS*:=-ce

.SETDIR=subdir : all

all :
	@+echo ":\$(PWD:f):"

EOT

mkdir -p "$file2"

output1=`eval ${DMAKEPROG} -r -f $file1`
result1=$?

if test "$output1" != ":$file2:"; then
  echo "Wrong result - use of .SETDIR was not successful."
  result1=1
fi 

if test $result1 -eq 0; then
  echo "Success - Cleaning up"
  rm -rf ${tmpfiles}
  result=0
else
  echo "Failure!"
  result=1
fi
exit $result
