#!/bin/sh

# 13.06.2006 Volker Quetschke
# Check that `%.a %.b :| %.x %.y 'Z' ; recipe` rules are handled correctly.
# (issues 48087 and 65122)

: ${DMAKEPROG:=dmake}
file1="mfile1.mk"
tmpfiles="$file1"

trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15

# Remove files from prior failed run
rm -rf $tmpfiles

# Remember to quote variables in generated makefiles( $ -> \$ ).
# Expect dummy, all.pp and all.xx to be build
# that gets build.
cat > $file1 <<EOT
SHELL*:=/bin/sh 
SHELLFLAGS*:=-ce

%.xx %.rr :| %.yy %.pp 'dummy' ; @+printf "\$@"

%.pp :
	@sleep 1
	@+printf "\$@"

dummy :
	@+printf "\$@"

EOT

output1=`eval ${DMAKEPROG} -r -f $file1 all.xx 2>&1 `
result1=$?

if echo $output1 | grep 'dummyall.ppall.xx' > /dev/null 2>&1 ; then
  dummy=1
  # OK
else
  echo "Test 1: Wrong result: $output1"
  echo
  result1=1
fi

if test $result1 -eq 0 ; then
  echo "Success - Cleaning up"
  rm -rf $tmpfiles
  result=0
else
  echo "Failure!"
  result=1
fi
exit $result
