#!/bin/sh

# 24.09.2007 Volker Quetschke
# Check that the .REMOVE target does not crash dmake in parallel builds.
# (issue 80012)

: ${DMAKEPROG:=dmake}
file1="mfile1.mk"
file2="aaa.aaa"
file3="aaa.bbb"
file4="aaa.ccc"
tmpfiles="$file1 $file2 $file3 $file4"

trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }' 1 2 3 15

# Remove files from prior failed run
rm -rf $tmpfiles

# Remember to quote variables in generated makefiles( $ -> \$ ).
cat > $file1 <<EOT
SHELL*:=/bin/sh
SHELLFLAGS*:=-ce

.REMOVE :; @echo remove intermediate target: \$<

%.aaa : %.bbb
	@echo built \$@

%.bbb : %.ccc
	@sleep 1
	@echo built \$@

%.ccc :
	@echo built \$@

all : aaa.aaa
	@echo Done

EOT

output1=`eval ${DMAKEPROG} -P2 -rf $file1 2>&1`
result1=$?

if test $result1 -ne 0; then
  echo "Failure! Remove the corefile!"
  echo "Output: $output1"
  result1=1
else
  echo "OK"
fi 

if test $result1 -eq 0 ; then
  echo "Success - Cleaning up"
  rm -rf $tmpfiles
  exit
else
  echo "Failure!"
  exit 1
fi
