// Don't modify, generated using unocommands.py

var unoCommandsArray = {
	'AcceptAllTrackedChanges':{text:{menu:_('Accept All'),},},
	'AcceptTrackedChange':{text:{context:_('Accept Change'),menu:_('Accept'),},},
	'AcceptTrackedChangeToNext':{text:{menu:_('Accept and Move to Next'),},},
	'AcceptTrackedChanges':{text:{context:_('Manage Tracked Changes'),menu:_('~Manage...'),},},
	'AccessibilityCheck':{text:{menu:_('~Accessibility Check...'),},},
	'AddName':{spreadsheet:{menu:_('~Define...'),},},
	'AddPrintArea':{spreadsheet:{menu:_('~Add'),},},
	'AddTheme':{global:{menu:_('Add Theme...'),},},
	'AddToWordbook':{global:{menu:_('Add To Dictionary'),},},
	'AlignBlock':{spreadsheet:{menu:_('Justified'),},},
	'AlignBottom':{spreadsheet:{menu:_('Align Bottom'),},text:{menu:_('Align Bottom to Anchor'),},},
	'AlignCenter':{global:{menu:_('~Centered'),},},
	'AlignDown':{global:{menu:_('~Bottom'),},},
	'AlignHorizontalCenter':{spreadsheet:{menu:_('Align Center'),},text:{menu:_('Center Horizontal'),},},
	'AlignLeft':{spreadsheet:{menu:_('Align Left'),},text:{menu:_('Align Left'),},},
	'AlignMiddle':{global:{menu:_('~Middle'),},},
	'AlignRight':{spreadsheet:{menu:_('Align Right'),},text:{menu:_('Align Right'),},},
	'AlignTop':{spreadsheet:{menu:_('Align Top'),},text:{menu:_('Align Top to Anchor'),},},
	'AlignUp':{global:{menu:_('~Top'),},},
	'AlignVCenter':{spreadsheet:{menu:_('Center Vertically'),},},
	'AnalysisOfVarianceDialog':{spreadsheet:{menu:_('~Analysis of Variance (ANOVA)...'),},},
	'AnchorMenu':{global:{menu:_('Anc~hor'),},},
	'AnimationEffects':{presentation:{menu:_('~Interaction...'),},},
	'ArrangeFrameMenu':{text:{menu:_('Arrange'),},},
	'ArrangeMenu':{global:{menu:_('A~rrange'),},presentation:{menu:_('~Arrange'),},},
	'ArrowShapes.chevron':{global:{menu:_('Chevron'),},},
	'ArrowShapes.circular-arrow':{global:{menu:_('Circular Arrow'),},},
	'ArrowShapes.corner-right-arrow':{global:{menu:_('Corner Right Arrow'),},},
	'ArrowShapes.down-arrow':{global:{menu:_('Down Arrow'),},},
	'ArrowShapes.down-arrow-callout':{global:{menu:_('Down Arrow Callout'),},},
	'ArrowShapes.left-arrow':{global:{menu:_('Left Arrow'),},},
	'ArrowShapes.left-arrow-callout':{global:{menu:_('Left Arrow Callout'),},},
	'ArrowShapes.left-right-arrow':{global:{menu:_('Left and Right Arrow'),},},
	'ArrowShapes.left-right-arrow-callout':{global:{menu:_('Left and Right Arrow Callout'),},},
	'ArrowShapes.notched-right-arrow':{global:{menu:_('Notched Right Arrow'),},},
	'ArrowShapes.pentagon-right':{global:{menu:_('Pentagon'),},},
	'ArrowShapes.quad-arrow':{global:{menu:_('4-way Arrow'),},},
	'ArrowShapes.quad-arrow-callout':{global:{menu:_('4-way Arrow Callout'),},},
	'ArrowShapes.right-arrow':{global:{menu:_('Right Arrow'),},},
	'ArrowShapes.right-arrow-callout':{global:{menu:_('Right Arrow Callout'),},},
	'ArrowShapes.s-sharped-arrow':{global:{menu:_('S-shaped Arrow'),},},
	'ArrowShapes.split-arrow':{global:{menu:_('Split Arrow'),},},
	'ArrowShapes.split-round-arrow':{global:{menu:_('Right or Left Arrow'),},},
	'ArrowShapes.striped-right-arrow':{global:{menu:_('Striped Right Arrow'),},},
	'ArrowShapes.up-arrow':{global:{menu:_('Up Arrow'),},},
	'ArrowShapes.up-arrow-callout':{global:{menu:_('Up Arrow Callout'),},},
	'ArrowShapes.up-down-arrow':{global:{menu:_('Up and Down Arrow'),},},
	'ArrowShapes.up-down-arrow-callout':{global:{menu:_('Up and Down Arrow Callout'),},},
	'ArrowShapes.up-right-arrow':{global:{menu:_('Up and Right Arrow'),},},
	'ArrowShapes.up-right-arrow-callout':{global:{menu:_('Up and Right Arrow Callout'),},},
	'ArrowShapes.up-right-down-arrow':{global:{menu:_('Up, Right and Down Arrow'),},},
	'AutoFill':{spreadsheet:{menu:_('AutoFill Data Series: automatic'),},},
	'AutoFormatMenu':{text:{menu:_('AutoCorr~ect'),},},
	'BackgroundColor':{global:{menu:_('Background Color'),},},
	'BasicShapes.block-arc':{global:{menu:_('Block Arc'),},},
	'BasicShapes.can':{global:{menu:_('Cylinder'),},},
	'BasicShapes.circle':{global:{menu:_('Circle'),},},
	'BasicShapes.circle-pie':{global:{menu:_('Circle Pie'),},},
	'BasicShapes.cross':{global:{menu:_('Cross'),},},
	'BasicShapes.cube':{global:{menu:_('Cuboid'),},},
	'BasicShapes.diamond':{global:{menu:_('Diamond'),},},
	'BasicShapes.ellipse':{global:{context:_('Ellipse (double click for multi-selection)'),menu:_('Ellipse'),},},
	'BasicShapes.frame':{global:{menu:_('Frame'),},},
	'BasicShapes.hexagon':{global:{menu:_('Hexagon'),},},
	'BasicShapes.isosceles-triangle':{global:{menu:_('Isosceles Triangle'),},},
	'BasicShapes.octagon':{global:{menu:_('Octagon'),},},
	'BasicShapes.paper':{global:{menu:_('Folded Corner'),},},
	'BasicShapes.parallelogram':{global:{menu:_('Parallelogram'),},},
	'BasicShapes.pentagon':{global:{menu:_('Pentagon'),},},
	'BasicShapes.quadrat':{global:{menu:_('Square'),},},
	'BasicShapes.rectangle':{global:{context:_('Rectangle (double click for multi-selection)'),menu:_('Rectangle'),},},
	'BasicShapes.right-triangle':{global:{menu:_('Right Triangle'),},},
	'BasicShapes.ring':{global:{menu:_('Ring'),},},
	'BasicShapes.round-quadrat':{global:{menu:_('Square, Rounded'),},},
	'BasicShapes.round-rectangle':{global:{menu:_('Rectangle, Rounded'),},},
	'BasicShapes.trapezoid':{global:{menu:_('Trapezoid'),},},
	'Bezier_Unfilled':{global:{menu:_('Curve'),},},
	'Bold':{global:{menu:_('Bold'),},},
	'BringToFront':{global:{menu:_('~Bring to Front'),},},
	'Calculate':{spreadsheet:{menu:_('~Recalculate'),},},
	'CalculatedFieldRun':{spreadsheet:{context:_('~Calculated Field...'),menu:_('~Calculated Field...'),},},
	'CalloutShapes.cloud-callout':{global:{menu:_('Cloud'),},},
	'CalloutShapes.line-callout-1':{global:{menu:_('Line Callout 1'),},},
	'CalloutShapes.line-callout-2':{global:{menu:_('Line Callout 2'),},},
	'CalloutShapes.line-callout-3':{global:{menu:_('Line Callout 3'),},},
	'CalloutShapes.rectangular-callout':{global:{menu:_('Rectangular Callout'),},},
	'CalloutShapes.round-callout':{global:{menu:_('Round Callout'),},},
	'CalloutShapes.round-rectangular-callout':{global:{menu:_('Rounded Rectangular Callout'),},},
	'CellVertBottom':{global:{context:_('Align Bottom'),menu:_('Bottom'),},},
	'CellVertCenter':{global:{context:_('Center Vertically'),menu:_('Center'),},},
	'CellVertTop':{global:{context:_('Align Top'),menu:_('Top'),},},
	'CenterPara':{global:{context:_('Align Center'),menu:_('Center'),},},
	'ChangeAlignment':{global:{menu:_('A~lignment...'),},},
	'ChangeBezier':{presentation:{menu:_('To ~Curve'),},},
	'ChangeCaseRotateCase':{global:{menu:_('Cycle Case'),},},
	'ChangeCaseToLower':{global:{menu:_('~lowercase'),},},
	'ChangeCaseToSentenceCase':{global:{menu:_('~Sentence case'),},},
	'ChangeCaseToTitleCase':{global:{menu:_('~Capitalize Every Word'),},},
	'ChangeCaseToToggleCase':{global:{menu:_('~tOGGLE cASE'),},},
	'ChangeCaseToUpper':{global:{menu:_('~UPPERCASE'),},},
	'ChangeDistance':{global:{menu:_('~Spacing...'),},},
	'ChangeFont':{global:{menu:_('~Fonts...'),},},
	'ChangeFontSize':{global:{menu:_('F~ont Size...'),},},
	'ChangesMenu':{global:{menu:_('Track Chan~ges'),},},
	'ChapterNumberingDialog':{text:{context:_('Set Heading Numbering'),menu:_('Heading ~Numbering...'),},},
	'CharBackColor':{global:{menu:_('Character Highlighting Color'),},},
	'CharFontName':{global:{menu:_('Font Name'),},},
	'CharmapControl':{global:{context:_('Insert Special Characters'),menu:_('Symbol'),},},
	'ChiSquareTestDialog':{spreadsheet:{menu:_('~Chi-square Test...'),},},
	'ClearOutline':{global:{menu:_('~Remove Outline'),},},
	'CloseMasterView':{presentation:{menu:_('Close Master View'),},},
	'Color':{global:{menu:_('Font Color'),},},
	'ColorScaleFormatDialog':{spreadsheet:{menu:_('Color Scale...'),},},
	'ColumnOperations':{spreadsheet:{menu:_('Column'),},},
	'ColumnWidth':{spreadsheet:{context:_('Column ~Width...'),menu:_('~Width...'),},},
	'CommonAlignBottom':{global:{menu:_('Bottom'),},},
	'CommonAlignHorizontalCenter':{global:{menu:_('Centered'),},},
	'CommonAlignJustified':{global:{menu:_('Justified'),},},
	'CommonAlignLeft':{global:{menu:_('Left'),},},
	'CommonAlignRight':{global:{menu:_('Right'),},},
	'CommonAlignTop':{global:{menu:_('Top'),},},
	'CommonAlignVerticalCenter':{global:{menu:_('Center'),},},
	'CompareDocuments':{global:{context:_('Compare Non-Track Changed Document'),menu:_('Compare'),},},
	'CompressGraphic':{global:{menu:_('Co~mpress...'),},presentation:{menu:_('Co~mpress...'),},},
	'CondDateFormatDialog':{spreadsheet:{menu:_('Date...'),},},
	'ConditionalFormatManagerDialog':{spreadsheet:{menu:_('Manage...'),},},
	'ConditionalFormatMenu':{spreadsheet:{menu:_('C~onditional'),},},
	'Connector':{global:{menu:_('Connector'),},},
	'ConnectorArrowEnd':{global:{menu:_('Connector Ends with Arrow'),},},
	'ConnectorArrows':{global:{menu:_('Connector with Arrows'),},},
	'ConnectorCurve':{global:{menu:_('Curved Connector'),},},
	'ConnectorCurveArrowEnd':{global:{menu:_('Curved Connector Ends with Arrow'),},},
	'ConnectorCurveArrows':{global:{menu:_('Curved Connector with Arrows'),},},
	'ConnectorLine':{global:{menu:_('Straight Connector'),},},
	'ConnectorLineArrowEnd':{global:{menu:_('Straight Connector ends with Arrow'),},},
	'ConnectorLineArrows':{global:{menu:_('Straight Connector with Arrows'),},},
	'ConnectorLines':{global:{menu:_('Line Connector'),},},
	'ConnectorLinesArrowEnd':{global:{menu:_('Line Connector Ends with Arrow'),},},
	'ConnectorToolbox':{global:{context:_('Connectors (double click for multi-selection)'),menu:_('Connectors'),},},
	'ContentControlProperties':{text:{context:_('Content Control Properties'),menu:_('Properties'),},},
	'ContinueNumbering':{text:{menu:_('~Add to List'),},},
	'ContourDialog':{global:{menu:_('~Edit Contour...'),},},
	'ControlCodes':{text:{context:_('Toggle Formatting Marks'),menu:_('For~matting Marks'),},},
	'ConvertFormulaToValue':{spreadsheet:{menu:_('Formula to Value'),},},
	'ConvertMenu':{presentation:{menu:_('~Convert'),},},
	'Copy':{global:{menu:_('Cop~y'),},},
	'CopyHyperlinkLocation':{global:{menu:_('Copy Hyperlink Location'),},},
	'CorrelationDialog':{spreadsheet:{menu:_('~Correlation...'),},},
	'CovarianceDialog':{spreadsheet:{menu:_('~Covariance...'),},},
	'Crop':{global:{context:_('Crop Image'),menu:_('Crop'),},},
	'CustomAnimation':{presentation:{menu:_('Animation'),},},
	'Cut':{global:{menu:_('~Cut'),},},
	'DataAreaRefresh':{spreadsheet:{menu:_('R~efresh Range'),},},
	'DataBarFormatDialog':{spreadsheet:{menu:_('Data Bar...'),},},
	'DataDataPilotRun':{spreadsheet:{context:_('~Properties...'),menu:_('Pi~vot Table...'),},},
	'DataFilterAutoFilter':{spreadsheet:{menu:_('Auto~Filter'),},},
	'DataFilterHideAutoFilter':{spreadsheet:{menu:_('~Hide AutoFilter'),},},
	'DataFilterRemoveFilter':{spreadsheet:{menu:_('~Reset Filter'),},},
	'DataFilterSpecialFilter':{spreadsheet:{menu:_('~Advanced Filter...'),},},
	'DataFilterStandardFilter':{spreadsheet:{menu:_('~Standard Filter...'),},},
	'DataMenu':{global:{menu:_('~Data'),},},
	'DataPilotMenu':{spreadsheet:{menu:_('~Pivot Table'),},},
	'DataRanges':{global:{menu:_('~Data Ranges...'),},},
	'DataSort':{spreadsheet:{menu:_('~Sort...'),},},
	'DataTableMenu':{spreadsheet:{menu:_('~Table'),},},
	'DatabaseSettings':{spreadsheet:{menu:_('Table Style Options'),},},
	'DecrementIndent':{global:{context:_('Decrease Indent'),menu:_('Decrease Indent'),},},
	'DecrementLevel':{text:{menu:_('Demote Outline Level'),},},
	'DecrementSubLevels':{text:{menu:_('Demote Outline Level with Subpoints'),},},
	'DefaultBullet':{global:{context:_('Toggle Unordered List'),menu:_('~Unordered List'),},},
	'DefaultNumbering':{global:{context:_('Toggle Ordered List'),menu:_('~Ordered List'),},},
	'DefineDBName':{spreadsheet:{menu:_('~Define Range...'),},},
	'DefineName':{spreadsheet:{menu:_('~Manage...'),},},
	'DefinePrintArea':{spreadsheet:{menu:_('~Define'),},},
	'Delete':{global:{menu:_('Delete C~ontents...'),},spreadsheet:{context:_('Cl~ear Contents...'),menu:_('Cle~ar Cells...'),},},
	'DeleteAllAnnotation':{presentation:{menu:_('Delete ~All Comments'),},},
	'DeleteAllNotes':{global:{menu:_('Delete All Comments'),},spreadsheet:{menu:_('Delete All Comments'),},},
	'DeleteAuthor':{global:{menu:_('Delete All Comments by This Author'),},},
	'DeleteAxis':{global:{menu:_('Delete Axis'),},},
	'DeleteCell':{spreadsheet:{context:_('De~lete...'),menu:_('Delete C~ells...'),},},
	'DeleteColumns':{global:{context:_('Delete selected columns'),menu:_('Delete ~Columns'),},text:{context:_('Delete selected columns'),menu:_('~Columns'),},},
	'DeleteComment':{global:{menu:_('Delete Comment'),},},
	'DeleteContentControl':{text:{context:_('Delete Content Control'),menu:_('Delete Content Control'),},},
	'DeleteDataLabel':{global:{menu:_('Delete Single Data Label'),},},
	'DeleteDataLabels':{global:{menu:_('Delete Data Labels'),},},
	'DeleteLegend':{global:{menu:_('Delete Legend'),},},
	'DeleteMajorGrid':{global:{menu:_('Delete Major Grid'),},},
	'DeleteMinorGrid':{global:{menu:_('Delete Minor Grid'),},},
	'DeleteNote':{spreadsheet:{menu:_('Delete Comment'),},},
	'DeletePage':{presentation:{menu:_('D~elete Page'),},},
	'DeletePivotTable':{spreadsheet:{menu:_('~Delete'),},},
	'DeletePrintArea':{spreadsheet:{menu:_('~Clear'),},},
	'DeleteRows':{presentation:{menu:_('Delete Row'),},spreadsheet:{menu:_('Delete Rows'),},text:{context:_('Delete selected rows'),menu:_('~Rows'),},},
	'DeleteSlide':{presentation:{menu:_('~Delete Slide'),},},
	'DeleteSparkline':{spreadsheet:{menu:_('Delete Sparkline'),},},
	'DeleteSparklineGroup':{spreadsheet:{menu:_('Delete Sparkline Group'),},},
	'DeleteTable':{presentation:{menu:_('Delete Table'),},text:{context:_('Delete table'),menu:_('~Table'),},},
	'DescriptiveStatisticsDialog':{spreadsheet:{menu:_('~Descriptive Statistics...'),},},
	'DiagramArea':{global:{menu:_('Chart ~Area...'),},},
	'DiagramAxisX':{global:{menu:_('~X Axis...'),},},
	'DiagramAxisY':{global:{menu:_('~Y Axis...'),},},
	'DiagramData':{global:{menu:_('~Data Table...'),},},
	'DiagramType':{global:{menu:_('Chart T~ype...'),},},
	'DiagramWall':{global:{menu:_('Chart ~Wall...'),},},
	'DistributeHorzCenter':{global:{menu:_('Horizontally ~Center'),},},
	'DistributeHorzDistance':{global:{menu:_('Horizontally ~Spacing'),},},
	'DistributeHorzLeft':{global:{menu:_('Horizontally ~Left'),},},
	'DistributeHorzRight':{global:{menu:_('Horizontally ~Right'),},},
	'DistributeVertBottom':{global:{menu:_('Vertically ~Bottom'),},},
	'DistributeVertCenter':{global:{menu:_('Vertically C~enter'),},},
	'DistributeVertDistance':{global:{menu:_('Vertically S~pacing'),},},
	'DistributeVertTop':{global:{menu:_('Vertically ~Top'),},},
	'DownSearch':{global:{menu:_('Find Next'),},},
	'DrawText':{global:{context:_('Insert Text Box'),menu:_('~Text Box'),},},
	'DuplicatePage':{presentation:{menu:_('Duplicate Page'),},},
	'DuplicateSlide':{presentation:{menu:_('Duplicate ~Slide'),},},
	'EditCurIndex':{text:{menu:_('Edit index'),},},
	'EditCurrentRegion':{text:{menu:_('Edit Section...'),},},
	'EditHeaderAndFooter':{spreadsheet:{menu:_('~Headers and Footers...'),},},
	'EditHyperlink':{global:{context:_('Edit Hyperlink...'),menu:_('~Hyperlink'),},},
	'EditMenu':{global:{menu:_('~Edit'),},},
	'EditPrintArea':{spreadsheet:{menu:_('~Edit...'),},},
	'EditRegion':{text:{menu:_('~Sections...'),},},
	'EditSparkline':{spreadsheet:{menu:_('Edit Sparkline...'),},},
	'EditSparklineGroup':{spreadsheet:{menu:_('Edit Sparkline Group...'),},},
	'EnterGroup':{global:{menu:_('~Enter Group'),},},
	'EntireCell':{text:{context:_('Select Cell'),menu:_('C~ell'),},},
	'EntireColumn':{presentation:{menu:_('Select Column'),},text:{menu:_('~Column'),},},
	'EntireRow':{presentation:{menu:_('Select Row'),},text:{menu:_('~Row'),},},
	'ExecuteAnimationEffect':{presentation:{menu:_('E~xecute Interaction...'),},},
	'ExponentialSmoothingDialog':{spreadsheet:{menu:_('~Exponential Smoothing...'),},},
	'FTestDialog':{spreadsheet:{menu:_('~F-test...'),},},
	'FillColor':{global:{menu:_('Fill Color'),},},
	'FilterMenu':{spreadsheet:{menu:_('More ~Filters'),},},
	'FlipHorizontal':{global:{menu:_('Flip Horizontally'),},},
	'FlipVertical':{global:{menu:_('Flip Vertically'),},},
	'FlowChartShapes.flowchart-alternate-process':{global:{menu:_('Flowchart: Alternate Process'),},},
	'FlowChartShapes.flowchart-card':{global:{menu:_('Flowchart: Card'),},},
	'FlowChartShapes.flowchart-collate':{global:{menu:_('Flowchart: Collate'),},},
	'FlowChartShapes.flowchart-connector':{global:{menu:_('Flowchart: Connector'),},},
	'FlowChartShapes.flowchart-data':{global:{menu:_('Flowchart: Data'),},},
	'FlowChartShapes.flowchart-decision':{global:{menu:_('Flowchart: Decision'),},},
	'FlowChartShapes.flowchart-delay':{global:{menu:_('Flowchart: Delay'),},},
	'FlowChartShapes.flowchart-direct-access-storage':{global:{menu:_('Flowchart: Direct Access Storage'),},},
	'FlowChartShapes.flowchart-display':{global:{menu:_('Flowchart: Display'),},},
	'FlowChartShapes.flowchart-document':{global:{menu:_('Flowchart: Document'),},},
	'FlowChartShapes.flowchart-extract':{global:{menu:_('Flowchart: Extract'),},},
	'FlowChartShapes.flowchart-internal-storage':{global:{menu:_('Flowchart: Internal Storage'),},},
	'FlowChartShapes.flowchart-magnetic-disk':{global:{menu:_('Flowchart: Magnetic Disc'),},},
	'FlowChartShapes.flowchart-manual-input':{global:{menu:_('Flowchart: Manual Input'),},},
	'FlowChartShapes.flowchart-manual-operation':{global:{menu:_('Flowchart: Manual Operation'),},},
	'FlowChartShapes.flowchart-merge':{global:{menu:_('Flowchart: Merge'),},},
	'FlowChartShapes.flowchart-multidocument':{global:{menu:_('Flowchart: Multidocument'),},},
	'FlowChartShapes.flowchart-off-page-connector':{global:{menu:_('Flowchart: Off-page Connector'),},},
	'FlowChartShapes.flowchart-or':{global:{menu:_('Flowchart: Or'),},},
	'FlowChartShapes.flowchart-predefined-process':{global:{menu:_('Flowchart: Predefined Process'),},},
	'FlowChartShapes.flowchart-preparation':{global:{menu:_('Flowchart: Preparation'),},},
	'FlowChartShapes.flowchart-process':{global:{menu:_('Flowchart: Process'),},},
	'FlowChartShapes.flowchart-punched-tape':{global:{menu:_('Flowchart: Punched Tape'),},},
	'FlowChartShapes.flowchart-sequential-access':{global:{menu:_('Flowchart: Sequential Access'),},},
	'FlowChartShapes.flowchart-sort':{global:{menu:_('Flowchart: Sort'),},},
	'FlowChartShapes.flowchart-stored-data':{global:{menu:_('Flowchart: Stored Data'),},},
	'FlowChartShapes.flowchart-summing-junction':{global:{menu:_('Flowchart: Summing Junction'),},},
	'FlowChartShapes.flowchart-terminator':{global:{menu:_('Flowchart: Terminator'),},},
	'FontColor':{global:{menu:_('Font Color'),},text:{menu:_('Font Color'),},},
	'FontDialog':{global:{menu:_('C~haracter...'),},},
	'FontHeight':{global:{menu:_('Font Size'),},},
	'FontworkGalleryFloater':{global:{context:_('Insert Fontwork Text'),menu:_('Fontwork...'),},},
	'FontworkShapeType':{global:{menu:_('Fontwork Shape'),},},
	'FontworkShapeType.fontwork-arch-down-curve':{global:{menu:_('Arch Down (Curve)'),},},
	'FontworkShapeType.fontwork-arch-down-pour':{global:{menu:_('Arch Down (Pour)'),},},
	'FontworkShapeType.fontwork-arch-left-curve':{global:{menu:_('Arch Left (Curve)'),},},
	'FontworkShapeType.fontwork-arch-right-curve':{global:{menu:_('Arch Right (Curve)'),},},
	'FontworkShapeType.fontwork-arch-right-pour':{global:{menu:_('Arch Right (Pour)'),},},
	'FontworkShapeType.fontwork-arch-up-curve':{global:{menu:_('Arch Up (Curve)'),},},
	'FontworkShapeType.fontwork-arch-up-pour':{global:{menu:_('Arch Up (Pour)'),},},
	'FontworkShapeType.fontwork-chevron-down':{global:{menu:_('Chevron Down'),},},
	'FontworkShapeType.fontwork-chevron-up':{global:{menu:_('Chevron Up'),},},
	'FontworkShapeType.fontwork-circle-curve':{global:{menu:_('Circle (Curve)'),},},
	'FontworkShapeType.fontwork-circle-pour':{global:{menu:_('Circle (Pour)'),},},
	'FontworkShapeType.fontwork-curve-down':{global:{menu:_('Curve Down'),},},
	'FontworkShapeType.fontwork-curve-up':{global:{menu:_('Curve Up'),},},
	'FontworkShapeType.fontwork-fade-down':{global:{menu:_('Fade Down'),},},
	'FontworkShapeType.fontwork-fade-left':{global:{menu:_('Fade Left'),},},
	'FontworkShapeType.fontwork-fade-right':{global:{menu:_('Fade Right'),},},
	'FontworkShapeType.fontwork-fade-up':{global:{menu:_('Fade Up'),},},
	'FontworkShapeType.fontwork-fade-up-and-left':{global:{menu:_('Fade Up and Left'),},},
	'FontworkShapeType.fontwork-fade-up-and-right':{global:{menu:_('Fade Up and Right'),},},
	'FontworkShapeType.fontwork-inflate':{global:{menu:_('Inflate'),},},
	'FontworkShapeType.fontwork-open-circle-curve':{global:{menu:_('Open Circle (Curve)'),},},
	'FontworkShapeType.fontwork-open-circle-pour':{global:{menu:_('Open Circle (Pour)'),},},
	'FontworkShapeType.fontwork-plain-text':{global:{menu:_('Plain Text'),},},
	'FontworkShapeType.fontwork-slant-down':{global:{menu:_('Slant Down'),},},
	'FontworkShapeType.fontwork-slant-up':{global:{menu:_('Slant Up'),},},
	'FontworkShapeType.fontwork-stop':{global:{menu:_('Stop'),},},
	'FontworkShapeType.fontwork-triangle-down':{global:{menu:_('Triangle Down'),},},
	'FontworkShapeType.fontwork-triangle-up':{global:{menu:_('Triangle Up'),},},
	'FontworkShapeType.fontwork-wave':{global:{menu:_('Wave'),},},
	'FootnoteDialog':{text:{menu:_('~Footnote/Endnote Settings...'),},},
	'FormatArea':{global:{menu:_('A~rea...'),},},
	'FormatAxis':{global:{menu:_('Format Axis...'),},},
	'FormatBulletsMenu':{global:{menu:_('Lis~ts'),},},
	'FormatCellDialog':{spreadsheet:{context:_('~Format Cells...'),menu:_('Ce~lls...'),},},
	'FormatChartArea':{global:{menu:_('Format Chart Area...'),},},
	'FormatColumns':{text:{menu:_('Co~lumns...'),},},
	'FormatDataLabel':{global:{menu:_('Format Single Data Label...'),},},
	'FormatDataLabels':{global:{menu:_('Format Data Labels...'),},},
	'FormatDataPoint':{global:{menu:_('Format Data Point...'),},},
	'FormatDataSeries':{global:{menu:_('Format Data Series...'),},},
	'FormatFloor':{global:{menu:_('Format Floor...'),},},
	'FormatFormMenu':{global:{menu:_('Fo~rm'),},},
	'FormatGroup':{global:{menu:_('~Group'),},},
	'FormatLegend':{global:{menu:_('Format Legend...'),},},
	'FormatLine':{global:{menu:_('L~ine...'),},},
	'FormatMajorGrid':{global:{menu:_('Format Major Grid...'),},},
	'FormatMeanValue':{global:{menu:_('Format Mean Value Line...'),},},
	'FormatMenu':{global:{menu:_('F~ormat'),},},
	'FormatMinorGrid':{global:{menu:_('Format Minor Grid...'),},},
	'FormatPaintbrush':{global:{menu:_('Clone Formatting'),},text:{menu:_('Clone Formatting'),},},
	'FormatSelection':{global:{menu:_('Format Selection...'),},},
	'FormatSpacingMenu':{global:{menu:_('~Spacing'),},},
	'FormatSparklineMenu':{spreadsheet:{menu:_('Sparklines'),},},
	'FormatStockGain':{global:{menu:_('Format Stock Gain...'),},},
	'FormatStockLoss':{global:{menu:_('Format Stock Loss...'),},},
	'FormatTextMenu':{global:{menu:_('Te~xt'),},},
	'FormatTitle':{global:{menu:_('Format Title...'),},},
	'FormatTrendline':{global:{menu:_('Format Trend Line...'),},},
	'FormatTrendlineEquation':{global:{menu:_('Format Trend Line Equation...'),},},
	'FormatUngroup':{global:{menu:_('~Ungroup'),},},
	'FormatWall':{global:{menu:_('Format Wall...'),},},
	'FormatXErrorBars':{global:{menu:_('Format X Error Bars...'),},},
	'FormatYErrorBars':{global:{menu:_('Format Y Error Bars...'),},},
	'FormattingMarkMenu':{global:{menu:_('Formatting Mark'),},},
	'FourierAnalysisDialog':{spreadsheet:{menu:_('F~ourier Analysis...'),},},
	'FrameDialog':{text:{menu:_('~Properties...'),},},
	'FreezeCellsMenu':{spreadsheet:{menu:_('Freeze ~Cells'),},},
	'FreezePanes':{spreadsheet:{context:_('Freeze Rows and Columns'),menu:_('Freeze Rows and Columns'),},},
	'FreezePanesColumn':{spreadsheet:{menu:_('Freeze First Column'),},},
	'FreezePanesRow':{spreadsheet:{menu:_('Freeze First Row'),},},
	'FullScreen':{global:{menu:_('F~ull Screen'),},},
	'FunctionDialog':{spreadsheet:{menu:_('~Function...'),},},
	'GoalSeekDialog':{spreadsheet:{menu:_('~Goal Seek...'),},},
	'GotoPage':{presentation:{menu:_('Go t~o Page...'),},text:{menu:_('Go t~o Page...'),},},
	'GotoSlide':{presentation:{menu:_('Go t~o Slide...'),},},
	'GrafContrast':{global:{menu:_('Contrast'),},},
	'GrafLuminance':{global:{menu:_('Brightness'),},},
	'GrafMode':{global:{menu:_('Image Mode'),},},
	'GrafTransparence':{global:{menu:_('Transparency'),},},
	'GraphicDialog':{text:{menu:_('~Properties...'),},},
	'GraphicFilterInvert':{global:{menu:_('Invert'),},},
	'GraphicFilterPopart':{global:{menu:_('Pop Art'),},},
	'GraphicFilterRemoveNoise':{global:{menu:_('Remove Noise'),},},
	'GraphicFilterSharpen':{global:{menu:_('Sharpen'),},},
	'GraphicFilterSobel':{global:{menu:_('Charcoal Sketch'),},},
	'GridUse':{global:{menu:_('Snap to Grid'),},},
	'GridVisible':{global:{context:_('Display Grid'),menu:_('~Display Grid'),},},
	'Group':{global:{menu:_('~Group...'),},},
	'GroupOutlineMenu':{spreadsheet:{menu:_('~Group and Outline'),},},
	'GroupSparklines':{spreadsheet:{menu:_('Group Sparklines'),},},
	'Grow':{global:{context:_('Increase Font Size'),menu:_('Increase Size'),},},
	'HeaderAndFooter':{presentation:{menu:_('~Header and Footer...'),},},
	'HelpMenu':{global:{menu:_('~Help'),},},
	'Hide':{spreadsheet:{menu:_('~Hide Sheet'),},},
	'HideColumn':{spreadsheet:{context:_('H~ide Columns'),menu:_('~Hide'),},},
	'HideDetail':{global:{menu:_('~Hide Details'),},},
	'HideRow':{spreadsheet:{context:_('H~ide Rows'),menu:_('H~ide'),},},
	'HideSlide':{presentation:{menu:_('~Hide Slide'),},},
	'HyperlinkDialog':{global:{context:_('Insert Hyperlink'),menu:_('~Hyperlink...'),},},
	'Hyphenate':{spreadsheet:{menu:_('~Hyphenation...'),},text:{context:_('Insert Soft Hyphen...'),menu:_('~Hyphenation...'),},},
	'Hyphenation':{presentation:{menu:_('~Hyphenation'),},},
	'IconSetFormatDialog':{spreadsheet:{menu:_('Icon Set...'),},},
	'IncrementIndent':{global:{context:_('Increase Indent'),menu:_('Increase Indent'),},},
	'IncrementLevel':{text:{menu:_('Promote Outline Level'),},},
	'IncrementSubLevels':{text:{menu:_('Promote Outline Level with Subpoints'),},},
	'IndexesMenu':{text:{menu:_('Table of Contents and Inde~x'),},},
	'InsertAVMedia':{global:{context:_('Insert Audio or Video'),menu:_('Media'),},},
	'InsertAnnotation':{global:{context:_('Insert Comment'),menu:_('Comme~nt'),},spreadsheet:{context:_('Insert Note'),menu:_('~Note'),},},
	'InsertThreadedComment':{spreadsheet:{context:_('Insert Comment'),menu:_('Comme~nt'),},},
	'InsertAuthorField':{presentation:{menu:_('~Author'),},text:{menu:_('First ~Author'),},},
	'InsertAxis':{global:{menu:_('Insert Axis'),},},
	'InsertAxisTitle':{global:{menu:_('Insert Axis Title'),},},
	'InsertBookmark':{text:{context:_('Insert Bookmark'),menu:_('Bookmar~k...'),},},
	'InsertBreak':{text:{menu:_('Manual ~Break...'),},},
	'InsertCalcTable':{spreadsheet:{context:_('Insert Table'),menu:_('Table...'),},},
	'InsertCalculation':{spreadsheet:{menu:_('Insert ~Calculated Field...'),},},
	'InsertCanvasSlide':{presentation:{menu:_('New Canvas Slide'),},},
	'InsertCaptionDialog':{text:{context:_('Insert Caption...'),menu:_('Caption...'),},},
	'InsertCell':{spreadsheet:{context:_('~Insert...'),menu:_('Insert ~Cells...'),},},
	'InsertColumnBreak':{spreadsheet:{menu:_('~Column Break'),},text:{menu:_('Insert Column Break'),},},
	'InsertColumnsAfter':{presentation:{menu:_('Insert Column After'),},spreadsheet:{context:_('Insert Columns ~After'),menu:_('Columns ~After'),},text:{context:_('Insert columns after'),menu:_('Columns A~fter'),},},
	'InsertColumnsBefore':{presentation:{menu:_('Insert Column Before'),},spreadsheet:{context:_('Insert Columns ~Before'),menu:_('Columns ~Before'),},text:{context:_('Insert columns before'),menu:_('Columns B~efore'),},},
	'InsertColumnsMenu':{spreadsheet:{menu:_('Insert Co~lumns'),},},
	'InsertCurrentDate':{spreadsheet:{menu:_('~Date'),},},
	'InsertCurrentTime':{spreadsheet:{menu:_('~Time'),},},
	'InsertDataLabel':{global:{menu:_('Insert Single Data Label'),},},
	'InsertDataLabels':{global:{menu:_('Insert Data Labels'),},},
	'InsertDateField':{text:{menu:_('~Date (fixed)'),},},
	'InsertDateFieldFix':{presentation:{menu:_('~Date (fixed)'),},},
	'InsertDateFieldVar':{presentation:{menu:_('Dat~e (variable)'),},text:{menu:_('Dat~e (variable)'),},},
	'InsertEndnote':{text:{context:_('Insert Endnote'),menu:_('~Endnote'),},},
	'InsertField':{text:{menu:_('~More Fields...'),},},
	'InsertFieldCtrl':{text:{context:_('Insert Field'),menu:_('Fiel~d'),},},
	'InsertFootnote':{text:{context:_('Insert Footnote'),menu:_('~Footnote'),},},
	'InsertFrame':{text:{context:_('Insert Frame'),menu:_('F~rame...'),},},
	'InsertGraphic':{global:{context:_('Insert Image...'),menu:_('~Image...'),},},
	'InsertHardHyphen':{global:{menu:_('Non-breaking ~Hyphen'),},},
	'InsertHeaderFooterMenu':{text:{menu:_('He~ader and Footer'),},},
	'InsertHyperlink':{global:{context:_('Insert Hyperlink...'),menu:_('~Hyperlink'),},},
	'InsertIndexesEntry':{text:{context:_('Insert Index Entry'),menu:_('~Index Entry...'),},},
	'InsertLRM':{global:{menu:_('~Left-to-Right Mark'),},},
	'InsertMajorGrid':{global:{menu:_('Insert Major Grid'),},},
	'InsertMeanValue':{global:{menu:_('Insert Mean ~Value Line'),},},
	'InsertMenu':{global:{menu:_('~Insert'),},},
	'InsertMenuTitles':{global:{menu:_('~Titles...'),},},
	'InsertMinorGrid':{global:{menu:_('Insert Minor Grid'),},},
	'InsertNeutralParagraph':{text:{menu:_('Insert Unnumbered Entry'),},},
	'InsertNonBreakingSpace':{global:{menu:_('~No-break Space'),},},
	'InsertObjectChart':{global:{context:_('Insert Chart'),menu:_('~Chart...'),},},
	'InsertObjectStarMath':{spreadsheet:{menu:_('~Formula Object...'),},text:{menu:_('~Formula Object...'),},},
	'InsertPage':{presentation:{menu:_('New Page'),},},
	'InsertPageCountField':{text:{menu:_('Page ~Count'),},},
	'InsertPageField':{presentation:{menu:_('~Page Number'),},},
	'InsertPageFooter':{text:{menu:_('Foote~r'),},},
	'InsertPageHeader':{text:{menu:_('He~ader'),},},
	'InsertPageNumberField':{global:{menu:_('~Page Numbers...'),},text:{context:_('Insert Page Number'),menu:_('~Page Number'),},},
	'InsertPageTitleField':{presentation:{menu:_('Page Tit~le'),},},
	'InsertPagebreak':{text:{context:_('Insert Page Break'),menu:_('~Page Break'),},},
	'InsertPagesField':{presentation:{menu:_('Page ~Count'),},},
	'InsertPivotTable':{spreadsheet:{menu:_('~Insert or Edit...'),},},
	'InsertQrCode':{global:{menu:_('QR and ~Barcode...'),},},
	'InsertRLM':{global:{menu:_('~Right-to-Left Mark'),},},
	'InsertReferenceField':{text:{context:_('Insert Cross-reference'),menu:_('Cross-~reference...'),},},
	'InsertRemoveAxes':{global:{menu:_('Insert/Delete Axes...'),},},
	'InsertRowsAfter':{presentation:{menu:_('Insert Row Below'),},spreadsheet:{context:_('Insert Rows ~Below'),menu:_('Rows ~Below'),},text:{context:_('Insert rows below'),menu:_('Rows ~Below'),},},
	'InsertRowsBefore':{presentation:{menu:_('Insert Row Above'),},spreadsheet:{context:_('Insert Rows ~Above'),menu:_('Rows ~Above'),},text:{context:_('Insert rows above'),menu:_('Rows ~Above'),},},
	'InsertRowsMenu':{spreadsheet:{menu:_('Insert ~Rows'),},},
	'InsertSection':{text:{menu:_('Se~ction...'),},},
	'InsertSignatureLine':{global:{menu:_('Signat~ure Line...'),},},
	'InsertSlide':{presentation:{menu:_('~New Slide'),},},
	'InsertSlideField':{presentation:{menu:_('~Slide Number'),},},
	'InsertSlideTitleField':{presentation:{menu:_('Slide Tit~le'),},},
	'InsertSlidesField':{presentation:{menu:_('Slide ~Count'),},},
	'InsertSoftHyphen':{global:{menu:_('~Soft Hyphen'),},},
	'InsertSparkline':{spreadsheet:{menu:_('Sparkline...'),},},
	'InsertSymbol':{global:{context:_('Insert Special Character'),menu:_('S~pecial Character...'),},},
	'InsertTable':{presentation:{menu:_('~Table...'),},text:{menu:_('Insert ~Table...'),},},
	'InsertTimeField':{global:{menu:_('Time Field'),},text:{menu:_('~Time (fixed)'),},},
	'InsertTimeFieldFix':{presentation:{menu:_('~Time (fixed)'),},},
	'InsertTimeFieldVar':{presentation:{menu:_('T~ime (variable)'),},text:{menu:_('Time (~variable)'),},},
	'InsertTitleField':{text:{menu:_('T~itle'),},},
	'InsertTitles':{global:{menu:_('Insert Titles...'),},},
	'InsertTopicField':{text:{menu:_('~Subject'),},},
	'InsertTrendline':{global:{menu:_('Insert Tre~nd Line...'),},},
	'InsertWJ':{global:{menu:_('~Word Joiner'),},},
	'InsertXErrorBars':{global:{menu:_('Insert ~X Error Bars...'),},},
	'InsertYErrorBars':{global:{menu:_('Insert ~Y Error Bars...'),},},
	'InsertZWSP':{global:{menu:_('~Zero-width Space'),},},
	'Italic':{global:{menu:_('Italic'),},},
	'JumpDownThisLevel':{text:{menu:_('To Next Paragraph in Level'),},},
	'JumpToTable':{spreadsheet:{menu:_('~Go to Sheet...'),},},
	'JumpUpThisLevel':{text:{menu:_('To Previous Paragraph in Level'),},},
	'JustifyPara':{global:{menu:_('Justified'),},},
	'LanguageMenu':{global:{menu:_('Language'),},},
	'LanguageStatus':{global:{menu:_('Language Status'),},},
	'LeaveGroup':{global:{menu:_('E~xit Group'),},},
	'LeftPara':{global:{context:_('Align Left'),menu:_('Left'),},},
	'Legend':{global:{menu:_('Format Legend'),},},
	'Line':{global:{context:_('Insert Line (double click for multi-selection)'),menu:_('Line'),},},
	'LineNumberingDialog':{text:{menu:_('~Line Numbering...'),},},
	'LineSpacing':{global:{context:_('Set Line Spacing'),menu:_('Line Spacing'),},},
	'ManageThemes':{global:{menu:_('Manage Themes...'),},},
	'MasterSlidesPanel':{presentation:{menu:_('Master Slides'),},},
	'MergeCells':{global:{menu:_('Merge Cells'),},},
	'ModifyPage':{presentation:{menu:_('Slide ~Layout'),},},
	'Move':{spreadsheet:{menu:_('~Move or Copy Sheet...'),},},
	'MoveDown':{text:{menu:_('Move Item Down'),},},
	'MoveDownSubItems':{text:{menu:_('Move Item Down with Subpoints'),},},
	'MoveUp':{text:{menu:_('Move Item Up'),},},
	'MoveUpSubItems':{text:{menu:_('Move Item Up with Subpoints'),},},
	'MovingAverageDialog':{spreadsheet:{menu:_('~Moving Average...'),},},
	'NameGroup':{global:{context:_('Give a label to identify an object'),menu:_('Name...'),},},
	'NamesMenu':{spreadsheet:{menu:_('~Named Ranges and Expressions'),},},
	'Navigator':{global:{context:_('Show Navigator Window'),menu:_('Na~vigator'),},},
	'NextTrackedChange':{text:{context:_('Next Tracked Change'),menu:_('Next'),},},
	'NumberFormatCurrency':{spreadsheet:{context:_('Format as Currency'),menu:_('Currency'),},text:{menu:_('Number Format: Currency'),},},
	'NumberFormatDate':{spreadsheet:{context:_('Format as Date'),menu:_('Date'),},text:{menu:_('Number Format: Date'),},},
	'NumberFormatDecDecimals':{spreadsheet:{menu:_('Delete Decimal Place'),},},
	'NumberFormatDecimal':{spreadsheet:{context:_('Format as Number'),menu:_('Number'),},text:{menu:_('Number Format: Decimal'),},},
	'NumberFormatIncDecimals':{spreadsheet:{menu:_('Add Decimal Place'),},},
	'NumberFormatMenu':{spreadsheet:{menu:_('Number Format'),},},
	'NumberFormatPercent':{spreadsheet:{context:_('Format as Percent'),menu:_('Percent'),},text:{menu:_('Number Format: Percent'),},},
	'NumberFormatScientific':{spreadsheet:{context:_('Format as Scientific'),menu:_('Scientific'),},text:{menu:_('Number Format: Exponential'),},},
	'NumberFormatStandard':{spreadsheet:{context:_('Format as General'),menu:_('General'),},text:{menu:_('Number Format: Standard'),},},
	'NumberFormatThousands':{spreadsheet:{menu:_('Thousands Separator'),},},
	'NumberFormatTime':{spreadsheet:{context:_('Format as Time'),menu:_('Time'),},text:{menu:_('Number Format: Time'),},},
	'NumberingStart':{text:{menu:_('Restart Numbering'),},},
	'ObjectAlignLeft':{global:{menu:_('~Left'),},},
	'ObjectAlignRight':{global:{menu:_('~Right'),},},
	'ObjectBackOne':{global:{menu:_('Back One'),},},
	'ObjectForwardOne':{global:{menu:_('Forward One'),},},
	'ObjectTitleDescription':{global:{context:_('Add descriptions of non-text content (for accessibility)'),menu:_('Description...'),},},
	'OnlineAutoFormat':{text:{menu:_('~While Typing'),},},
	'OpenHyperlinkOnCursor':{global:{menu:_('Open Hyperlink'),},},
	'Orientation':{text:{menu:_('Orientation'),},},
	'OutlineBullet':{global:{menu:_('~Bullets and Numbering...'),},},
	'OutlineFont':{global:{menu:_('Outline Font Effect'),},},
	'Overline':{global:{menu:_('Overline'),},},
	'PageDialog':{global:{menu:_('~Page...'),},text:{menu:_('~Page Style...'),},},
	'PageDown':{text:{menu:_('Next Page'),},},
	'PageFormatDialog':{spreadsheet:{context:_('Format Pa~ge...'),menu:_('~Page Style...'),},},
	'PageMenu':{presentation:{menu:_('~Page'),},},
	'PageNumberWizard':{text:{context:_('Insert page number'),menu:_('~Page Number...'),},},
	'PageSetup':{presentation:{menu:_('Page Properties...'),},},
	'PageUp':{text:{menu:_('Previous Page'),},},
	'ParaLeftToRight':{global:{menu:_('Left-To-Right'),},},
	'ParaRightToLeft':{global:{menu:_('Right-To-Left'),},},
	'ParagraphDialog':{global:{menu:_('P~aragraph...'),},},
	'ParaspaceDecrease':{global:{context:_('Decrease Paragraph Spacing'),menu:_('Decrease Paragraph Spacing'),},},
	'ParaspaceIncrease':{global:{context:_('Increase Paragraph Spacing'),menu:_('Increase Paragraph Spacing'),},},
	'Paste':{global:{menu:_('~Paste'),},},
	'PasteSpecial':{global:{menu:_('Paste ~Special...'),},presentation:{menu:_('Paste ~Special...'),},spreadsheet:{menu:_('Paste ~Special...'),},text:{context:_('~More Options...'),menu:_('Paste ~Special...'),},},
	'PickList':{global:{menu:_('~File'),},},
	'PreviousTrackedChange':{text:{context:_('Previous Tracked Change'),menu:_('Pr~evious'),},},
	'Print':{global:{menu:_('~Print...'),},},
	'PrintRangesMenu':{spreadsheet:{menu:_('Prin~t Ranges'),},},
	'Protect':{spreadsheet:{menu:_('Protect ~Sheet...'),},text:{menu:_('Protect Cells'),},},
	'RecalcPivotTable':{spreadsheet:{menu:_('~Refresh'),},},
	'Redo':{global:{menu:_('~Redo'),},},
	'RegressionDialog':{spreadsheet:{menu:_('~Regression...'),},},
	'ReinstateTrackedChange':{text:{context:_('Reject tracked change but keep it'),menu:_('Reject but Track'),},},
	'RejectAllTrackedChanges':{text:{menu:_('Reject All'),},},
	'RejectTrackedChange':{text:{context:_('Reject Change'),menu:_('Reject'),},},
	'RejectTrackedChangeToNext':{text:{menu:_('Reject and Move to Next'),},},
	'Remove':{spreadsheet:{menu:_('~Delete Sheet...'),},},
	'RemoveBullets':{text:{menu:_('No List'),},},
	'RemoveCalcTable':{spreadsheet:{menu:_('~Remove Table...'),},},
	'RemoveHyperlink':{global:{menu:_('~Remove Hyperlink'),},},
	'RemoveTableOf':{text:{menu:_('Delete Index'),},},
	'RenameMasterPage':{presentation:{menu:_('Rename Master'),},},
	'RenameTable':{spreadsheet:{menu:_('Rename S~heet...'),},},
	'ReplyComment':{global:{menu:_('Reply Comment'),},},
	'ResetAllDataPoints':{global:{menu:_('Reset all Data Points'),},},
	'ResetAttributes':{global:{context:_('Clear Direct Formatting'),menu:_('~Clear Direct Formatting'),},spreadsheet:{context:_('Clear Direct Formatting'),menu:_('Clear ~Direct Formatting'),},text:{context:_('Clear Direct Formatting'),menu:_('Clear ~Direct Formatting'),},},
	'ResetDataPoint':{global:{menu:_('Reset Data Point'),},},
	'RightPara':{global:{context:_('Align Right'),menu:_('Right'),},},
	'RotateLeft':{text:{menu:_('Rotate 90° ~Left'),},},
	'RotateMenu':{global:{menu:_('Rot~ate'),},},
	'RotateRight':{text:{menu:_('Rotate 90° ~Right'),},},
	'RowHeight':{spreadsheet:{context:_('Row ~Height...'),menu:_('~Height...'),},},
	'RowOperations':{spreadsheet:{menu:_('Row'),},},
	'RunInsCalcTable':{spreadsheet:{menu:_('~Insert Table...'),},},
	'RunMacro':{global:{menu:_('R~un Macro...'),},},
	'SamplingDialog':{spreadsheet:{menu:_('~Sampling...'),},},
	'Save':{global:{menu:_('~Save'),},},
	'SaveAs':{global:{menu:_('Save ~As...'),},},
	'SaveGraphic':{global:{menu:_('Save...'),},presentation:{menu:_('~Save...'),},},
	'SearchDialog':{global:{menu:_('Find and Rep~lace...'),},},
	'SelectAll':{global:{menu:_('Select ~All'),},},
	'SelectBackground':{presentation:{menu:_('Set Background Image...'),},},
	'SelectDB':{spreadsheet:{menu:_('Select ~Range...'),},},
	'SelectSheetView':{spreadsheet:{menu:_('Select Sheet View'),},},
	'SelectTable':{presentation:{context:_('Select Table'),menu:_('~Select Table'),},text:{context:_('Select Table'),menu:_('~Table'),},},
	'SendToBack':{global:{menu:_('~Send to Back'),},},
	'SetAnchorAtChar':{text:{menu:_('To ~Character'),},},
	'SetAnchorToCell':{spreadsheet:{menu:_('To ~Cell'),},},
	'SetAnchorToCellResize':{spreadsheet:{menu:_('To Cell (~resize with cell)'),},},
	'SetAnchorToChar':{text:{menu:_('As C~haracter'),},},
	'SetAnchorToFrame':{text:{menu:_('To ~Frame'),},},
	'SetAnchorToPage':{spreadsheet:{menu:_('To P~age'),},text:{menu:_('To P~age'),},},
	'SetAnchorToPara':{text:{menu:_('To ~Paragraph'),},},
	'SetBorderStyle':{global:{menu:_('Borders (Shift to overwrite)'),},},
	'SetDefault':{global:{context:_('Clear Direct Formatting'),menu:_('Clear ~Direct Formatting'),},},
	'SetDocumentProperties':{global:{menu:_('Propert~ies...'),},},
	'SetLanguageAllTextMenu':{global:{menu:_('For All Text'),},},
	'SetLanguageParagraphMenu':{global:{menu:_('For Paragraph'),},},
	'SetLanguageSelectionMenu':{global:{menu:_('For Selection'),},},
	'SetObjectToBackground':{global:{menu:_('To Background'),},},
	'SetObjectToForeground':{global:{menu:_('To Foreground'),},},
	'SetOptimalColumnWidth':{presentation:{menu:_('Optimal Column Width'),},spreadsheet:{menu:_('~Optimal Width...'),},text:{menu:_('Optimal Column Width'),},},
	'SetOptimalRowHeight':{presentation:{menu:_('Optimal Row Height'),},spreadsheet:{menu:_('~Optimal Height...'),},text:{menu:_('Optimal Row Height'),},},
	'Shadowed':{global:{context:_('Toggle Shadow'),menu:_('Shadow'),},},
	'ShapesMenu':{global:{menu:_('~Shape'),},},
	'SheetMenu':{spreadsheet:{menu:_('~Sheet'),},},
	'SheetRightToLeft':{spreadsheet:{context:_('Sheet R~ight-To-Left'),menu:_('R~ight-To-Left'),},},
	'Show':{spreadsheet:{menu:_('~Show Sheet...'),},},
	'ShowAnnotations':{global:{menu:_('Comments'),},},
	'ShowColumn':{spreadsheet:{context:_('S~how Columns'),menu:_('~Show'),},},
	'ShowDetail':{global:{menu:_('~Show Details'),},},
	'ShowLicense':{global:{menu:_('License Information'),},},
	'ShowResolvedAnnotations':{text:{menu:_('Resolved Comments'),},},
	'ShowRow':{spreadsheet:{context:_('Sho~w Rows'),menu:_('~Show'),},},
	'ShowSlide':{presentation:{menu:_('Sho~w Slide'),},},
	'ShowTrackedChanges':{text:{menu:_('Show'),},},
	'Shrink':{global:{context:_('Decrease Font Size'),menu:_('Decrease Size'),},},
	'Shuffle':{spreadsheet:{menu:_('Shuffle'),},},
	'Sidebar':{global:{menu:_('Sidebar'),},},
	'SidebarDeck.A11yCheckDeck':{text:{menu:_('Open the Accessibility Check Deck'),},},
	'SidebarDeck.ElementsDeck':{global:{menu:_('Open the Elements Deck'),},},
	'SidebarDeck.StyleListDeck':{global:{menu:_('Open the Styles Deck'),},},
	'Signature':{global:{menu:_('Digital Signatu~res...'),},},
	'SlideChangeWindow':{presentation:{menu:_('Slide Transition'),},},
	'SlideMenu':{presentation:{menu:_('S~lide'),},},
	'SlideSetup':{presentation:{menu:_('Slide Properties...'),},},
	'SmallCaps':{global:{menu:_('Small capitals'),},},
	'SortAscending':{spreadsheet:{menu:_('Sort Ascending'),},},
	'SortDescending':{spreadsheet:{menu:_('Sort Descending'),},},
	'SpacePara1':{global:{menu:_('Line Spacing: 1'),},},
	'SpacePara15':{global:{menu:_('Line Spacing: 1.5'),},},
	'SpacePara115':{global:{menu:_('Line Spacing: 1.15'),},},
	'SpacePara2':{global:{menu:_('Line Spacing: 2'),},},
	'Spacing':{global:{context:_('Set Character Spacing'),menu:_('Character Spacing'),},},
	'SpellCheckApplySuggestion':{global:{menu:_('Apply Suggestion'),},},
	'SpellCheckIgnore':{global:{menu:_('Ignore'),},},
	'SpellCheckIgnoreAll':{global:{menu:_('Ignore All'),},},
	'SpellDialog':{global:{menu:_('~Spelling...'),},},
	'SpellOnline':{global:{context:_('Toggle Automatic Spell Checking'),menu:_('~Automatic Spell Checking'),},},
	'SpellingAndGrammarDialog':{global:{menu:_('~Spelling...'),},},
	'SplitCell':{global:{menu:_('Split Cells...'),},spreadsheet:{menu:_('Unmerge Cells'),},},
	'SplitTable':{text:{menu:_('Split Table...'),},},
	'StarShapes.bang':{global:{menu:_('Explosion'),},},
	'StarShapes.concave-star6':{global:{menu:_('6-Point Star, Concave'),},},
	'StarShapes.doorplate':{global:{menu:_('Doorplate'),},},
	'StarShapes.horizontal-scroll':{global:{menu:_('Horizontal Scroll'),},},
	'StarShapes.signet':{global:{menu:_('Signet'),},},
	'StarShapes.star12':{global:{menu:_('12-Point Star'),},},
	'StarShapes.star24':{global:{menu:_('24-Point Star'),},},
	'StarShapes.star4':{global:{menu:_('4-Point Star'),},},
	'StarShapes.star5':{global:{menu:_('5-Point Star'),},},
	'StarShapes.star6':{global:{menu:_('6-Point Star'),},},
	'StarShapes.star8':{global:{menu:_('8-Point Star'),},},
	'StarShapes.vertical-scroll':{global:{menu:_('Vertical Scroll'),},},
	'StatisticsMenu':{spreadsheet:{menu:_('Statistics'),},},
	'Strikeout':{global:{menu:_('Strikethrough'),},},
	'SubScript':{global:{menu:_('Subscript'),},text:{menu:_('Subscript'),},},
	'SuperScript':{global:{menu:_('Superscript'),},text:{menu:_('Superscript'),},},
	'SymbolShapes.brace-pair':{global:{menu:_('Double Brace'),},},
	'SymbolShapes.bracket-pair':{global:{menu:_('Double Bracket'),},},
	'SymbolShapes.cloud':{global:{menu:_('Cloud'),},},
	'SymbolShapes.diamond-bevel':{global:{menu:_('Diamond Bevel'),},},
	'SymbolShapes.flower':{global:{menu:_('Flower'),},},
	'SymbolShapes.forbidden':{global:{menu:_('Prohibited'),},},
	'SymbolShapes.heart':{global:{menu:_('Heart'),},},
	'SymbolShapes.left-brace':{global:{menu:_('Left Brace'),},},
	'SymbolShapes.left-bracket':{global:{menu:_('Left Bracket'),},},
	'SymbolShapes.lightning':{global:{menu:_('Lightning Bolt'),},},
	'SymbolShapes.moon':{global:{menu:_('Moon'),},},
	'SymbolShapes.octagon-bevel':{global:{menu:_('Octagon Bevel'),},},
	'SymbolShapes.puzzle':{global:{menu:_('Puzzle'),},},
	'SymbolShapes.quad-bevel':{global:{menu:_('Square Bevel'),},},
	'SymbolShapes.right-brace':{global:{menu:_('Right Brace'),},},
	'SymbolShapes.right-bracket':{global:{menu:_('Right Bracket'),},},
	'SymbolShapes.smiley':{global:{menu:_('Smiley Face'),},},
	'SymbolShapes.sun':{global:{menu:_('Sun'),},},
	'TTestDialog':{spreadsheet:{menu:_('Paired ~t-test...'),},},
	'TableCellBackgroundColor':{text:{menu:_('Table Cell Background Color'),},},
	'TableDeleteMenu':{global:{menu:_('~Delete'),},},
	'TableDialog':{presentation:{context:_('Ta~ble Properties...'),menu:_('~Properties...'),},text:{context:_('~Table Properties...'),menu:_('~Properties...'),},},
	'TableInsertMenu':{global:{menu:_('~Insert'),},},
	'TableMenu':{global:{menu:_('T~able'),},},
	'TableNumberFormatDialog':{text:{menu:_('Number Format...'),},},
	'TableSelectMenu':{text:{menu:_('~Select'),},},
	'TableSort':{presentation:{menu:_('So~rt...'),},text:{menu:_('So~rt...'),},},
	'TaskPaneInsertPage':{presentation:{menu:_('Insert Slide'),},},
	'Text':{global:{context:_('Insert Text Box (double click for multi-selection)'),menu:_('~Text Box'),},},
	'TextAlign':{global:{menu:_('Align Tex~t'),},},
	'TextWrap':{text:{menu:_('Text Wrap...'),},},
	'ThemeDialog':{global:{menu:_('Theme...'),},},
	'ThesaurusDialog':{global:{menu:_('~Thesaurus...'),},text:{menu:_('~Thesaurus...'),},},
	'TitlePageDialog':{text:{menu:_('Title Page...'),},},
	'ToggleGridHorizontal':{global:{menu:_('Horizontal Grids'),},},
	'ToggleGridVertical':{global:{menu:_('Vertical Grids'),},},
	'ToggleLegend':{global:{menu:_('Legend On/Off'),},},
	'ToggleMergeCells':{spreadsheet:{context:_('Merge and center or unmerge cells depending on the current toggle state'),menu:_('M~erge and Center Cells'),},},
	'TogglePrintGrid':{spreadsheet:{menu:_('Print Grid Lines'),},},
	'ToggleSheetGrid':{spreadsheet:{menu:_('View Grid Lines'),},},
	'ToolsMenu':{global:{menu:_('~Tools'),},},
	'TrackChanges':{text:{context:_('Record Tracked Changes'),menu:_('~Record'),},},
	'TransformDialog':{global:{menu:_('Position and Si~ze...'),},},
	'Translate':{text:{menu:_('Translate...'),},},
	'Underline':{global:{menu:_('Underline'),},},
	'UnderlineDouble':{global:{menu:_('Double Underline'),},},
	'Undo':{global:{menu:_('~Undo'),},},
	'UnfloatFrame':{text:{menu:_('Unfloat Frame Content'),},},
	'Ungroup':{global:{menu:_('~Ungroup...'),},},
	'UngroupSparklines':{spreadsheet:{menu:_('Ungroup Sparklines'),},},
	'UnsetCellsReadOnly':{text:{menu:_('Unprotect Cells'),},},
	'UpSearch':{global:{menu:_('Find Previous'),},},
	'UpdateAll':{text:{menu:_('~Update All'),},},
	'UpdateCurIndex':{text:{context:_('Update ~Index'),menu:_('Current ~Index'),},},
	'Validation':{spreadsheet:{menu:_('~Validity...'),},},
	'VerticalText':{global:{context:_('Insert Vertical Text'),menu:_('Vertical Text'),},},
	'View3D':{global:{menu:_('~3D View...'),},},
	'ViewMenu':{global:{menu:_('~View'),},},
	'Watermark':{text:{menu:_('Watermark...'),},},
	'WordCountDialog':{text:{menu:_('~Word Count...'),},},
	'WrapAnchorOnly':{text:{menu:_('~First Paragraph'),},},
	'WrapContour':{text:{menu:_('~Contour'),},},
	'WrapIdeal':{text:{menu:_('~Optimal'),},},
	'WrapLeft':{text:{menu:_('Before'),},},
	'WrapMenu':{text:{menu:_('~Wrap'),},},
	'WrapOff':{text:{menu:_('None'),},},
	'WrapOn':{text:{menu:_('~Parallel'),},},
	'WrapRight':{text:{menu:_('After'),},},
	'WrapText':{spreadsheet:{menu:_('Wrap Text'),},},
	'WrapThrough':{text:{menu:_('~Through'),},},
	'WrapThroughTransparencyToggle':{text:{menu:_('In ~Background'),},},
	'XLineColor':{global:{menu:_('Line Color'),},},
	'ZTestDialog':{spreadsheet:{menu:_('~Z-test...'),},},
	'ZoomMinus':{global:{menu:_('Zoom Out'),},},
	'ZoomPlus':{global:{menu:_('Zoom In'),},},
};

window._UNO = function(string, component, isContext) {
	var command = string.substr(5);
	var context = 'menu';
	if (isContext === true) {
		context = 'context';
	}
	var entry = unoCommandsArray[command];
	if (entry === undefined) {
		return command;
	}
	if (component == 'drawing') {
		component = 'presentation';
	}
	var componentEntry = entry[component];
	if (componentEntry === undefined) {
		componentEntry = entry['global'];
		if (componentEntry === undefined) {
			return command;
		}
	}
	var text = componentEntry[context];
	if (text === undefined) {
		text = componentEntry['menu'];
		if (text === undefined) {
			return command;
		}
	}

	return this.removeAccessKey(text);
}

window.removeAccessKey = function(text) {
	// Remove access key markers from translated strings
	// 1. access key in parenthesis in case of non-latin scripts
	text = text.replace(/\(~[A-Za-z]\)/, '');
	// 2. remove normal access key
	text = text.replace('~', '');

	return text;
}
