// Don't modify, generated using scripts/unoshortcuts.py
/* eslint-disable no-unused-vars */

var unoShortcutsMap = {
	'.uno:AlignBlock': 'Ctrl+J',
	'.uno:AlignHorizontalCenter': 'Ctrl+E',
	'.uno:AlignLeft': 'Ctrl+L',
	'.uno:AlignRight': 'Ctrl+R',
	'.uno:Bold': 'Ctrl+B',
	'.uno:BringToFront': 'Ctrl+Shift++',
	'.uno:Calculate': 'F9',
	'.uno:CenterPara': 'Ctrl+E',
	'.uno:ChangeCaseRotateCase': 'Shift+F3',
	'.uno:CommonAlignHorizontalCenter': 'Ctrl+E',
	'.uno:CommonAlignJustified': 'Ctrl+J',
	'.uno:CommonAlignLeft': 'Ctrl+L',
	'.uno:CommonAlignRight': 'Ctrl+R',
	'.uno:ControlCodes': 'Ctrl+F10',
	'.uno:Copy': 'Ctrl+C',
	'.uno:Cut': 'Ctrl+X',
	'.uno:DataFilterAutoFilter': 'Ctrl+Shift+L',
	'.uno:DefaultBullet': 'Ctrl+Shift+L',
	'.uno:DefineName': 'Ctrl+F3',
	'.uno:Delete': 'Delete',
	'.uno:DeleteCell': 'Ctrl+-',
	'.uno:EnterGroup': 'F3',
	'.uno:FontDialog': 'Alt+C',
	'.uno:FormatCellDialog': 'Ctrl+1',
	'.uno:FormatGroup': 'Ctrl+Shift+G',
	'.uno:FormatUngroup': 'Ctrl+Shift+Alt+G',
	'.uno:FullScreen': 'Ctrl+Shift+J',
	'.uno:FunctionDialog': 'Ctrl+F2',
	'.uno:GotoPage': 'Ctrl+Shift+F5',
	'.uno:GraphicDialog': 'F4',
	'.uno:Group': 'Shift+Alt+Right',
	'.uno:Grow': 'Ctrl+]',
	'.uno:HyperlinkDialog': 'Ctrl+K',
	'.uno:InsertAnnotation': 'Ctrl+Alt+C',
	'.uno:InsertCell': 'Ctrl++',
	'.uno:InsertColumnBreak': 'Ctrl+Shift+Return',
	'.uno:InsertCurrentDate': 'Ctrl+;',
	'.uno:InsertCurrentTime': 'Ctrl+Shift+;',
	'.uno:InsertEndnote': 'Ctrl+Alt+D',
	'.uno:InsertField': 'Ctrl+F2',
	'.uno:InsertFootnote': 'Ctrl+Alt+F',
	'.uno:InsertHardHyphen': 'Ctrl+Shift+-',
	'.uno:InsertNonBreakingSpace': 'Ctrl+Shift+Space',
	'.uno:InsertObjectStarMath': 'Shift+Alt+E',
	'.uno:InsertPage': 'Ctrl+M',
	'.uno:InsertPagebreak': 'Ctrl+Return',
	'.uno:InsertSoftHyphen': 'Ctrl+-',
	'.uno:InsertTable': 'Ctrl+F12',
	'.uno:InsertZWSP': 'Ctrl+/',
	'.uno:Italic': 'Ctrl+I',
	'.uno:JustifyPara': 'Ctrl+J',
	'.uno:KeyboardShortcuts': 'Ctrl+Shift+?',
	'.uno:LeaveGroup': 'Ctrl+F3',
	'.uno:LeftPara': 'Ctrl+L',
	'.uno:MoveDown': 'Ctrl+Alt+Down',
	'.uno:MoveUp': 'Ctrl+Alt+Up',
	'.uno:Navigator': 'F5',
	'.uno:NumberFormatCurrency': 'Ctrl+Shift+4',
	'.uno:NumberFormatDate': 'Ctrl+Shift+3',
	'.uno:NumberFormatDecimal': 'Ctrl+Shift+1',
	'.uno:NumberFormatPercent': 'Ctrl+Shift+5',
	'.uno:NumberFormatScientific': 'Ctrl+Shift+2',
	'.uno:NumberFormatStandard': 'Ctrl+Shift+6',
	'.uno:PageDialog': 'Shift+Alt+P',
	'.uno:PageDown': 'PageDown',
	'.uno:PageUp': 'PageUp',
	'.uno:ParaLeftToRight': 'Ctrl+Shift+A',
	'.uno:ParaRightToLeft': 'Ctrl+Shift+D',
	'.uno:Paste': 'Ctrl+V',
	'.uno:PasteSpecial': 'Ctrl+Shift+V',
	'.uno:Print': 'Ctrl+P',
	'.uno:Redo': 'Ctrl+Y',
	'.uno:RemoveBullets': 'Ctrl+Shift+F12',
	'.uno:ResetAttributes': 'Ctrl+M',
	'.uno:RightPara': 'Ctrl+R',
	'.uno:Save': 'Ctrl+S',
	'.uno:SaveAs': 'Ctrl+Shift+S',
	'.uno:SearchDialog': 'Ctrl+H',
	'.uno:SelectAll': 'Ctrl+A',
	'.uno:SendToBack': 'Ctrl+Shift+-',
	'.uno:SetDefault': 'Ctrl+M',
	'.uno:Shrink': 'Ctrl+[',
	'.uno:Sidebar': 'Ctrl+F5',
	'.uno:SidebarDeck.A11yCheckDeck': 'Alt+8',
	'.uno:SidebarDeck.ElementsDeck': 'Alt+2',
	'.uno:SidebarDeck.StyleListDeck': 'Alt+2',
	'.uno:SmallCaps': 'Ctrl+Shift+K',
	'.uno:SpacePara1': 'Ctrl+1',
	'.uno:SpacePara15': 'Ctrl+5',
	'.uno:SpacePara2': 'Ctrl+2',
	'.uno:SpellDialog': 'F7',
	'.uno:SpellOnline': 'Shift+F7',
	'.uno:SpellingAndGrammarDialog': 'F7',
	'.uno:Strikeout': 'Ctrl+Alt+5',
	'.uno:SubScript': 'Ctrl+Shift+B',
	'.uno:SuperScript': 'Ctrl+Shift+P',
	'.uno:Text': 'F2',
	'.uno:ThesaurusDialog': 'Ctrl+F7',
	'.uno:TransformDialog': 'F4',
	'.uno:Underline': 'Ctrl+U',
	'.uno:UnderlineDouble': 'Ctrl+D',
	'.uno:Undo': 'Ctrl+Z',
	'.uno:Ungroup': 'Ctrl+F12',
	'.uno:ZoomMinus': 'Ctrl+Shift+PageDown',
	'.uno:ZoomPlus': 'Ctrl+Shift+PageUp',
};

var unoShortcutsL10N = {
	bs: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	da: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	de: {
		'.uno:AlignBlock': 'Ctrl+B',
		'.uno:Bold': 'Ctrl+Shift+F',
		'.uno:ChangeCaseRotateCase': 'Ctrl+Shift+F3',
		'.uno:FormatCellDialog': 'Alt+0',
		'.uno:FormatUngroup': 'Ctrl+Shift+H',
		'.uno:FunctionDialog': 'Shift+F3',
		'.uno:Group': 'Ctrl+F12',
		'.uno:InsertAnnotation': 'Shift+F2',
		'.uno:InsertCurrentDate': 'Ctrl+.',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+.',
		'.uno:Italic': 'Ctrl+Shift+K',
		'.uno:Navigator': 'Ctrl+F',
		'.uno:PasteSpecial': 'Ctrl+Alt+V',
		'.uno:SearchDialog': 'Ctrl+Alt+F',
		'.uno:Shrink': 'Ctrl+Shift+;',
		'.uno:SmallCaps': 'Ctrl+Shift+Q',
		'.uno:Strikeout': 'Ctrl+5',
		'.uno:SubScript': 'Ctrl+T',
		'.uno:SuperScript': 'Ctrl+H',
		'.uno:Underline': 'Ctrl+Shift+U',
		'.uno:UnderlineDouble': 'Ctrl+Shift+D',
		'.uno:Ungroup': 'Ctrl+Shift+F12',
	},
	es: {
		'.uno:AlignHorizontalCenter': 'Ctrl+T',
		'.uno:Bold': 'Ctrl+N',
		'.uno:HyperlinkDialog': 'Ctrl+Alt+K',
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
		'.uno:Italic': 'Ctrl+K',
		'.uno:Save': 'Ctrl+G',
		'.uno:SearchDialog': 'Ctrl+Alt+B',
		'.uno:SelectAll': 'Ctrl+E',
		'.uno:Underline': 'Ctrl+S',
	},
	et: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	fi: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	fo: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	fr: {
		'.uno:Bold': 'Ctrl+G',
		'.uno:InsertCurrentTime': 'Ctrl+:',
	},
	hr: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	hu: {
		'.uno:InsertAnnotation': 'Ctrl+Shift+H',
		'.uno:InsertCurrentDate': 'Ctrl+.',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+.',
		'.uno:Shrink': 'Ctrl+Shift+,',
	},
	is: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	it: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	nb: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	nn: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	pt: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	'pt-BR': {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	ro: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	ru: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	sl: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	sq: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	sr: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
	sv: {
		'.uno:Grow': 'Ctrl+9',
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
		'.uno:Shrink': 'Ctrl+8',
	},
	tr: {
		'.uno:InsertCurrentDate': 'Ctrl+,',
		'.uno:InsertCurrentTime': 'Ctrl+Shift+,',
	},
};

var unoShortcutsL10NKeyBindings = {
	de: [
		{
			key: 'b',
			modifier: 1,
			unoAction: '.uno:AlignBlock',
			docType: 'spreadsheet',
		},
		{ key: 'F', modifier: 5, unoAction: '.uno:Bold' },
		{ key: '+', modifier: 5, unoAction: '.uno:CalculateSel', docType: 'text' },
		{
			key: 'd',
			modifier: 1,
			unoAction: '.uno:CopyObjects',
			docType: 'presentation',
		},
		{
			key: 'M',
			modifier: 5,
			unoAction: '.uno:DecrementIndent',
			docType: 'text',
		},
		{
			key: '/',
			modifier: 1,
			unoAction: '.uno:DefaultNumbering',
			docType: 'text',
		},
		{
			key: 'F5',
			modifier: 0,
			unoAction: '.uno:FocusCellAddress',
			docType: 'spreadsheet',
		},
		{
			key: 'F3',
			modifier: 4,
			unoAction: '.uno:FunctionDialog',
			docType: 'spreadsheet',
		},
		{
			key: 'F9',
			modifier: 4,
			unoAction: '.uno:GridVisible',
			docType: 'presentation',
		},
		{
			key: 'F12',
			modifier: 1,
			unoAction: '.uno:Group',
			docType: 'spreadsheet',
		},
		{
			key: 'm',
			modifier: 1,
			unoAction: '.uno:IncrementIndent',
			docType: 'text',
		},
		{ key: 'K', modifier: 5, unoAction: '.uno:Italic' },
		{ key: 'f', modifier: 1, unoAction: '.uno:Navigator', docType: 'text' },
		{ key: 'g', modifier: 1, unoAction: '.uno:RecSearch' },
		{
			key: ' ',
			modifier: 1,
			unoAction: '.uno:RemoveDirectCharFormats',
			docType: 'presentation',
		},
		{
			key: 'F9',
			modifier: 1,
			unoAction: '.uno:ShowRuler',
			docType: 'presentation',
		},
		{ key: ';', modifier: 5, unoAction: '.uno:Shrink', docType: 'spreadsheet' },
		{ key: 'Q', modifier: 5, unoAction: '.uno:SmallCaps', docType: 'text' },
		{ key: '1', modifier: 1, unoAction: '.uno:SpacePara1', docType: 'text' },
		{
			key: '5',
			modifier: 1,
			unoAction: '.uno:Strikeout',
			docType: 'spreadsheet',
		},
		{
			key: '+',
			modifier: 1,
			unoAction: '.uno:SubScript',
			docType: 'presentation',
		},
		{
			key: '*',
			modifier: 1,
			unoAction: '.uno:SuperScript',
			docType: 'presentation',
		},
		{ key: 'h', modifier: 1, unoAction: '.uno:SuperScript' },
		{
			key: 'D',
			modifier: 5,
			unoAction: '.uno:UnderlineDouble',
			docType: 'text',
		},
		{
			key: 'F12',
			modifier: 5,
			unoAction: '.uno:Ungroup',
			docType: 'spreadsheet',
		},
		{ key: 'c', modifier: 2, unoAction: '.uno:UnicodeNotationToggle' },
	],
	es: [
		{ key: 'u', modifier: 1, unoAction: '.uno:AddDirect' },
		{ key: 'n', modifier: 1, unoAction: '.uno:Bold' },
		{ key: 'k', modifier: 1, unoAction: '.uno:Italic' },
		{ key: 'a', modifier: 1, unoAction: '.uno:Open' },
		{ key: 'g', modifier: 1, unoAction: '.uno:Save' },
		{ key: 'e', modifier: 1, unoAction: '.uno:SelectAll' },
		{ key: 's', modifier: 1, unoAction: '.uno:Underline' },
	],
	eu: [{ key: 'c', modifier: 2, unoAction: '.uno:UnicodeNotationToggle' }],
	fr: [{ key: 'g', modifier: 1, unoAction: '.uno:Bold' }],
	gl: [{ key: 'c', modifier: 2, unoAction: '.uno:UnicodeNotationToggle' }],
	nl: [{ key: 'c', modifier: 2, unoAction: '.uno:UnicodeNotationToggle' }],
	'pt-BR': [{ key: 'c', modifier: 2, unoAction: '.uno:UnicodeNotationToggle' }],
	'zh-CN': [
		{
			key: ' ',
			modifier: 5,
			unoAction: '.uno:SelectColumn',
			docType: 'spreadsheet',
		},
	],
	'zh-TW': [
		{
			key: ' ',
			modifier: 5,
			unoAction: '.uno:SelectColumn',
			docType: 'spreadsheet',
		},
	],
};

var unoShortcutsModifierL10N = {
	ca: { Shift: 'Maj' },
	de: { Ctrl: 'Strg', Shift: 'Umschalt' },
	es: { Shift: 'Mayús' },
	fr: { Shift: 'Maj' },
	it: { Shift: 'Maiusc' },
	lt: { Ctrl: 'Vald', Shift: 'Lyg2' },
	nb: { Shift: 'Skift' },
	nn: { Shift: 'Skift' },
	sl: { Ctrl: 'Krmilka', Shift: 'Dvigalka', Alt: 'Izmenjalka' },
	sv: { Shift: 'Skift' },
};
