/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_test_XTestListener_idl__
#define __com_sun_star_test_XTestListener_idl__

#include <com/sun/star/lang/XEventListener.idl>
#include <com/sun/star/test/TestEvent.idl>



module com { module sun { module star { module test {

/** is used to handle errors/exceptions and warnings during tests.
*/
published interface XTestListener: com::sun::star::lang::XEventListener
{
    /** gets called when an error occurs while performing an test.
        If the error results from an exception, the exception
        can be found in the Exception member of the TestEvent

        @param evt
        This property contains the <type>TestEvent</type> object that
        describes the event source and error description.
    */
    void notifyError( [in] com::sun::star::test::TestEvent evt );

    /** gets called when an warning occurs while performing an test.

        @param evt
        This property contains the <type>TestEvent</type> object that
        describes the event source and warning description.
    */
    void notifyWarning( [in] com::sun::star::test::TestEvent evt );

    /** can be called by the broadcaster to inform the listener about
        the progress of the test. The listener can use this information
        for example to write it into a test protocol file.

        @param evt
        This property contains the <type>TestEvent</type> object that
        describes the protocol message.
    */
    void protocol( [in] com::sun::star::test::TestEvent evt );

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
