/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
module ooo { module vba { module access {
    constants AcSearchDirection {
        const long acDown = 1;
        const long acSearchAll = 2;
        const long acUp = 0;
    };
}; }; };

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
