/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XMLExportFilter.idl,v $
 *
 *  $Revision: 1.6 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 09:36:43 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/

#ifndef __com_sun_star_xml_XMLExportFilter_idl__
#define __com_sun_star_xml_XMLExportFilter_idl__


#ifndef __com_sun_star_document_ExportFilter_idl__
#include <com/sun/star/document/ExportFilter.idl>
#endif

//=============================================================================

module com { module sun { module star { module xml {

//=============================================================================
/** describes an export filter for XML-based file formats.

    <p>It is an extension of <type scope="com::sun::star::document">ExportFilter</type>
    and differs from it only in that an
    <type scope="com::sun::star::xml::sax">XDocumentHandler</type> needs to
    be passed through the XInitialization interface. This
    XDocumentHandler will then be used to export the XML data stream.  */
published service XMLExportFilter
{
    /** An com.sun.star.xml.sax.XDocumentHandler needs to be passed to
       the <method scope="com::sun::star::lang">XInitialization::initialize</method> call.
    */
    service com::sun::star::document::ExportFilter;
};

//=============================================================================

}; }; }; };

#endif
