/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_sdb_application_CopyTableRowEvent_idl__
#define __com_sun_star_sdb_application_CopyTableRowEvent_idl__

#include <com/sun/star/lang/EventObject.idl>
#include <com/sun/star/sdbc/XResultSet.idl>


module com { module sun { module star { module sdb { module application {


/** specifies an event happening while copying table data between databases.

    <p>Whenever this event is fired to an XCopyTableListener,
    com::sun::star::lang::EventObject::Source contains the
    wizard instance which actually does the copying.</p>

    @see CopyTableWizard
 */
struct CopyTableRowEvent : ::com::sun::star::lang::EventObject
{
    /** contains the result set which is being copied by the wizard currently.
    */
    ::com::sun::star::sdbc::XResultSet  SourceData;

    /** denotes the error which happened while copying the data.

        <p>Usually, this contains an instance of com::sun::star::sdbc::SQLException.</p>
    */
    any Error;
};


}; }; }; }; };


#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
