/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XAdapter.idl,v $
 *
 *  $Revision: 1.12 $
 *
 *  last change: $Author: rt $ $Date: 2005-12-14 11:32:56 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_uno_XAdapter_idl__
#define __com_sun_star_uno_XAdapter_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __com_sun_star_uno_XReference_idl__
#include <com/sun/star/uno/XReference.idl>
#endif


//=============================================================================

 module com {  module sun {  module star {  module uno {

//=============================================================================

/** This is the server-side interface to a weak adapter.

    <p>The implementation of <type>XAdapter</type> must know
    but not hold the adapted object, because it must not
    affect the lifetime of the adapted object.

    </p>@see XWeak
        for description of concepts.
 */
published interface XAdapter: com::sun::star::uno::XInterface
{
    //-------------------------------------------------------------------------

    // DocMerge from xml: method com::sun::star::uno::XAdapter::queryAdapted
    /** queries the adapted object if it is alive.
     */
    com::sun::star::uno::XInterface queryAdapted();

    //-------------------------------------------------------------------------

    // DocMerge from xml: method com::sun::star::uno::XAdapter::addReference
    /** adds a reference to the adapter.



        <p>All added references are called when the adapted object dies.

        </p>
     */
    void addReference( [in] com::sun::star::uno::XReference xRef );

    //-------------------------------------------------------------------------

    // DocMerge from xml: method com::sun::star::uno::XAdapter::removeReference
    /** removes a reference from the adapter.
     */
    void removeReference( [in] com::sun::star::uno::XReference xRef );

};

//=============================================================================

}; }; }; };

/*=============================================================================

=============================================================================*/
#endif
