/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 */

#ifndef com_sun_star_graphic_XTextLayouter_idl
#define com_sun_star_graphic_XTextLayouter_idl

#include <com/sun/star/uno/XInterface.idl>

module com { module sun { module star { module graphic
{

/** Text layouter interface
*/

interface XTextLayouter : ::com::sun::star::uno::XInterface
{
};

}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
