/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_configuration_GroupUpdate_idl__
#define __com_sun_star_configuration_GroupUpdate_idl__

#ifndef __com_sun_star_configuration_GroupAccess_idl__
#include <com/sun/star/configuration/GroupAccess.idl>
#endif

#ifndef __com_sun_star_container_XNameReplace_idl__
#include <com/sun/star/container/XNameReplace.idl>
#endif

//=============================================================================

module com { module sun { module star { module configuration {

//=============================================================================
/** provides write access to a predefined heterogeneous group of values
 and nested trees as part of a hierarchy.

 <p>This service extends <type>GroupAccess</type> to support
 modifying values.
 </p>
*/
published service GroupUpdate
{
/** is the basic service providing read access to a group element of the
 hierarchy.

 <p>Any child and descendant objects support modifying access as well,
 unless they represent a read-only tree element as indicated by
 <const scope="com::sun::star::beans">PropertyAttribute::READONLY</const>.
 </p>
*/
    service GroupAccess;

/** allows replacing values.

 <p>This service extends the interface
 <type scope="com::sun::star::container">XNameAccess</type> supported
 by service <type>GroupAccess</type> to allow changing values.
 This strongly overlaps with functionality available through
 <type>PropertyHierarchy</type> (from <type>GroupAccess</type>), so that
 <code>xGroup.setPropertyValue( aName, aValue )</code> is equivalent to
 <code>xGroup.replaceByName( aName, aValue )</code>.
 </p>

 <p>Changes can be observed by registering a listener with interface
 <type scope="com::sun::star::beans">XPropertySet</type> or
 <type scope="com::sun::star::beans">XMultiPropertySet</type>.
 </p>

 <p>Elements of this group may be replaced only if they are of simple type.
 The type returned by
 <member scope="com::sun::star::container">XElementAccess::getElementType()</member>
 must not be an interface type. Replacing whole subtrees is not supported.
 </p>
*/
    interface com::sun::star::container::XNameReplace;

};

//=============================================================================

}; }; }; };

#endif

