/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_report_Calculation_idl__
#define __com_sun_star_report_Calculation_idl__



 module com {  module sun {  module star {  module report {


/** Specifies how to calculate a value.
    @see XFormattedField
 */
constants Calculation
{

    /** returns the average of a field.
     */
    const short NONE = 0;

    /** returns the average of a field.
     */
    const short AVERAGE = 1;

    /** returns the correlation of two fields.
     */
    const short CORRELATION = 2;

    /** counts the number of values, from the field.
    */
    const short COUNT = 3;

    /** returns the measure of the linear relation between paired variables.
    */
    const short COVARIANCE = 4;

    /** returns the number of none repeating values, from the field.
    */
    const short DISTINCTCOUNT = 5;

    /** returns the largest value from the field.
    */
    const short MAXIMUM = 6;

    /** returns the middle value in a sequence of numeric values.
    */
    const short MEDIAN = 7;

    /** returns the smallest value from the field.
    */
    const short MINIMUM = 8;

    /** returns the most frequently returning value from the field.
    */
    const short MODE = 9;

    /** returns the Nth largest value from the field.
    */
    const short NTHLARGEST = 10;

    /** returns the Nth most commonly occurring value from the field.
    */
    const short NTHMOSTFREQUENT = 11;

    /** returns the Nth smallest value from the field.
    */
    const short NTHSMALLEST = 12;

    /** returns as a percentage of the grand total summary.
    */
    const short PERCENTAGE = 13;

    /** returns the value for a specified percentile in a Number or Currency field.
    */
    const short PERCENTILE = 14;

    /** returns how much each value in the field deviate from the mean or average value for that field.
    */
    const short POPSTANDARDDEVIATION = 15;

    /** returns the square of the standard deviation.
    */
    const short POPVARIANCE = 16;

    /** returns the sample standard deviation for the field.
    */
    const short SAMPLESTANDARDDEVIATION = 17;

    /** returns the sample variance for the field.
    */
    const short SAMPLEVARIANCE = 18;

    /** returns the total of all the values for the field.
    */
    const short SUM = 19;

    /** returns the weighted average for the field.
    */
    const short WEIGHTEDAVG = 20;
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
