/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_report_GroupOn_idl__
#define __com_sun_star_report_GroupOn_idl__



 module com {  module sun {  module star {  module report {


/** Specifies how to group data.
    @see XGroup
 */
constants GroupOn
{

    /** The same value in the column value or expression.
     */
    const short DEFAULT = 0;

    /** The same first nth of characters in the column value or expression.
     */
    const short PREFIX_CHARACTERS = 1;

    /** Dates in the same calendar year.
    */
    const short YEAR= 2;

    /** Dates in the same calendar quarter.
    */
    const short QUARTAL = 3;

    /** Dates in the same month.
    */
    const short MONTH = 4;

    /** Dates in the same week.
    */
    const short WEEK = 5;

    /** Dates on the same date.
    */
    const short DAY = 6;

    /** Times in the same hour.
    */
    const short HOUR = 7;

    /** Times in the same minute.
    */
    const short MINUTE = 8;

    /** Values within an interval you specify.
    */
    const short INTERVAL = 9;
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
