module ooo { module vba { module office {
    constants MsoAnimationType {
        const long msoAnimationAppear = 32;
        const long msoAnimationBeginSpeaking = 4;
        const long msoAnimationCharacterSuccessMajor = 6;
        const long msoAnimationCheckingSomething = 103;
        const long msoAnimationDisappear = 31;
        const long msoAnimationEmptyTrash = 116;
        const long msoAnimationGestureDown = 113;
        const long msoAnimationGestureLeft = 114;
        const long msoAnimationGestureRight = 19;
        const long msoAnimationGestureUp = 115;
        const long msoAnimationGetArtsy = 100;
        const long msoAnimationGetAttentionMajor = 11;
        const long msoAnimationGetAttentionMinor = 12;
        const long msoAnimationGetTechy = 101;
        const long msoAnimationGetWizardy = 102;
        const long msoAnimationGoodbye = 3;
        const long msoAnimationGreeting = 2;
        const long msoAnimationIdle = 1;
        const long msoAnimationListensToComputer = 26;
        const long msoAnimationLookDown = 104;
        const long msoAnimationLookDownLeft = 105;
        const long msoAnimationLookDownRight = 106;
        const long msoAnimationLookLeft = 107;
        const long msoAnimationLookRight = 108;
        const long msoAnimationLookUp = 109;
        const long msoAnimationLookUpLeft = 110;
        const long msoAnimationLookUpRight = 111;
        const long msoAnimationPrinting = 18;
        const long msoAnimationRestPose = 5;
        const long msoAnimationSaving = 112;
        const long msoAnimationSearching = 13;
        const long msoAnimationSendingMail = 25;
        const long msoAnimationThinking = 24;
        const long msoAnimationWorkingAtSomething = 23;
        const long msoAnimationWritingNotingSomething = 22;
    };
}; }; };
