/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: ListSourceType.idl,v $
 *
 *  $Revision: 1.7 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 00:21:18 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_form_ListSourceType_idl__
#define __com_sun_star_form_ListSourceType_idl__


//=============================================================================

 module com {  module sun {  module star {  module form {

//=============================================================================

/** describes the kind of data source used to fill the list data of a listbox or a combobox control.
    @see com::sun::star::form::component::ListBox
    @see com::sun::star::form::component::ComboBox
 */
published enum ListSourceType
{
    //-------------------------------------------------------------------------

    /** The control should be filled with a list of string values.
     */
    VALUELIST,

    //-------------------------------------------------------------------------

    /** The control should be filled with the data of a table.
     */
    TABLE,

    //-------------------------------------------------------------------------

    /** The control should be filled with the results of a database query.
     */
    QUERY,

    //-------------------------------------------------------------------------

    /** The control should be filled with the results of a database statement.
     */
    SQL,

    //-------------------------------------------------------------------------

    /** The control should be filled with the results of a database statement,
        which is not evaluated by the database engine.
     */
    SQLPASSTHROUGH,

    //-------------------------------------------------------------------------

    /** The control should be filled with the field names of a database table.
     */
    TABLEFIELDS

};

//=============================================================================

}; }; }; };

/*=============================================================================

=============================================================================*/
#endif
