/*************************************************************************
 *
 *  $RCSfile: CellProperties.idl,v $
 *
 *  $Revision: 1.11 $
 *
 *  last change: $Author: hr $ $Date: 2004-08-02 17:55:19 $
 *
 *  The Contents of this file are made available subject to the terms of
 *  either of the following licenses
 *
 *         - GNU Lesser General Public License Version 2.1
 *         - Sun Industry Standards Source License Version 1.1
 *
 *  Sun Microsystems Inc., October, 2000
 *
 *  GNU Lesser General Public License Version 2.1
 *  =============================================
 *  Copyright 2000 by Sun Microsystems, Inc.
 *  901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License version 2.1, as published by the Free Software Foundation.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *  MA  02111-1307  USA
 *
 *
 *  Sun Industry Standards Source License Version 1.1
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.1 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://www.openoffice.org/license.html.
 *
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 *
 *  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 *
 *  Copyright: 2000 by Sun Microsystems, Inc.
 *
 *  All Rights Reserved.
 *
 *  Contributor(s): _______________________________________
 *
 *
 ************************************************************************/

#ifndef __com_sun_star_table_CellProperties_idl__
#define __com_sun_star_table_CellProperties_idl__

#ifndef __com_sun_star_util_Color_idl__
#include <com/sun/star/util/Color.idl>
#endif

#ifndef __com_sun_star_beans_XPropertySet_idl__
#include <com/sun/star/beans/XPropertySet.idl>
#endif

#ifndef __com_sun_star_table_ShadowFormat_idl__
#include <com/sun/star/table/ShadowFormat.idl>
#endif

#ifndef __com_sun_star_table_CellHoriJustify_idl__
#include <com/sun/star/table/CellHoriJustify.idl>
#endif

#ifndef __com_sun_star_table_CellVertJustify_idl__
#include <com/sun/star/table/CellVertJustify.idl>
#endif

#ifndef __com_sun_star_table_CellOrientation_idl__
#include <com/sun/star/table/CellOrientation.idl>
#endif

#ifndef __com_sun_star_util_CellProtection_idl__
#include <com/sun/star/util/CellProtection.idl>
#endif

#ifndef __com_sun_star_table_TableBorder_idl__
#include <com/sun/star/table/TableBorder.idl>
#endif

#ifndef __com_sun_star_table_BorderLine_idl__
#include <com/sun/star/table/BorderLine.idl>
#endif

#ifndef __com_sun_star_container_XNameContainer_idl__
#include <com/sun/star/container/XNameContainer.idl>
#endif

//=============================================================================

module com {  module sun {  module star {  module table {

//=============================================================================

/** contains the properties of a table cell.

    @see com::sun::star::table::Cell
    @see com::sun::star::table::CellRange
 */
published service CellProperties
{
    //-------------------------------------------------------------------------

//!published service PropertySet
    /** provides access to the properties.
     */
    interface com::sun::star::beans::XPropertySet;

    //=========================================================================

    /** contains the name of the style of the cell.
     */
    [optional, property] string CellStyle;

    //-------------------------------------------------------------------------

    /** contains the cell background color.
     */
    [property] com::sun::star::util::Color CellBackColor;

    //-------------------------------------------------------------------------

    /** is <TRUE/>, if the cell background is transparent.

        <p>In this case the <member>CellProperties::CellBackColor</member>
        value is not used.</p>
     */
    [property] boolean IsCellBackgroundTransparent;

    //-------------------------------------------------------------------------

    /** contains the horizontal alignment of the cell contents.
     */
    [property] com::sun::star::table::CellHoriJustify HoriJustify;

    //-------------------------------------------------------------------------

    /** contains the vertical alignment of the cell contents.
     */
    [property] com::sun::star::table::CellVertJustify VertJustify;

    //-------------------------------------------------------------------------

    /** is <TRUE/>, if text in the cells will be wrapped automatically
        at the right border.
     */
    [property] boolean IsTextWrapped;

    //-------------------------------------------------------------------------

    /** defines the indentation of the cell contents (in 1/100 mm).
     */
    [property] short ParaIndent;

    //-------------------------------------------------------------------------

    /** contains the orientation of the cell contents.

        <p>If the <member>CellProperties::RotateAngle</member> property
        is non-zero, this value is not used.</p>
     */
    [property] com::sun::star::table::CellOrientation Orientation;

    //-------------------------------------------------------------------------

    /** defines how much the content of cells is rotated (in 1/100 degrees).
     */
    [property] long RotateAngle;

    //-------------------------------------------------------------------------

    /** defines at which edge rotated cells are aligned.
     */
    [property] com::sun::star::table::CellVertJustify RotateReference;

    //-------------------------------------------------------------------------

    /** selects Asian character orientation in vertical orientation.

        <p>If the <member>CellProperties::Orientation</member> property is
        <const>CellOrientation::STACKED</const>, in Asian mode only Asian
        characters are printed in horizontal orientation instead of all
        characters.
        For other values of <member>CellProperties::Orientation</member>,
        this value is not used.</p>
     */
    [optional, property] boolean AsianVerticalMode;

    //-------------------------------------------------------------------------

    /** contains a description of the cell or cell range border.

        <p>If used with a cell range, the top, left, right, and bottom
        lines are at the edges of the entire range, not at the edges of
        the individual cell.</p>
     */
    [property] com::sun::star::table::TableBorder TableBorder;

    //-------------------------------------------------------------------------

    /** contains a description of the top border line of each cell.
     */
    [property] com::sun::star::table::BorderLine TopBorder;

    //-------------------------------------------------------------------------

    /** contains a description of the bottom border line of each cell.
    */
    [property] com::sun::star::table::BorderLine BottomBorder;

    //-------------------------------------------------------------------------

    /** contains a description of the left border line of each cell.
     */
    [property] com::sun::star::table::BorderLine LeftBorder;

    //-------------------------------------------------------------------------

    /** contains a description of the right border line of each cell.
     */
    [property] com::sun::star::table::BorderLine RightBorder;

    //-------------------------------------------------------------------------

    /** contains the index of the number format that is used in the cells.

        <p>The proper value can be determined by using the
        <type scope="com::sun::star::util">NumberFormatter</type>
        interface of the document.</p>
     */
    [property] long NumberFormat;

    //-------------------------------------------------------------------------

    /** contains a description of the shadow.
     */
    [property] com::sun::star::table::ShadowFormat ShadowFormat;

    //-------------------------------------------------------------------------

    /** contains a description of the cell protection.

        <p>Cell protection is active only if the sheet is protected.</p>
     */
    [property] com::sun::star::util::CellProtection CellProtection;

    //-------------------------------------------------------------------------

    /** stores additional attributes.

        <p>This property is used i.e. by the XML filters to load and
        restore unknown attributes.</p>
        */
    [optional, property] com::sun::star::container::XNameContainer
        UserDefinedAttributes;

    //-------------------------------------------------------------------------

    /** contains a description of the top left to bottom right diagonal line of each cell.
     */
    [optional, property] com::sun::star::table::BorderLine DiagonalTLBR;

    //-------------------------------------------------------------------------

    /** contains a description of the bottom left to top right diagonal line of each cell.
     */
    [optional, property] com::sun::star::table::BorderLine DiagonalBLTR;

    //-------------------------------------------------------------------------

    /** is <TRUE/>, if the cell content will be shrinked to fit in the cell.
     */
    [optional, property] boolean ShrinkToFit;

    //-------------------------------------------------------------------------
};

//=============================================================================

}; }; }; };

#endif

