/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_table_TableSortField_idl__
#define __com_sun_star_table_TableSortField_idl__

#include <com/sun/star/lang/Locale.idl>
#include <com/sun/star/table/TableSortFieldType.idl>



module com {  module sun {  module star {  module table {

/** describes how to sort a single field (row/column) in a tables
    sort descriptor.

    @see com::sun::star::table::TableSortDescriptor2

    @since OOo 1.1.2
 */
published struct TableSortField
{
    /** index of the row or column in the table to be sorted; 0-based.
     */
    long Field;

    /** `TRUE` if data are sorted in ascending order,
        `FALSE` if in descending order.
     */
    boolean IsAscending;

    /** specifies if the case of letters is important when comparing entries.
     */
    boolean IsCaseSensitive;

    /** type of contents in the field.

        <p>If the value is
        com::sun::star::table::TableSortFieldType::AUTOMATIC
        the algorithm used for sorting is application specific.
        Especially it may or may not use the values given by
        "CollatorLocale" and "CollatorAlgorithm".</p>
     */
    com::sun::star::table::TableSortFieldType FieldType;

    /** the locale used by the collator when comparing/sorting text.

        <p>This property will not be used when the "FieldType" is
        com::sun::star::table::TableSortFieldType::NUMERIC
        </p>

        @see   com::sun::star::i18n::XCollator
     */
    com::sun::star::lang::Locale CollatorLocale;

    /** the algorithm used by the collator when comparing/sorting text.

        <p>This property will not be used when the "FieldType" is
        com::sun::star::table::TableSortFieldType::NUMERIC
        </p>

        @see   com::sun::star::i18n::XCollator
     */
    string CollatorAlgorithm;

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
