/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

module com {  module sun {  module star {  module table {

/** provides access to the settings of a pivot chart object in a
    table or spreadsheet.

    @since LibreOffice 5.4
 */
interface XTablePivotChart: com::sun::star::uno::XInterface
{
    /** returns the pivot table name of the associated pivot table
     */
    string getPivotTableName();
};

}; }; }; };

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
