/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XTableColumns.idl,v $
 *
 *  $Revision: 1.9 $
 *
 *  last change: $Author: rt $ $Date: 2005-11-11 13:24:12 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/

#ifndef __com_sun_star_table_XTableColumns_idl__
#define __com_sun_star_table_XTableColumns_idl__

#ifndef __com_sun_star_container_XIndexAccess_idl__
#include <com/sun/star/container/XIndexAccess.idl>
#endif

//=============================================================================

module com {  module sun {  module star {  module table {

//=============================================================================

/** provides methods to access columns via index and to insert and remove
    columns.

    @see com::sun::star::table::TableColumns
 */
published interface XTableColumns: com::sun::star::container::XIndexAccess
{
    //-------------------------------------------------------------------------

    /** inserts new columns.

        <p>When the index or combination of index and count is out
        of bounds an exception will be thrown.</p>

        @param nIndex
            is the index the first inserted column will have.

        @param nCount
            is the number of columns to insert.
     */
    void insertByIndex( [in] long nIndex, [in] long nCount );

    //-------------------------------------------------------------------------

    /** deletes columns.

        <p>When the index or combination of index and count is out
        of bounds an exception will be thrown.</p>

        @param nIndex
            is the index of the first column to delete.

        @param nCount
            is the number of columns to delete.
     */
    void removeByIndex( [in] long nIndex, [in] long nCount );

};

//=============================================================================

}; }; }; };

#endif

