/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Copyright 2000, 2010 Oracle and/or its affiliates.
 *
 * OpenOffice.org - a multi-platform office productivity suite
 *
 * This file is part of OpenOffice.org.
 *
 * OpenOffice.org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License version 3
 * only, as published by the Free Software Foundation.
 *
 * OpenOffice.org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License version 3 for more details
 * (a copy is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3 along with OpenOffice.org.  If not, see
 * <http://www.openoffice.org/license.html>
 * for a copy of the LGPLv3 License.
 *
 ************************************************************************/
#ifndef __com_sun_star_sdbc_ConnectionProperties_idl__
#define __com_sun_star_sdbc_ConnectionProperties_idl__

 module com {  module sun {  module star {  module sdbc {



/** represents the properties for a connection (session) with a specific
    database. These properties can be used when calling the method
    <member scope="com::sun::star::sdbc">XDriver::connect()</member> or
    <member scope="com::sun::star::sdbc">XDriverManager::getConnectionWithInfo()</member>.

    <p>
    The properties for a connection contain additional information about how to connect to a database and
    how to control the behavior of the resulting connection should be.

    </p>
    @see com::sun::star::sdbc::XDriver
    @see com::sun::star::sdbc::XDriverManager
    @see com::sun::star::sdbc::JDBCConnectionProperties
    @see com::sun::star::sdbc::ODBCConnectionProperties
    @see com::sun::star::sdbc::FILEConnectionProperties
    @see com::sun::star::sdbc::DBASEConnectionProperties
    @see com::sun::star::sdbc::FLATConnectionProperties

 */
published service ConnectionProperties
{
    /** the username
    */
    [optional, property] string user;

    /** the password
    */
    [optional, property] string password;
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
