/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_sdbc_FILEConnectionProperties_idl__
#define __com_sun_star_sdbc_FILEConnectionProperties_idl__

#include <com/sun/star/sdbc/ConnectionProperties.idl>

module com {  module sun {  module star {  module sdbc {

/** represents the properties for a FILE connection (session) with a specific
    database. These properties can be used when calling the method
    com::sun::star::sdbc::XDriver::connect() or
    com::sun::star::sdbc::XDriverManager::getConnectionWithInfo().

    <p>
    The properties for a connection contain additional information about how to connect to a database and
    how to control the behavior of the resulting connection should be.

    </p>
    @see com::sun::star::sdbc::XDriver
    @see com::sun::star::sdbc::XDriverManager
    @see com::sun::star::sdbc::ConnectionProperties
 */
service FILEConnectionProperties
{
    service com::sun::star::sdbc::ConnectionProperties;

    /** specifies the encoding to use to translate the backend data

        <p>See the <a href="http://www.iana.org/assignments/character-sets">IANA character set list</a>
        for a list of valid values.</p>

        <p>For internal purposes (e.g., when using an encoding for which no IANA character set name
        exists), this may also be an UNSIGNED SHORT value representing one of the rtl_TextEncoding
        values in rtl/textenc.h.</p>
    */
    [optional, property] string CharSet;
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
