/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_sdbc_XResultSetMetaDataSupplier_idl__
#define __com_sun_star_sdbc_XResultSetMetaDataSupplier_idl__

#include <com/sun/star/uno/XInterface.idl>

#include <com/sun/star/sdbc/SQLException.idl>

 module com {  module sun {  module star {  module sdbc {

 published interface XResultSetMetaData;


/** provides access to the meta data of a result set.


    <p>
    The number, types, and properties of a ResultSet's columns are
    provided by the
    <type scope="com::sun::star::sdbc">XResultSetMetaData</type>
    interface returned by the
    <member scope="com::sun::star::sdbc">XResultSetMetaDataSupplier::getMetaData()</member>
    method.
    </p>
 */
published interface XResultSetMetaDataSupplier: com::sun::star::uno::XInterface
{

    /** retrieves the number, types, and properties of a ResultSet's columns.
        @returns
            the meta data of the ResultSet.
        @throws SQLException
            if a database access error occurs.
     */
    XResultSetMetaData getMetaData() raises (SQLException);
};


}; }; }; };

/*===========================================================================
===========================================================================*/
#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
