// buildhost settings - paths and the like
apply from: 'variables.gradle'

layout.buildDirectory.set(file("${absTopBuilddir}/android/build"))

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.3.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.register('clean', Delete) {
    delete layout.buildDirectory
}

afterEvaluate {
    clean.dependsOn(':lib:clean')
}
