/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_sdb_tools_XIndexAlteration_idl__
#define __com_sun_star_sdb_tools_XIndexAlteration_idl__

#include <com/sun/star/sdbc/SQLException.idl>
#include <com/sun/star/sdb/tools/XConnectionSupplier.idl>
#include <com/sun/star/lang/XInitialization.idl>
#include <com/sun/star/beans/XPropertySet.idl>

module com {  module sun {  module star {  module sdb { module tools {

/** allows to alter the indexes of a table.

    @see com::sun::star::sdb::DataSource::Settings
    @see com::sun::star::sdbcx::XAppend
    @see com::sun::star::sdbcx::XDrop

    @since OOo 3.3
*/
interface XIndexAlteration
{
    interface XConnectionSupplier;

    /** drops an object of the related container identified by its name.
        @param table
            the table to be altered
        @param index
            the name of the column to be dropped
        @throws com::sun::star::sdbc::SQLException
            if a database access error occurs.
     */
    void dropIndex([in] com::sun::star::beans::XPropertySet table,[in] string index)
        raises ( com::sun::star::sdbc::SQLException);

    /** creates a new object using the given descriptor and appends it
        to the related container.
        <b>
        Note:
        </b>
        The descriptor will not be changed and can be used again to append another object.
        @param table
            the table to be altered
        @param descriptor
            the descriptor which should be serve to append a new object
        @throws com::sun::star::sdbc::SQLException
            if a database access error occurs.
     */
    void addIndex([in] com::sun::star::beans::XPropertySet table,[in]com::sun::star::beans::XPropertySet descriptor)
        raises (com::sun::star::sdbc::SQLException);


};
}; }; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
