# Config for Collabora Office app for Windows

# This is obviously COKit-only
--enable-kit-always-active

# Build environment
--enable-python=fully-internal
--disable-ccache
--disable-pch
--enable-mergelibs
--enable-symbols
--with-visual-studio=2026
--with-buildconfig-recorded
--without-lxml

# Branding
--with-branding=icon-themes/galaxy/brand_cp
--with-vendor=Collabora Productivity Limited

# MPLv2 subset
--disable-gpgmepp
--disable-mariadb-sdbc
--with-theme=colibre colibre_svg

# No Java
--without-java
--without-junit

# COKit – tiled rendering
--disable-skia
--enable-cairo-rgba
--enable-headless

# Misc features
--disable-cli
--disable-database-connectivity
--disable-librelogo
--disable-opencl
--disable-sal-log
--disable-sdremote
--disable-sdremote-bluetooth
INCLUDE:Langs
--with-myspell-dicts
--without-galleries
--without-help
--without-templates

# Sensible font bundling settings for desktop
--with-fonts
--with-docrepair-fonts
--disable-noto-font
