--build=x86_64-unknown-linux-gnu
--enable-android-kit
--with-android-api-level=21
--with-android-package-name=com.collabora.libreoffice
--with-vendor=Collabora Productivity Limited
--without-export-validation
--without-helppack-integration
--without-junit
--disable-largefile
--with-theme=colibre
--disable-poppler
--disable-scripting-beanshell
--disable-scripting-javascript
--with-myspell-dicts
--with-docrepair-fonts
--enable-pdfimport
--enable-release-build
--disable-librelogo
INCLUDE:Langs
