# Shared linux config, included via INCLUDE:CPLinuxCommon from
# CPLinuxQtFlatpak, CPLinux-LOKit, and CPLinux-LOKit-Dev
--disable-dbus
--disable-dconf
--disable-evolution2
--disable-gio
--disable-gtk3
--disable-gui
--disable-librelogo
--disable-randr
--disable-sdremote
--disable-xmlhelp

--enable-cairo-rgba
--enable-hardening-flags
--enable-ld
--enable-mergelibs
--enable-quickjs
--enable-symbols

--with-branding=icon-themes/galaxy/brand_cp
--with-buildconfig-recorded
--with-docrepair-fonts
--with-fonts
--with-galleries=no
--with-linker-hash-style=both
--with-theme=colibre colibre_svg
--with-vendor=Collabora Productivity Limited
--without-help
--without-junit
--with-system-dicts
--with-system-zlib
--without-system-cairo
--without-system-jpeg
--without-templates
