# Config for Collabora Office app for macOS

# Build environment
--enable-hardening-flags
--disable-python
--enable-macosx-sandbox
--enable-mergelibs
--with-buildconfig-recorded
--without-lxml

# Branding
--with-branding=icon-themes/galaxy/brand_cp
--with-vendor=Collabora Productivity Limited

# MPLv2 subset
--disable-gpgmepp
--with-theme=colibre colibre_svg

# No Java
--without-junit

# COKit – tiled rendering
--disable-avmedia
--disable-skia
--enable-cairo-rgba
--enable-headless
--without-system-fontconfig
--without-system-freetype

# Misc features
--disable-cli
--disable-librelogo
--disable-openssl
--disable-sal-log
--disable-sdremote
--disable-sdremote-bluetooth
INCLUDE:Langs
--with-myspell-dicts
--without-galleries
--without-help
--without-templates

# Sensible font bundling settings for desktop
--with-fonts
--with-docrepair-fonts
--disable-noto-font
