--host=wasm32-local-emscripten
--enable-mpl-subset
--with-vendor=Collabora Productivity Limited
--enable-cairo-rgba
--without-junit
--without-help
--with-galleries=no
--disable-dbus
--disable-kf5
--disable-gtk3
--disable-qt5
--disable-evolution2
--disable-gio
--disable-gui
--disable-scripting
--disable-sdremote
--disable-sdremote-bluetooth
--disable-randr
--disable-dconf
--without-templates
--disable-librelogo
