--enable-fuzzers
--enable-readonly-installset
--disable-dynamic-loading
--disable-runtime-optimizations
--disable-scripting
--disable-cairo-canvas
--disable-coinmp
--disable-cups
--disable-dbus
--disable-dconf
--disable-gen
--disable-gio
--disable-gtk3
--disable-gui
--disable-libcmis
--disable-skia
--disable-zxing
--with-locales=en
--without-fonts
--without-galleries
--without-webdav
