/*************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Copyright 2008 by Sun Microsystems, Inc.
 *
 * OpenOffice.org - a multi-platform office productivity suite
 *
 * $RCSfile: XApplication.idl,v $
 * $Revision: 1.4 $
 *
 * This file is part of OpenOffice.org.
 *
 * OpenOffice.org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License version 3
 * only, as published by the Free Software Foundation.
 *
 * OpenOffice.org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License version 3 for more details
 * (a copy is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3 along with OpenOffice.org.  If not, see
 * <http://www.openoffice.org/license.html>
 * for a copy of the LGPLv3 License.
 *
 ************************************************************************/
#ifndef __org_openoffice_excel_XApplication_idl__
#define __org_openoffice_excel_XApplication_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __org_openoffice_vba_XHelperInterface_idl__
#include <org/openoffice/vba/XHelperInterface.idl>
#endif

module org {  module openoffice {  module excel {

interface XRange;
interface XWorkbook;
interface XWorkbooks;
interface XWorksheets;
interface XWorksheetFunction;
interface XWindow;
interface XWorksheet;

interface XApplication
{

    interface ::org::openoffice::vba::XHelperInterface;

    [attribute, readonly] any Selection;
    [attribute, readonly] XWorkbook ActiveWorkbook;
    [attribute, readonly] XRange ActiveCell;
    [attribute, readonly] XWindow ActiveWindow;
    [attribute, readonly] XWorksheet ActiveSheet;
    [attribute] long Calculation;
    //#TODO #FIXME this is more of a placeholder, will return
    // the value of activeworkbook, in xl 'ThisWorkbook' should return the
    // workbook in which the 'calling' macro is running. Should be possible
    // to determine this
    [attribute, readonly] XWorkbook ThisWorkbook;
    [attribute, readonly] string Name;
    [attribute] boolean ScreenUpdating;
    [attribute] boolean DisplayStatusBar;
    [attribute] boolean DisplayAlerts;
    [attribute] boolean DisplayFormulaBar;
    [attribute] any CutCopyMode;
    [attribute] any StatusBar;
    [attribute] long Cursor;
    [attribute, readonly] string Version;

    void setDefaultFilePath([in] string DefaultFilePath) raises(com::sun::star::script::BasicErrorException);

    string getDefaultFilePath() raises(com::sun::star::script::BasicErrorException);

    string LibraryPath() raises(com::sun::star::script::BasicErrorException);
    string TemplatesPath() raises(com::sun::star::script::BasicErrorException);
    string PathSeparator() raises(com::sun::star::script::BasicErrorException);
    any Workbooks( [in] any aIndex );
    any Worksheets( [in] any aIndex );
    any Windows( [in] any aIndex );
    any WorksheetFunction();
    any Evaluate( [in] string Name );
    any Dialogs( [in] any DialogIndex );
    any Range( [in] any Cell1, [in] any Cell2 );
    any Names();
    void GoTo( [in] any Reference, [in] any Scroll );
    // #FIXME #TODO up to 30 args needed
    double CountA( [in] any arg1 );
    void wait( [in] double time );
    void Calculate() raises(com::sun::star::script::BasicErrorException);
    XRange Intersect([in] XRange Arg1, [in] XRange Arg2, [in] /*Optional*/ any Arg3, [in] /*Optional*/ any Arg4, [in] /*Optional*/ any Arg5, [in] /*Optional*/ any Arg6, [in] /*Optional*/ any Arg7, [in] /*Optional*/ any Arg8, [in] /*Optional*/ any Arg9, [in] /*Optional*/ any Arg10, [in] /*Optional*/ any Arg11, [in] /*Optional*/ any Arg12, [in] /*Optional*/ any Arg13, [in] /*Optional*/ any Arg14, [in] /*Optional*/ any Arg15, [in] /*Optional*/ any Arg16, [in] /*Optional*/ any Arg17, [in] /*Optional*/ any Arg18, [in] /*Optional*/ any Arg19, [in] /*Optional*/ any Arg20, [in] /*Optional*/ any Arg21, [in] /*Optional*/ any Arg22, [in] /*Optional*/ any Arg23, [in] /*Optional*/ any Arg24, [in] /*Optional*/ any Arg25, [in] /*Optional*/ any Arg26, [in] /*Optional*/ any Arg27, [in] /*Optional*/ any Arg28, [in] /*Optional*/ any Arg29, [in] /*Optional*/ any Arg30)
        raises(com::sun::star::script::BasicErrorException);
    void Volatile([in] any Volatile);
    void DoEvents();
};

}; }; };

#endif


