/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __ooo_vba_excel_Button_idl__
#define __ooo_vba_excel_Button_idl__

#include <ooo/vba/excel/XSheetObject.idl>
#include <ooo/vba/excel/XControlObject.idl>
#include <ooo/vba/excel/XButton.idl>

//=============================================================================

/*  Note: This file collects all compatibility interfaces for drawing objects
    and drawing controls embedded in sheets. All these symbols are deprecated
    in VBA and kept for compatibility with old VBA scripts. */

//=============================================================================

module ooo {  module vba { module excel {

//=============================================================================

//=============================================================================

/** Represents a drawing button control in a spreadsheet. */
service Button
{
    interface XSheetObject;
    interface XControlObject;
    interface XButton;
};

//=============================================================================

}; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
