/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __ooo_vba_excel_XGlobals_idl__
#define __ooo_vba_excel_XGlobals_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/script/BasicErrorException.idl>
#include <ooo/vba/excel/XWorkbook.idl>
#include <ooo/vba/excel/XWorksheet.idl>
#include <ooo/vba/XAssistant.idl>
#include <ooo/vba/excel/XApplication.idl>


module ooo {  module vba {  module excel {
interface XRange;
interface XWindow;
interface XGlobals: com::sun::star::uno::XInterface
{
    [attribute, readonly] ooo::vba::excel::XWorkbook ActiveWorkbook;
    [attribute, readonly] ooo::vba::excel::XWorksheet ActiveSheet;
    [attribute, readonly] ooo::vba::excel::XWindow ActiveWindow;
    [attribute, readonly] ooo::vba::excel::XRange ActiveCell;
    [attribute, readonly] ooo::vba::XAssistant Assistant;
    [attribute, readonly] any Selection;
    [attribute, readonly] XWorkbook ThisWorkbook;
    [attribute, readonly] ooo::vba::excel::XApplication Excel;
    [attribute, readonly] any Debug;


    void Calculate() raises(com::sun::star::script::BasicErrorException);
    XRange Cells([in] any RowIndex, [in] any ColumnIndex);
    XRange Columns([in] any Index);
    any CommandBars( [in] any Index );
    any Evaluate( [in] string Name );
XRange Intersect([in] XRange Arg1, [in] XRange Arg2, [in] /*Optional*/ any Arg3, [in] /*Optional*/ any Arg4, [in] /*Optional*/ any Arg5, [in] /*Optional*/ any Arg6, [in] /*Optional*/ any Arg7, [in] /*Optional*/ any Arg8, [in] /*Optional*/ any Arg9, [in] /*Optional*/ any Arg10, [in] /*Optional*/ any Arg11, [in] /*Optional*/ any Arg12, [in] /*Optional*/ any Arg13, [in] /*Optional*/ any Arg14, [in] /*Optional*/ any Arg15, [in] /*Optional*/ any Arg16, [in] /*Optional*/ any Arg17, [in] /*Optional*/ any Arg18, [in] /*Optional*/ any Arg19, [in] /*Optional*/ any Arg20, [in] /*Optional*/ any Arg21, [in] /*Optional*/ any Arg22, [in] /*Optional*/ any Arg23, [in] /*Optional*/ any Arg24, [in] /*Optional*/ any Arg25, [in] /*Optional*/ any Arg26, [in] /*Optional*/ any Arg27, [in] /*Optional*/ any Arg28, [in] /*Optional*/ any Arg29, [in] /*Optional*/ any Arg30)
        raises(com::sun::star::script::BasicErrorException);
    any WorkSheets( [in] any Index );
    any WorkBooks( [in] any Index );
    any WorksheetFunction();
    any Windows( [in] any Index );
    any Sheets( [in] any Index );
    any Range( [in] any Cell1, [in] any Cell2 );
    XRange Rows([in] any Index);
    any Names( [in] any Index );
    XRange Union([in] XRange Arg1, [in] XRange Arg2, [in] /*Optional*/ any Arg3, [in] /*Optional*/ any Arg4, [in] /*Optional*/ any Arg5, [in] /*Optional*/ any Arg6, [in] /*Optional*/ any Arg7, [in] /*Optional*/ any Arg8, [in] /*Optional*/ any Arg9, [in] /*Optional*/ any Arg10, [in] /*Optional*/ any Arg11, [in] /*Optional*/ any Arg12, [in] /*Optional*/ any Arg13, [in] /*Optional*/ any Arg14, [in] /*Optional*/ any Arg15, [in] /*Optional*/ any Arg16, [in] /*Optional*/ any Arg17, [in] /*Optional*/ any Arg18, [in] /*Optional*/ any Arg19, [in] /*Optional*/ any Arg20, [in] /*Optional*/ any Arg21, [in] /*Optional*/ any Arg22, [in] /*Optional*/ any Arg23, [in] /*Optional*/ any Arg24, [in] /*Optional*/ any Arg25, [in] /*Optional*/ any Arg26, [in] /*Optional*/ any Arg27, [in] /*Optional*/ any Arg28, [in] /*Optional*/ any Arg29, [in] /*Optional*/ any Arg30)
        raises(com::sun::star::script::BasicErrorException);
    any MenuBars( [in] any aIndex );

};

}; }; };

#endif


/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
