/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
module ooo { module vba { module excel {
    constants XlCommandUnderlines {
        const long xlCommandUnderlinesAutomatic = -4105;
        const long xlCommandUnderlinesOff = -4146;
        const long xlCommandUnderlinesOn = 1;
    };
}; }; };

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
