/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

module ooo { module vba { module excel {
    constants XlPaperSize {
        const long xlPaper10x14 = 16;
        const long xlPaper11x17 = 17;
        const long xlPaperA3 = 8;
        const long xlPaperA4 = 9;
        const long xlPaperA4Small = 10;
        const long xlPaperA5 = 11;
        const long xlPaperB4 = 12;
        const long xlPaperB5 = 13;
        const long xlPaperCsheet = 24;
        const long xlPaperDsheet = 25;
        const long xlPaperEnvelope10 = 20;
        const long xlPaperEnvelope11 = 21;
        const long xlPaperEnvelope12 = 22;
        const long xlPaperEnvelope14 = 23;
        const long xlPaperEnvelope9 = 19;
        const long xlPaperEnvelopeB4 = 33;
        const long xlPaperEnvelopeB5 = 34;
        const long xlPaperEnvelopeB6 = 35;
        const long xlPaperEnvelopeC3 = 29;
        const long xlPaperEnvelopeC4 = 30;
        const long xlPaperEnvelopeC5 = 28;
        const long xlPaperEnvelopeC6 = 31;
        const long xlPaperEnvelopeC65 = 32;
        const long xlPaperEnvelopeDL = 27;
        const long xlPaperEnvelopeItaly = 36;
        const long xlPaperEnvelopeMonarch = 37;
        const long xlPaperEnvelopePersonal = 38;
        const long xlPaperEsheet = 26;
        const long xlPaperExecutive = 7;
        const long xlPaperFanfoldLegalGerman = 41;
        const long xlPaperFanfoldStdGerman = 40;
        const long xlPaperFanfoldUS = 39;
        const long xlPaperFolio = 14;
        const long xlPaperLedger = 4;
        const long xlPaperLegal = 5;
        const long xlPaperLetter = 1;
        const long xlPaperLetterSmall = 2;
        const long xlPaperNote = 18;
        const long xlPaperQuarto = 15;
        const long xlPaperStatement = 6;
        const long xlPaperTabloid = 3;
        const long xlPaperUser = 256;
    };
}; }; };

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
