module ooo { module vba { module excel {
    constants XlRangeAutoFormat {
        const long xlRangeAutoFormat3DEffects1 = 13;
        const long xlRangeAutoFormat3DEffects2 = 14;
        const long xlRangeAutoFormatAccounting1 = 4;
        const long xlRangeAutoFormatAccounting2 = 5;
        const long xlRangeAutoFormatAccounting3 = 6;
        const long xlRangeAutoFormatAccounting4 = 17;
        const long xlRangeAutoFormatClassic1 = 1;
        const long xlRangeAutoFormatClassic2 = 2;
        const long xlRangeAutoFormatClassic3 = 3;
        const long xlRangeAutoFormatClassicPivotTable = 31;
        const long xlRangeAutoFormatColor1 = 7;
        const long xlRangeAutoFormatColor2 = 8;
        const long xlRangeAutoFormatColor3 = 9;
        const long xlRangeAutoFormatList1 = 10;
        const long xlRangeAutoFormatList2 = 11;
        const long xlRangeAutoFormatList3 = 12;
        const long xlRangeAutoFormatLocalFormat1 = 15;
        const long xlRangeAutoFormatLocalFormat2 = 16;
        const long xlRangeAutoFormatLocalFormat3 = 19;
        const long xlRangeAutoFormatLocalFormat4 = 20;
        const long xlRangeAutoFormatNone = -4142;
        const long xlRangeAutoFormatPTNone = 42;
        const long xlRangeAutoFormatReport1 = 21;
        const long xlRangeAutoFormatReport10 = 30;
        const long xlRangeAutoFormatReport2 = 22;
        const long xlRangeAutoFormatReport3 = 23;
        const long xlRangeAutoFormatReport4 = 24;
        const long xlRangeAutoFormatReport5 = 25;
        const long xlRangeAutoFormatReport6 = 26;
        const long xlRangeAutoFormatReport7 = 27;
        const long xlRangeAutoFormatReport8 = 28;
        const long xlRangeAutoFormatReport9 = 29;
        const long xlRangeAutoFormatSimple = -4154;
        const long xlRangeAutoFormatTable1 = 32;
        const long xlRangeAutoFormatTable10 = 41;
        const long xlRangeAutoFormatTable2 = 33;
        const long xlRangeAutoFormatTable3 = 34;
        const long xlRangeAutoFormatTable4 = 35;
        const long xlRangeAutoFormatTable5 = 36;
        const long xlRangeAutoFormatTable6 = 37;
        const long xlRangeAutoFormatTable7 = 38;
        const long xlRangeAutoFormatTable8 = 39;
        const long xlRangeAutoFormatTable9 = 40;
    };
}; }; };
