/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_ui_dialogs_TemplateDescription_idl__
#define __com_sun_star_ui_dialogs_TemplateDescription_idl__


module com { module sun { module star { module ui { module dialogs {

/** The implementation of a FilePicker service may support the usage of
    different templates. The following constants define the currently
    specified templates.

    @see com::sun::star::ui::dialogs::FilePicker
 */

published constants TemplateDescription
{
    /** A FileOpen dialog without any additional controls.
    */
    const short FILEOPEN_SIMPLE                                = 0;

    /** A FileSave dialog without any additional controls.
    */
    const short FILESAVE_SIMPLE                                = 1;

    /** A FileSave dialog with additional controls.
        <ul>
            <li>A checkbox "Auto Extension"</li>
            <li>A checkbox "Password"</li>
        </ul>
    */
    const short FILESAVE_AUTOEXTENSION_PASSWORD                = 2;

    /** A FileSave dialog with additional controls.
        <ul>
            <li>A checkbox "Auto Extension"</li>
            <li>A checkbox "Password"</li>
            <li>A checkbox "Filter Options"</li>
        </ul>
    */
    const short FILESAVE_AUTOEXTENSION_PASSWORD_FILTEROPTIONS  = 3;

    /** A FileSave dialog with additional controls.
        <ul>
            <li>A checkbox "Auto Extension"</li>
            <li>A checkbox "Selection"</li>
        </ul>
    */
    const short FILESAVE_AUTOEXTENSION_SELECTION               = 4;

    /** A FileSave dialog with additional controls.
        <ul>
            <li>A checkbox "Auto Extension"</li>
            <li>A listbox "Template" for selecting different templates</li>
        </ul>
    */
    const short FILESAVE_AUTOEXTENSION_TEMPLATE                = 5;

    /** A FileOpen dialog with additional controls.
        <ul>
            <li>A checkbox "Insert as link"
            <li>A checkbox "Show Preview"
            <li>A listbox  "Image Template" for inserting an image with different styles.</li>
            <li>A window for displaying a file preview</li>
        </ul>
    */
    const short FILEOPEN_LINK_PREVIEW_IMAGE_TEMPLATE           = 6;

    /** A FileOpen dialog with additional controls.
        <ul>
            <li>A push button "Play"</li>
        </ul>
    */
    const short FILEOPEN_PLAY                                  = 7;

    /** A FileOpen dialog with additional controls.
        <ul>
            <li>A checkbox "Read only"</li>
            <li>A listbox "Version" for selecting a document version</li>
        </ul>
    */
    const short FILEOPEN_READONLY_VERSION                      = 8;

    /** A FileOpen dialog with additional controls.
        <ul>
            <li>A checkbox "Insert as link"</li>
            <li>A checkbox "Show Preview"</li>
            <li>A window for displaying a file preview</li>
        </ul>
    */
    const short FILEOPEN_LINK_PREVIEW                          = 9;

    /** A FileSave dialog with additional controls.
        <ul>
            <li>A checkbox "Auto Extension"</li>
        </ul>
    */
    const short FILESAVE_AUTOEXTENSION                         = 10;

    /** A FileOpen dialog with additional controls.
        <ul>
            <li>A checkbox "Show Preview"</li>
            <li>A window for displaying a file preview</li>
        </ul>

        @since LibreOffice 5.3
    */
    const short FILEOPEN_PREVIEW                               = 11;

    /** A FileOpen dialog with additional controls.
        <ul>
            <li>A checkbox "Insert as link"</li>
            <li>A push button "Play"</li>
        </ul>

        @since LibreOffice 5.3
    */
    const short FILEOPEN_LINK_PLAY                             = 12;

    /** A FileOpen dialog with additional controls.
        <ul>
            <li>A checkbox "Insert as link"
            <li>A checkbox "Show Preview"
            <li>A listbox  "Image Anchor" for choosing how to anchor the image in Calc.</li>
            <li>A window for displaying a file preview</li>
        </ul>

        @since LibreOffice 6.1
    */
    const short FILEOPEN_LINK_PREVIEW_IMAGE_ANCHOR             = 13;
};


}; }; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
