/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XFilePickerListener.idl,v $
 *
 *  $Revision: 1.4 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 08:39:14 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/

#ifndef __com_sun_star_ui_dialogs_XFilePickerListener_idl__
#define __com_sun_star_ui_dialogs_XFilePickerListener_idl__

#ifndef __com_sun_star_lang_XEventListener_idl__
#include <com/sun/star/lang/XEventListener.idl>
#endif

#ifndef __com_sun_star_ui_dialogs_FilePickerEvent_idl__
#include <com/sun/star/ui/dialogs/FilePickerEvent.idl>
#endif

//=============================================================================

module com { module sun { module star { module ui { module dialogs {

//=============================================================================

//=============================================================================
/** Interface to be implemented by a FilePicker listener.

    <p> The <type>XFilePickerListener</type> interface must be implemented by
    the clients of the FilePicker service which need to be informed about
    events while the FilePicker service is displayed.</p>
*/

published interface XFilePickerListener: com::sun::star::lang::XEventListener
{
    //-------------------------------------------------------------------------
    /** A client receives this event if the file selection within the
        FilePicker service dialog changes.

        @param aEvent
        of type <type>FilePickerEvent</type> that describes the event

        @see com::sun::star::ui::dialogs::FilePickerEvent
    */
    void fileSelectionChanged( [in] FilePickerEvent aEvent );


    //-------------------------------------------------------------------------
    /** A client receives this event if the directory selection within the
        FilePicker dialog changes.

        @param aEvent
        Of type <type>FilePickerEvent</type> that describes the event.

        @see com::sun::star::ui::dialogs::FilePickerEvent
    */
    void directoryChanged( [in] FilePickerEvent aEvent );

    //-------------------------------------------------------------------------
    /** A client receives this event if the F1 key or the help button was
        pressed.

        @param aEvent
        of type <type>FilePickerEvent</type> that describes the event

        @returns
        A help string which the FilePicker dialog should use to display
        a help for a specific control. If the returned string is empty it is
        undefined how the FilePicker implementation will behave.
        It may show a message 'no help available' or may show no
        help at all.

        @see com::sun::star::ui::dialogs::FilePickerEvent
    */
    string helpRequested( [in] FilePickerEvent aEvent );

    //-------------------------------------------------------------------------
    /** A client receives this event if the state of a control within the
        FilePicker service dialog changes.

        @param aEvent
        of type <type>FilePickerEvent</type> that describes the event.

        @see com::sun::star::ui::dialogs::FilePickerEvent
    */
    void controlStateChanged( [in] FilePickerEvent aEvent );

    //-------------------------------------------------------------------------
    /** A client receives this event if the size of the FilePicker dialog
        has changed. If the FilePicker dialog contains a preview the client
        may ask for the new dimension of the preview area.
    */
    void dialogSizeChanged( );
};

//=============================================================================

}; }; }; }; };


#endif
