/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: types.idl,v $
 *
 *  $Revision: 1.4 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-07 22:58:15 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/

#include "com/sun/star/uno/XInterface.idl"

module test { module javauno { module acquire {

interface XBase: com::sun::star::uno::XInterface {};

interface XDerived: XBase {};

interface XTest: com::sun::star::uno::XInterface
{
    void setInterfaceToInterface([in] com::sun::star::uno::XInterface obj);
    void setBaseToInterface([in] XBase obj);
    void setDerivedToInterface([in] XDerived obj);
    com::sun::star::uno::XInterface getInterfaceFromInterface();
    void clearInterface();

    void setBaseToBase([in] XBase obj);
    void setDerivedToBase([in] XDerived obj);
    com::sun::star::uno::XInterface getInterfaceFromBase();
    XBase getBaseFromBase();
    void clearBase();

    void setDerivedToDerived([in] XDerived obj);
    com::sun::star::uno::XInterface getInterfaceFromDerived();
    XBase getBaseFromDerived();
    XDerived getDerivedFromDerived();
    void clearDerived();

    com::sun::star::uno::XInterface roundTripInterfaceToInterface(
        [in] com::sun::star::uno::XInterface obj);
    com::sun::star::uno::XInterface roundTripBaseToInterface([in] XBase obj);
    com::sun::star::uno::XInterface roundTripDerivedToInterface(
        [in] XDerived obj);

    XBase roundTripBaseToBase([in] XBase obj);
    XBase roundTripDerivedToBase([in] XDerived obj);

    XDerived roundTripDerivedToDerived([in] XDerived obj);
};

}; }; };
