/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_geometry_RealRectangle3D_idl__
#define __com_sun_star_geometry_RealRectangle3D_idl__

module com {  module sun {  module star {  module geometry {

/** This structure contains the necessary information for a
    three-dimensional cube.<p>

    @since OOo 2.0
 */
struct RealRectangle3D
{
    /// minimum X coordinate.
    double X1;


    /// minimum Y coordinate.
    double Y1;


    /// minimum Z coordinate.
    double Z1;


    /** maximum X coordinate.<p>

        Must be greater than X1 for non-empty cubes.<p>.
    */
    double X2;


    /** maximum Y coordinate.<p>

        Must be greater than Y1 for non-empty cubes.<p>
     */
    double Y2;


    /** maximum Z coordinate.<p>

        Must be greater than Z1 for non-empty cubes.<p>
     */
    double Z2;
};

}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
