/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_geometry_RealSize2D_idl__
#define __com_sun_star_geometry_RealSize2D_idl__

module com {  module sun {  module star {  module geometry {

/** This structure contains data representing a two-dimensional size.<p>

    The data is stored real-valued.<p>

    @since OpenOffice 2.0
 */
published struct RealSize2D
{
    /// Amount of space occupied in the x direction.
    double Width;

    //-------------------------------------------------------------------------

    /// Amount of space occupied in the y direction.
    double Height;
};

}; }; }; };

#endif
