/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: BibliographyDataType.idl,v $
 *
 *  $Revision: 1.9 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 06:05:40 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_text_BibliographyDataType_idl__
#define __com_sun_star_text_BibliographyDataType_idl__

//=============================================================================

 module com {  module sun {  module star {  module text {
//=============================================================================

// DocMerge from idl: constants com::sun::star::text::BibliographyDataType
/** These values define the type of bibliographic data like book, journal, magazine, etc.
 */
published constants BibliographyDataType
{
    //-------------------------------------------------------------------------

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::ARTICLE
    /** An article from a journal or magazine.
     */
    const short ARTICLE         = 0;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::BOOK
    /** A book with an explicit publisher.
     */
    const short BOOK            = 1;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::BOOKLET
    /** A work that is printed and bound, but without a named publisher or sponsoring institution.
     */
    const short BOOKLET         = 2;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::CONFERENCE
    /** An article in the proceedings of a conference. This entry is identical to the 'inproceedings'
    entry and is included for compatibility with BiBTex.
     */
    const short CONFERENCE      = 3;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::INBOOK
    /** A part of a book, which may be a chapter and/or a range of pages.
     */
    const short INBOOK          = 4;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::INCOLLECTION
    /** A part of a book with its own title.
     */
    const short INCOLLECTION    = 5;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::INPROCEEDINGS
    /** An article in the proceedings of a conference.
     */
    const short INPROCEEDINGS   = 6;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::JOURNAL
    /** A journal or magazine.
     */
    const short JOURNAL         = 7;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::MANUAL
    /** Technical documentation.
     */
    const short MANUAL          = 8;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::MASTERSTHESIS
    /** A Master's thesis.
     */
    const short MASTERSTHESIS   = 9;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::MISC
    /** This type is used when nothing else seems appropriate.
     */
    const short MISC            = 10;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::PHDTHESIS
    /** A PhD thesis.
     */
    const short PHDTHESIS       = 11;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::PROCEEDINGS
    /** The proceedings of a conference.
     */
    const short PROCEEDINGS     = 12;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::TECHREPORT
    /** A report published by a school or other institution, usually numbered within a series.
     */
    const short TECHREPORT      = 13;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::UNPUBLISHED
    /** A document with an author and title, but not formally published.
     */
    const short UNPUBLISHED     = 14;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::EMAIL
    /** An eMail document
     */
    const short EMAIL           = 15;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::WWW
    /** A Web document
     */
    const short WWW             = 16;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::CUSTOM1
    /** A user defined document type
     */
    const short CUSTOM1         = 17;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::CUSTOM2
    /** A user defined document type
     */
    const short CUSTOM2         = 18;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::CUSTOM3
    /** A user defined document type
     */
    const short CUSTOM3         = 19;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::CUSTOM4
    /** A user defined document type
     */
    const short CUSTOM4         = 20;

    // DocMerge from idl: value com::sun::star::text::BibliographyDataType::CUSTOM5
    /** A user defined document type
     */
    const short CUSTOM5         = 21;
};
//=============================================================================

}; }; }; };

#endif
