/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: ChapterNumberingRule.idl,v $
 *
 *  $Revision: 1.9 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 06:07:32 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_text_ChapterNumberingRule_idl__
#define __com_sun_star_text_ChapterNumberingRule_idl__

#ifndef __com_sun_star_style_NumberingRule_idl__
#include <com/sun/star/style/NumberingRule.idl>
#endif


//=============================================================================

 module com {  module sun {  module star {  module text {

//=============================================================================

// DocMerge from xml: service com::sun::star::text::ChapterNumberingRule
/** describes the rules for chapter numbering in a text document.



    <p>Some of the properties that are available in the interface are
    ignored here.

    </p>
    <p>The type of numbering can only be:
    NUM_CHARS_UPPER_LETTER, NUM_CHARS_LOWER_LETTER, NUM_ROMAN_UPPER,
    NUM_ROMAN_LOWER, NUM_ARABIC, or NUM_NUMBER_NONE

    </p>
    <p>In the <type scope="com::sun::star::style">NumberingAlignment</type> only the field
    <member scope="com::sun::star::style">NumberingAlignment::Alignment</member> is applied.

    </p>
    <p>Depending on the numbering types, the parameters for bullets or bit maps
    may be ignored.  The character style name for the numbering symbol is
    also ignored.</p>
 */
published service ChapterNumberingRule
{
    // DocMerge: empty anyway
    service com::sun::star::style::NumberingRule;

    //-------------------------------------------------------------------------

    // DocMerge from xml: property com::sun::star::text::ChapterNumberingRule::HeadingStyleName
    /** contains the name of the paragraph style that marks this heading
        level.



        <p>It is necessary that each style name appears only
        once in the sequence of numbering rules.</p>
     */
    [property] string HeadingStyleName;

};

//=============================================================================

}; }; }; };

#endif
