/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_text_HoriOrientation_idl__
#define __com_sun_star_text_HoriOrientation_idl__



 module com {  module sun {  module star {  module text {

/** These enumeration values specify the horizontal orientation.
 */
published constants HoriOrientation
{
    /** no hard alignment is applied.

                <p>For text tables this means that the tables position is
                defined by the left and right margins.

                <p>For frame objects (text frames, graphics,...) this means
                that the position is defined by a left offset.
     */
    const short NONE = 0;

    /** The object is aligned at the right side.
     */
    const short RIGHT = 1;

    /** The object is aligned at the middle.
     */
    const short CENTER = 2;

    /** The object is aligned at the left side.
     */
    const short LEFT = 3;

    /** TODO
     */
    const short INSIDE = 4;

    /** TODO
     */
    const short OUTSIDE = 5;

    /** The object uses the full space (for text tables only).
     */
    const short FULL = 6;

    /** The left offset and the width of the object are defined.
                <p> For text tables this means that the tables position is
                defined by the left margin and the width.
     */
    const short LEFT_AND_WIDTH = 7;

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
