/*************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Copyright 2008 by Sun Microsystems, Inc.
 *
 * OpenOffice.org - a multi-platform office productivity suite
 *
 * $RCSfile: NotePrintMode.idl,v $
 * $Revision: 1.9 $
 *
 * This file is part of OpenOffice.org.
 *
 * OpenOffice.org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License version 3
 * only, as published by the Free Software Foundation.
 *
 * OpenOffice.org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License version 3 for more details
 * (a copy is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3 along with OpenOffice.org.  If not, see
 * <http://www.openoffice.org/license.html>
 * for a copy of the LGPLv3 License.
 *
 ************************************************************************/
#ifndef __com_sun_star_text_NotePrintMode_idl__
#define __com_sun_star_text_NotePrintMode_idl__


//=============================================================================

 module com {  module sun {  module star {  module text {

//=============================================================================

// DocMerge from xml: enum com::sun::star::text::NotePrintMode
/** enumeration values are used to define the printing of notes in a
    document.
 */
published enum NotePrintMode
{
    //-------------------------------------------------------------------------

    // DocMerge from xml: value com::sun::star::text::NotePrintMode::NOT
    /** Notes are not printed.
     */
    NOT,

    //-------------------------------------------------------------------------

    // DocMerge from xml: value com::sun::star::text::NotePrintMode::ONLY
    /** Only notes are printed.
     */
    ONLY,

    //-------------------------------------------------------------------------

    // DocMerge from xml: value com::sun::star::text::NotePrintMode::DOC_END
    /** Notes are collected at the end of the document.
     */
    DOC_END,

    //-------------------------------------------------------------------------

    // DocMerge from xml: value com::sun::star::text::NotePrintMode::PAGE_END
    /** Notes are collected at the end of a page and printed on an inserted page.
     */
    PAGE_END

};

//=============================================================================

}; }; }; };


#endif
