/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_text_PlaceholderType_idl__
#define __com_sun_star_text_PlaceholderType_idl__



 module com {  module sun {  module star {  module text {


// DocMerge from idl: constants com::sun::star::text::PlaceholderType
/** These constants define how the place-holder text fields act in a document.
 */
published constants PlaceholderType
{

    // DocMerge from idl: value com::sun::star::text::PlaceholderType::TEXT
    /** The field represents a piece of text.
     */
    const short TEXT = 0;


    // DocMerge from idl: value com::sun::star::text::PlaceholderType::TABLE
    /** The field initiates the insertion of a text table.
     */
    const short TABLE = 1;


    // DocMerge from idl: value com::sun::star::text::PlaceholderType::TEXTFRAME
    /** The field initiates the insertion of a text frame.
     */
    const short TEXTFRAME = 2;


    // DocMerge from idl: value com::sun::star::text::PlaceholderType::GRAPHIC
    /** The field initiates the insertion of a graphic object.
     */
    const short GRAPHIC = 3;


    // DocMerge from idl: value com::sun::star::text::PlaceholderType::OBJECT
    /** The field initiates the insertion of an embedded object.
     */
    const short OBJECT = 4;

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
