/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_text_PrintSettings_idl__
#define __com_sun_star_text_PrintSettings_idl__

#include <com/sun/star/text/NotePrintMode.idl>



 module com {  module sun {  module star {  module text {

/** These properties describe the printing of the content of a text document.
 */
published service PrintSettings
{
    /** determines if graphic objects are printed
     */
    [property] boolean PrintGraphics;

    /** determines if text tables are printed.
     */
    [property] boolean PrintTables;

    /** determines if shapes are printed.
     */
    [property] boolean PrintDrawings;

    /** determines if left pages are printed.
     */
    [property] boolean PrintLeftPages;

    /** determines if right pages are printed.
     */
    [property] boolean PrintRightPages;

    /** determines if control shapes are printed.
     */
    [property] boolean PrintControls;

    /** determines if the pages are printed in the reverse order, starting with the last page.
     */
    [property] boolean PrintReversed;

    /** specifies if the printer paper tray selection of the system
        printer is used.



        <p>If com::sun::star::view::PrintSettings::PaperFromSetup is `FALSE`,
        then the paper tray selection of the page styles is used.</p>
     */
    [property] boolean PrintPaperFromSetup;

    /** contains the name of the fax.
     */
    [property] string PrintFaxName;

    /** determines how notes are printed.@see NotePrintMode
     */
    [property] com::sun::star::text::NotePrintMode PrintAnnotationMode;

    /** determines if prospect printing is used.
     */
    [property] boolean PrintProspect;

    /** determines if the background color / background graphic of pages is printed.
     */
    [property] boolean PrintPageBackground;

    /** determines if characters are always printed in black.
     */
    [property] boolean PrintBlackFonts;


        /** determines if automatically inserted empty pages are printed.
         */
        [optional, property] boolean PrintEmptyPages;
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
