/*************************************************************************
 *
 *  $RCSfile: SizeType.idl,v $
 *
 *  $Revision: 1.3 $
 *
 *  last change: $Author: mi $ $Date: 2000-11-08 12:44:27 $
 *
 *  The Contents of this file are made available subject to the terms of
 *  either of the following licenses
 *
 *         - GNU Lesser General Public License Version 2.1
 *         - Sun Industry Standards Source License Version 1.1
 *
 *  Sun Microsystems Inc., October, 2000
 *
 *  GNU Lesser General Public License Version 2.1
 *  =============================================
 *  Copyright 2000 by Sun Microsystems, Inc.
 *  901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License version 2.1, as published by the Free Software Foundation.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *  MA  02111-1307  USA
 *
 *
 *  Sun Industry Standards Source License Version 1.1
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.1 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://www.openoffice.org/license.html.
 *
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 *
 *  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 *
 *  Copyright: 2000 by Sun Microsystems, Inc.
 *
 *  All Rights Reserved.
 *
 *  Contributor(s): _______________________________________
 *
 *
 ************************************************************************/
#ifndef __com_sun_star_text_SizeType_idl__
#define __com_sun_star_text_SizeType_idl__


//=============================================================================

 module com {  module sun {  module star {  module text {

//=============================================================================

// DocMerge from idl: constants com::sun::star::text::SizeType
/** The height value of objects like text frames or table rows may
        be interpreted in different ways.

        <p>The values may specify the absolute height (SIZETYPE_FIX), the
        minimum height (SIZETYPE_MIN), or they are ignored (SIZETYPE_VAR),
        in which case the real height depends on the content. This information
        is contained in a property called "SizeType".
 */
constants SizeType
{
    //-------------------------------------------------------------------------
    // The height of the object is determind by the content only.

    // DocMerge: empty anyway
    const short VARIABLE = 0;

    //-------------------------------------------------------------------------
    // The height property determins the height of the object.

    // DocMerge: empty anyway
    const short FIX = 1;

    //-------------------------------------------------------------------------

    // DocMerge from idl: value com::sun::star::text::SizeType::MIN
    /** The height property determins the minimum height of the object but the
             actual height will be increased if the content demands it.
     */
    const short MIN = 2;

};

//=============================================================================

}; }; }; };

/*=============================================================================

    $Log: not supported by cvs2svn $
    Revision 1.1.1.1  2000/09/18 23:36:03  hjs
    initial import

    Revision 1.5  2000/09/11 11:53:00  mi
    documentation merged from XML

    Revision 1.3  2000/03/31 11:53:56  os
    #74034# Documentation changed

    Revision 1.2  2000/02/07 11:25:01  mi
    zu #70728# missing documentation marked

    Revision 1.1.1.1  1999/11/11 09:48:46  jsc
    new


=============================================================================*/
#endif
