/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: TemplateDisplayFormat.idl,v $
 *
 *  $Revision: 1.9 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 06:25:05 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_text_TemplateDisplayFormat_idl__
#define __com_sun_star_text_TemplateDisplayFormat_idl__


//=============================================================================

 module com {  module sun {  module star {  module text {

//=============================================================================

// DocMerge from idl: constants com::sun::star::text::TemplateDisplayFormat
/** These constants are used to specify which information about a template is
        displayed in a field.
 */
published constants TemplateDisplayFormat
{
    //-------------------------------------------------------------------------
    // The complete path of the file will be displayed.

    // DocMerge: empty anyway
    const short FULL = 0;

    //-------------------------------------------------------------------------
    // Only the path of the template file will be displayed.

    // DocMerge: empty anyway
    const short PATH = 1;

    //-------------------------------------------------------------------------

    // DocMerge from idl: value com::sun::star::text::TemplateDisplayFormat::NAME
    /** Only the file name, without file extension, of the template
                file will be displayed.
     */
    const short NAME = 2;

    //-------------------------------------------------------------------------

    // DocMerge from idl: value com::sun::star::text::TemplateDisplayFormat::NAME_AND_EXT
    /** The file name and the file extension of the template
                file will be displayed.
     */
    const short NAME_AND_EXT = 3;

    //-------------------------------------------------------------------------

    // DocMerge from idl: value com::sun::star::text::TemplateDisplayFormat::AREA
    /** The name of the template area is displayed.
     */
    const short AREA = 4;

    //-------------------------------------------------------------------------

    // DocMerge from idl: value com::sun::star::text::TemplateDisplayFormat::TITLE
    /** The title of the template file is displayed.
     */
    const short TITLE = 5;

};

//=============================================================================

}; }; }; };

#endif
