/*************************************************************************
 *
 *  $RCSfile: TextFrame.idl,v $
 *
 *  $Revision: 1.3 $
 *
 *  last change: $Author: mi $ $Date: 2000-11-08 12:44:27 $
 *
 *  The Contents of this file are made available subject to the terms of
 *  either of the following licenses
 *
 *         - GNU Lesser General Public License Version 2.1
 *         - Sun Industry Standards Source License Version 1.1
 *
 *  Sun Microsystems Inc., October, 2000
 *
 *  GNU Lesser General Public License Version 2.1
 *  =============================================
 *  Copyright 2000 by Sun Microsystems, Inc.
 *  901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License version 2.1, as published by the Free Software Foundation.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *  MA  02111-1307  USA
 *
 *
 *  Sun Industry Standards Source License Version 1.1
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.1 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://www.openoffice.org/license.html.
 *
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 *
 *  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 *
 *  Copyright: 2000 by Sun Microsystems, Inc.
 *
 *  All Rights Reserved.
 *
 *  Contributor(s): _______________________________________
 *
 *
 ************************************************************************/
#ifndef __com_sun_star_text_TextFrame_idl__
#define __com_sun_star_text_TextFrame_idl__

#ifndef __com_sun_star_text_TextContent_idl__
#include <com/sun/star/text/TextContent.idl>
#endif

#ifndef __com_sun_star_text_XTextFrame_idl__
#include <com/sun/star/text/XTextFrame.idl>
#endif

#ifndef __com_sun_star_drawing_XShape_idl__
#include <com/sun/star/drawing/XShape.idl>
#endif

#ifndef __com_sun_star_beans_XPropertySet_idl__
#include <com/sun/star/beans/XPropertySet.idl>
#endif

#ifndef __com_sun_star_container_XNamed_idl__
#include <com/sun/star/container/XNamed.idl>
#endif
#ifndef __com_sun_star_style_GraphicLocation_idl__
#include <com/sun/star/style/GraphicLocation.idl>
#endif

//=============================================================================

 module com {  module sun {  module star {  module text {

//=============================================================================

// DocMerge from xml: service com::sun::star::text::TextFrame
/** specifies a rectangular shape which contains a <type scope="com::sun::star::drawing">Text</type> object
    and is attached to a piece of surrounding <type scope="com::sun::star::drawing">Text</type>.

    @see service Text

    @example StarBasic

    <p>This example shows how to create a <type>TextFrame</type> and insert
    it at the very beginning of <type>Text</text> component. The macro
    is ready to run, if it is a script within a text document. </p>

    <listing>
    Sub Main
    oFrame = ThisComponent.createInstance( "com.sun.star.text.TextFrame" )
    oFrame.Width = 6000
    ThisComponent.Text.insertTextContent( ThisComponent.Text.Start, oFrame, false )
    oFrame.Text.String = "Hello, this text is within the frame."
    End Sub
    </listing>
 */
service TextFrame
{
    // DocMerge: empty anyway
    service com::sun::star::text::TextContent;


    // DocMerge from xml: service com::sun::star::text::TextFrame: interface com::sun::star::text::XTextFrame
    /** This interface makes it possible to access the text within this
                text frame.
     */
    interface com::sun::star::text::XTextFrame;


    // DocMerge from xml: service com::sun::star::text::TextFrame: interface com::sun::star::drawing::XShape
    /** This interface specifies the access to the shape data (position
                and size) of the text frame.

                <p>This interface is valid before the text frame is attached
                to a surrounding text, but when attached the values can change
                (e.g. due to a revised layout of the surrounding text).

                <p>The position is relative to the position of the anchor
                [see <method>XTextFrame::getAnchor()</method>]. Size and position are
                both measured in 100th mm. The size is not valid if the
                size is relative and no layout exists or if the layout is invalid.

                <p>This interface is only for the layout.  In particular, the
                setting of values is only allowed for the layout component of the
                owner text of this text component.
     */
    interface com::sun::star::drawing::XShape;


    // DocMerge from xml: service com::sun::star::text::TextFrame: interface com::sun::star::beans::XPropertySet
    /** This interface makes it possible to access the properties of
                this text frame.

                <p>This interface is valid before the text frame is attached to
                a surrounding text.
     */
    interface com::sun::star::beans::XPropertySet;


    // DocMerge from xml: service com::sun::star::text::TextFrame: interface com::sun::star::container::XNamed
    /** This interface specifies the name of this text frame.

                <p>The name may be set automatically by the container if it is not
                set when inserted. In this case a random, unique name is assigned.
     */
    interface com::sun::star::container::XNamed;

    //-------------------------------------------------------------------------

    // DocMerge from xml: property com::sun::star::text::TextFrame::FrameHeightAbsolute
    /** contains the metric height value of the frame.
     */
    [property] long FrameHeightAbsolute;

    //-------------------------------------------------------------------------

    // DocMerge from xml: property com::sun::star::text::TextFrame::FrameWidthAbsolute
    /** contains the metric width value of the frame.
     */
    [property] long FrameWidthAbsolute;

    //-------------------------------------------------------------------------

    // DocMerge from xml: property com::sun::star::text::TextFrame::FrameWidthPercent
    /** specifies a width relative to the width of the
        surrounding text.



        <p>If the value for "WidthPercent" is 0, the absolute value from





        is used.</p>
     */
    [property] byte FrameWidthPercent;

    //-------------------------------------------------------------------------

    // DocMerge from xml: property com::sun::star::text::TextFrame::FrameHeightPercent
    /** specifies a width relative to the width of the
        surrounding text.



        <p>If the value for "HeightPercent" is 0, the absolute value from





        is used.</p>
     */
    [property] byte FrameHeightPercent;

    //-------------------------------------------------------------------------

    // DocMerge from xml: property com::sun::star::text::TextFrame::FrameIsAutomaticHeight
    /** If "AutomaticHeight" is set, then the object grows if it is required
        by the frame content.
     */
    [property] boolean FrameIsAutomaticHeight;
    //-------------------------------------------------------------------------

    // DocMerge from xml: property com::sun::star::text::TextFrame::BackGraphicURL
    /** contains the URL for the background graphic.
     */
    [property] string BackGraphicURL;

    //-------------------------------------------------------------------------

    // DocMerge from xml: property com::sun::star::text::TextFrame::BackGraphicFilter
    /** contains the name of the file filter for the background graphic.
     */
    [property] string BackGraphicFilter;

    //-------------------------------------------------------------------------

    // DocMerge from xml: property com::sun::star::text::TextFrame::BackGraphicLocation
    /** determines the position of the background graphic.@see enum GraphicLocation
     */
    [property] com::sun::star::style::GraphicLocation BackGraphicLocation;


};

//=============================================================================

}; }; }; };

/*=============================================================================

    $Log: not supported by cvs2svn $
    Revision 1.2  2000/10/16 16:27:27  mi
    example code added

    Revision 1.1.1.1  2000/09/18 23:36:03  hjs
    initial import

    Revision 1.7  2000/09/11 11:53:01  mi
    documentation merged from XML

    Revision 1.5  2000/06/16 11:42:16  os
    #75622# BackGraphicLocation/URL/Filter added/changed

    Revision 1.4  2000/04/05 13:44:03  os
    syntax

    Revision 1.3  2000/03/31 11:53:57  os
    #74034# Documentation changed

    Revision 1.2  2000/02/07 11:25:02  mi
    zu #70728# missing documentation marked

    Revision 1.1.1.1  1999/11/11 09:48:46  jsc
    new


=============================================================================*/
#endif
