/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_text_UserFieldFormat_idl__
#define __com_sun_star_text_UserFieldFormat_idl__


//=============================================================================

 module com {  module sun {  module star {  module text {

//=============================================================================

// DocMerge from idl: constants com::sun::star::text::UserFieldFormat
/** These constants describe how the content of a user text field is
        formatted.
 */
published constants UserFieldFormat
{
    //-------------------------------------------------------------------------

    // DocMerge from idl: value com::sun::star::text::UserFieldFormat::SYSTEM
    /** The number format of the operating system is used.
     */
    const short SYSTEM = 0;

    //-------------------------------------------------------------------------

    // DocMerge from idl: value com::sun::star::text::UserFieldFormat::TEXT
    /** The content is formatted as text.
     */
    const short TEXT = 1;

    //-------------------------------------------------------------------------

    // DocMerge from idl: value com::sun::star::text::UserFieldFormat::NUM
    /** The number format of the property "NumberFormat" is used.
     */
    const short NUM = 2;

};

//=============================================================================

}; }; }; };

#endif
