/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XAutoTextGroup.idl,v $
 *
 *  $Revision: 1.9 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 06:37:58 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_text_XAutoTextGroup_idl__
#define __com_sun_star_text_XAutoTextGroup_idl__

#ifndef __com_sun_star_container_XNameAccess_idl__
#include <com/sun/star/container/XNameAccess.idl>
#endif

#ifndef __com_sun_star_lang_IllegalArgumentException_idl__
#include <com/sun/star/lang/IllegalArgumentException.idl>
#endif

#ifndef __com_sun_star_container_ElementExistException_idl__
#include <com/sun/star/container/ElementExistException.idl>
#endif

#ifndef __com_sun_star_io_IOException_idl__
#include <com/sun/star/io/IOException.idl>
#endif

#ifndef __com_sun_star_text_XAutoTextEntry_idl__
#include <com/sun/star/text/XAutoTextEntry.idl>
#endif

#ifndef __com_sun_star_text_XTextRange_idl__
#include <com/sun/star/text/XTextRange.idl>
#endif

#ifndef __com_sun_star_container_NoSuchElementException_idl__
#include <com/sun/star/container/NoSuchElementException.idl>
#endif


//=============================================================================

 module com {  module sun {  module star {  module text {

//=============================================================================

// DocMerge from xml: interface com::sun::star::text::XAutoTextGroup
/** The interface provide methods to insert, rename and delete autotext entries from the current autotext group.
 */
published interface XAutoTextGroup: com::sun::star::container::XNameAccess
{
    //-------------------------------------------------------------------------

    // DocMerge from idl: method com::sun::star::text::XAutoTextGroup::getTitles
    /** returns the titles of all autotext entries. The order of the entries
                corresponds to the output of the function getElementNames().
     */
    sequence<string> getTitles();

    //-------------------------------------------------------------------------

    // DocMerge from xml: method com::sun::star::text::XAutoTextGroup::renameByName
    /** renames an entry in the autotext group.



        <p>The position of the autotext entry is not changed.

        </p>
     */
    void renameByName( [in] string aElementName,
             [in] string aNewElementName,
             [in] string aNewElementTitle )
            raises( com::sun::star::lang::IllegalArgumentException,
                    com::sun::star::container::ElementExistException,
                    com::sun::star::io::IOException );

    //-------------------------------------------------------------------------

    // DocMerge from xml: method com::sun::star::text::XAutoTextGroup::insertNewByName
    /** creates a new <type>AutoTextEntry</type> entry.
     */
    com::sun::star::text::XAutoTextEntry insertNewByName( [in] string aName,
             [in] string aTitle,
             [in] com::sun::star::text::XTextRange xTextRange )
            raises( com::sun::star::container::ElementExistException );

    //-------------------------------------------------------------------------

    // DocMerge from xml: method com::sun::star::text::XAutoTextGroup::removeByName
    /** removes the specified autotext entry.
     */
    void removeByName( [in] string aEntryName )
            raises( com::sun::star::container::NoSuchElementException );

};

//=============================================================================

}; }; }; };


#endif
