/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_text_XTextRangeCompare_idl__
#define __com_sun_star_text_XTextRangeCompare_idl__

#include <com/sun/star/uno/XInterface.idl>

#include <com/sun/star/lang/IllegalArgumentException.idl>


 module com {  module sun {  module star {  module text {

 published interface XText;
 published interface XTextRange;

/** compares the positions of two TextRanges within a
    Text.



    <p>Only TextRange instances within the same Text
    can be compared.
    </p>
 */
published interface XTextRangeCompare: com::sun::star::uno::XInterface
{
    /** @returns
                    1 if <var>xR1</var> starts before <var>xR2</var>,
                    0 if <var>xR1</var> starts at the same position as <var>xR2</var> and
                    -1 if <var>xR1</var> starts behind <var>xR2</var>.

                @throws com::sun::star::lang::IllegalArgumentException
                    if either <var>xR1</var> or <var>xR2</var> is not within this
                    text.
     */
    short compareRegionStarts( [in] XTextRange xR1, [in] XTextRange xR2 )
            raises( com::sun::star::lang::IllegalArgumentException );

    /** @returns
                    1, if <var>xR1</var> ends before <var>xR2</var>,
                    0, if <var>xR1</var> ends at the same position as <var>xR2</var> and
                    -1, if <var>xR1</var> ends behind <var>xR2</var>.

                @throws com::sun::star::lang::IllegalArgumentException
                    if either <var>xR1</var> or <var>xR2</var> is not within this
                    text.
     */
    short compareRegionEnds( [in] XTextRange xR1, [in] XTextRange xR2 )
            raises( com::sun::star::lang::IllegalArgumentException );
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
