/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: NamedArgument.idl,v $
 *
 *  $Revision: 1.5 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-09 15:07:00 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_bridge_oleautomation_NamedArgument_idl__
#define __com_sun_star_bridge_oleautomation_NamedArgument_idl__


module com {  module sun {  module star {  module bridge {  module oleautomation {

/** represents a named argument in a call to a method of an Automation object.
    <p>
    The Automation bridge accepts values of <type>NamedArgument</type> when a
    call to an Automation object is made. The call is done through the
    <method scope="com::sun::star::script">XInvocation::invoke</method>
    method, which takes all arguments in a sequence of anys. Usually the order
    of the arguments must correspond to the order of arguments in the Automation
    method. By using instances of <type>NamedArgument</type> the arguments in the
    sequence can be unordered. The Automation object being called must support
    named arguments, otherwise the call fails.
    </p>

    @since OOo 1.1.2
 */
struct NamedArgument
{
    /** The name of the argument, for which
        <member>NamedArgument::Value</member> is intended.
     */
    string Name;

    /** The value of the argument whoose name is the one as contained in the
        member <member>Name</member>.
     */
    any Value;
};

}; }; }; }; };


#endif
