/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_bridge_oleautomation_SCode_idl__
#define __com_sun_star_bridge_oleautomation_SCode_idl__


module com {  module sun {  module star {  module bridge {  module oleautomation {

/** <p>is the UNO representation of the Automation type SCODE.
    </p>
    <p>
    A <code>SCODE</code> is used to express errors in Automation.
    In UNO it could be represented by a `long` and therefore a typedef
    from `long` to a particular error type  would do. But a typedef
    cannot be expressed in all language bindings. In the case where no typedefs
    are supported the actual type is used. That is, a typedef'd error type would
    be represented as <code>int</code> in Java. The information that the
    <code>int</code> is an error type is lost.
    </p>
    <p>
    When calling Automation objects from UNO the distinction between error type
    and `long` is important. Therefore the Scode is
    declared as struct.
    </p>

    @since OOo 1.1.2
 */


struct SCode
{
    long Value;
};

}; }; }; }; };


#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
