/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4; fill-column: 100 -*- */
/*
 * Copyright the Collabora Office contributors.
 *
 * SPDX-License-Identifier: MPL-2.0
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

module scriptinterop {

interface XFill : XBase
{
    XSolidFill getSolidFill();

    FillType getType();

    boolean isVisible();

    [overload setSolidFill] void setSolidFill([in] any color);

    [overload setSolidFill] void setSolidFillWithAlpha([in] any color, [in] double alpha);

    [overload setSolidFill] void setSolidFillRgb([in] long red, [in] long green, [in] long blue);

    [overload setSolidFill] void setSolidFillRgbWithAlpha([in] long red, [in] long green,
                                                       [in] long blue, [in] double alpha);

    void setTransparent();
};

};

/* vim:set shiftwidth=4 softtabstop=4 expandtab cinoptions=b1,g0,N-s cinkeys+=0=break: */
