/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_awt_AccessibleList_idl__
#define __com_sun_star_awt_AccessibleList_idl__

#include <com/sun/star/accessibility/AccessibleContext.idl>

module com { module sun { module star { module accessibility {

 interface XAccessible;
 interface XAccessibleExtendedComponent;
 interface XAccessibleComponent;
 interface XAccessibleSelection;

}; }; }; };

module com { module sun { module star { module awt {



/** Accessible lists are used by combo boxes as container for
    the list items.

    @see com::sun::star::accessibility::AccessibleContext

    @see com::sun::star::accessibility::XAccessibleComponent
    @see com::sun::star::accessibility::XAccessibleExtendedComponent
    @see ::com::sun::star::accessibility::XAccessibleSelection

    @since OOo 1.1.2
*/
service AccessibleList
{
    /** This interface gives access to the structural information of a list:

       <ul>
       <li>Role: The role of a list is
           ::com::sun::star::accessibility::AccessibleRole::LIST.</li>
       <li>Name: The name of a list is its localized label.</li>
       <li>Description: The description of a list is its localized
           help text.</li>
       <li>Children: There exists children.
            Each child is of type com::sun::star::awt::AccessibleListItem. </li>
       <li>Parent: The parent can be of type
            <ul>
            <li>com::sun::star::awt::AccessibleComboBox</li>
            <li>com::sun::star::awt::AccessibleListBox</li>
            <li>com::sun::star::awt::AccessibleDropDownListBox</li>
            <li>com::sun::star::awt::AccessibleDropDownComboBox</li>
            </ul>
       </li>
       <li>Relations: There are no relations.</li>
       <li>States: The states supported by this service are
           <ul>
           <li>com::sun::star::accessibility::AccessibleStateType::DEFUNC
               is set if the object has already been disposed
               and subsequent calls to this object result in
               com::sun::star::lang::DisposedException
               exceptions.</li>
           <li>com::sun::star::accessibility::AccessibleStateType::ENABLED
               is set if the object is enabled.</li>
           <li>com::sun::star::accessibility::AccessibleStateType::FOCUSABLE
               is always set.</li>
           <li>com::sun::star::accessibility::AccessibleStateType::FOCUSED
               is set if the object currently has the keyboard focus.</li>
           <li>com::sun::star::accessibility::AccessibleStateType::ACTIVE
               is set if a child has currently the focus.</li>
           <li>com::sun::star::accessibility::AccessibleStateType::RESIZABLE
               is set if the object can be resized.</li>
           <li>com::sun::star::accessibility::AccessibleStateType::SHOWING
               is set if the object is displayed on the screen.</li>
           <li>com::sun::star::accessibility::AccessibleStateType::VISIBLE
               is always set.</li>
           <li>com::sun::star::accessibility::AccessibleStateType::MULTI_SELECTABLE
               is set if the list supports multi selection.</li>
           <li>com::sun::star::accessibility::AccessibleStateType::MANAGES_DESCENDANTS
               is always set.
               The children are transient.</li>
           </ul>
           </li>
       </ul>
    */
    service   com::sun::star::accessibility::AccessibleContext;

    interface com::sun::star::accessibility::XAccessibleComponent;
    interface com::sun::star::accessibility::XAccessibleExtendedComponent;

    /** Support of the com::sun::star::accessibility::XAccessible interface may be
        discontinued in the future.
    */
    interface com::sun::star::accessibility::XAccessible;

    /** This interface gives access to the selectable children of a
        list.
     */
    interface com::sun::star::accessibility::XAccessibleSelection;
};

}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
