/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: FontSlant.idl,v $
 *
 *  $Revision: 1.10 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-07 21:02:57 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_awt_FontSlant_idl__
#define __com_sun_star_awt_FontSlant_idl__


//=============================================================================

 module com {  module sun {  module star {  module awt {

//=============================================================================

/** used to specify the slant of a font.
 */
published enum FontSlant
{
    //-------------------------------------------------------------------------

    /** specifies a font without slant.
     */
    NONE,

    //-------------------------------------------------------------------------

    /** specifies an oblique font (slant not designed into the font).
     */
    OBLIQUE,

    //-------------------------------------------------------------------------

    /** specifies an italic font (slant designed into the font).
     */
    ITALIC,

    //-------------------------------------------------------------------------

    /** specifies a font with an unknown slant.
     */
    DONTKNOW,

    //-------------------------------------------------------------------------

    /** specifies a reverse oblique font (slant not designed into the font).
     */
    REVERSE_OBLIQUE,

    //-------------------------------------------------------------------------

    /** specifies a reverse italic font (slant designed into the font).
     */
    REVERSE_ITALIC

};

//=============================================================================

}; }; }; };

#endif
