/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */


module com { module sun { module star { module awt {

/** This struct extends the Gradient definition by adding a sequence
    of ColorStops to allow definition of multi-color gradients.
  */
struct Gradient2 : Gradient
{
    /** contains the full multi-color gradient definition.
      */
    com::sun::star::awt::ColorStopSequence ColorStops;
};


}; }; }; };

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
