/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_awt_ImageScaleMode_idl__
#define __com_sun_star_awt_ImageScaleMode_idl__


module com { module sun { module star { module awt {


/** defines modes how an image displayed in a given area should be scaled to fit this area
 */
constants ImageScaleMode
{
    /** specifies that no scaling should happen at all
    */
    const short None = 0;

    /** specifies that the image should be scaled up or down to the size of the surrounding area isotropically,
        i.e. by keeping its aspect ratio.
    */
    const short Isotropic = 1;

    /** specifies that the image should be scaled up or down to the size of the surrounding area anisotropically.

        <p>The image will finally cover all of the surrounding area, but its dimensions might be distorted.</p>
    */
    const short Anisotropic = 2;
};


}; }; }; };


#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
