/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_awt_MouseWheelBehavior_idl__
#define __com_sun_star_awt_MouseWheelBehavior_idl__


module com { module sun { module star { module awt {


/** describes the scroll behavior of the mouse wheel for a control
    @since OOo 3.2
 */
constants MouseWheelBehavior
{
    /** defines that the mouse wheel cannot be used to scroll through the control's content
    */
    const short SCROLL_DISABLED = 0;

    /** defines that the mouse can only be used to scroll through the control's content if it currently
        has the focus.
    */
    const short SCROLL_FOCUS_ONLY = 1;

    /** defines that the mouse can be used to scroll through the control's content, no matter whether or not
        it has the focus, as long as the mouse pointer is over the control.
    */
    const short SCROLL_ALWAYS = 2;
};


}; }; }; };


#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
