/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_awt_UnoControl_idl__
#define __com_sun_star_awt_UnoControl_idl__

#include <com/sun/star/lang/XComponent.idl>
#include <com/sun/star/awt/XControl.idl>
#include <com/sun/star/awt/XWindow.idl>
#include <com/sun/star/awt/XView.idl>
#include <com/sun/star/accessibility/XAccessible.idl>



 module com {  module sun {  module star {  module awt {


/** specifies an abstract control.

    <p>All components which implement this service can
    be integrated in a windowing environment. This service describes
    the controller of the Smalltalk model view controller design.</p>

    <p>You must set a model and a stub to the UnoControl before using
    other methods.  The implementation only allows the change of the
    graphics (XView) if the window is not visible. The
    change of the graphics in visible state should redirect the output
    to these graphics, but this behavior is implementation-specific.</p>

    <p>The change of data directly at the control may not affect the
    model data. To ensure this behavior, modify the data of the model.</p>
 */
published service UnoControl
{
    interface com::sun::star::lang::XComponent;

    interface com::sun::star::awt::XControl;

    interface com::sun::star::awt::XWindow;

    interface com::sun::star::awt::XView;

    /** provides access to the accessible context associated with this object.

        @since OOo 1.1.2
     */
    [optional] interface com::sun::star::accessibility::XAccessible;

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
