/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_awt_XDataTransferProviderAccess_idl__
#define __com_sun_star_awt_XDataTransferProviderAccess_idl__

#include <com/sun/star/uno/XInterface.idl>


module com { module sun { module star { module datatransfer {
module dnd {
     published interface XDragGestureRecognizer;
     published interface XDragSource;
     published interface XDropTarget;
};
module clipboard {
     published interface XClipboard;
};
}; }; }; };


module com { module sun { module star { module awt {

 published interface XWindow;


/** This interface extends the XToolkit interface with clipboard and
    drag-and-drop support.
*/
published interface XDataTransferProviderAccess: com::sun::star::uno::XInterface
{

    /** returns the drag gesture recognizer of the specified window.

        @returns the drag gesture recognizer.

        @param window
        a window created by the same toolkit instance.
    */
    com::sun::star::datatransfer::dnd::XDragGestureRecognizer getDragGestureRecognizer( [in] XWindow window );


    /** returns the drag source of the specified window.

        @returns the drag source.

        @param window
        a window created by the same toolkit instance.
    */
    com::sun::star::datatransfer::dnd::XDragSource getDragSource( [in] XWindow window );


    /** returns the drop target of the specified window.

        @returns the drop target.

        @param window
        a window created by the same toolkit instance.
    */
    com::sun::star::datatransfer::dnd::XDropTarget getDropTarget( [in] XWindow window );


    /** returns the specified clipboard.

        @returns the specified clipboard (if available).

        @param clipboardName
        the name of the clipboard to return.
        If an empty string is passed in, the default clipboard is returned.
    */
    com::sun::star::datatransfer::clipboard::XClipboard getClipboard( [in] string clipboardName );
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
