/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_awt_XRegion_idl__
#define __com_sun_star_awt_XRegion_idl__

#include <com/sun/star/uno/XInterface.idl>

#include <com/sun/star/awt/Rectangle.idl>



 module com {  module sun {  module star {  module awt {


/** manages multiple rectangles which make up a region.
 */
published interface XRegion: com::sun::star::uno::XInterface
{

    /** returns the bounding box of the shape.
     */
    Rectangle getBounds();


    /** makes this region an empty region.
     */
    [oneway] void clear();


    /** moves this region by the specified horizontal and vertical delta.
     */
    [oneway] void move( [in] long nHorzMove,
             [in] long nVertMove );


    /** adds the specified rectangle to this region.
     */
    [oneway] void unionRectangle( [in] Rectangle Rect );


    /** intersects the specified rectangle with the current region.
     */
    [oneway] void intersectRectangle( [in] Rectangle Region );


    /** removes the area of the specified rectangle from this region.
     */
    [oneway] void excludeRectangle( [in] Rectangle Rect );


    /** applies an exclusive-or operation with the specified rectangle
        to this region.
     */
    [oneway] void xOrRectangle( [in] Rectangle Rect );


    /** adds the specified region to this region.
     */
    [oneway] void unionRegion( [in] XRegion Region );


    /** intersects the specified region with the current region.
     */
    [oneway] void intersectRegion( [in] XRegion Region );


    /** removes the area of the specified region from this region.
     */
    [oneway] void excludeRegion( [in] XRegion Region );


    /** applies an exclusive-or operation with the specified region
        to this region.
     */
    [oneway] void xOrRegion( [in] XRegion Region );


    /** returns all rectangles which are making up this region.
     */
    sequence<Rectangle> getRectangles();

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
