/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_awt_XRequestCallback_idl__
#define __com_sun_star_awt_XRequestCallback_idl__

#include <com/sun/star/awt/XCallback.idl>


module com { module sun { module star { module awt {


/** specifies an interface which can be used to call back
    an implementation
 */
interface XRequestCallback
{

    /** adds a callback request to the implementation

        @param aData
        any private data which will be provided to the callback implementation.

        @param xCallback
        a reference to the callback which should be called by the implementation
        of this interface.
    */
    void addCallback( [in] XCallback xCallback, [in] any aData );
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
