/*************************************************************************
 *
 *  $RCSfile: XWindow.idl,v $
 *
 *  $Revision: 1.6 $
 *
 *  last change: $Author: obo $ $Date: 2004-06-03 17:48:53 $
 *
 *  The Contents of this file are made available subject to the terms of
 *  either of the following licenses
 *
 *         - GNU Lesser General Public License Version 2.1
 *         - Sun Industry Standards Source License Version 1.1
 *
 *  Sun Microsystems Inc., October, 2000
 *
 *  GNU Lesser General Public License Version 2.1
 *  =============================================
 *  Copyright 2000 by Sun Microsystems, Inc.
 *  901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License version 2.1, as published by the Free Software Foundation.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *  MA  02111-1307  USA
 *
 *
 *  Sun Industry Standards Source License Version 1.1
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.1 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://www.openoffice.org/license.html.
 *
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 *
 *  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 *
 *  Copyright: 2000 by Sun Microsystems, Inc.
 *
 *  All Rights Reserved.
 *
 *  Contributor(s): _______________________________________
 *
 *
 ************************************************************************/
#ifndef __com_sun_star_awt_XWindow_idl__
#define __com_sun_star_awt_XWindow_idl__

#ifndef __com_sun_star_lang_XComponent_idl__
#include <com/sun/star/lang/XComponent.idl>
#endif

#ifndef __com_sun_star_awt_Rectangle_idl__
#include <com/sun/star/awt/Rectangle.idl>
#endif

#ifndef __com_sun_star_awt_XWindowListener_idl__
#include <com/sun/star/awt/XWindowListener.idl>
#endif

#ifndef __com_sun_star_awt_XFocusListener_idl__
#include <com/sun/star/awt/XFocusListener.idl>
#endif

#ifndef __com_sun_star_awt_XKeyListener_idl__
#include <com/sun/star/awt/XKeyListener.idl>
#endif

#ifndef __com_sun_star_awt_XMouseListener_idl__
#include <com/sun/star/awt/XMouseListener.idl>
#endif

#ifndef __com_sun_star_awt_XMouseMotionListener_idl__
#include <com/sun/star/awt/XMouseMotionListener.idl>
#endif

#ifndef __com_sun_star_awt_XPaintListener_idl__
#include <com/sun/star/awt/XPaintListener.idl>
#endif


//=============================================================================

 module com {  module sun {  module star {  module awt {

//=============================================================================

/** specifies the basic operations for a window component.

    <p>A window is a rectangular region on an output device with
    its own position, size, and internal coordinate system.
    A window is used for displaying data. In addition, the window
    receives events from the user.</p>
 */
published interface XWindow: com::sun::star::lang::XComponent
{
    //-------------------------------------------------------------------------

    /** sets the outer bounds of the window.

        @param X
        the x-coordinate of the window.

        @param Y
        the y-coordinate of the window.

        @param Width
        the width of the window.

        @param Height
        the height of the window.

        @param Flags
        Flags are of type <type>PosSize</type> and specify, which parameters
        are taken into account when setting the outer bounds of the window.
    */
    [oneway] void setPosSize( [in] long X,
             [in] long Y,
             [in] long Width,
             [in] long Height,
             [in] short Flags );

    //-------------------------------------------------------------------------

    /** returns the outer bounds of the window.
     */
    com::sun::star::awt::Rectangle getPosSize();

    //-------------------------------------------------------------------------

    /** shows or hides the window depending on the parameter.
     */
    [oneway] void setVisible( [in] boolean Visible );

    //-------------------------------------------------------------------------

    /** enables or disables the window depending on the parameter.
     */
    [oneway] void setEnable( [in] boolean Enable );

    //-------------------------------------------------------------------------

    /** sets the focus to the window.
     */
    [oneway] void setFocus();

    //-------------------------------------------------------------------------

    /** adds a window listener to the object.
     */
    [oneway] void addWindowListener( [in] com::sun::star::awt::XWindowListener xListener );

    //-------------------------------------------------------------------------

    /** removes the specified window listener from the listener list.
     */
    [oneway] void removeWindowListener( [in] com::sun::star::awt::XWindowListener xListener );

    //-------------------------------------------------------------------------

    /** adds a focus listener to the object.
     */
    [oneway] void addFocusListener( [in] com::sun::star::awt::XFocusListener xListener );

    //-------------------------------------------------------------------------

    /** removes the specified focus listener from the listener list.
     */
    [oneway] void removeFocusListener( [in] com::sun::star::awt::XFocusListener xListener );

    //-------------------------------------------------------------------------

    /** adds a key listener to the object.
     */
    [oneway] void addKeyListener( [in] com::sun::star::awt::XKeyListener xListener );

    //-------------------------------------------------------------------------

    /** removes the specified key listener from the listener list.
     */
    [oneway] void removeKeyListener( [in] com::sun::star::awt::XKeyListener xListener );

    //-------------------------------------------------------------------------

    /** adds a mouse listener to the object.
     */
    [oneway] void addMouseListener( [in] com::sun::star::awt::XMouseListener xListener );

    //-------------------------------------------------------------------------

    /** removes the specified mouse listener from the listener list.
     */
    [oneway] void removeMouseListener( [in] com::sun::star::awt::XMouseListener xListener );

    //-------------------------------------------------------------------------

    /** adds a mouse motion listener to the object.
     */
    [oneway] void addMouseMotionListener( [in] com::sun::star::awt::XMouseMotionListener xListener );

    //-------------------------------------------------------------------------

    /** removes the specified mouse motion listener from the listener list.
     */
    [oneway] void removeMouseMotionListener( [in] com::sun::star::awt::XMouseMotionListener xListener );

    //-------------------------------------------------------------------------

    /** adds a paint listener to the object.
     */
    [oneway] void addPaintListener( [in] com::sun::star::awt::XPaintListener xListener );

    //-------------------------------------------------------------------------

    /** removes the specified paint listener from the listener list.
     */
    [oneway] void removePaintListener( [in] com::sun::star::awt::XPaintListener xListener );

};

//=============================================================================

}; }; }; };

#endif
