/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: DataPilotDescriptor.idl,v $
 *
 *  $Revision: 1.6 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 04:28:39 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/

#ifndef __com_sun_star_sheet_DataPilotTableDescriptor_idl__
#define __com_sun_star_sheet_DataPilotTableDescriptor_idl__

#ifndef __com_sun_star_sheet_XDataPilotDescriptor_idl__
#include <com/sun/star/sheet/XDataPilotDescriptor.idl>
#endif

#ifndef __com_sun_star_beans_XPropertySet_idl__
#include <com/sun/star/beans/XPropertySet.idl>
#endif

//=============================================================================

module com { module sun { module star { module sheet {

//=============================================================================

/** represents the description of the layout of a data pilot table.

    @see com::sun::star::sheet::DataPilotTable
*/
published service DataPilotDescriptor
{
    //-------------------------------------------------------------------------

    /** provides access to the layout settings of the data pilot table.
     */
    interface com::sun::star::sheet::XDataPilotDescriptor;

    //-------------------------------------------------------------------------

    /** provides access to the layout settings of the data pilot table.
     */
    [optional] interface com::sun::star::beans::XPropertySet;

    //=========================================================================

    /** specifies the orientation of the field.
     */
    [optional, property] boolean IgnoreEmptyRows;

    //-------------------------------------------------------------------------

    /** specifies the orientation of the field.
     */
    [optional, property] boolean RepeatIfEmpty;

    //-------------------------------------------------------------------------

    /** specifies the orientation of the field.
     */
    [optional, property] boolean ColumnGrand;

    //-------------------------------------------------------------------------

    /** specifies the orientation of the field.
     */
    [optional, property] boolean RowGrand;

    //-------------------------------------------------------------------------

    /** specifies whether the filter button is shown.
     */
    [optional, property] boolean ShowFilterButton;

    //-------------------------------------------------------------------------

    /** specifies whether to drill down to details or go into edit mode.
     */
    [optional, property] boolean DrillDownOnDoubleClick;

    //-------------------------------------------------------------------------
};

//=============================================================================

}; }; }; };

#endif
