/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/



#ifndef __com_sun_star_sheet_DataPilotTable_idl__
#define __com_sun_star_sheet_DataPilotTable_idl__

#ifndef __com_sun_star_sheet_XDataPilotDescriptor_idl__
#include <com/sun/star/sheet/XDataPilotDescriptor.idl>
#endif

#ifndef __com_sun_star_sheet_XDataPilotTable_idl__
#include <com/sun/star/sheet/XDataPilotTable.idl>
#endif

#ifndef __com_sun_star_util_XModifyBroadcaster_idl__
#include <com/sun/star/util/XModifyBroadcaster.idl>
#endif

//=============================================================================

module com {  module sun {  module star {  module sheet {

//=============================================================================

/** represents a data pilot table on a spreadsheet.
 */
published service DataPilotTable
{
    //-------------------------------------------------------------------------

    /** provides access to the layout settings of the data pilot table.
     */
    interface com::sun::star::sheet::XDataPilotDescriptor;

    //-------------------------------------------------------------------------

    /** provides methods to control a data pilot table.
     */
    interface com::sun::star::sheet::XDataPilotTable;

    //-------------------------------------------------------------------------

    /** allows notification of modifications to the data pilot table.

    @since OpenOffice 3.3

    */
    [optional] interface com::sun::star::util::XModifyBroadcaster;
};

//=============================================================================

}; }; }; };

#endif

