/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/



#ifndef __com_sun_star_sheet_ExternalReference_idl__
#define __com_sun_star_sheet_ExternalReference_idl__

module com {  module sun {  module star {  module sheet {

//=============================================================================

/** Data structure to store information about an external reference.  An
    external reference can be either a single cell reference, a cell range
    reference, or a named range.

    @see FormulaMapGroupSpecialOffset::PUSH

    @since OpenOffice 3.1
 */
struct ExternalReference
{
    //-------------------------------------------------------------------------

    /** Index of an externally linked document.  Each externally-linked document
        has a unique index value.

        <p>You can get the index value of an external document from the
        corresponding <type scope="com::sun::star::sheet">ExternalDocLink</type>
        instance through its attribute <type scope="com::sun::star::sheet::ExternalDocLink">TokenIndex</type>.</p>

        @see com::sun::star::sheet::ExternalDocLink
        @see com::sun::star::sheet::ExternalDocLink::TokenIndex
     */
    long Index;

#if 0
    //-------------------------------------------------------------------------

    /** Name of the sheet that the external reference points to.

        <p>In case of a cell range reference that spans across multiple
        sheets, this is the name of the first sheet in that range.</p>

        <p>Note that an external range name ignores this value at the moment,
        but <i>it may make use of this data in the future when Calc supports a
        sheet-specific range name.</i></p>
     */
    string SheetName;
#endif

    //-------------------------------------------------------------------------

    /** Reference data.

        <p>This can store either <type>SingleReference</type> for a single
        cell reference, <type>ComplexReference</type> for a cell range
        reference, or simply a <type>string</type> for a defined name.</p>

        <p>The <member>SingleReference::Sheet</member> member shall contain
        the index of the external sheet cache containing the values of the
        externally referenced cells.</p>

        @see com::sun::star::sheet::SingleReference
        @see com::sun::star::sheet::ComplexReference
     */
    any Reference;
};

//=============================================================================

}; }; }; };

#endif
