/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/



#ifndef __com_sun_star_sheet_FillDateMode_idl__
#define __com_sun_star_sheet_FillDateMode_idl__

//=============================================================================

module com {  module sun {  module star {  module sheet {

//=============================================================================

/** used to specify how an arithmetic date series is calculated.

    @see com::sun::star::sheet::FillMode
 */
published enum FillDateMode
{
    //-------------------------------------------------------------------------

    /** for every new value a single day is added.
     */
    FILL_DATE_DAY,

    //-------------------------------------------------------------------------

    /** for evey new value a single day is added, but Saturdays and
        Sundays are skipped.
     */
    FILL_DATE_WEEKDAY,

    //-------------------------------------------------------------------------

    /** for every new value one month is added (day keeps unchanged).
     */
    FILL_DATE_MONTH,

    //-------------------------------------------------------------------------

    /** for every new value one year is added (day and month keep unchanged).
     */
    FILL_DATE_YEAR

};

//=============================================================================

}; }; }; };

#endif

