/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#ifndef __com_sun_star_sheet_FilterFieldValue_idl__
#define __com_sun_star_sheet_FilterFieldValue_idl__

module com {  module sun {  module star {  module sheet {

/**
 * @since LibreOffice 3.5
 */
struct FilterFieldValue
{
    /** selects whether the TableFilterFieldValue::NumericValue
        or the TableFilterFieldValue::StringValue is used.

        @deprecated - Use FilterType instead.
     */
    boolean IsNumeric;

    /** specifies a numeric value for the condition.
     */
    double NumericValue;

    /** specifies a string value for the condition.
     */
    string StringValue;

    /** Which field should be used for filtering:

        <ul>
            <li>com::sun::star::sheet::FilterFieldType::NUMERIC -> NumericValue</li>
            <li>com::sun::star::sheet::FilterFieldType::STRING -> StringValue</li>
            <li>com::sun::star::sheet::FilterFieldType::DATE -> StringValue</li>
            <li>com::sun::star::sheet::FilterFieldType::TEXT_COLOR -> color</li>
            <li>com::sun::star::sheet::FilterFieldType::BACKGROUND_COLOR -> StringValue</li>
        </ul>

        @see com::sun::star::sheet::FilterFieldType
        @since LibreOffice 7.2
     */
    short FilterType;

    /** The color which is used for filtering

        @since LibreOffice 7.2
     */
    com::sun::star::util::Color ColorValue;

};

}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
