/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/



#ifndef __com_sun_star_sheet_FilterOperator_idl__
#define __com_sun_star_sheet_FilterOperator_idl__

//=============================================================================

module com {  module sun {  module star {  module sheet {

//=============================================================================

/** specifies the type of a single condition in a filter descriptor.
 */
published enum FilterOperator
{
    //-------------------------------------------------------------------------

    /** selects empty entries.
     */
    EMPTY,

    //-------------------------------------------------------------------------

    /** selects non-empty entries.
     */
    NOT_EMPTY,

    //-------------------------------------------------------------------------

    /** value has to be equal to the specified value.
     */
    EQUAL,

    //-------------------------------------------------------------------------

    /** value must not be equal to the specified value.
     */
    NOT_EQUAL,

    //-------------------------------------------------------------------------

    /** value has to be greater than the specified value.
     */
    GREATER,

    //-------------------------------------------------------------------------

    /** value has to be greater than or equal to the specified value.
     */
    GREATER_EQUAL,

    //-------------------------------------------------------------------------

    /** value has to be less than the specified value.
     */
    LESS,

    //-------------------------------------------------------------------------

    /** value has to be less than or equal to the specified value.
     */
    LESS_EQUAL,

    //-------------------------------------------------------------------------

    /** selects a specified number of entries with the greatest values.
     */
    TOP_VALUES,

    //-------------------------------------------------------------------------

    /** selects a specified percentage of entries with the greatest values.
     */
    TOP_PERCENT,

    //-------------------------------------------------------------------------

    /** selects a specified number of entries with the lowest values.
     */
    BOTTOM_VALUES,

    //-------------------------------------------------------------------------

    /** selects a specified percentage of entries with the lowest values.
     */
    BOTTOM_PERCENT

};

//=============================================================================

}; }; }; };

#endif

