/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_sheet_SpreadsheetView_idl__
#define __com_sun_star_sheet_SpreadsheetView_idl__

#include <com/sun/star/frame/Controller.idl>
#include <com/sun/star/sheet/SpreadsheetViewSettings.idl>
#include <com/sun/star/sheet/SpreadsheetViewPane.idl>
#include <com/sun/star/sheet/XSpreadsheetView.idl>
#include <com/sun/star/container/XIndexAccess.idl>
#include <com/sun/star/view/XSelectionSupplier.idl>
#include <com/sun/star/sheet/XViewSplitable.idl>
#include <com/sun/star/sheet/XViewFreezable.idl>
#include <com/sun/star/sheet/XRangeSelection.idl>
#include <com/sun/star/container/XEnumerationAccess.idl>
#include <com/sun/star/sheet/XActivationBroadcaster.idl>
#include <com/sun/star/sheet/XEnhancedMouseClickBroadcaster.idl>


 module com {  module sun {  module star {  module sheet {


/** represents a view of a spreadsheet document.
 */
published service SpreadsheetView
{
    /** provides the integration into the framework.
     */
    service com::sun::star::frame::Controller;

    /** provides the view's settings.
     */
    service com::sun::star::sheet::SpreadsheetViewSettings;

    /** provides direct access to the view's active pane.
     */
    service com::sun::star::sheet::SpreadsheetViewPane;

    /** provides access to the active sheet in the view.
     */
    interface com::sun::star::sheet::XSpreadsheetView;

    /** provides access to the collection of view panes.
     */
    interface com::sun::star::container::XIndexAccess;

    /** creates an enumeration of view panes.

        @see com::sun::star::sheet::SpreadsheetViewPanesEnumeration

     */
    interface com::sun::star::container::XEnumerationAccess;

    /** provides access to the view's selection.
    <p>The selection in a spreadsheet view can be a
        com::sun::star::sheet::SheetCell,
        com::sun::star::sheet::SheetCellRange,
        com::sun::star::sheet::SheetCellRanges,
        com::sun::star::drawing::Shape or
        com::sun::star::drawing::Shapes object.
    </p>
     */
    interface com::sun::star::view::XSelectionSupplier;

    /** allows to split the view.
     */
    interface com::sun::star::sheet::XViewSplitable;

    /** allows to freeze columns and rows of the view.
     */
    interface com::sun::star::sheet::XViewFreezable;

    /** allows to let the user interactively select a cell range.
     */
    interface com::sun::star::sheet::XRangeSelection;

    [optional] interface com::sun::star::sheet::XEnhancedMouseClickBroadcaster;

    [optional] interface com::sun::star::sheet::XActivationBroadcaster;
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
