/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/



#ifndef __com_sun_star_sheet_XDataPilotMemberResults_idl__
#define __com_sun_star_sheet_XDataPilotMemberResults_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __com_sun_star_sheet_MemberResult_idl__
#include <com/sun/star/sheet/MemberResult.idl>
#endif

//=============================================================================

module com {  module sun {  module star {  module sheet {

//=============================================================================

/** provides access to a sequence of results of a data pilot source level.

    <p>These results are used to fill the data area for the level in a data
    pilot table.</p>

    @see com::sun::star::sheet::DataPilotSourceLevel
    @see com::sun::star::sheet::DataPilotSource
    @see com::sun::star::sheet::XDataPilotResults
 */
published interface XDataPilotMemberResults: com::sun::star::uno::XInterface
{
    //-------------------------------------------------------------------------

    /** returns the sequence of results for the regarding data pilot
        source level.
     */
    sequence< com::sun::star::sheet::MemberResult > getResults();

};

//=============================================================================

}; }; }; };

#endif

