/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_sheet_XDDELinkResults_idl__
#define __com_sun_star_sheet_XDDELinkResults_idl__

#include <com/sun/star/uno/XInterface.idl>


module com {  module sun {  module star {  module sheet {


/** provides access to the DDE link results.

    @see com::sun::star::sheet::DDELink

    @since OOo 3.0
 */
published interface XDDELinkResults: com::sun::star::uno::XInterface
{

    /** returns the DDE link results.

        @returns
            the DDE link results. The outer sequence contains the value rows.
            The inner sequences contain the result values for one row.
     */
    sequence< sequence< any > > getResults();


    /** sets the DDE link results.

        @param aResults
            the DDE link results. The outer sequence contains the value rows.
            The inner sequences contain the result values for one row.
            If the outer sequence is empty, the existing DDE link results are
            cleared.
     */
    void setResults( [in] sequence< sequence< any > > aResults );

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
