/*************************************************************************
 *
 *  $RCSfile: XNamedRanges.idl,v $
 *
 *  $Revision: 1.8 $
 *
 *  last change: $Author: hr $ $Date: 2003-03-26 13:56:10 $
 *
 *  The Contents of this file are made available subject to the terms of
 *  either of the following licenses
 *
 *         - GNU Lesser General Public License Version 2.1
 *         - Sun Industry Standards Source License Version 1.1
 *
 *  Sun Microsystems Inc., October, 2000
 *
 *  GNU Lesser General Public License Version 2.1
 *  =============================================
 *  Copyright 2000 by Sun Microsystems, Inc.
 *  901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License version 2.1, as published by the Free Software Foundation.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *  MA  02111-1307  USA
 *
 *
 *  Sun Industry Standards Source License Version 1.1
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.1 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://www.openoffice.org/license.html.
 *
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 *
 *  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 *
 *  Copyright: 2000 by Sun Microsystems, Inc.
 *
 *  All Rights Reserved.
 *
 *  Contributor(s): _______________________________________
 *
 *
 ************************************************************************/

#ifndef __com_sun_star_sheet_XNamedRanges_idl__
#define __com_sun_star_sheet_XNamedRanges_idl__

#ifndef __com_sun_star_container_XNameAccess_idl__
#include <com/sun/star/container/XNameAccess.idl>
#endif

#ifndef __com_sun_star_table_CellAddress_idl__
#include <com/sun/star/table/CellAddress.idl>
#endif

#ifndef __com_sun_star_table_CellRangeAddress_idl__
#include <com/sun/star/table/CellRangeAddress.idl>
#endif

#ifndef __com_sun_star_sheet_Border_idl__
#include <com/sun/star/sheet/Border.idl>
#endif

//=============================================================================

module com {  module sun {  module star {  module sheet {

//=============================================================================

/** provides access to the members in a collection of named ranges and to
    insert and remove them.

    @see com::sun::star::sheet::NamedRanges
    @see com::sun::star::sheet::NamedRange
 */
interface XNamedRanges: com::sun::star::container::XNameAccess
{
    //-------------------------------------------------------------------------

    /** adds a new named range to the collection.

        @param aName
            the new name of the named range.

        @param aContent
            the formula expression.

            <p>A cell range address is one possible content of a named
            range.</p>

        @param aPosition
            specifies the base address for relative cell references.

        @param nType
            a combination of flags that specify the type of a named range,
            as defined in <type>NamedRangeFlag</type>.

            <p>This parameter will be zero for any common named range.</p>
     */
    void addNewByName(
            [in] string aName,
            [in] string aContent,
            [in] com::sun::star::table::CellAddress aPosition,
            [in] long nType );

    //-------------------------------------------------------------------------

    /** creates named cell ranges from titles in a cell range.

        <p>The names for the named ranges are taken from title cells in the
        top or bottom row, or from the cells of the left or right column
        of the range (depending on the parameter <const>aBorder</const>.
        The named ranges refer to single columns or rows in the inner
        part of the original range, excluding the labels.</p>

        <p>Example: The source range is A1:B3. The named ranges shall be
        created using row titles. This requires <member>Border::TOP</member>
        for the second parameter. The method creates two named ranges. The
        name of the first is equal to the content of cell A1 and contains the
        range $Sheet.$A$2:$A$3 (excluding the title cell). The latter named
        range is named using cell B1 and contains the cell range address
        $Sheet.$B$2:$B$3.</p>

        @param aSource
            the cell range used to create the named ranges.

        @param aBorder
            specifies the location of the title cells.
     */
    void addNewFromTitles(
            [in] com::sun::star::table::CellRangeAddress aSource,
            [in] com::sun::star::sheet::Border aBorder );

    //-------------------------------------------------------------------------

    /** removes a named range from the collection.
     */
    void removeByName( [in] string aName );

    //-------------------------------------------------------------------------

    /** writes a list of all named ranges into the document.

        <p>The first column of the list contains the names. The second
        column contains the contents of the named ranges.</p>

        @param aOutputPosition
            specifies the top left cell of the output range.
     */
    void outputList( [in] com::sun::star::table::CellAddress aOutputPosition );

};

//=============================================================================

}; }; }; };

#endif

