/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * Version: MPL 1.1 / GPLv3+ / LGPLv3+
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License or as specified alternatively below. You may obtain a copy of
 * the License at http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * Major Contributor(s):
 *   Copyright (C) 2011 Kohei Yoshida <kohei.yoshida@suse.com>
 *
 * All Rights Reserved.
 *
 * For minor contributions see the git repository.
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 3 or later (the "GPLv3+"), or
 * the GNU Lesser General Public License Version 3 or later (the "LGPLv3+"),
 * in which case the provisions of the GPLv3+ or the LGPLv3+ are applicable
 * instead of those above.
 */

#ifndef __com_sun_star_sheet_XSheetFilterDescriptor3_idl__
#define __com_sun_star_sheet_XSheetFilterDescriptor3_idl__

#include <com/sun/star/sheet/TableFilterField3.idl>
#include <com/sun/star/uno/XInterface.idl>

module com {  module sun {  module star {  module sheet {

/** provides access to a collection of filter conditions (filter fields).

    <p>This interface uses the <type>TableFilterField3</type> struct.
    whereas the <type>XSheetFilterDescriptor2</type> interface uses the
    <type>TableFilterField2</type> struct.</p>

    @see SheetFilterDescriptor2

    @since LibreOffice 3.5
 */
interface XSheetFilterDescriptor3: com::sun::star::uno::XInterface
{

    /** returns the collection of filter fields.
     */
    sequence<TableFilterField3> getFilterFields3();


    /** sets a new collection of filter fields.
     */
    void setFilterFields3( [in] sequence<TableFilterField3> aFilterFields );

};

}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
