/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_sheet_XSheetLinkable_idl__
#define __com_sun_star_sheet_XSheetLinkable_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/sheet/SheetLinkMode.idl>


module com {  module sun {  module star {  module sheet {


/** enables a sheet to refer to another sheet in a different document.

    <p>To insert a sheet link, the sheet used as linked sheet has to exist
    already. The method XSheetLinkable::link() creates a
    SheetLink object in the document's SheetLinks
    collection and links the sheet to the specified external sheet.</p>

    @see com::sun::star::sheet::SheetLinks
    @see com::sun::star::sheet::SheetLink

    @deprecated
 */
published interface XSheetLinkable: com::sun::star::uno::XInterface
{

    /** returns the link mode of the spreadsheet.

        <p>If the returned value is SheetLinkMode::NORMAL,
        formulas are copied. With SheetLinkMode::VALUE,
        only results of formulas are used.</p>
     */
    com::sun::star::sheet::SheetLinkMode getLinkMode();


    /** enables the linking of the sheet and controls whether formulas
        are copied.

        @param nLinkMode
            the value specifying the link mode for this spreadsheet.

            <p>If the value is SheetLinkMode::NORMAL,
            formulas are copied.  With SheetLinkMode::VALUE,
            only results of formulas are used.</p>
     */
    void setLinkMode( [in] com::sun::star::sheet::SheetLinkMode nLinkMode );


    /** returns the target URL of the link.
     */
    string getLinkUrl();


    /** sets the target URL of the link.

        <p>A SheetLink object with the same file name must
        exist already or the link will not work.</p>
     */
    void setLinkUrl( [in] string aLinkUrl );


    /** returns the sheet name of the sheet in the source document.
     */
    string getLinkSheetName();


    /** sets the name of the linked sheet in the source document.

        <p>This method sets the sheet name in the SheetLink
        object, it does not modify the sheet name in the source document.</p>
     */
    void setLinkSheetName( [in] string aLinkSheetName );


    /** links the sheet to another sheet in another document.

        <p>A SheetLink object is created if it does not exist,
        and the link mode, the URL of the linked document and the linked
        sheet name are set.</p>
     */
    void link( [in] string aUrl,
             [in] string aSheetName,
             [in] string aFilterName,
             [in] string aFilterOptions,
             [in] com::sun::star::sheet::SheetLinkMode nMode );

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
