/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef _com_sun_star_ucb_CommandEnvironment_idl_
#define _com_sun_star_ucb_CommandEnvironment_idl_

#include <com/sun/star/ucb/XCommandEnvironment.idl>
#include <com/sun/star/task/XInteractionHandler.idl>
#include <com/sun/star/ucb/XProgressHandler.idl>

module com { module sun { module star { module ucb {

 /* This service implements an <type>XCommandEnvironment</type> that can be
    initialized with any implementation of
    <type scope="com::sun::star::task">XInteractionHandler</type> and
    <type scope="com::sun::star::ucb">XProgressHandler</type>. The respective
    get methods will simply return these handlers.

    @since OOo 3.3
 */
 published service CommandEnvironment : ::com::sun::star::ucb::XCommandEnvironment
 {
    /** Constructor.

        @param InteractionHandler the interaction handler instance that will be
                                  returned by this service's implementation of
                                  <method>XCommandEnvironemt::getInteractionHandler</method>

        @param ProgressHandler    the progress handler instance that will be
                                  returned by this service's implementation of
                                  <method>XCommandEnvironemt::getProgressHandler</method>
    */
     create( [in] com::sun::star::task::XInteractionHandler InteractionHandler,
             [in] com::sun::star::ucb::XProgressHandler ProgressHandler );
 };

};};};};

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
