/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_ucb_FetchError_idl__
#define __com_sun_star_ucb_FetchError_idl__


module com { module sun { module star { module ucb {

/** These values are used to specify whether and which error has occurred
    while fetching data of some ContentResultSet rows.

    @see FetchResult
*/
published constants FetchError
{
    /** indicates that fetching of data was successful.
    */
    const short SUCCESS = 0;

    /** indicates that during fetching we went beyond the last or first row.

        <p>Therefore the FetchResult does not contain the full
        count of demanded rows, but the maximum possible count must be
        contained.
    */
    const short ENDOFDATA = 1;

    /** indicates that during fetching we got an exception.

        <p>The row, that causes the exception, and all following ( "following"
        in read order! ) rows are not contained in the FetchResult.
        Therefore the FetchResult does not contain the full count
        of demanded rows. But all properly read rows so far must be contained.
    */
    const short EXCEPTION = 2;
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
