/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_ucb_RemoteAccessContentProvider_idl__
#define __com_sun_star_ucb_RemoteAccessContentProvider_idl__

#include <com/sun/star/ucb/ContentProvider.idl>
#include <com/sun/star/ucb/XParameterizedContentProvider.idl>


module com { module sun { module star { module ucb {

/** A <type>RemoteAccessContentProvider</type> is a
    <type>ContentProvider</type> that provides access to contents available at
    other (remote) UCBs.
*/
published service RemoteAccessContentProvider
{
    /** A <type>RemoteAccessContentProvider</type> is a specialized
        <type>ContentProvider</type>.
     */
    service com::sun::star::ucb::ContentProvider;

    /** allows configuration of the <type>RemoteAccessContentProvider</type>,
        to specify that certain <type>XContentIdentifier</type>s map to
        <type>XContent</type>s from a certain remote UCB.  The Arguments
        string in the
        <member>XParameterizedContentProvider::registerInstance</member>
        call must contain the UNO URL of the remote UCB.

        @descr
        The <type>XContentProvider</type>s obtained through this interface
        implement the service <type>ContentProvider</type> and, if
        appropriate, also the interface <type>XFileIdentifierConverter</type>.
     */
    interface com::sun::star::ucb::XParameterizedContentProvider;
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
