/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_ucb_RuleOperator_idl__
#define __com_sun_star_ucb_RuleOperator_idl__



module com { module sun { module star { module ucb {

/** These are the possible values for RuleTerm::RuleOperator.

    @see RuleSet
    @see Rule
*/
published constants RuleOperator
{
    /** "Contains" - Object contains RuleTerm::Operand.
    */
    const short CONTAINS = 1;

    /** "ContainsNot" - Object does not contain
        RuleTerm::Operand.
    */
    const short CONTAINSNOT = 2;

    /** "GreaterEqual" - Object is greater than or equal to
        RuleTerm::Operand.
    */
    const short GREATEREQUAL = 3;

    /** "LessEqual" - Object is less than or equal to
        RuleTerm::Operand.
    */
    const short LESSEQUAL = 4;

    /** "Equal" - Object is equal to RuleTerm::Operand.
    */
    const short EQUAL = 5;

    /** "NotEqual" - Object is not equal to RuleTerm::Operand.
    */
    const short NOTEQUAL = 6;

    /** "True" - Object has the value `TRUE`.
    */
    const short VALUE_TRUE = 7;

    /** "False" - Object has the value `FALSE`.
    */
    const short VALUE_FALSE = 8;

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
