/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_ucb_XAnyCompare_idl__
#define __com_sun_star_ucb_XAnyCompare_idl__

#include <com/sun/star/uno/XInterface.idl>


module com { module sun { module star { module ucb {

/** compares two `any`s.
*/

published interface XAnyCompare: com::sun::star::uno::XInterface
{
    /** allows comparison of two `any`s.

        @param Any1
        is the first compare value

        @param Any2
        is the second compare value

        @returns
        <ul>
        <li>
        <code>-1</code>, if the first any is less than the second ( Any1 &lt; Any2 )
        </li>
        <li>
        <code>0</code>, if the first any is equal to the second ( Any1 == Any2 )
        </li>
        <li>
        <code>+1</code>, if the first any is greater than the second ( Any1 &gt; Any2 )
        </li>
        </ul>
    */

    short   compare( [in] any Any1, [in] any Any2 );
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
