/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XContentIdentifier.idl,v $
 *
 *  $Revision: 1.7 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 08:03:25 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_ucb_XContentIdentifier_idl__
#define __com_sun_star_ucb_XContentIdentifier_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif


//=============================================================================

module com { module sun { module star { module ucb {

//=============================================================================
/** An identifier for contents.

     @version  1.0
     @author   Kai Sommerfeld
     @see      XContent
*/
published interface XContentIdentifier: com::sun::star::uno::XInterface
{
    //-------------------------------------------------------------------------
    /** returns the content identifier string.

        @returns
        the content identifier string. This must be a valid URI
        (Uniform Resource Identifier, see RFC 2396). This string
        is required. If a content provider 'implements' some
        existent URI scheme (e.g., a content provider offering
        access to a file system would implement the 'file' scheme,
        and a content provider offering access to IMAP servers
        would implement the 'imap' scheme), the content identifier
        strings should use that scheme. If on the other hand a
        content provider offers access to content for which no
        appropriate URI scheme exists, a vendor-specific URL scheme
        starting with 'vnd.' must be created (see the Internet Draft
        draft-king-vnd-urlscheme-00.txt).
    */
    string getContentIdentifier();

    //-------------------------------------------------------------------------
    /** returns the content provider scheme string.

          <p>This string will   be calculated from the content identifier string
        and must be lower-cased(!). It is the 'scheme' the content provider is
        registered for. In example, a provider for FTP contents will use
        ftp-URL's as content identifiers. The content provider scheme for all
        contents provided by that provider will be "ftp".
        </p>

        @returns
        the content provider scheme string.
    */
    string getContentProviderScheme();

};

//=============================================================================

}; }; }; };

#endif
