/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_ucb_XContentIdentifier_idl__
#define __com_sun_star_ucb_XContentIdentifier_idl__

#include <com/sun/star/uno/XInterface.idl>



module com { module sun { module star { module ucb {

/** An identifier for contents.

     @version  1.0
     @author   Kai Sommerfeld
     @see      XContent
*/
published interface XContentIdentifier: com::sun::star::uno::XInterface
{
    /** returns the content identifier string.

        @returns
        the content identifier string. This must be a valid URI
        (Uniform Resource Identifier, see RFC 2396). This string
        is required. If a content provider "implements" some
        existent URI scheme (e.g., a content provider offering
        access to a file system would implement the "file" scheme,
        and a content provider offering access to IMAP servers
        would implement the "imap" scheme), the content identifier
        strings should use that scheme. If on the other hand a
        content provider offers access to content for which no
        appropriate URI scheme exists, a vendor-specific URL scheme
        starting with "vnd." must be created (see the Internet Draft
        draft-king-vnd-urlscheme-00.txt).
    */
    string getContentIdentifier();

    /** returns the content provider scheme string.

          <p>This string will   be calculated from the content identifier string
        and must be lower-cased(!). It is the "scheme" the content provider is
        registered for. In example, a provider for FTP contents will use
        ftp-URLs as content identifiers. The content provider scheme for all
        contents provided by that provider will be "ftp".
        </p>

        @returns
        the content provider scheme string.
    */
    string getContentProviderScheme();

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
