/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XSimpleFileAccess2.idl,v $
 *
 *  $Revision: 1.5 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 08:15:26 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/

#ifndef __com_sun_star_ucb_XSimpleFileAccess2_idl__
#define __com_sun_star_ucb_XSimpleFileAccess2_idl__

#ifndef __com_sun_star_ucb_XSimpleFileAccess_idl__
#include <com/sun/star/ucb/XSimpleFileAccess.idl>
#endif

#ifndef __com_sun_star_io_XInputStream_idl__
#include <com/sun/star/io/XInputStream.idl>
#endif

#ifndef __com_sun_star_uno_Exception_idl__
#include <com/sun/star/uno/Exception.idl>
#endif

//=============================================================================

module com { module sun { module star { module ucb {

//=============================================================================
/** This is an extension to the interface <type>XSimpleFileAccess</type>.
*/
published interface XSimpleFileAccess2 : com::sun::star::ucb::XSimpleFileAccess
{

    //-------------------------------------------------------------------------
    /** Overwrites the file content with the given data.

        <p>If the file does not exist, it will be created.

        @param FileURL
        File to write

        @param data
        A stream containing the data for the file to be (over-)written
    */
    void writeFile( [in] string FileURL,
                    [in] com::sun::star::io::XInputStream data )
        raises( com::sun::star::uno::Exception );

};

//=============================================================================

}; }; }; };

#endif
