/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_formula_SymbolDescriptor_idl__
#define __com_sun_star_formula_SymbolDescriptor_idl__


 module com {  module sun {  module star {  module formula {

/** @deprecated draft
    - nWeight should be changed to float as in FontWeight.idl
    - nItalic probably needs to have FontItalic extended by the two
      extra defines REVERSE_* listed in FontSlant.idl
    - nCharSet should have the CharSet.idl extended by the new defines
      from rtl/textenc.h
*/
published struct SymbolDescriptor
{
    /** The name of the symbol.
    */
    string sName;

    /** The export name of the symbol.
    */
    string sExportName;

    /** Specifies the name of the symbol set to which this symbol belongs.
    */
    string sSymbolSet;

    /** Specifies the Unicode character of the symbol.
    */
    long nCharacter;

    /** Specifies the exact name of the font ("Arial", "Courier", etc.).
    */
    string sFontName;

    /** Specifies the character set which is supported by the font.

        @see   com::sun::star::awt::CharSet
    */
    short nCharSet;

    /** Specifies the general style of the font.

        @see   com::sun::star::awt::FontFamily
    */
    short nFamily;

    /** Specifies the pitch of the font.

        @see   com::sun::star::awt::FontPitch
    */
    short nPitch;

    /** Specifies the thickness of the line.

        @see   com::sun::star::awt::FontWeight

        The allowed integer values correspond as follows:
        0 : com::sun::star::awt::FontWeight::DONTKNOW
        1 : com::sun::star::awt::FontWeight::THIN
        2 : com::sun::star::awt::FontWeight::ULTRALIGHT
        3 : com::sun::star::awt::FontWeight::LIGHT
        4 : com::sun::star::awt::FontWeight::SEMILIGHT
        5 : com::sun::star::awt::FontWeight::NORMAL
        7 : com::sun::star::awt::FontWeight::SEMIBOLD
        8 : com::sun::star::awt::FontWeight::BOLD
        9 : com::sun::star::awt::FontWeight::ULTRABOLD
        10 : com::sun::star::awt::FontWeight::BLACK

    */
    short nWeight;

    /** Specifies if the font is italic.

        @see   com::sun::star::awt::FontSlant

        The values
        com::sun::star::awt::FontSlant::REVERSE_OBLIQUE and
        com::sun::star::awt::FontSlant::REVERSE_ITALIC
        may not be used.
    */
    short nItalic;
};
}; }; }; };
#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
