/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XDispatchHelper.idl,v $
 *
 *  $Revision: 1.7 $
 *
 *  last change: $Author: rt $ $Date: 2005-12-14 13:21:31 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_frame_XDispatchHelper_idl__
#define __com_sun_star_frame_XDispatchHelper_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __com_sun_star_frame_XDispatchProvider_idl__
#include <com/sun/star/frame/XDispatchProvider.idl>
#endif

#ifndef __com_sun_star_beans_PropertyValue_idl__
#include <com/sun/star/beans/PropertyValue.idl>
#endif

//=============================================================================

 module com {  module sun {  module star {  module frame {

//=============================================================================
/** provides an easy way to dispatch functions useful at UI level.

    @see XDispatch

    @since OOo 1.1.2
 */
published interface XDispatchHelper : com::sun::star::uno::XInterface
{
    //-------------------------------------------------------------------------
        /** executes the dispatch.

        Listeners are not supported here!

        @param DispatchProvider
             points to the provider, which should be asked for valid dispatch objects

        @param URL
            describes the feature which should be supported by internally used dispatch object

        @param TargetFrameName
            specifies the frame which should be the target for this request

        @param SearchFlags
            optional search parameter for finding the frame if no special
            <var>TargetFrameName</var> was used

        @param Arguments
            optional arguments for this request
            They depend on the real implementation of the dispatch object.

        @return
            A possible result of the executed internal dispatch.
            The information behind this <atom>any</atom> depends on the dispatch!

        @see XDispatch::dispatch()
        */

        any executeDispatch(
                [in] XDispatchProvider DispatchProvider,
                [in] string URL,
                [in] string TargetFrameName,
                [in] long SearchFlags,
                [in] sequence< com::sun::star::beans::PropertyValue > Arguments );
};

//=============================================================================

}; }; }; };

#endif
