/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/



#ifndef __com_sun_star_frame_XInplaceLayout_idl__
#define __com_sun_star_frame_XInplaceLayout_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

//=============================================================================

module com { module sun { module star { module frame {

//=============================================================================

/** special interface to support inplace editing of components inside
    OpenOffice.org.

    @deprecated

    @since OpenOffice 2.0
*/

interface XInplaceLayout : com::sun::star::uno::XInterface
{
    /** sets an inplace menu to the container window of the attached frame.

        @param InplaceMenuBarPointer
            must be a VCL menu bar pointer which is accessible within the
            layout manager process.
    */
    void setInplaceMenuBar( [in] hyper InplaceMenuBarPointer );

    /** removes an inplace menu and sets back a previously created menu bar if one
        has been set before.
    */
    void resetInplaceMenuBar();
};

}; }; }; };

#endif
