/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XStorable2.idl,v $
 *
 *  $Revision: 1.3 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 01:26:53 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_frame_XStorable2_idl__
#define __com_sun_star_frame_XStorable2_idl__

#ifndef __com_sun_star_frame_XStorable_idl__
#include <com/sun/star/frame/XStorable.idl>
#endif

#ifndef __com_sun_star_lang_IllegalArgumentException_idl__
#include <com/sun/star/lang/IllegalArgumentException.idl>
#endif

#ifndef __com_sun_star_io_IOException_idl__
#include <com/sun/star/io/IOException.idl>
#endif

#ifndef __com_sun_star_beans_PropertyValue_idl__
#include <com/sun/star/beans/PropertyValue.idl>
#endif


//=============================================================================

 module com {  module sun {  module star {  module frame {

//=============================================================================
/** extends <type>XStorable</type>.
 */
published interface XStorable2: XStorable
{
    /** stores the data to the URL from which it was loaded.

        <p>
            Only objects which know their locations can be stored.
        </p>

        <p>
            This is an extention of the <method>XStorable::store()</method>.
            This method allows to specify some additional parametes for
            storing process.
        </p>

        @param lArguments
            optional parameters for saving, can take values from subset of
            <type scope="com::sun::star::document">MediaDescriptor</type>

        @thrown ::com::sun::star::lang::IllegalArgumentException
            the optional parameters contain unacceptable for save entry

        @throws com::sun::star::io::IOException
            if an IO error occured during save operation

        @see XStorable::store
     */
    void storeSelf(
        [in] sequence<com::sun::star::beans::PropertyValue> lArguments )
            raises( com::sun::star::lang::IllegalArgumentException,
                    com::sun::star::io::IOException );

};

//=============================================================================

}; }; }; };

#endif

