/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_frame_XSynchronousDispatch_idl__
#define __com_sun_star_frame_XSynchronousDispatch_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __com_sun_star_util_URL_idl__
#include <com/sun/star/util/URL.idl>
#endif

#ifndef __com_sun_star_beans_PropertyValue_idl__
#include <com/sun/star/beans/PropertyValue.idl>
#endif

//=============================================================================

module com {  module sun {  module star {  module frame {

//=============================================================================
/** additional interfaces for dispatch objects: allow to execute with return value
    @since OpenOffice 2.0
    @see XDispatch
 */
published interface XSynchronousDispatch: com::sun::star::uno::XInterface
{
    //-------------------------------------------------------------------------
    /** dispatches a URL synchronously and offers a return values

        <p>
        After getting a dispatch object as a result of a queryDispatch call, this interface can
        be used to dispatch the URL synchronously and with a return value.
        </p>

        @param URL
            full parsed URL wich describe the feature which should be dispatched (executed)

        @param Arguments
            optional arguments for this request
            They depend on the real implementation of the dispatch object.
     */
     any dispatchWithReturnValue(
        [in] com::sun::star::util::URL URL,
        [in] sequence<com::sun::star::beans::PropertyValue> Arguments);
};

//=============================================================================

}; }; }; };

#endif
