/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __ooo_vba_adodb_EventReasonEnum_idl__
#define __ooo_vba_adodb_EventReasonEnum_idl__

module ooo { module vba { module adodb {
    constants EventReasonEnum {
        const long adRsnAddNew = 1;
        const long adRsnClose = 9;
        const long adRsnDelete = 2;
        const long adRsnFirstChange = 11;
        const long adRsnMove = 10;
        const long adRsnMoveFirst = 12;
        const long adRsnMoveLast = 15;
        const long adRsnMoveNext = 13;
        const long adRsnMovePrevious = 14;
        const long adRsnRequery = 7;
        const long adRsnResynch = 8;
        const long adRsnUndoAddNew = 5;
        const long adRsnUndoDelete = 6;
        const long adRsnUndoUpdate = 4;
        const long adRsnUpdate = 3;
    };
}; }; };

#endif
