/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
module ooo { module vba { module adodb {
    constants ResyncEnum {
        const long adResyncAllValues = 2;
        const long adResyncUnderlyingValues = 1;
    };
}; }; };

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
