/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_text_textfield_docinfo_Custom_idl__
#define __com_sun_star_text_textfield_docinfo_Custom_idl_

#include <com/sun/star/text/TextField.idl>


module com { module sun { module star {
    module text { module textfield { module docinfo {

/** specifies service of a text field that refers to the content of a
    user-defined field in the document information.

    @since OOo 3.0

    @see com::sun::star::text::TextField
*/
published service Custom
{
    service  com::sun::star::text::TextField;

    /** the name of the user-defined property that this field refers to.
     */
    [property] string Name;

    /** contains the current content of the text field.
        <p>This property is useful for import/export purposes.</p>
     */
    [property] string CurrentPresentation;

    /** If this flag is set to `FALSE`, the content is updated when
        the document information changes.
     */
    [property] boolean IsFixed;
};


}; }; }; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
