/*************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Copyright 2008 by Sun Microsystems, Inc.
 *
 * OpenOffice.org - a multi-platform office productivity suite
 *
 * $RCSfile: XAcceptor.idl,v $
 * $Revision: 1.13 $
 *
 * This file is part of OpenOffice.org.
 *
 * OpenOffice.org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License version 3
 * only, as published by the Free Software Foundation.
 *
 * OpenOffice.org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License version 3 for more details
 * (a copy is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3 along with OpenOffice.org.  If not, see
 * <http://www.openoffice.org/license.html>
 * for a copy of the LGPLv3 License.
 *
 ************************************************************************/
#ifndef _COM_SUN_STAR_CONNECTION_XACCEPTOR_IDL_
#define _COM_SUN_STAR_CONNECTION_XACCEPTOR_IDL_

#include <com/sun/star/connection/ConnectionSetupException.idl>
#include <com/sun/star/connection/AlreadyAcceptingException.idl>
#include <com/sun/star/lang/IllegalArgumentException.idl>
#include <com/sun/star/connection/XConnection.idl>


module com {  module sun {  module star {  module connection {

/** allows to passively accept connection attempts from other processes.

    <p>
    This is the counterpart to the XConnector interface.
 */
published interface XAcceptor: com::sun::star::uno::XInterface
{
    // DocMerge from xml: method com::sun::star::connection::XAcceptor::accept
    /** accepts an interprocess connection. Waits until someone connects to the resource.
        <p>
        After a successful return, the method may be called again to accept
        further connections, but the parameter string MUST be left unchanged.


       @param sConnectionDescription
                contains the kind of the connection plus a
              comma seperated list of attributes,
               e.g., <em>socket,host=localhost,port=2345</em> for a tcpip connection.

       @return null reference,
            stopAccepting was called.
            Otherwise a valid XConnection reference.

       @throws AlreadyAcceptingException
                Only one acceptor-thread per instance allowed.
       @throws ConnectionSetupException
            Problems during setting up the acceptor.
          (e.g., Security-reasons, socket already busy, etc.)
       @throws com::sun::star::lang::IllegalArgumentException
                  sConnectionDescription could not be interpreted

     */
    XConnection accept( [in] string sConnectionDescription )
        raises( AlreadyAcceptingException,
                ConnectionSetupException,
                com::sun::star::lang::IllegalArgumentException);


    /** pushes acceptor out of the accept-call.
     */
    void stopAccepting();
};

};};};};

#endif
