/*************************************************************************
 *
 *  $RCSfile: PropertyStateChangeEvent.idl,v $
 *
 *  $Revision: 1.4 $
 *
 *  last change: $Author: mi $ $Date: 2000-11-08 12:28:20 $
 *
 *  The Contents of this file are made available subject to the terms of
 *  either of the following licenses
 *
 *         - GNU Lesser General Public License Version 2.1
 *         - Sun Industry Standards Source License Version 1.1
 *
 *  Sun Microsystems Inc., October, 2000
 *
 *  GNU Lesser General Public License Version 2.1
 *  =============================================
 *  Copyright 2000 by Sun Microsystems, Inc.
 *  901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License version 2.1, as published by the Free Software Foundation.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *  MA  02111-1307  USA
 *
 *
 *  Sun Industry Standards Source License Version 1.1
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.1 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://www.openoffice.org/license.html.
 *
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 *
 *  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 *
 *  Copyright: 2000 by Sun Microsystems, Inc.
 *
 *  All Rights Reserved.
 *
 *  Contributor(s): _______________________________________
 *
 *
 ************************************************************************/
#ifndef __com_sun_star_beans_PropertyStateChangeEvent_idl__
#define __com_sun_star_beans_PropertyStateChangeEvent_idl__

#ifndef __com_sun_star_lang_EventObject_idl__
#include <com/sun/star/lang/EventObject.idl>
#endif

#ifndef __com_sun_star_beans_PropertyState_idl__
#include <com/sun/star/beans/PropertyState.idl>
#endif


//=============================================================================

 module com {  module sun {  module star {  module beans {

//=============================================================================

// DocMerge from xml: struct com::sun::star::beans::PropertyStateChangeEvent
/** gets delivered whenever the state of a "bound" property is changed.



    <p>It is sent as an argument to the method of
    <type>XPropertyStateChangeListener</type>.

    </p>
    <p>Normally these events are accompanied by the name and the old
    and new values of the changed property.

    </p>
    <p>Void values may be provided for the old and new values if their
    true values are not known.</p>
 */
struct PropertyStateChangeEvent: com::sun::star::lang::EventObject
{
    //-------------------------------------------------------------------------

    // DocMerge from xml: field com::sun::star::beans::PropertyStateChangeEvent::PropertyName
    /** specifies the name of the property which changes its value.



        <p>This name identifies the property uniquely within an
        <type>XPropertySet</type>.</p>
     */
    string PropertyName;

    //-------------------------------------------------------------------------

    // DocMerge from xml: field com::sun::star::beans::PropertyStateChangeEvent::PropertyHandle
    /** contains the implementation handle for the property.



        <p>It may be -1 if the implementation has no handle. You can use this
        handle to get values from the <type>XFastPropertySet</type>
        interface.</p>
     */
    long PropertyHandle;

    //-------------------------------------------------------------------------

    // DocMerge from xml: field com::sun::star::beans::PropertyStateChangeEvent::OldValue
    /** contains the old value of the property.
     */
    com::sun::star::beans::PropertyState OldValue;

    //-------------------------------------------------------------------------

    // DocMerge from xml: field com::sun::star::beans::PropertyStateChangeEvent::NewValue
    /** contains the new value of the property.
     */
    com::sun::star::beans::PropertyState NewValue;

};

//=============================================================================

}; }; }; };

/*=============================================================================

    $Log: not supported by cvs2svn $
    Revision 1.1.1.1  2000/09/18 23:34:56  hjs
    initial import

    Revision 1.5  2000/09/11 11:52:11  mi
    documentation merged from XML

    Revision 1.3  2000/03/09 10:15:44  mi
    #70728# missing documentation

    Revision 1.2  2000/02/07 11:24:18  mi
    zu #70728# missing documentation marked

    Revision 1.1.1.1  1999/11/11 09:48:40  jsc
    new


=============================================================================*/
#endif
