/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_beans_XHierarchicalPropertySetInfo_idl__
#define __com_sun_star_beans_XHierarchicalPropertySetInfo_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __com_sun_star_beans_Property_idl__
#include <com/sun/star/beans/Property.idl>
#endif

#ifndef __com_sun_star_beans_UnknownPropertyException_idl__
#include <com/sun/star/beans/UnknownPropertyException.idl>
#endif

#ifndef __com_sun_star_lang_IllegalArgumentException_idl__
#include <com/sun/star/lang/IllegalArgumentException.idl>
#endif


//=============================================================================

module com {  module sun {  module star {  module beans {

//=============================================================================

/** specifies a hierarchy of properties.

    <p>The specification only describes the properties, it does not contain
    any values.</p>
 */
published interface XHierarchicalPropertySetInfo: com::sun::star::uno::XInterface
{
    //-------------------------------------------------------------------------

    /** @returns
                the property with the specified name from the hierarchy.

        @param aHierarchicalName
                specifies the nested name of the property.

        @throws UnknownPropertyException
                if the property does not exist.

        @throws com::sun::star::lang::IllegalArgumentException
                if <var>aHierarchicalName</var> is not a well-formed
                nested name for this hierarchy.
                   An implementation is not required to detect this
                condition.

     */
    com::sun::star::beans::Property getPropertyByHierarchicalName( [in] string aHierarchicalName )
            raises( com::sun::star::beans::UnknownPropertyException );

    //-------------------------------------------------------------------------

    /** @returns
                <TRUE/> if a property with the specified name exists;
                otherwise <FALSE/> is returned.

        @param  aHierarchicalName
                specifies the name of the property.

        @throws com::sun::star::lang::IllegalArgumentException
                if <var>aHierarchicalName</var> is not a well-formed
                nested name for this hierarchy.
                   An implementation is not required to detect this
                condition.
     */
    boolean hasPropertyByHierarchicalName( [in] string aHierarchicalName );

};

//=============================================================================

}; }; }; };

#endif
