/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XVetoableChangeListener.idl,v $
 *
 *  $Revision: 1.10 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-09 14:58:37 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_beans_XVetoableChangeListener_idl__
#define __com_sun_star_beans_XVetoableChangeListener_idl__

#ifndef __com_sun_star_lang_XEventListener_idl__
#include <com/sun/star/lang/XEventListener.idl>
#endif

#ifndef __com_sun_star_beans_PropertyChangeEvent_idl__
#include <com/sun/star/beans/PropertyChangeEvent.idl>
#endif

#ifndef __com_sun_star_beans_PropertyVetoException_idl__
#include <com/sun/star/beans/PropertyVetoException.idl>
#endif


//=============================================================================

module com {  module sun {  module star {  module beans {

//=============================================================================

/** is used to receive <type>PropertyChangeEvent</type>s
    whenever a "constrained" property is changed.

    <p>You can register an <type>XVetoableChangeListener</type> with
    a source object so as to be notified of any constrained property updates.</p>
 */
published interface XVetoableChangeListener: com::sun::star::lang::XEventListener
{
    //-------------------------------------------------------------------------

    /** gets called when a constrained property is changed.
     */
    void vetoableChange( [in] com::sun::star::beans::PropertyChangeEvent aEvent )
            raises( com::sun::star::beans::PropertyVetoException );

};

//=============================================================================

}; }; }; };

#endif
