/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: GalleryThemeProvider.idl,v $
 *
 *  $Revision: 1.3 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 01:33:29 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/

#ifndef __com_sun_star_gallery_GalleryThemeProvider_idl__
#define __com_sun_star_gallery_GalleryThemeProvider_idl__

#ifndef __com_sun_star_gallery_XGalleryThemeProvider_idl__
#include <com/sun/star/gallery/XGalleryThemeProvider.idl>
#endif
#ifndef __com_sun_star_lang_XInitialization_idl__
#include <com/sun/star/lang/XInitialization.idl>
#endif

//=============================================================================

module com {  module sun {  module star {  module gallery {

//=============================================================================

/** provides access to a container of <type>GalleryTheme</type>s
    and makes it possible for you to manipulate them.

    @see XGalleryThemeProvider
 */
service GalleryThemeProvider
{
    /** lets you access and create <type>GalleryTheme</type>s
     */
    interface com::sun::star::gallery::XGalleryThemeProvider;

    /** allows initializing the provider
        <p>You do not need to call the initialize method directly, instead you may use the createInstanceWithArguments
        method of your <type scope="com::sun::star::lang">XMultiServiceFactory</type>.</p>

        <p>You specify a parameter by passing one (or more)
        <type scope="com::sun::star::beans">PropertyValue</type>
        object(s) to the initialize method, where the <em>Name</em> field contains a string describing which aspect
        you want to affect, and the <em>Value</em> field containing a value.</p>

        <p>Currently, there are no public properties available</p>
    */
    interface com::sun::star::lang::XInitialization;
};

//=============================================================================

}; }; }; };

#endif
