/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: LayerParser.idl,v $
 *
 *  $Revision: 1.5 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-07 22:44:20 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_configuration_backend_xml_LayerParser_idl__
#define __com_sun_star_configuration_backend_xml_LayerParser_idl__

#ifndef __com_sun_star_configuration_backend_XLayer_idl__
#include <com/sun/star/configuration/backend/XLayer.idl>
#endif

#ifndef __com_sun_star_io_XActiveDataSink_idl__
#include <com/sun/star/io/XActiveDataSink.idl>
#endif

#ifndef __com_sun_star_lang_XInitialization_idl__
#include <com/sun/star/lang/XInitialization.idl>
#endif

//=============================================================================

module com { module sun { module star { module configuration { module backend {
module xml {

//=============================================================================

/**
    represents a configuration data layer that is stored in a stream in
    OOR Update XML format.

    <p> The configuration layer xml from a given stream is parsed and fed to a
    <type scope="com::sun::star::configuration::backend">XLayerHandler</type>.
    </p>

    @see com::sun::star::configuration::backend::xml::SchemaParser
        Service that represents a configuration schema stored in xml.

    @see com::sun::star::configuration::backend::xml::LayerWriter
        Service that writes OOR Update XML for data described via
        <type scope="com::sun::star::configuration::backend">XLayerHandler</type>.

    @since OOo 1.1.2
*/
published service LayerParser
{
    //-------------------------------------------------------------------------

    /** provides access to the parsed layer data.
      */
    interface com::sun::star::configuration::backend::XLayer ;

    //-------------------------------------------------------------------------

    /** provides access to the source xml stream.
      */
    interface com::sun::star::io::XActiveDataSink ;

    //-------------------------------------------------------------------------

    /** allows initializing the source stream.

        <p> The source can be passed
            as a <type scope="com::sun::star::io">XInputStream</type> or
            as a <type scope="com::sun::star::xml::sax">InputSource</type>.
        </p>
      */
    interface com::sun::star::lang::XInitialization ;

    //-------------------------------------------------------------------------
} ;

//=============================================================================
} ;
} ; } ; } ; } ; } ;

#endif
