/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XSystemShellExecute.idl,v $
 *
 *  $Revision: 1.7 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 05:42:41 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/

#ifndef __com_sun_star_system_XSystemShellExecute_idl__
#define __com_sun_star_system_XSystemShellExecute_idl__

#ifndef __com_sun_star_uno_RuntimeException_idl__
#include <com/sun/star/uno/RuntimeException.idl>
#endif

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __com_sun_star_lang_IllegalArgumentException_idl__
#include <com/sun/star/lang/IllegalArgumentException.idl>
#endif

#ifndef __com_sun_star_system_SystemShellExecuteException_idl__
#include <com/sun/star/system/SystemShellExecuteException.idl>
#endif

//=============================================================================

module com { module sun { module star { module system {

//=============================================================================
/** Specifies an interface for executing a system command.
*/


published interface XSystemShellExecute: com::sun::star::uno::XInterface
{
    //-------------------------------------------------------------------------
    /** Executes an abitrary system command.

        @param aCommand
        Specifies the command to execute. This may be an executable file or a
        document which is registered with an application on a specific platform,
        so that the platform knows what application to launch for that document.
        If the command specifies a path to an executable, etc, this has to be
        a system specific path.

        @param aParameter
        Specifies a list of space separated parameters. The method does not
        validate the given parameters, but only passes it as a parameter to the
        specified command.

        @param nFlags
        Specifies different flags to control the execution of this method, for example,
        avoid showing system error messages, in case of failures, etc.

        @throws com::sun::star::lang::IllegalArgumentException
        when the specified flags are wrong or exclude each other.
.
        @throws com::sun::star::sys::SystemExecuteException
        in the case of errors when trying to executed the specified command.

        @see com::sun::star::system::SystemShellExecuteFlags
    */
    void execute( [in] string aCommand, [in] string aParameter, [in] long nFlags )
        raises( ::com::sun::star::lang::IllegalArgumentException, ::com::sun::star::system::SystemShellExecuteException );
};

//=============================================================================

}; }; }; };

#endif

