/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __ooo_vba_dao_QueryDefTypeEnum_idl__
#define __ooo_vba_dao_QueryDefTypeEnum_idl__

module ooo { module vba { module dao {
    constants QueryDefTypeEnum {
        const long dbQAction = 240;
        const long dbQAppend = 64;
        const long dbQCompound = 160;
        const long dbQCrosstab = 16;
        const long dbQDDL = 96;
        const long dbQDelete = 32;
        const long dbQMakeTable = 80;
        const long dbQProcedure = 224;
        const long dbQSelect = 0;
        const long dbQSetOperation = 128;
        const long dbQSPTBulk = 144;
        const long dbQSQLPassThrough = 112;
        const long dbQUpdate = 48;
    };
}; }; };

#endif
