/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
module ooo { module vba { module excel {
    constants XlChartLocation {
        const long xlLocationAsNewSheet = 1;
        const long xlLocationAsObject = 2;
        const long xlLocationAutomatic = 3;
    };
}; }; };

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
