/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
module ooo { module vba { module excel {
    constants XlDirection {
        const long xlDown = -4121;
        const long xlToLeft = -4159;
        const long xlToRight = -4161;
        const long xlUp = -4162;
    };
}; }; };

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
