# vim: set noet sw=4 ts=4:
# -*- Mode: makefile-gmake; tab-width: 4; indent-tabs-mode: t -*-
#
# This file is part of the LibreOffice project.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

$(eval $(call gb_CustomTarget_CustomTarget,static/wasm_fs_image))

# WASM assumes the image has the same layout then instdir, so everything you want
# to include must be "installed" somewhere in it, as there is no mechanism to easily
# change paths or rename them (you could hack soffice.data.js.metadata).
# We make them relative paths as input for the file_packager.py!
gb_wasm_image_filelist := \
    $(call gb_UnoApi_get_target,offapi) \
    $(call gb_UnoApi_get_target,udkapi) \
    $(INSTROOT)/$(LIBO_ETC_FOLDER)/$(call gb_Helper_get_rcfile,bootstrap) \
    $(INSTROOT)/$(LIBO_ETC_FOLDER)/$(call gb_Helper_get_rcfile,fundamental) \
    $(INSTROOT)/$(LIBO_ETC_FOLDER)/$(call gb_Helper_get_rcfile,louno) \
    $(INSTROOT)/$(LIBO_ETC_FOLDER)/$(call gb_Helper_get_rcfile,setup) \
    $(INSTROOT)/$(LIBO_ETC_FOLDER)/$(call gb_Helper_get_rcfile,soffice) \
    $(INSTROOT)/$(LIBO_ETC_FOLDER)/$(call gb_Helper_get_rcfile,version) \
    $(INSTROOT)/$(LIBO_ETC_FOLDER)/services/services.rdb \
    $(INSTROOT)/$(LIBO_URE_ETC_FOLDER)/$(call gb_Helper_get_rcfile,uno) \
    $(INSTROOT)/$(LIBO_URE_MISC_FOLDER)/services.rdb \
    $(INSTROOT)/program/resource/common/fonts/opens___.ttf \
    $(INSTROOT)/program/shell/logo_inverted.svg \
    $(INSTROOT)/program/shell/logo-sc.svg \
    $(INSTROOT)/program/shell/logo-sc_inverted.svg \
    $(INSTROOT)/program/shell/logo.svg \
    $(INSTROOT)/program/shell/about.svg \
    $(INSTROOT)/program/types/offapi.rdb \
    $(INSTROOT)/program/types/oovbaapi.rdb \
    $(INSTROOT)/share/registry/cjk.xcd \
    $(INSTROOT)/share/registry/ctlseqcheck.xcd \
    $(INSTROOT)/share/registry/ctl.xcd \
    $(INSTROOT)/share/registry/graphicfilter.xcd \
    $(INSTROOT)/share/registry/Langpack-en-US.xcd \
    $(INSTROOT)/share/registry/lingucomponent.xcd \
    $(INSTROOT)/share/registry/main.xcd \
    $(INSTROOT)/share/registry/writer.xcd \
    $(INSTROOT)/share/registry/xsltfilter.xcd \
    $(INSTROOT)/share/registry/res/fcfg_langpack_en-US.xcd \
    $(INSTROOT)/share/registry/res/registry_en-US.xcd \
    $(INSTROOT)/program/intro-highres.png \
    $(INSTROOT)/program/intro.png \
    $(INSTROOT)/presets/autotext/mytexts.bau \
    $(INSTROOT)/presets/basic/Standard/Module1.xba \
    $(INSTROOT)/presets/basic/Standard/script.xlb \
    $(INSTROOT)/presets/basic/Standard/dialog.xlb \
    $(INSTROOT)/presets/basic/script.xlc \
    $(INSTROOT)/presets/basic/dialog.xlc \
    $(INSTROOT)/presets/config/autotbl.fmt \
    $(INSTROOT)/presets/gallery/sg30.thm \
    $(INSTROOT)/presets/gallery/sg30.sdv \
    $(INSTROOT)/share/config/wizard/form/styles/orange.css \
    $(INSTROOT)/share/config/wizard/form/styles/water.css \
    $(INSTROOT)/share/config/wizard/form/styles/dark.css \
    $(INSTROOT)/share/config/wizard/form/styles/beige.css \
    $(INSTROOT)/share/config/wizard/form/styles/violet.css \
    $(INSTROOT)/share/config/wizard/form/styles/grey.css \
    $(INSTROOT)/share/config/wizard/form/styles/ibg.css \
    $(INSTROOT)/share/config/wizard/form/styles/red.css \
    $(INSTROOT)/share/config/wizard/form/styles/bgr.css \
    $(INSTROOT)/share/config/wizard/form/styles/ice.css \
    $(INSTROOT)/share/config/soffice.cfg/fps/ui/explorerfiledialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/fps/ui/foldernamedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/fps/ui/breadcrumb.ui \
    $(INSTROOT)/share/config/soffice.cfg/fps/ui/remotefilesdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/desktop/ui/extensionmanager.ui \
    $(INSTROOT)/share/config/soffice.cfg/desktop/ui/extensionmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/desktop/ui/updateinstalldialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/desktop/ui/updatedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/desktop/ui/showlicensedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/desktop/ui/installforalldialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/desktop/ui/updaterequireddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/desktop/ui/dependenciesdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/desktop/ui/licensedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/screenshotparent.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/printerdevicepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/printprogressdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/querydialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/interimtearableparent.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/cupspassworddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/dockingwindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/printerpropertiesdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/menutogglebutton3.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/errornocontentdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/menutogglebutton4.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/errornoprinterdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/editmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/aboutbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/combobox.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/interimdockparent.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/wizard.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/printdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/vcl/ui/printerpaperpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/xmlsec/ui/certgeneral.ui \
    $(INSTROOT)/share/config/soffice.cfg/xmlsec/ui/securitytrustpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/xmlsec/ui/certdetails.ui \
    $(INSTROOT)/share/config/soffice.cfg/xmlsec/ui/viewcertdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/xmlsec/ui/selectcertificatedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/xmlsec/ui/digitalsignaturesdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/xmlsec/ui/macrosecuritydialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/xmlsec/ui/securitylevelpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/xmlsec/ui/certpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/uui/ui/simplenameclash.ui \
    $(INSTROOT)/share/config/soffice.cfg/uui/ui/sslwarndialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/uui/ui/password.ui \
    $(INSTROOT)/share/config/soffice.cfg/uui/ui/unknownauthdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/uui/ui/masterpassworddlg.ui \
    $(INSTROOT)/share/config/soffice.cfg/uui/ui/filterselect.ui \
    $(INSTROOT)/share/config/soffice.cfg/uui/ui/logindialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/uui/ui/setmasterpassworddlg.ui \
    $(INSTROOT)/share/config/soffice.cfg/uui/ui/authfallback.ui \
    $(INSTROOT)/share/config/soffice.cfg/uui/ui/macrowarnmedium.ui \
    $(INSTROOT)/share/config/soffice.cfg/formula/ui/parameter.ui \
    $(INSTROOT)/share/config/soffice.cfg/formula/ui/structpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/formula/ui/functionpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/formula/ui/formuladialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/editeng/ui/spellmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/writerperfect/ui/wpftencodingdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/writerperfect/ui/exportepub.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/paraulspacing.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/surfacewindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/tablewindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/fillctrlbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/sidebareffect.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/sidebartextpanel.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/colorwindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/colsmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/directionwindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/selectionmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/cellmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/classificationdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/passwd.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/rulermenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/sidebarempty.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/accessibilitycheckentry.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/addnamespacedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/adddataitemdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/sidebarstylespanel.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/xformspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/accessibilitycheckdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/querysavecontchangesdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/formfielddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/headfootformatpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/stylemenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/floatinglinestyle.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/deleteheaderdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/fontworkalignmentcontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/fontworkcharacterspacingcontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/formpropertydialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/querymodifyimagemapchangesdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/textcharacterspacingcontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/dockingcolorreplace.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/textcontrolparadialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/medialine.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/sidebarpossize.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/absrecbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/grafctrlbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/floatinglineend.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/gallerymenu2.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/querydeleteobjectdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/sidebarline.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/labelbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/paralinespacingcontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/floatingcontour.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/sidebarfontwork.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/numberingwindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/paralrspacing.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/sidebarshadow.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/queryunlinkgraphicsdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/charsetmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/toolbarpopover.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/mediaplayback.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/zoommenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/imapdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/rowsmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/depthwindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/currencywindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/floatingframeborder.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/savemodifieddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/sidebargallery.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/floatingareastyle.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/gallerymenu1.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/inspectortextpanel.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/lightingwindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/docking3deffects.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/textcontrolchardialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/checkbuttonbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/metricfieldbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/applystylebox.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/grafmodebox.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/sidebarparagraph.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/navigationbar.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/mediawindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/xmlsecstatmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/addmodeldialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/functionmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/formlinkwarndialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/imapmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/dockingcolorwindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/fontsizebox.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/stylespreview.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/formdatamenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/textunderlinecontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/asianphoneticguidedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/filtermenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/deletefooterdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/addsubmissiondialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/sidebargraphic.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/redlinecontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/addconditiondialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/linkwarndialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/fontnamebox.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/defaultshapespanel.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/fontworkspacingdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/acceptrejectchangesdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/filternavigator.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/sidebararea.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/docrecoverysavedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/dockingfontwork.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/docrecoverybrokendialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/docrecoveryprogressdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/floatinglineproperty.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/fontworkgallerydialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/compressgraphicdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/optgridpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/datanavigator.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/clipboardmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/formnavigator.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/sidebartextcolumnspanel.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/findbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/chineseconversiondialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/namespacedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/fileexporteddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/redlineviewpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/addinstancedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/querydeletethemedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/querydeletecontourdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/presetmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/extrustiondepthdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/querynewcontourdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/redlinefilterpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/safemodedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/sidebarlists.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/floatingundoredo.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/docrecoveryrecoverdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/columnswindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/findreplacedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/measurewidthbar.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/chinesedictionary.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/formnavimenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/crashreportdlg.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/findreplacedialog-mobile.ui \
    $(INSTROOT)/share/config/soffice.cfg/svx/ui/querysaveimagemapchangesdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/filter/ui/pdflinkspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/filter/ui/testxmlfilter.ui \
    $(INSTROOT)/share/config/soffice.cfg/filter/ui/xmlfiltertabpagetransformation.ui \
    $(INSTROOT)/share/config/soffice.cfg/filter/ui/pdfviewpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/filter/ui/pdfuserinterfacepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/filter/ui/pdfsecuritypage.ui \
    $(INSTROOT)/share/config/soffice.cfg/filter/ui/xmlfiltertabpagegeneral.ui \
    $(INSTROOT)/share/config/soffice.cfg/filter/ui/xsltfilterdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/filter/ui/xmlfiltersettings.ui \
    $(INSTROOT)/share/config/soffice.cfg/filter/ui/pdfgeneralpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/filter/ui/warnpdfdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/filter/ui/pdfoptionsdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/filter/ui/pdfsignpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/drawingobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/fullscreenbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/drawbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/standardbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/formsfilterbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/formcontrols.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/starshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/fontworkshapetype.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/calloutshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/flowchartshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/formtextobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/insertbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/textobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/arrowshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/mediaobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/viewerbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/drawtextobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/frameobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/graffilterbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/extrusionobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/fontworkobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/oleobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/optimizetablebar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/mailmerge.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/bezierobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/tableobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/colorbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/alignmentbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/formsnavigationbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/basicshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/numobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/toolbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/graphicobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/symbolshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/insertobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/formdesign.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/toolbar/previewobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/popupmenu/text.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/popupmenu/oleobject.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/popupmenu/table.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/popupmenu/draw.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/popupmenu/annotation.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/popupmenu/formrichtext.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/popupmenu/frame.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/popupmenu/form.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/popupmenu/preview.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/popupmenu/media.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/popupmenu/insertfield.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/popupmenu/drawtext.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/popupmenu/graphic.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/popupmenu/anchor.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/statusbar/statusbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swform/menubar/menubar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/drawingobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/fullscreenbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/drawbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/standardbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/formsfilterbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/formcontrols.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/starshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/fontworkshapetype.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/calloutshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/flowchartshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/formtextobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/insertbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/textobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/arrowshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/mediaobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/viewerbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/drawtextobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/frameobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/graffilterbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/extrusionobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/fontworkobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/oleobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/optimizetablebar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/findbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/bezierobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/tableobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/colorbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/textstylebar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/alignmentbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/formsnavigationbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/basicshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/numobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/toolbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/graphicobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/symbolshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/insertobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/formdesign.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/toolbar/previewobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/text.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/oleobject.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/table.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/draw.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/annotation.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/formrichtext.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/frame.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/form.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/preview.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/media.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/insertfield.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/drawtext.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/graphic.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/showtrackedchanges.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/popupmenu/anchor.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/statusbar/statusbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sglobal/menubar/menubar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/StartModule/menubar/menubar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/drawingobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/fullscreenbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/drawbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/standardbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/formsfilterbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/formcontrols.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/starshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/fontworkshapetype.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/calloutshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/flowchartshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/formtextobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/insertbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/textobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/arrowshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/mediaobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/viewerbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/drawtextobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/frameobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/graffilterbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/extrusionobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/fontworkobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/oleobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/optimizetablebar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/mailmerge.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/findbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/bezierobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/tableobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/colorbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/alignmentbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/formsnavigationbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/basicshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/numobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/toolbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/graphicobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/symbolshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/insertobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/formdesign.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/toolbar/previewobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/text.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/oleobject.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/table.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/draw.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/annotation.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/formrichtext.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/frame.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/form.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/preview.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/media.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/insertfield.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/drawtext.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/graphic.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/showtrackedchanges.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/popupmenu/anchor.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/statusbar/statusbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swxform/menubar/menubar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/drawingobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/fullscreenbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/drawbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/standardbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/formsfilterbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/formcontrols.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/starshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/fontworkshapetype.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/calloutshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/flowchartshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/formtextobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/insertbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/textobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/arrowshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/mediaobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/viewerbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/drawtextobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/frameobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/graffilterbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/extrusionobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/fontworkobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/oleobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/optimizetablebar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/mailmerge.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/bezierobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/tableobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/colorbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/alignmentbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/formsnavigationbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/basicshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/numobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/toolbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/graphicobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/symbolshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/insertobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/formdesign.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/toolbar/previewobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/text.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/oleobject.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/table.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/draw.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/annotation.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/formrichtext.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/frame.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/form.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/preview.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/media.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/insertfield.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/drawtext.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/graphic.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/showtrackedchanges.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/popupmenu/anchor.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/statusbar/statusbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swreport/menubar/menubar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/drawingobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/fullscreenbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/drawbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/standardbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/arrowsbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/formsfilterbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/formcontrols.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/starshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/fontworkshapetype.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/calloutshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/classificationbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/flowchartshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/formtextobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/insertbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/textobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/arrowshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/mediaobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/viewerbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/drawtextobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/frameobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/changes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/singlemode.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/graffilterbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/linesbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/extrusionobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/fontworkobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/oleobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/optimizetablebar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/mailmerge.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/findbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/bezierobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/tableobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/colorbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/textstylebar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/alignmentbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/formsnavigationbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/basicshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/numobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/toolbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/graphicobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/symbolshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/navigationobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/notebookbarshortcuts.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/formdesign.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/toolbar/previewobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mmoutputtypepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/optcompatpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/viewoptionspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/pageheaderpanel.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/zoombox.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/wrappage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/optformataidspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/footnoteareapage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/notebookbar_groupedbar_full.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/picturedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/tocstylespage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mmsendmails.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/fldrefpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/printeroptions.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/captionoptions.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/opttestpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/alreadyexistsdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/sectionpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/insertbreak.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/createautomarkdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/abstractdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/warnemaildialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/envaddresspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/frmaddpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/navigatorpanel.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/tocentriespage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/bibliofragment.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/savemonitordialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/insertdbcolumnsdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/frmtypepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mmlayoutpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/inputfielddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/toxentrywidget.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/navigatorcontextmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/framedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/floatingsync.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/addressfragment.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/warndatasourcedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/templatedialog16.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/cardmediumpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/findentrydialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mailmerge.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/asciifilterdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/footendnotedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/pageorientationcontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/unfloatbutton.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/comboboxfragment.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/charurlpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/inputeditbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/dropcapspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/dateformfielddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/pagecolumncontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/numparapage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/selectaddressdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/formdropdown.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/calendar.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/optfonttabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/readonlymenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/notebookbar_single.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/newuserindexdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/formattablepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/addentrydialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/pagestylespanel.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/sidebarwrap.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/assignstylesdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/tableproperties.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/datasourcesunavailabledialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/frmurlpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/selecttabledialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/wordcount-mobile.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/tocdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/fldfuncpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/optgeneralpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/pageformatpanel.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/objectdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/labelformatpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mailmergedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/querydefaultcompatdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/envprinterpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/editbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/printmergedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/saveashtmldialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/paradialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/bulletsandnumbering.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/pagefooterpanel.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/managechangessidebar.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/gotopagedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mmmailbody.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/annotation.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/subjectdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/templatedialog8.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/querysavelabeldialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/notebookbar_compact.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/poseditbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/tabletextflowpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/tokenwidget.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/pagemargincontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/createauthorentry.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/editsectiondialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/rowheight.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/assignfragment.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/testmailsettings.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/outlinepositionpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/numberingnamedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/inforeadonlydialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/inserttable.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/templatedialog4.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/printmonitordialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/cannotsavelabeldialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/converttexttable.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/insertautotextdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/asksearchdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/autoformattable.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/stringinput.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mastercontextmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/columndialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/characterproperties.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/outlinebutton.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/sortdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/autotext.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/privateuserpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/authenticationsettingsdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/flddocinfopage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/jumpposbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/indexentry.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/selectblockdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/bibliographyentry.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/opttablepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/tablecolumnpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/watermarkdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/selectindexdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/fldvarpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/spellmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/optcomparison.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/selectautotextdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/floatingnavigation.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/flddbpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/conditionpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/previewzoomdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/notebookbar_groups.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/optcaptionpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/toxbuttonwidget.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/sidebartheme.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/labeloptionspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/checkbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/bookmarkmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mmaddressblockpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/textgridpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/linenumbering.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/insertbookmark.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/notebookbar.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/dropdownfielddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/labeldialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mmcreatingdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/infonotfounddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/templatedialog1.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/notebookbar_groupedbar_compact.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/picturepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/insertcaption.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/outlinenumbering.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/wordcount.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/envdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/querycontinuebegindialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/formatsectiondialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/combobox.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/splittable.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/insertsectiondialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/printoptionspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/statisticsinfopage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/templatedialog2.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/fielddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/flddocumentpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/sidebarstylepresets.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/queryredlinedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/pagesizecontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/optredlinepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/customizeaddrlistdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mmresultprintdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/hfmenubutton.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/captiondialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mmselectpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/editcategories.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/querycontinueenddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/editfielddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/insertscript.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/columnwidth.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/envformatpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/createaddresslist.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/attachnamedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/tocindexpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/insertfootnote.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mmresultsavedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/renameentrydialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mergetabledialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/pbmenubutton.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mergeconnectdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/inputwinmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/pagestylemenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mailconfigpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/notebookbar_online.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/footnotesendnotestabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/ccdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/renameobjectdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/columnpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/queryrotateintostandarddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/tablepreviewdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mmresultemaildialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/businessdatapage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/renameautotextdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/outlinenumberingpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/savelabeldialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/indentpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/dropdownformfielddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/endnotepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/footnotepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/exchangedatabases.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/wrapdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/previewmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/sidebartableedit.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/assignfieldsdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/addressblockdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/mmsalutationpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/ui/titlepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/text.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/oleobject.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/table.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/draw.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/annotation.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/notebookbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/formrichtext.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/frame.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/form.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/preview.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/media.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/insertfield.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/drawtext.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/graphic.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/showtrackedchanges.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/popupmenu/anchor.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/statusbar/statusbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/menubar/mscompatibleformsmenu.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/swriter/menubar/menubar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/drawingobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/fullscreenbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/standardbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/formsfilterbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/formcontrols.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/starshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/fontworkshapetype.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/calloutshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/flowchartshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/formtextobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/insertbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/textobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/arrowshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/mediaobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/viewerbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/drawtextobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/frameobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/graffilterbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/extrusionobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/fontworkobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/oleobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/optimizetablebar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/findbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/bezierobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/tableobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/colorbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/formsnavigationbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/basicshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/numobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/toolbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/graphicobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/symbolshapes.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/formdesign.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/toolbar/previewobjectbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/popupmenu/source.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/popupmenu/text.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/popupmenu/oleobject.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/popupmenu/table.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/popupmenu/annotation.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/popupmenu/formrichtext.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/popupmenu/frame.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/popupmenu/form.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/popupmenu/preview.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/popupmenu/insertfield.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/popupmenu/graphic.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/popupmenu/showtrackedchanges.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/popupmenu/anchor.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/statusbar/statusbar.xml \
    $(INSTROOT)/share/config/soffice.cfg/modules/sweb/menubar/menubar.xml \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/querychangelineenddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/formatnumberdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/searchattrdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/newlibdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optfltrembedpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/pageformatpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/editdictionarydialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/connectortabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optionsdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/showcoldialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/hatchpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/borderareatransparencydialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/breaknumberoption.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/querydeletechartcolordialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/dimensionlinestabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/hangulhanjaconversiondialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/pickgraphicpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/hangulhanjaadddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/eventsconfigpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/acorexceptpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/formatcellsdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/movemenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optappearancepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/textanimtabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optfltrpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/querydeletelinestyledialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/wordcompletionpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/objectnamedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/linedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/screenshotannotationdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/opthtmlpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/paragalignpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/imagetabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/charnamepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/insertrowcolumn.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/graphictestentry.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optfontspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/macroassignpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/dbregisterpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optbasicidepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/pickoutlinepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/applylocalizedpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/swpossizepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/querydeletecolordialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/possizetabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/linetabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/galleryapplyprogress.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/galleryfilespage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/namedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/querydeletelineenddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/embossdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/additionsdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/paratabspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/smarttagoptionspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/acorreplacepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/fontfragment.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/autocorrectdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optctlpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/diagramdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/querydeletegradientdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/querydeletebitmapdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/chapterfragment.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/paraindentspacing.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/patterntabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/textflowpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/entrycontextmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/additionsfragment.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/aboutconfigvaluedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/agingdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/gallerygeneralpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/picknumberingpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optpathspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optgeneralpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/baselinksdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/pickbulletpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/gallerythemeiddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/spinbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/smoothdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/selectpathdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/hangulhanjaeditdictdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/newtabledialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/macroselectordialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/positionsizedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/recordnumberdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/numberingoptionspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/javaclasspathdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/password.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/querysavelistdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/pastespecial.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/linestyletabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/colorfragment.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/personalization_tab.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/similaritysearchdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/croppage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/galleryupdateprogress.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/colorpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/numberingpositionpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/transparencytabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optviewpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/databaselinkdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/queryduplicatedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/positionpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/multipathdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/calloutpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/gradientpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/hyperlinkdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/solarizedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/insertoleobject.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optnewdictionarydialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/aboutdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/iconselectordialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/hyperlinkmailpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/gallerysearchprogress.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/qrcodegen.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/hyperlinknewdocpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/splitcellsdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/imageviewer.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/javastartparametersdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optasianpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/gallerytitledialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/toolbarmodedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/editmodulesdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/hyperlinkmarkdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/objecttitledescdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/querynoloadedfiledialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/borderbackgrounddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/borderpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/gallerythemedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optsecuritypage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optchartcolorspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/menuassignpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/hangulhanjaoptdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/fontfeaturesdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/spelloptionsdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/scriptorganizer.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/iconchangedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/insertfloatingframe.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/querydeletehatchdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optproxypage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/certdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/numberingformatpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/hyperlinkinternetpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/eventassigndialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/shadowtabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optlanguagespage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optuserpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/comment.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/effectspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/specialcharacters.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/slantcornertabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/hyperlinkdocpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optonlineupdatepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/acoroptionspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optlingupage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/accelconfigpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/searchformatdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/thesaurus.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/textdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/rotationtabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optadvancedpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/storedwebconnectiondialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/percentdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/graphictestdlg.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/calloutdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/areatabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optaccessibilitypage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optemailpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/signatureline.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/signsignatureline.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/lineendstabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/fmsearchdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/textattrtabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/aboutconfigdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/connpooloptions.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/applyautofmtpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/customizedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/hyphenate.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/newtoolbardialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/cellalignment.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/textcolumnstabpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/bulletandposition.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/querydeletedictionarydialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/colorpickerdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/cuiimapdlg.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/macroassigndialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optjsearchpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/queryupdategalleryfilelistdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/querynosavefiledialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/twolinespage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/areadialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/mosaicdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/zoomdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/securityoptionsdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/tsaurldialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/asiantypography.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/assigncomponentdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/colorconfigwin.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/optsavepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/eventassignpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/spellingdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/cui/ui/posterdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/combocontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/tabbuttons.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/listcontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/subtoolbar.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/calendar.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/thineditcontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/placeedit.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/printersetupdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/emptypage.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/linewindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/inputbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/javadisableddialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/fixedtextcontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/tabbuttonsmirrored.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/interimparent.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/editcontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/managedtoolbar.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/tabbaredit.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/querydeletedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/datewindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/fileviewmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/addresstemplatedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/textviewcontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/graphicexport.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/restartdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/fixedimagecontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/checkboxcontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/svt/ui/spinfieldcontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/helpbookmarkpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/notebookbarpopup.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/tabbarcontents.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/panel.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/emojicontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/searchdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/stylecontextmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/custominfopage.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/documentfontspage.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/urlbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/safemodequerydialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/linefragment.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/tabbar.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/helpcontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/editdurationdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/securityinfopage.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/printeroptionsdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/navigator.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/autoredactdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/managestylepage.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/password.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/documentpropertiesdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/alienwarndialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/commandpopup.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/newstyle.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/addtargetdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/descriptioninfopage.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/documentinfopage.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/startcenter.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/linkeditdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/loadtemplatedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/versioncommentdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/cmisline.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/helpindexpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/bookmarkdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/singletabdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/deck.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/classificationbox.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/versionsofdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/infobar.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/checkin.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/devtoolsmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/bookmarkmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/charviewmenu.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/querysavedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/notebookbar.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/versionscmis.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/editdocumentdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/optprintpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/helpcontentpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/charmapcontrol.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/helpsearchpage.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/templatecategorydlg.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/helpmanual.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/inputdialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/licensedialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/templatedlg.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/developmenttool.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/errorfindemaildialog.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/helpwindow.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/saveastemplatedlg.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/cmisinfopage.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/tabbutton.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/extrabutton.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/templatepanel.ui \
    $(INSTROOT)/share/config/soffice.cfg/sfx/ui/floatingrecord.ui \
    $(INSTROOT)/share/config/images_breeze.zip \

wasm_fs_image_WORKDIR := $(call gb_CustomTarget_get_workdir,static/wasm_fs_image)

# we just need data.js.link at link time, which is equal to soffice.data.js
$(call gb_CustomTarget_get_target,static/wasm_fs_image): \
    $(wasm_fs_image_WORKDIR)/soffice.data \
    $(wasm_fs_image_WORKDIR)/soffice.data.js.link \
    $(wasm_fs_image_WORKDIR)/soffice.data.js.metadata \

$(wasm_fs_image_WORKDIR)/soffice.data $(wasm_fs_image_WORKDIR)/soffice.data.js : $(wasm_fs_image_WORKDIR)/soffice.data.js.metadata

$(wasm_fs_image_WORKDIR)/soffice.data.js.link: $(wasm_fs_image_WORKDIR)/soffice.data.js
	cp $^ $^.tmp
	$(call gb_Helper_replace_if_different_and_touch,$^.tmp,$@)

$(wasm_fs_image_WORKDIR)/soffice.data.filelist: $(gb_wasm_image_filelist) | $(wasm_fs_image_WORKDIR)/.dir
	TEMPFILE=$(call var2file,$(shell $(gb_MKTEMP)),1,$(subst $(BUILDDIR)/,,$^)) && \
	    mv $$TEMPFILE $@.tmp
	$(call gb_Helper_replace_if_different_and_touch,$@.tmp,$@)

# Unfortunatly the file packager just allows a cmdline file list, but all paths are
# relative to $(BUILDDIR), so we won't run out of cmdline space that fast...
$(wasm_fs_image_WORKDIR)/soffice.data.js.metadata: $(wasm_fs_image_WORKDIR)/soffice.data.filelist \
	$(call gb_Output_announce,$(subst $(BUILDDIR)/,,$(wasm_fs_image_WORKDIR)/soffice.data),$(true),GEN,2)
	$(EMSDK_FILE_PACKAGER) $(wasm_fs_image_WORKDIR)/soffice.data --preload $(shell cat $^) --js-output=$(wasm_fs_image_WORKDIR)/soffice.data.js --separate-metadata \
	    || rm -f $(wasm_fs_image_WORKDIR)/soffice.data.js $(wasm_fs_image_WORKDIR)/soffice.data $(wasm_fs_image_WORKDIR)/soffice.data.js.metadata

# vim: set noet sw=4:
