/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_script_vba_VBAScriptEventId_idl__
#define __com_sun_star_script_vba_VBAScriptEventId_idl__


module com {  module sun {  module star { module script { module vba {


/** Identifies a VBA script event fired via <member>XVBACompatibility::
    broadcastVBAScriptEvent</member>, and received by <member>
    XVBAScriptListener::notifyVBAScriptEvent</member>.

    @see VBAScriptEvent
    @see XVBACompatibility
    @see XVBAScriptListener
 */
constants VBAScriptEventId
{
    /** This event is fired when a VBA script in the current document has been
        started.

        <p>Several scripts may run simultaneously, e.g. when a running script
        triggers a document event that starts another script.</p>

        <p>The number of running scripts can be obtained via <member>
        XVBACompatibility::RunningVBAScripts</member>. The number returned
        there will already contain the new script notified with this event.</p>

        <p>The member <member>VBAScriptEvent::ModuleName</member> of the event
        object will contain the name of the code module that contains the
        started script.</p>
     */
    const long SCRIPT_STARTED = 0;

    /** This event is fired when a VBA script in the current document stops
        running.

        <p>Several scripts may run simultaneously, e.g. when a running script
        triggers a document event that starts another script.</p>

        <p>The number of scripts still running can be obtained via <member>
        XVBACompatibility::RunningVBAScripts</member>. The number returned
        there will not contain the stopped script notified with this event
        anymore.</p>

        <p>The member <member>VBAScriptEvent::ModuleName</member> of the event
        object will contain the name of the code module that contains the
        script that has been stopped.</p>
     */
    const long SCRIPT_STOPPED = 1;

    /** This event is fired when a VBA script in the current document tries to
        instanciate a userform.

        <p>The member <member>VBAScriptEvent::ModuleName</member> of the event
        object will contain the name of the userform module.</p>
     */
    const long INITIALIZE_USERFORM = 2;

};


}; }; }; }; };


#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
