/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_inspection_InteractiveSelectionResult_idl__
#define __com_sun_star_inspection_InteractiveSelectionResult_idl__

module com {  module sun {  module star {  module inspection {

/** describes possible results of an interactive selection of a property value
    in an object inspector

    @see XPropertyHandler::onInteractivePropertySelection

    @since OOo 2.0.3
*/
enum InteractiveSelectionResult
{
    /** The interactive selection of a property value was canceled.
    */
    Cancelled,

    /** The interactive selection of a property value succeeded, and the
        new property value chosen by the user has already been set at the
        inspected component.
    */
    Success,

    /** The interactive selection of a property value succeeded, a new
        property value has been obtained, but not yet set at the inspected
        component.

        <p>In this case, the obtained value is passed to the caller of
        XPropertyHandler::onInteractivePropertySelection(), which is
        responsible for forwarding this value to the inspected component.</p>
    */
    ObtainedValue,

    /** The interactive selection of a property value is still pending.

        <p>This is usually used when this selection involves non-modal user interface.</p>
    */
    Pending
};


}; }; }; };

#endif


/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
