/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: PropertyLineElement.idl,v $
 *
 *  $Revision: 1.2 $
 *
 *  last change: $Author: vg $ $Date: 2006-03-14 11:06:37 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/

#ifndef __com_sun_star_inspection_PropertyLineElement_idl__
#define __com_sun_star_inspection_PropertyLineElement_idl__

//=============================================================================
module com {  module sun {  module star {  module inspection {

//-----------------------------------------------------------------------------
/** describes elements of a single line in an object inspector, used to represent a
    single property

    @see XPropertyHandler::describePropertyLine
    @see LineDescriptor
*/
constants PropertyLineElement
{
    /// specifies the input control in a group of controls related to a single property
    const short InputControl    = 0x01;
    /// specifies the primary button (if present) in a group of controls related to a single property
    const short PrimaryButton   = 0x02;
    /// specifies the secondary button (if present) in a group of controls related to a single property
    const short SecondaryButton = 0x04;

    /// specifies all elements
    const short All             = 0xFF;
};

//=============================================================================

}; }; }; };

#endif

