/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_inspection_PropertyLineElement_idl__
#define __com_sun_star_inspection_PropertyLineElement_idl__

module com {  module sun {  module star {  module inspection {

/** describes elements of a single line in an object inspector, used to represent a
    single property

    @see XPropertyHandler::describePropertyLine
    @see LineDescriptor

    @since OOo 2.0.3
*/
constants PropertyLineElement
{
    /// specifies the input control in a group of controls related to a single property
    const short InputControl    = 0x01;
    /// specifies the primary button (if present) in a group of controls related to a single property
    const short PrimaryButton   = 0x02;
    /// specifies the secondary button (if present) in a group of controls related to a single property
    const short SecondaryButton = 0x04;

    /// specifies all elements
    const short All             = 0xFF;
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
