/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
module ooo { module vba {
    constants VbCompareMethod {
        const long vbBinaryCompare = 0;
        const long vbDatabaseCompare = 2;
        const long vbTextCompare = 1;
    };
}; };

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
