/*************************************************************************
 *
 *  $RCSfile: testcorefl.idl,v $
 *
 *  $Revision: 1.1.1.1 $
 *
 *  last change: $Author: hr $ $Date: 2000-09-18 15:29:35 $
 *
 *  The Contents of this file are made available subject to the terms of
 *  either of the following licenses
 *
 *         - GNU Lesser General Public License Version 2.1
 *         - Sun Industry Standards Source License Version 1.1
 *
 *  Sun Microsystems Inc., October, 2000
 *
 *  GNU Lesser General Public License Version 2.1
 *  =============================================
 *  Copyright 2000 by Sun Microsystems, Inc.
 *  901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License version 2.1, as published by the Free Software Foundation.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *  MA  02111-1307  USA
 *
 *
 *  Sun Industry Standards Source License Version 1.1
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.1 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://www.openoffice.org/license.html.
 *
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 *
 *  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 *
 *  Copyright: 2000 by Sun Microsystems, Inc.
 *
 *  All Rights Reserved.
 *
 *  Contributor(s): _______________________________________
 *
 *
 ************************************************************************/
#include <com/sun/star/uno/XInterface.idl>

module ModuleA
{
    exception ExceptionA
    {
        boolean aBoolean;
    };

    struct StructA
    {
        long aLong;
        short aShort;
    };

    struct StructB : StructA
    {
        double aDouble;
        float   aFloat;
    };

    struct StructC : StructB
    {
        string                              aString;
        sequence<com::sun::star::uno::XInterface>   aInterfaceSeq;
    };

    exception ExceptionB : ExceptionA
    {
        StructC aStructC;
    };

    [ uik(e227a3A1-33d6-12d1-aabe02a0-249d5590), ident("InterfaceB", 1.0) ]
    interface XInterface1 : com::sun::star::uno::XInterface
    {
    };

    exception ExceptionC : ExceptionB
    {
        XInterface1 aInterface1;
    };

    module ModuleB
    {
        enum EnumA { VAL_1, VAL_2, VAL_3 = 17};
    };

};

module ModuleC
{
    const boolean           aConstBoolean   = True;
    const byte              aConstByte      = 0;
    const short             aConstShort     = -1;
    const unsigned short    aConstUShort    = 1;
    const long              aConstLong      = -2;
    const unsigned long     aConstULong     = 2;
//      const hyper             aConstHyper     = -3;
//      const unsigned hyper    aConstUHyper    = 3;
    const float             aConstFloat     = 3.14;
    const double            aConstDouble    = 3.14e-10;
    const string            aConstString    = "test";


    [ uik(e227a3A0-33d6-11d1-aabe02a0-249d5590), ident("InterfaceA", 1.0) ]
    interface XInterfaceA : com::sun::star::uno::XInterface
    {
        void methodA();
        [oneway] void methodB([in] short aShort);
        sequence<ModuleA::StructB> methodC([in] ModuleA::StructC aStructC, [inout] ModuleA::StructA aStructA);
    };

    [ uik(e227a3A1-33d6-11d1-aabe02a0-12345678), ident("InterfaceB", 1.0) ]
    interface XInterfaceB : XInterfaceA
    {
        [attribute] string aString;

        XInterfaceA methodD([in] ModuleA::ModuleB::EnumA aEnumA) raises (ModuleA::ExceptionA, ModuleA::ExceptionB, ModuleA::ExceptionC);
    };
};
