/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openoffice_OpenOffice */

#ifndef _Included_NativeView
#define _Included_NativeView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openoffice_OpenOffice
 * Method:    getNativeWindowSystemType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_OfficeDev_samples_DesktopEnvironment_NativeView_getNativeWindowSystemType
  (JNIEnv *, jobject);

/*
 * Class:     org_openoffice_OpenOffice
 * Method:    getNativeWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_OfficeDev_samples_DesktopEnvironment_NativeView_getNativeWindow
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
