LSTLOADSETTINGS_ITEM_CHANGED = "sessionSelected" # "lstLoadSettingsItemChanged"
BTNLOADSESSION_ACTION_PERFORMED = "loadSession" # "btnLoadSessionActionPerformed"
BTNDELSESSION_ACTION_PERFORMED = "delSession" # "btnDelSessionActionPerformed"
BTNADDDOC_ACTION_PERFORMED = "addDocument" # "btnAddDocActionPerformed"
BTNREMOVEDOC_ACTION_PERFORMED = "removeDocument" # "btnRemoveDocActionPerformed"
BTNDOCUP_ACTION_PERFORMED = "docUp" # "btnDocUpActionPerformed"
BTNDOCDOWN_ACTION_PERFORMED = "docDown" # "btnDocDownActionPerformed"
LSTSTYLES_ITEM_CHANGED = "refreshStylePreview" # "lstStylesItemChanged"
BTNBACKGROUNDS_ACTION_PERFORMED = "chooseBackground" # "btnBackgroundsActionPerformed"
BTNICONSETS_ACTION_PERFORMED = "chooseIconset" # "btnIconSetsActionPerformed"
BTNFAVICON_ACTION_PERFORMED = "chooseFavIcon" # "btnFavIconActionPerformed"
BTNPREVIEW_ACTION_PERFORMED = "documentPreview" # "btnPreviewActionPerformed"
BTNFTP_ACTION_PERFORMED = "setFTPPublish" # "btnFTPActionPerformed"
CHKLOCALDIR_ITEM_CHANGED = "checkPublish" # "chkLocalDirItemChanged"
CHKSAVESETTINGS_ITEM_CHANGED = "checkPublish" # "chkSaveSettingsItemChanged"
TXTSAVESETTINGS_TEXT_CHANGED = "checkPublish" # "txtSaveSettingsTextChanged"
BTNLOCALDIR_ACTION_PERFORMED = "setPublishLocalDir" # "btnLocalDirActionPerformed"
BTNZIP_ACTION_PERFORMED = "setZipFilename" # "btnZipActionPerformed"
CONFIG_PATH = "/org.openoffice.Office.WebWizard/WebWizard"
CONFIG_READ_PARAM = "cp_"
TASK = "WWIZ"
TASK_PREPARE = "t-prep"
LOCAL_PUBLISHER = "local"
FTP_PUBLISHER = "ftp"
ZIP_PUBLISHER = "zip"
TASK_EXPORT = "t_exp"
TASK_EXPORT_PREPARE = "t_exp_prep"
TASK_EXPORT_DOCUMENTS = "t_exp_docs"
TASK_GENERATE_PREPARE = "t_gen_prep"
TASK_GENERATE_XSL = "t_gen_x"
TASK_GENERATE_COPY = "t_gen_cp"
TASK_PUBLISH_PREPARE = "t_pub_prep"
TASK_FINISH = "t_fin"

'''
when the user adds more than this number
of documents to the list, a status dialog opens.
'''
MIN_ADD_FILES_FOR_DIALOG = 2
