/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_sdbcx_Descriptor_idl__
#define __com_sun_star_sdbcx_Descriptor_idl__

#include <com/sun/star/beans/XPropertySet.idl>

 module com {  module sun {  module star {  module sdbcx {


/** is used to create a new object within a database.

    <p>
    A descriptor is commonly created by the container of a specific object, such as, tables or views.
    After the creation of the descriptor the properties have to be filled.
    Afterwards, you append the descriptor to the container and the container creates a new object based
    on the informations of the descriptor. The descriptor can be used to create several objects.
    </p>
    <p>
    A descriptor contains at least the informations of the name of an object.
    </p>
    @see com::sun::star::sdbcx::XAppend
 */
published service Descriptor
{
    // gives access to the properties.
    interface com::sun::star::beans::XPropertySet;


    /** is the name for the object to create.
     */
    [property] string Name;
};


}; }; }; };

/*===========================================================================
===========================================================================*/
#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
