/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: Group.idl,v $
 *
 *  $Revision: 1.7 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 03:58:42 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_sdbcx_Group_idl__
#define __com_sun_star_sdbcx_Group_idl__

#ifndef __com_sun_star_beans_XPropertySet_idl__
#include <com/sun/star/beans/XPropertySet.idl>
#endif

 module com {  module sun {  module star {  module sdbcx {

 published interface XUsersSupplier;
 published interface XAuthorizable;


// DocMerge from xml: service com::sun::star::sdbcx::Group
/** represents a group of users, which has certain access rights for the objects
    of the database.
 */
published service Group
{
    /** gives access to the users which contains to this group.
    */
    interface XUsersSupplier;

    /** shows the access rights of this group.
    */
    interface XAuthorizable;

    // gives access to the properties.
    interface com::sun::star::beans::XPropertySet;


    // DocMerge from xml: property com::sun::star::sdbcx::Group::Name
    /** is the name of the group.
     */
    [readonly, property] string Name;
};

//=============================================================================

}; }; }; };

/*===========================================================================
===========================================================================*/
#endif
