/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: KeyType.idl,v $
 *
 *  $Revision: 1.6 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 04:01:02 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_sdbcx_KeyType_idl__
#define __com_sun_star_sdbcx_KeyType_idl__

 module com {  module sun {  module star {  module sdbcx {


// DocMerge from idl: constants com::sun::star::sdbcx::KeyType
/** determines the type of a key.
 */
published constants KeyType
{

    // DocMerge from idl: value com::sun::star::sdbcx::KeyType::PRIMARY
    /** indicates that the key is the primary key of a table.
     */
    const long PRIMARY  = 1;
    //-------------------------------------------------------------------------

    // DocMerge from idl: value com::sun::star::sdbcx::KeyType::UNIQUE
    /** indicates that the key is unique, NULL values are allowed.
     */
    const long UNIQUE = 2;
    //-------------------------------------------------------------------------

    // DocMerge from idl: value com::sun::star::sdbcx::KeyType::FOREIGN
    /** indicates that the key is a foreign key of a table.
     */
    const long FOREIGN = 3;
};

//=============================================================================

}; }; }; };

/*===========================================================================
===========================================================================*/
#endif
