/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_sdbcx_XDeleteRows_idl__
#define __com_sun_star_sdbcx_XDeleteRows_idl__

#include <com/sun/star/uno/XInterface.idl>

#include <com/sun/star/sdbc/SQLException.idl>

 module com {  module sun {  module star {  module sdbcx {


/** provides for the deletion of more than one row at a time.
 */
published interface XDeleteRows: com::sun::star::uno::XInterface
{

    /** deletes one or more rows identified by their bookmarks.
             @param rows
                list of bookmarks identifying the rows.
             @returns
                an array of update counts containing one element for each
                 row. The array is ordered according to the order in
                which bookmarks were given.
             @throws com::sun::star::sdbc::SQLException
                if a fatal error occurs, for instance, the connection gets lost if bookmarks
                are used which do not belong to the according result set.
     */
    sequence<long> deleteRows([in]sequence<any> rows)
        raises (com::sun::star::sdbc::SQLException);
};


}; }; }; };

/*===========================================================================
===========================================================================*/
#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
