/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XUser.idl,v $
 *
 *  $Revision: 1.9 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-08 04:08:14 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_sdbcx_XUser_idl__
#define __com_sun_star_sdbcx_XUser_idl__

#ifndef __com_sun_star_sdbcx_XAuthorizable_idl__
#include <com/sun/star/sdbcx/XAuthorizable.idl>
#endif

 module com {  module sun {  module star {  module sdbcx {

// DocMerge from xml: interface com::sun::star::sdbcx::XUser
/** allows for changing a users password.
 */
published interface XUser: XAuthorizable
{

    // DocMerge from xml: method com::sun::star::sdbcx::XUser::changePassword
    /** allows modifying a user password.
        @param oldPassword
            the old password to be reset
        @param newPassword
            the new password
        @throws com::sun::star::sdbc::SQLException
            if a database access error occurs.
     */
    void changePassword([in]string oldPassword, [in]string newPassword)
        raises (com::sun::star::sdbc::SQLException);
};

//=============================================================================

}; }; }; };

/*===========================================================================
===========================================================================*/
#endif
