/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */


#ifndef __com_sun_star_sdb_ContentLoader_idl__
#define __com_sun_star_sdb_ContentLoader_idl__

#include <com/sun/star/frame/FrameLoader.idl>

module com {  module sun {  module star {  module sdb {

/** implements a loader for various datasource-related user interface components.

    <p>Usually, you don't deal with this loader directly. Instead, use an instance with
    the com::sun::star::frame::XComponentLoader interface, and pass
    one of the below-mentioned URLs to it.</p>

    @see com::sun::star::frame::XComponentLoader
    @see com::sun::star::frame::Desktop
*/
published service ContentLoader
{
    /** ensures the basic functionality.

        <p>
        Supporting this service ensures that you can plug any of the components
        the loader can create into an arbitrary frame.
        </p>

        The loader should be registered for the URL scheme
        <b>
        .component:DB/ *
        </b>
        , the concrete URLs supported are:
        <ul>
            <li><b>.component:DB/DataSourceBrowser</b><br/>
                Using this URL creates an instance of the
                com::sun::star::sdb::DataSourceBrowser
                service and plugs it into the frame passed to the loader.
            </li>
            <li><b>.component:DB/FormGridView</b><br/>
                Using this URL creates an instance of the
                com::sun::star::sdb::ExternalSourceBrowser
                service and plugs it into the frame passed to the loader.
            </li>
            <li><b>.component:DB/QueryDesign</b><br/>
                Using this URL creates an instance of the
                com::sun::star::sdb::QueryDesign
                service and plugs it into the frame passed to the loader.
            </li>
            <li><b>.component:DB/TableDesign</b><br/>
                Using this URL creates an instance of the
                com::sun::star::sdb::TableDesign
                service and plugs it into the frame passed to the loader.
            </li>
            <li><b>.component:DB/RelationDesign</b><br/>
                Using this URL creates an instance of the
                com::sun::star::sdb::RelationDesign
                service and plugs it into the frame passed to the loader.
            </li>
        </ul>

        The parameters passed to the
        com::sun::star::frame::XFrameLoader::load()
        are forwarded to the object being created,
        in particular to its
        com::sun::star::lang::XInitialization
        interface.
    **/
    service com::sun::star::frame::FrameLoader;
};

}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
