/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_sdb_DataColumn_idl__
#define __com_sun_star_sdb_DataColumn_idl__

#include <com/sun/star/sdb/ResultColumn.idl>

 module com {  module sun {  module star {  module sdb {

 published interface XColumn;
 published interface XColumnUpdate;


/** defines a column used for a result set which contains the data definition
    and the data of the column of the current row of a result set.
 */
published service DataColumn
{
    service com::sun::star::sdb::ResultColumn;


    /** is used to retrieve the columns value.
     */
    interface XColumn;


    /** is used to update the columns value.
     */
    interface XColumnUpdate;


    /** contains the column's value. This could be a constraint property, to
        veto modifications, if a new value does not fit into rules
        defined for the column.
     */
    [optional, property] any Value;


    /** contains the original value of the column.
     */
    [optional, readonly, property] any OriginalValue;
};


}; }; }; };

/*===========================================================================
===========================================================================*/
#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
