/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_sdb_DatabaseAccessConnection_idl__
#define __com_sun_star_sdb_DatabaseAccessConnection_idl__

#include <com/sun/star/container/XChild.idl>

#include <com/sun/star/sdbcx/DatabaseDefinition.idl>

#include <com/sun/star/sdbc/Connection.idl>

 module com {  module sun {  module star {  module sdb {

 published interface XQueriesSupplier;
 published interface XFormDocumentsSupplier;
 published interface XReportDocumentsSupplier;
 published interface XSQLQueryComposerFactory;


/** specifies a component, which supplies and stores additional information related
    to a certain database connection, such as, DatabaseQueries, FormDocuments, and ReportDocuments.
    Objects for data definition are supplied as well, for instance, Tables, Views, etc.

    <p>
    Implements the service
    <type scope="com::sun::star::sdbc">Connection</type>
    .
    It is possible to open more than one connection at the same time, but the method
    <member scope="com::sun::star::sdb">DatabaseAccessConnection::dispose()</member>
    will close only one of these connections. You have to close all connections in order
    to close the connection to the database.
    </p>

    @deprecated
*/
published service DatabaseAccessConnection
{
    /** supporting of the base connection service.
             <p><B>Note:</B><br/>
                 Don't use the "dispose" method of the XComponent interface, as the DataAccess
                 uses a more sophisticated interface for closing a connection.
                 @see XDatabaseAccess
             </p>
     */
    service com::sun::star::sdbc::Connection;

    /** access to the DatabaseDefinition beans of the connection.
     */
    service com::sun::star::sdbcx::DatabaseDefinition;

    /** access to the owning data access bean.
     */
    interface com::sun::star::container::XChild;

    /** returns a tool for composing queries.
     */
    interface XSQLQueryComposerFactory;

    /** provides access to the queries.
    */
    interface XQueriesSupplier;
};


}; }; }; };

/*===========================================================================
===========================================================================*/
#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
