/*************************************************************************
 *
 *  $RCSfile: Table.idl,v $
 *
 *  $Revision: 1.3 $
 *
 *  last change: $Author: mi $ $Date: 2000-11-08 12:43:31 $
 *
 *  The Contents of this file are made available subject to the terms of
 *  either of the following licenses
 *
 *         - GNU Lesser General Public License Version 2.1
 *         - Sun Industry Standards Source License Version 1.1
 *
 *  Sun Microsystems Inc., October, 2000
 *
 *  GNU Lesser General Public License Version 2.1
 *  =============================================
 *  Copyright 2000 by Sun Microsystems, Inc.
 *  901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License version 2.1, as published by the Free Software Foundation.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *  MA  02111-1307  USA
 *
 *
 *  Sun Industry Standards Source License Version 1.1
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.1 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://www.openoffice.org/license.html.
 *
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 *
 *  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 *
 *  Copyright: 2000 by Sun Microsystems, Inc.
 *
 *  All Rights Reserved.
 *
 *  Contributor(s): _______________________________________
 *
 *
 ************************************************************************/
#ifndef __com_sun_star_sdb_Table_idl__
#define __com_sun_star_sdb_Table_idl__

#ifndef __com_sun_star_sdbcx_Table_idl__
#include <com/sun/star/sdbcx/Table.idl>
#endif

#ifndef __com_sun_star_sdb_DataSettings_idl__
#include <com/sun/star/sdb/DataSettings.idl>
#endif

 module com {  module sun {  module star {  module sdb {


// DocMerge from xml: service com::sun::star::sdb::Table
/** extends the <type scope="com::sun::star::sdbcx">Table</type> with additional
    display information, sorting and filtering criterias.
 */
service Table
{
    // DocMerge: empty anyway
    service com::sun::star::sdbcx::Table;


    // DocMerge from xml: service com::sun::star::sdb::Table: service com::sun::star::sdb::DataSettings
    /** is used for customization of data appearance.
     */
    service com::sun::star::sdb::DataSettings;


    // DocMerge from xml: property com::sun::star::sdb::Table::Privileges
    /** indicates the privileges for the table.@see com::sun::star::sdbcx::Privilege
     */
    [readonly, property] long Privileges;
};

//=============================================================================

}; }; }; };

/*===========================================================================
    $Log: not supported by cvs2svn $
    Revision 1.1.1.1  2000/09/18 23:35:37  hjs
    initial import

    Revision 1.8  2000/09/11 11:52:40  mi
    documentation merged from XML

    Revision 1.6  2000/06/05 13:35:37  dg
    services changed

    Revision 1.5  2000/06/05 13:20:27  dg
    services changed

    Revision 1.4  1999/12/20 16:32:43  dg
    #70278# files removed and new doc

    Revision 1.3  1999/12/08 14:42:26  dg
    #70278# new Composer files

    Revision 1.2  1999/11/29 12:14:13  dg
    Documentation

    Revision 1.1  1999/11/24 08:39:01  dg
    new Star Data Beans

===========================================================================*/
#endif
