/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/



#ifndef __com_sun_star_sdb_XDataAccessDescriptorFactory_idl__
#define __com_sun_star_sdb_XDataAccessDescriptorFactory_idl__

#ifndef __com_sun_star_beans_XPropertySet_idl__
#include <com/sun/star/beans/XPropertySet.idl>
#endif

//=============================================================================

module com { module sun { module star { module sdb {

//=============================================================================

/** allows creating instances of the DataAccessDescriptor service.

    <p>Data access descriptors are finally only bags of properties with a defined
    semantics. Depending on the context in which you use them, certain of their
    properties are needed or unneeded.<br/>
    The descriptor factory allows you to create instances which offer
    all properties potentially needed at a descriptor.</p>
 */
interface XDataAccessDescriptorFactory
{
    /** creates a <type>DataAccessDescriptor</type> which supports all properties
        defined for this service, even if they're normally optional only.
    */
    ::com::sun::star::beans::XPropertySet
        createDataAccessDescriptor();
};

//=============================================================================

}; }; }; };

//=============================================================================

#endif
