/*************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Copyright 2000, 2010 Oracle and/or its affiliates.
 *
 * OpenOffice.org - a multi-platform office productivity suite
 *
 * This file is part of OpenOffice.org.
 *
 * OpenOffice.org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License version 3
 * only, as published by the Free Software Foundation.
 *
 * OpenOffice.org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License version 3 for more details
 * (a copy is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3 along with OpenOffice.org.  If not, see
 * <http://www.openoffice.org/license.html>
 * for a copy of the LGPLv3 License.
 *
 ************************************************************************/
#ifndef com_sun_star_chart2_XChartTypeContainer_idl
#define com_sun_star_chart2_XChartTypeContainer_idl

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/chart2/XChartType.idl>
#include <com/sun/star/lang/IllegalArgumentException.idl>
#include <com/sun/star/container/NoSuchElementException.idl>

module com
{
module sun
{
module star
{
module chart2
{

interface XChartTypeContainer : com::sun::star::uno::XInterface
{
    /** add a chart type to the chart type container

        @throws IllegalArgumentException
            If the given chart type is already contained in the chart type container.
     */
    void addChartType( [in] XChartType aChartType )
        raises( com::sun::star::lang::IllegalArgumentException );

    /** removes one data series from the chart type container.
     */
    void removeChartType( [in] XChartType aChartType )
        raises( com::sun::star::container::NoSuchElementException );

    /** retrieve all chart types
     */
    sequence< XChartType > getChartTypes();

    /** set all chart types
     */
    void setChartTypes( [in] sequence< XChartType > aChartTypes )
        raises( com::sun::star::lang::IllegalArgumentException );
};

} ; // chart2
} ; // com
} ; // sun
} ; // star

#endif
