#ifndef com_sun_star_chart_XLegendSymbolProvider_idl
#define com_sun_star_chart_XLegendSymbolProvider_idl

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/drawing/XShape.idl>

module com
{
module sun
{
module star
{
module chart2
{

/**
 */
interface XLegendSymbolProvider : ::com::sun::star::uno::XInterface
{
    /** The returned shape is used for display in the legend.  It may
        also be used for display at a data points.

        <p>The shape returned here, will be resized using
        <member scope="com::sun::star::drawing">XShape::setSize</member>
        to fit the available space in the legend.</p>
     */
    com::sun::star::drawing::XShape getSymbol();
};

} ; // chart2
} ; // com
} ; // sun
} ; // star

#endif
