#ifndef com_sun_star_chart2_XTarget_idl
#define com_sun_star_chart2_XTarget_idl

#include <com/sun/star/uno/XInterface.idl>


module com {  module sun {  module star {  module chart2 {

//................... wrong --> XDrawGroup

// [in] com::sun::star::drawing::XShapes xShapes

interface XTarget : ::com::sun::star::uno::XInterface
{
    void addDrawElement(); //(DrawElement);

    //... provide something for creation of Transformation ...
};

}; }; }; };

#endif
