/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4; fill-column: 100 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

module com { module sun { module star { module media {

/** Interface to be implemented by a Player listener.

    <p> The XPlayerListener interface must be implemented by
    the clients of the Player service which need to be informed about
    events while the Player service is displayed.</p>

    @since LibreOffice 7.4
*/

interface XPlayerListener : com::sun::star::lang::XEventListener
{
    /** A client receives this event when the preferred player size of an XPlayer
        is available to be queried.
    */
    void preferredPlayerWindowSizeAvailable([in] com::sun::star::lang::EventObject e);
};

}; }; }; };

/* vim:set shiftwidth=4 softtabstop=4 expandtab cinoptions=b1,g0,N-s cinkeys+=0=break: */
