/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_reflection_ProxyFactory_idl__
#define __com_sun_star_reflection_ProxyFactory_idl__

#include <com/sun/star/reflection/XProxyFactory.idl>



 module com {  module sun {  module star {  module reflection {


/** Service to create proxy objects acting on behalf of a given
    target object.<br>
    A proxy delegates calls to a given target object.
    In addition, it is aggregatable, thus it is possible to
    intercept calls on the proxy's interfaces.

    @attention
    A proxy object is UNO conform, but does NOT provide original target
    interfaces on queryInterface() calls.  This may lead to problems
    regarding object identity, e.g. when dealing with listener proxies.

    @deprecated
    Aggregation will no longer be supported as a high-level concept of UNO.
    You may still have the option to implement a UNO object consisting of
    several single objects in your specific programming language, though this
    depends on your programming language.
    Thus this service is deprecated, too.
*/
published service ProxyFactory : XProxyFactory;


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
