/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_reflection_XMethodParameter_idl__
#define __com_sun_star_reflection_XMethodParameter_idl__

#include <com/sun/star/uno/XInterface.idl>

#include <com/sun/star/reflection/XTypeDescription.idl>


//=============================================================================

 module com {  module sun {  module star {  module reflection {

//=============================================================================

/** Reflects a method parameter.

    <p>This type is superseded by <type>XParameter</type>, which supports
    parameters of service constructors as well as parameters of interface
    methods.</p>

    @see XInterfaceMethodTypeDescription
*/
published interface XMethodParameter: com::sun::star::uno::XInterface
{
    /** Returns the name of the parameter

        @return
                name of parameter
    */
    string getName();

    /** Returns the type of the parameter.

        @return
                type of parameter
    */
    com::sun::star::reflection::XTypeDescription getType();

    /** Returns true, if the parameter is declared as [in] or [inout] in IDL.

        @return
                true, if declared [in] or [inout] parameter
    */
    boolean isIn();

    /** Returns true, if the parameter is declared as [out] or [inout] in IDL.

        @return
                true, if declared [out] or [inout] parameter
    */
    boolean isOut();

    /** Returns the position of the parameter regarding the IDL method declaration.

        @return
                position of the parameter
    */
    long getPosition();
};

//=============================================================================

}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
