/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_view_PrinterDescriptor_idl__
#define __com_sun_star_view_PrinterDescriptor_idl__

#include <com/sun/star/view/PaperOrientation.idl>

#include <com/sun/star/view/PaperFormat.idl>

#include <com/sun/star/awt/Size.idl>



module com {  module sun {  module star {  module view {


/** describes a printer by specifying the queue name and some settings.

    <p>This service may be represented by a
    com::sun::star::beans::PropertyValue[].

    @see com::sun::star::beans::PropertyValue
 */
published service PrinterDescriptor
{
    /** specifies the name of the printer queue to be used.

        <p>Which printer queues are available, can be figured out with the
        system library of the used programming language/environment.
     */
    [property] string Name;

    /** specifies the orientation of the paper.
     */
    [property] com::sun::star::view::PaperOrientation PaperOrientation;

    /** specifies a predefined paper size or if the paper size
        is a user-defined size.

        <p>Setting this property may change the value of
        PrinterDescriptor::PaperSize.</p>
     */
    [property] com::sun::star::view::PaperFormat PaperFormat;

    /** specifies the size of the paper in 100th mm.

        <p>Setting this property may change the value of
        PrinterDescriptor::PaperFormat.</p>
     */
    [property] com::sun::star::awt::Size PaperSize;

    /** indicates, whether the printer is busy or not.
     */
    [readonly, property] boolean IsBusy;

    /** indicates, whether the printer allows changes to
        PrinterDescriptor::PaperOrientation.
     */
    [readonly, property] boolean CanSetPaperOrientation;

    /** indicates, whether the printer allows changes to
        PrinterDescriptor::PaperFormat.
     */
    [readonly, property] boolean CanSetPaperFormat;


    /** indicates if the printer allows changes to
        PrinterDescriptor::PaperSize.
     */
    [readonly, property] boolean CanSetPaperSize;

};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
