/*************************************************************************
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Copyright 2008 by Sun Microsystems, Inc.
 *
 * OpenOffice.org - a multi-platform office productivity suite
 *
 * $RCSfile: XSelectionSupplier.idl,v $
 * $Revision: 1.11 $
 *
 * This file is part of OpenOffice.org.
 *
 * OpenOffice.org is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License version 3
 * only, as published by the Free Software Foundation.
 *
 * OpenOffice.org is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License version 3 for more details
 * (a copy is included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU Lesser General Public License
 * version 3 along with OpenOffice.org.  If not, see
 * <http://www.openoffice.org/license.html>
 * for a copy of the LGPLv3 License.
 *
 ************************************************************************/
#ifndef __com_sun_star_view_XSelectionSupplier_idl__
#define __com_sun_star_view_XSelectionSupplier_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __com_sun_star_lang_IllegalArgumentException_idl__
#include <com/sun/star/lang/IllegalArgumentException.idl>
#endif

#ifndef __com_sun_star_view_XSelectionChangeListener_idl__
#include <com/sun/star/view/XSelectionChangeListener.idl>
#endif


//=============================================================================

module com {  module sun {  module star {  module view {

//=============================================================================

/** makes it possible to access and change the selection in a view.

    @see OfficeDocumentView
 */
published interface XSelectionSupplier: com::sun::star::uno::XInterface
{
    //-------------------------------------------------------------------------
    /** selects the object represented by <var>xSelection</var> if it is
        known and selectable in this object.
     */
    boolean select( [in] any xSelection )
            raises( com::sun::star::lang::IllegalArgumentException );

    //-------------------------------------------------------------------------
    /** @returns
                the current selection.

        <p>The selection is either specified by an object which is contained
        in the component to which the view belongs, or it is an interface of a
        collection which contains such objects.
     */
    any getSelection();

    //-------------------------------------------------------------------------
    /** registers an event listener, which is called when the selection changes.
     */
    void addSelectionChangeListener( [in] com::sun::star::view::XSelectionChangeListener xListener );

    //-------------------------------------------------------------------------
    /** unregisters an event listener which was registered with
        <method>XSelectionSupplier::addSelectionChangeListener</method>.
     */
    void removeSelectionChangeListener( [in] com::sun::star::view::XSelectionChangeListener xListener );

};

//=============================================================================

}; }; }; };

#endif
