officecfg_FILES := \
    FirstStartWizard \
    Inet \
    Interaction \
    LDAP \
    Office/Accelerators \
    Office/Addons \
    Office/Calc \
    Office/CalcAddIns \
    Office/Canvas \
    Office/Chart \
    Office/Commands \
    Office/Common \
    Office/Compatibility \
    Office/DataAccess \
    Office/DataAccess/Drivers \
    Office/Draw \
    Office/Embedding \
    Office/Events \
    Office/ExtendedColorScheme \
    Office/ExtensionManager \
    Office/FormWizard \
    Office/Histories \
    Office/Impress \
    Office/Java \
    Office/Jobs \
    Office/Labels \
    Office/Linguistic \
    Office/Logging \
    Office/Math \
    Office/OOoImprovement/Settings \
    Office/OptionsDialog \
    Office/Paths \
    Office/ProtocolHandler \
    Office/Recovery \
    Office/SFX \
    Office/Scripting \
    Office/Security \
    Office/Substitution \
    Office/TabBrowse \
    Office/TableWizard \
    Office/TypeDetection \
    Office/UI \
    Office/UI/BaseWindowState \
    Office/UI/BasicIDECommands \
    Office/UI/BasicIDEWindowState \
    Office/UI/BibliographyCommands \
    Office/UI/BibliographyWindowState \
    Office/UI/CalcCommands \
    Office/UI/CalcWindowState \
    Office/UI/Category \
    Office/UI/ChartCommands \
    Office/UI/ChartWindowState \
    Office/UI/Commands \
    Office/UI/Controller \
    Office/UI/DbBrowserWindowState \
    Office/UI/DbQueryWindowState \
    Office/UI/DbRelationWindowState \
    Office/UI/DbTableDataWindowState \
    Office/UI/DbTableWindowState \
    Office/UI/DbuCommands \
    Office/UI/DrawImpressCommands \
    Office/UI/DrawWindowState \
    Office/UI/Effects \
    Office/UI/Factories \
    Office/UI/GenericCategories \
    Office/UI/GenericCommands \
    Office/UI/GlobalSettings \
    Office/UI/ImpressWindowState \
    Office/UI/MathCommands \
    Office/UI/MathWindowState \
    Office/UI/StartModuleCommands \
    Office/UI/StartModuleWindowState \
    Office/UI/WindowContentFactories \
    Office/UI/WindowState \
    Office/UI/WriterCommands \
    Office/UI/WriterFormWindowState \
    Office/UI/WriterGlobalWindowState \
    Office/UI/WriterReportWindowState \
    Office/UI/WriterWebWindowState \
    Office/UI/WriterWindowState \
    Office/UI/XFormsWindowState \
    Office/Views \
    Office/WebWizard \
    Office/Writer \
    Office/WriterWeb \
    Setup \
    System \
    TypeDetection/Filter \
    TypeDetection/GraphicFilter \
    TypeDetection/Misc \
    TypeDetection/Types \
    TypeDetection/UISort \
    UserProfile \
    VCL \
    ucb/Configuration \
    ucb/Hierarchy \
    ucb/InteractionHandler \
    ucb/Store \

