/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/



#ifndef __offapi_com_sun_star_form_runtime_XFormControllerContext_idl__
#define __offapi_com_sun_star_form_runtime_XFormControllerContext_idl__

#include <com/sun/star/awt/XControl.idl>

//=============================================================================

module com { module sun { module star { module form { module runtime {

//=============================================================================

/** provides a context for a <type>FormController</type>

<p>A <type>FormController</type> knows about the controls it is responsible
    for, and about the control container which those controls live in. However, it doesn't know
    about a possible larger context, like a scrollable view which the controls are embedded into.
    To compensate this, it can be provided a <code>XFormControllerContext</code>.</p>
 */
interface XFormControllerContext
{
    /** ensures the given control is visible, by scrolling the view if necessary.
    */
    void    makeVisible( [in] ::com::sun::star::awt::XControl _Control );
};

//=============================================================================

}; }; }; }; };

//=============================================================================

#endif
