/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_xml_sax_XFastDocumentHandler_idl__
#define __com_sun_star_xml_sax_XFastDocumentHandler_idl__

#include <com/sun/star/uno/XInterface.idl>

#include <com/sun/star/xml/sax/SAXException.idl>

#include <com/sun/star/xml/sax/XFastAttributeList.idl>
#include <com/sun/star/xml/sax/XFastContextHandler.idl>
#include <com/sun/star/xml/sax/XLocator.idl>



module com {  module sun {  module star {  module xml {  module sax {


/** receives notification of sax document events from a
    <type>XFastParser</type>
 */
interface XFastDocumentHandler: XFastContextHandler
{

    /** called by the parser when parsing of an XML stream is started.
     */
    void startDocument()
            raises( com::sun::star::xml::sax::SAXException );


    /** called by the parser after the last XML element of a stream is processed.
     */
    void endDocument()
            raises( com::sun::star::xml::sax::SAXException );


    /** receives an object for locating the origin of SAX document events.
     */
    void setDocumentLocator( [in] com::sun::star::xml::sax::XLocator xLocator )
            raises( com::sun::star::xml::sax::SAXException );

};


}; }; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
