/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_awt_tree_XTreeEditListener_idl__
#define __com_sun_star_awt_tree_XTreeEditListener_idl__

#include <com/sun/star/awt/tree/XTreeNode.idl>
#include <com/sun/star/lang/XEventListener.idl>
#include <com/sun/star/util/VetoException.idl>


module com {  module sun {  module star {  module awt {  module tree {


/** You can implement this interface and register with <method scope="XTreeControl">addTreeEditListener</method>
    to get notifications when editing of a node starts and ends.

    <p>You have to set the <member>TreeControlModel::Editable</member> property to
    <TRUE/> before a tree supports editing.</p>
 */
interface XTreeEditListener : ::com::sun::star::lang::XEventListener
{
    /** This method is called from the <type>TreeControl</type> implementation when editing of
        <var>Node</var> is requested by calling <member>XTreeControl::startEditingAtNode()</member>.

        @param Node
            the <type>XTreeNode</type> for that an edit request was fired by calling
            <method scope="XTreeControl">startEditingAtNode</method>

        @throws VetoException
            if thrown the editing will not start.
    */
    void nodeEditing( [in] XTreeNode Node )
        raises ( ::com::sun::star::util::VetoException );

    /** This method is called from the <type>TreeControl</type> implementation when editing
        of <var>Node</var> is finished and was not canceled.

        <p>Implementations that register a <type>XTreeEditListener</type> must update the
        display value at the Node.</p>

        @param Node
            the <type>XTreeNode</type> for that an edit request was fired by calling
            <method scope="XTreeControl">startEditingAtNode</method>

        @param NewText
            the text that was entered by the user.
    */
    void nodeEdited( [in] XTreeNode Node, [in] string NewText );
};


}; }; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
