/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: IiopBridge.idl,v $
 *
 *  $Revision: 1.8 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-09 14:59:59 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_bridge_Iiop_idl__
#define __com_sun_star_bridge_Iiop_idl__

#ifndef __com_sun_star_lang_XInitialization_idl__
#include <com/sun/star/lang/XInitialization.idl>
#endif

#ifndef __com_sun_star_lang_XComponent_idl__
#include <com/sun/star/lang/XComponent.idl>
#endif

#ifndef __com_sun_star_bridge_XBridge_idl__
#include <com/sun/star/bridge/XBridge.idl>
#endif

//=============================================================================

 module com {  module sun {  module star {  module bridge {

//=============================================================================
/** Concrete service of the meta service Bridge for iiop.

    <p> This bridge works with the iiop protocol. </p>

    @see com.sun.star.bridge.Bridge
 */
published service IiopBridge
{
    /** This interface allows to initialize the bridge service with the necessary
        arguments. The sequence&lt;any&gt; must have 4 members.

        <ol>
            <li> String: The unique name of the bridge or an empty string</li>
            <li> String: iiop</li>
            <li> XConnection: The bidirectional connection, the bridge should work on</li>
            <li> XInstanceProvider:
                The instance provider, that shall be called to access the initial object.</li>
        </ol>
     */
    interface com::sun::star::lang::XInitialization;

    /** The main interface of the service.
     */
    interface com::sun::star::bridge::XBridge;

    /** allows to terminate the interprocess bridge.
     */
    interface com::sun::star::lang::XComponent;

};
//=============================================================================

}; }; }; };
#endif
