/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */

#ifndef __com_sun_star_logging_XConsoleHandler_idl__
#define __com_sun_star_logging_XConsoleHandler_idl__

#include <com/sun/star/logging/XLogHandler.idl>


module com { module sun { module star { module logging {


/** implemented by a log handler whose output channel is the processes console.

    <p>Note that a console handler will ignore its formatter's head and tail, since
    it cannot decided whether they should be emitted on <code>stdout</code> or <code>stderr</code>.</p>

    @since OOo 2.3
 */
interface XConsoleHandler : XLogHandler
{
    /** denotes the LogLevel threshold used to determine to which
        console the events should be logged.

        <p>Events with a level greater or equal to <code>Threshold</code> will be
        logged to <code>stderr</code>, all others to <code>stdout</code>.</p>

        <p>The default value for this attribute is LogLevel::SEVERE.</p>
    */
    [attribute] long    Threshold;
};


}; }; }; };


#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
