/*************************************************************************
 *
 *  $RCSfile: DocumentInfo.idl,v $
 *
 *  $Revision: 1.8 $
 *
 *  last change: $Author: kz $ $Date: 2004-05-19 10:38:31 $
 *
 *  The Contents of this file are made available subject to the terms of
 *  either of the following licenses
 *
 *         - GNU Lesser General Public License Version 2.1
 *         - Sun Industry Standards Source License Version 1.1
 *
 *  Sun Microsystems Inc., October, 2000
 *
 *  GNU Lesser General Public License Version 2.1
 *  =============================================
 *  Copyright 2000 by Sun Microsystems, Inc.
 *  901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License version 2.1, as published by the Free Software Foundation.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *  MA  02111-1307  USA
 *
 *
 *  Sun Industry Standards Source License Version 1.1
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.1 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://www.openoffice.org/license.html.
 *
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 *
 *  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 *
 *  Copyright: 2000 by Sun Microsystems, Inc.
 *
 *  All Rights Reserved.
 *
 *  Contributor(s): _______________________________________
 *
 *
 ************************************************************************/
#ifndef __com_sun_star_document_DocumentInfo_idl__
#define __com_sun_star_document_DocumentInfo_idl__

#ifndef __com_sun_star_document_XDocumentInfo_idl__
#include <com/sun/star/document/XDocumentInfo.idl>
#endif

#ifndef __com_sun_star_lang_XComponent_idl__
#include <com/sun/star/lang/XComponent.idl>
#endif

#ifndef __com_sun_star_beans_XPropertySet_idl__
#include <com/sun/star/beans/XPropertySet.idl>
#endif

#ifndef __com_sun_star_beans_XFastPropertySet_idl__
#include <com/sun/star/beans/XFastPropertySet.idl>
#endif

#ifndef __com_sun_star_util_DateTime_idl__
#include <com/sun/star/util/DateTime.idl>
#endif

#ifndef __com_sun_star_lang_Locale_idl__
#include <com/sun/star/lang/Locale.idl>
#endif

//=============================================================================

  module com {   module sun {   module star {   module document {

//=============================================================================
/** this service provides document-specific information like the
    author, creation date and user fields

    <p>
    Contrary to the service <type>StandaloneDocumentInfo</type> the document - which
    contains such informations - must be loaded completly. As a result of that this
    DocumengInfo service is available on an open document via the interface
    <type>XDocumentInfoSupplier</type> only.
    </p>

    @see StandaloneDocumentInfo
    @see XDocumentInfoSupplier
 */
service DocumentInfo
{
    //-------------------------------------------------------------------------
    /** provides access to the user fields for the information regarding the
        document

        <p>
        These fields are additional to normal properties.
        (see below)
        </p>
     */
    interface XDocumentInfo;

    //-------------------------------------------------------------------------
    /** neccessary to support normal properties
     */
    interface com::sun::star::beans::XPropertySet;

    //-------------------------------------------------------------------------
    /** supports faster access on well known properties by using index
     */
    interface com::sun::star::beans::XFastPropertySet;

    //-------------------------------------------------------------------------
    /** contains the intial author of the document
     */
    [property] string Author;

    //-------------------------------------------------------------------------
    /** identifies application was used to create or last modify the document
     */
    [property] string Generator;

    //-------------------------------------------------------------------------
    /** contains the date and time of the first time the
        document was stored
     */
    [property] com::sun::star::util::DateTime CreationDate;

    //-------------------------------------------------------------------------
    /** contains the title of the document
     */
    [property] string Title;

    //-------------------------------------------------------------------------
    /** subject of document

        @deprecated
        use <member>DocumentInfo::Title</member> instead.
     */
    [property] string Subject;

    //-------------------------------------------------------------------------
    /** contains a multi-line comment of the document

        <p>
        Line delimiters can be UNIX, Macintosh or DOS style.
        </p>
     */
    [property] string Description;

    //-------------------------------------------------------------------------
    /** contains a comma separated list of keywords for
        the document
     */
    [property] string Keywords;

    //-------------------------------------------------------------------------
    /** contains the MIME-type of the document's resource

        <p>
        The MIME-type is neither stored in the document information nor in
        the document; it is sent within a protocol header or is
        detected, thus it cannot be changed.
        </p>
     */
    [readonly, property] string MIMEType;

    //-------------------------------------------------------------------------
    /** default language of the document
     */
    [property] com::sun::star::lang::Locale Language;

    //-------------------------------------------------------------------------
    /** contains the name of the editor who was the last
        person to store this document
     */
    [property] string ModifiedBy;

    //-------------------------------------------------------------------------
    /** contains the date and time of the last time the
        document was stored
     */
    [property] com::sun::star::util::DateTime ModifyDate;

    //-------------------------------------------------------------------------
    /** contains the name of the editor who was the last
        person to print the document
     */
    [property] string PrintedBy;

    //-------------------------------------------------------------------------
    /** contains the date and time of when the document was
        last printed
     */
    [property] com::sun::star::util::DateTime PrintDate;

    //-------------------------------------------------------------------------
    /** contains the path and name of the template from
        which the document was created

        <p>
        The value is an empty string if the document was not created
        from a template or if it was detached from the template.
        </p>
     */
    [property] string Template;

    //-------------------------------------------------------------------------
    /** contains the date and time of when the document
        was created or updated from the template
     */
    [property] com::sun::star::util::DateTime TemplateDate;

    //-------------------------------------------------------------------------
    /** contains the URL to load automatically after a
        specified time after the document is loaded into a desktop frame
     */
    [property] string AutoloadURL;

    //-------------------------------------------------------------------------
    /** contains the number of seconds after which a specified
        URL is to be loaded after the document is loaded into a desktop
        frame
     */
    [property] long AutoloadSecs;

    //-------------------------------------------------------------------------
    /** contains the name of the default frame into which
        links should be loaded if no target is specified

        <p>
        This applies to the autoload feature too, but to others as well.
        </p>
     */
    [property] string DefaultTarget;

    //-------------------------------------------------------------------------
    /** @deprecated
     */
    [property] string BlindCopiesTo;

    //-------------------------------------------------------------------------
    /** @deprecated
     */
    [property] string CopyTo;

    //-------------------------------------------------------------------------
    /** @deprecated
     */
    [property] string InReplyTo;

    //-------------------------------------------------------------------------
    /** @deprecated
     */
    [property] string Newsgroups;

    //-------------------------------------------------------------------------
    /** @deprecated
     */
    [property] string Original;

    //-------------------------------------------------------------------------
    /** @deprecated
     */
    [property] short Priority;

    //-------------------------------------------------------------------------
    /** @deprecated
     */
    [property] string Recipient;

    //-------------------------------------------------------------------------
    /** @deprecated
     */
    [property] string References;

    //-------------------------------------------------------------------------
    /** @deprecated
     */
    [property] string ReplyTo;

    //-------------------------------------------------------------------------
    /** contains the theme of the document.
     */
    [property] string Theme;

    //-------------------------------------------------------------------------
    /** @deprecated
     */
    [readonly, property] boolean IsEncrypted;

    //-------------------------------------------------------------------------
    /** @deprecated
     */
    [property] boolean AutoloadEnabled;
};

//=============================================================================

}; }; }; };

#endif
