/*************************************************************************
 *
 *  $RCSfile: MediaDescriptor.idl,v $
 *
 *  $Revision: 1.3 $
 *
 *  last change: $Author: mi $ $Date: 2001-03-22 17:25:56 $
 *
 *  The Contents of this file are made available subject to the terms of
 *  either of the following licenses
 *
 *         - GNU Lesser General Public License Version 2.1
 *         - Sun Industry Standards Source License Version 1.1
 *
 *  Sun Microsystems Inc., October, 2000
 *
 *  GNU Lesser General Public License Version 2.1
 *  =============================================
 *  Copyright 2000 by Sun Microsystems, Inc.
 *  901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License version 2.1, as published by the Free Software Foundation.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *  MA  02111-1307  USA
 *
 *
 *  Sun Industry Standards Source License Version 1.1
 *  =================================================
 *  The contents of this file are subject to the Sun Industry Standards
 *  Source License Version 1.1 (the "License"); You may not use this file
 *  except in compliance with the License. You may obtain a copy of the
 *  License at http://www.openoffice.org/license.html.
 *
 *  Software provided under this License is provided on an "AS IS" basis,
 *  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
 *  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
 *  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
 *  See the License for the specific provisions governing your rights and
 *  obligations concerning the Software.
 *
 *  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
 *
 *  Copyright: 2000 by Sun Microsystems, Inc.
 *
 *  All Rights Reserved.
 *
 *  Contributor(s): _______________________________________
 *
 *
 ************************************************************************/
#ifndef __com_sun_star_document_MediaDescriptor_idl__
#define __com_sun_star_document_MediaDescriptor_idl__

#ifndef __com_sun_star_io_XInputStream_idl__
#include <com/sun/star/io/XInputStream.idl>
#endif

#ifndef __com_sun_star_awt_Rectangle_idl__
#include <com/sun/star/awt/Rectangle.idl>
#endif

#ifndef __com_sun_star_util_URL_idl__
#include <com/sun/star/util/URL.idl>
#endif

//=============================================================================

module com { module sun { module star { module document {

//=============================================================================

/** describes properties of a document, regarding the relationsship
    between the loaded document and the resource the document is
    loaded from / stored to.

    <p>This service may be represented by a
    <type scope="com::sun::star::beans" dim="[]">PropertyValue</type>. </p>

    @see com::sun::star::beans::PropertyValue
 */
service MediaDescriptor
{
    //-------------------------------------------------------------------------
    /** document is a template
     */
    [property] boolean AsTemplate;

    //-------------------------------------------------------------------------
    /** identifier of used character set
     */
    [property] string CharacterSet;

    //-------------------------------------------------------------------------
    /** internal filter name
     */
    [property] string FilterName;

    //-------------------------------------------------------------------------
    /** name of target frame
     */
    [property] string FrameName;

    //-------------------------------------------------------------------------
    /** load doucment unvisible
     */
    [property] boolean Hidden;

    //-------------------------------------------------------------------------
    /** content of document
     */
    [property] com::sun::star::io::XInputStream InputStream;

    //-------------------------------------------------------------------------
    /** specifies the name of a mark within the document where the first
        view is to position to.

        <p>This is the same as the text behind a '#' in a http URL. But
        this syntax with a '#' is not specified in most other URL schemas.
        </p>
     */
    [property] string JumpMark;
    //-------------------------------------------------------------------------
    /** mime type
     */
    [property] string MediaType;

    //-------------------------------------------------------------------------
    /** open a new view for already loaded document
     */
    [property] boolean OpenNewView;

    //-------------------------------------------------------------------------
    /** position and size of document window
     */
    [property] com::sun::star::awt::Rectangle PosSize;

    //-------------------------------------------------------------------------
    /** contains the data for HTTP post method as a sequence of byte.

        <p>This is for example the data from a web form. This property
        is actually handled, not <member>MediaDescriptor::PostString</member>,
        which is for convienience. </p>
     */
    [property] sequence<byte> PostData;

    //-------------------------------------------------------------------------
    /** contains the data for HTTP post method as a sequence of byte.

        <p>This is for example the data from a web form. This property
        is actually only for convienience and the data will interally processed
        as <member>MediaDescriptor::PostData</member>. </p>
     */
    [property] string PostString;

    //-------------------------------------------------------------------------
    /** show preview
     */
    [property] boolean Preview;

    //-------------------------------------------------------------------------
    /** open document readonly
     */
    [property] boolean ReadOnly;

    //-------------------------------------------------------------------------
    /** name of document referrer
     */
    [property] string Referer;

    //-------------------------------------------------------------------------
    /** prevents dialogs to query for more information.
     */
    [property] boolean Silent;

    //-------------------------------------------------------------------------
    /** name of the template instead of the URL.

        <p>Use always in conjunction with
        <member>MediaDescriptor::TemplateRegionName</member>. </p>

        @deprecated
     */
    [property] string TemplateName;

    //-------------------------------------------------------------------------
    /** name of the region of the template.

        <p>Use always in conjunction with
        <member>MediaDescriptor::TemplateName</member>. </p>

        @deprecated
     */
    [property] string TemplateRegionName;

    //-------------------------------------------------------------------------
    /** url of the document
     */
    [property] com::sun::star::util::URL URL;// FileName

    //-------------------------------------------------------------------------
    /** storage version
     */
    [property] short Version;

    //-------------------------------------------------------------------------
    /** id of the initial view.
     */
    [property] short ViewId;
};

//=============================================================================

}; }; }; };

#endif
