/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XDocumentSubStorageSupplier.idl,v $
 *
 *  $Revision: 1.4 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-07 23:10:40 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_document_XDocumentSubStorageSupplier_idl__
#define __com_sun_star_document_XDocumentSubStorageSupplier_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __com_sun_star_embed_XStorage_idl__
#include <com/sun/star/embed/XStorage.idl>
#endif


//=============================================================================

module com {   module sun {   module star {   module document {

//=============================================================================
/** through this interface documents can provide access to their substorages

    <p>
    A temporary interface to get access to documents substorages.
    </p>

    @see DocumentInfo
    @see StandaloneDocumentInfo
 */
interface XDocumentSubStorageSupplier: com::sun::star::uno::XInterface
{
    //-------------------------------------------------------------------------
    /** provides the access to a substorage with specified name

        @param sStorageName
            the name of requested substorage

        @param nMode
            a mode the storage should be opened in can take value from ::com::sun::star::embed::ElementModes

        @returns
            XStorage implementation that refers to specified substorage
     */
    com::sun::star::embed::XStorage getDocumentSubStorage(
                                        [in] string aStorageName,
                                        [in] long nMode );

    //-------------------------------------------------------------------------
    /** provides the list of substorages

        @returns
            sequence of substorages names
     */
    sequence< string > getDocumentSubStoragesNames()
        raises( ::com::sun::star::io::IOException );

};

//=============================================================================

}; }; }; };

#endif

