/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_document_XOOXMLDocumentPropertiesImporter_idl__
#define __com_sun_star_document_XOOXMLDocumentPropertiesImporter_idl__

#ifndef __com_sun_star_document_XDocumentProperties_idl__
#include <com/sun/star/document/XDocumentProperties.idl>
#endif

#ifndef __com_sun_star_embed_XStorage_idl__
#include <com/sun/star/embed/XStorage.idl>
#endif

#ifndef __com_sun_star_xml_sax_SAXException_idl__
#include <com/sun/star/xml/sax/SAXException.idl>
#endif

#ifndef __com_sun_star_lang_IllegalArgumentException_idl__
#include <com/sun/star/lang/IllegalArgumentException.idl>
#endif

#ifndef __com_sun_star_uno_Exception_idl__
#include <com/sun/star/uno/Exception.idl>
#endif

//=============================================================================

module com { module sun { module star { module document {

//=============================================================================
/** allows to import the document properties from OOXML fomat
 */
interface XOOXMLDocumentPropertiesImporter: com::sun::star::uno::XInterface
{
    // -----------------------------------------------------------------------
    /** allows to import the document properties from OOXML format

        <p>
        The implementation should parse the document properties from OOXML
        format storage and set them to the target
        <type>XDocumentProperties</type> implementation.
        </p>

        <p>
        The storage must represent OOXML format and support
        <type scope="com::sun::star::embed">XRelationshipAccess</type>
        interface. Please see
        <type scope="com::sun::star::embed">StorageFactory</type> for details
        regarding creation of such a storage.
        </p>

        @param xSource
            the source storage representing OOXML document

        @param xDocumentProperties
            the target <type>XDocumentProperties</type> interface implementation

        @throws ::com::sun::star::lang::IllegalArgumentException
            the exception is thrown in case unexpected arguments are provided

        @throws ::com::sun::star::xml::sax::SAXException
            the exception is thrown in case of parsing problems

        @throws ::com::sun::star::uno::Exception
            the exception is thrown in case of other problems during the import
     */

    void importProperties(
        [in] com::sun::star::embed::XStorage xSource,
        [in] com::sun::star::document::XDocumentProperties xDocumentProperties )
            raises( com::sun::star::lang::IllegalArgumentException,
                    com::sun::star::xml::sax::SAXException,
                    com::sun::star::uno::Exception );
};

//=============================================================================

}; }; }; };

#endif

