# Auto-generated by pythonmaker - DO NOT EDIT.
from __future__ import annotations

from com.sun.star.uno.XComponentContext import XComponentContext as com_sun_star_uno_XComponentContext_
from com.sun.star.uno.XInterface import XInterface as com_sun_star_uno_XInterface_

class this:
    @staticmethod
    def this(ctx: com_sun_star_uno_XComponentContext_, this: int) -> com_sun_star_uno_XInterface_:
        ...

