/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: AnimationCalcMode.idl,v $
 *
 *  $Revision: 1.3 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-07 20:34:55 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_animations_AnimationCalcMode_idl__
#define __com_sun_star_animations_AnimationCalcMode_idl__

//=============================================================================

 module com {  module sun {  module star {  module animations {

//=============================================================================

/** Specifies the interpolation mode for the animation.

    @see <type>XAnimation</type>
    @see http://www.w3.org/TR/smil20/animation.html#adef-calcMode
    @see http://www.w3.org/TR/smil20/animation.html#adef-SplineAnimation-calcMode
*/
constants AnimationCalcMode
{
    /** This specifies that the animation function will jump from one value to the next without any interpolation.
    */
    const short DISCRETE = 0;

    /** Simple linear interpolation between values is used to calculate the animation function.
        <br>
        This is the default.
    */
    const short LINEAR = 1;

    /** Defines interpolation to produce an even pace of change across the animation.
        <br>
        This is only supported for values that define a linear numeric range, and
        for which some notion of "distance" between points can be calculated
        (e.g. position, width, height, etc.).
    */
    const short PACED = 2;

    /** Interpolates from one value in the values list to the next according to a
        time function defined by a cubic Bezier spline. The points of the spline are
        defined in the <member>KeyTimes</member> attribute, and the control points
        for each interval are defined in the <member>KeySplines</member> attribute.
    */
    const short SPLINE = 3;
};

//=============================================================================

}; }; }; };

#endif
