/*************************************************************************
 *
 *  OpenOffice.org - a multi-platform office productivity suite
 *
 *  $RCSfile: XAnimateTransform.idl,v $
 *
 *  $Revision: 1.3 $
 *
 *  last change: $Author: rt $ $Date: 2005-09-07 20:40:46 $
 *
 *  The Contents of this file are made available subject to
 *  the terms of GNU Lesser General Public License Version 2.1.
 *
 *
 *    GNU Lesser General Public License Version 2.1
 *    =============================================
 *    Copyright 2005 by Sun Microsystems, Inc.
 *    901 San Antonio Road, Palo Alto, CA 94303, USA
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License version 2.1, as published by the Free Software Foundation.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 *    MA  02111-1307  USA
 *
 ************************************************************************/
#ifndef __com_sun_star_animations_XAnimateTransform_idl__
#define __com_sun_star_animations_XAnimateTransform_idl__

#ifndef __com_sun_star_animations_XAnimate_idl__
#include <com/sun/star/animations/XAnimate.idl>
#endif

//=============================================================================

 module com {  module sun {  module star {  module animations {

//=============================================================================

/** animates a transformation attribute on a target element, thereby allowing
    animations to control translation, scaling, rotation and/or skewing.

    The member <member>XAnimate::Attributes</member> contains a short from
    <const>AnimationTransformType</const>.

    Depending on the value in <member>XAnimate::Attributes</member>, the
    members <member>XAnimate::From</member>, <member>XAnimate::To</member>,
    <member>XAnimate::By</member> or <member>XAnimate::Values</member>
    contain the following

    <ul>
    <li><const>AnimationTransformType::TRANSLATE</const><br>
        <type>ValuePair</type> of <i>tx</i> and <i>ty</i></li>
    <li><const>AnimationTransformType::SCALE</const><br>
        <type>ValuePair</type> of <i>sx</i> and <i>sy</i></li>
    <li><const>AnimationTransformType::ROTATE</const><br>
        Values for a rotation angle</li>
    <li><const>AnimationTransformType::SKEWX</const><br>
        Values for a skew-angle</li>
    <li><const>AnimationTransformType::SKEWY</const><br>
        Values for a skew-angle</li>
    </ul>

    @see http://www.w3.org/TR/SVG/animate.html#AnimateTransformElement
*/
interface XAnimateTransform : XAnimate
{
    /**
        @see <const>AnimationTransformType</const>
    */
    [attribute] short TransformType;
};

//=============================================================================

}; }; }; };

#endif

