/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_animations_XAnimateMotion_idl__
#define __com_sun_star_animations_XAnimateMotion_idl__

#include <com/sun/star/animations/XAnimate.idl>


 module com {  module sun {  module star {  module animations {


/** Interface for animation by defining motion on a path.

    @see http://www.w3.org/TR/smil20/animation.html#edef-animateMotion
*/
interface XAnimateMotion : XAnimate
{
    /** Specifies an optional path.
        <br>
        If a path is used, the <member>From</member>, <member>To</member> and
        <member>By</member> members are ignored.
        The value type of the path depends on the used rendering system.
        Possible types maybe a svg:d path encoded in a string.
    */
    [attribute] any Path;

    /**  Specifies the origin of motion for the animation. The values and semantics
        of this attribute are dependent upon the used animation engine.
    */
    [attribute] any Origin;
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
