#*************************************************************************
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
# 
# Copyright 2000, 2010 Oracle and/or its affiliates.
#
# OpenOffice.org - a multi-platform office productivity suite
#
# This file is part of OpenOffice.org.
#
# OpenOffice.org is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License version 3
# only, as published by the Free Software Foundation.
#
# OpenOffice.org is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU Lesser General Public License version 3 for more details
# (a copy is included in the LICENSE file that accompanied this code).
#
# You should have received a copy of the GNU Lesser General Public License
# version 3 along with OpenOffice.org.	If not, see
# <http://www.openoffice.org/license.html>
# for a copy of the LGPLv3 License.
#
#*************************************************************************

$(eval $(call gb_UnoApiTarget_UnoApiTarget,oovbaapi))

$(eval $(call gb_UnoApiTarget_add_rdbfiles,oovbaapi,\
    udkapi \
    offapi \
))

$(eval $(call gb_UnoApiTarget_set_include,oovbaapi,\
	$$(INCLUDE) \
	-I$(SRCDIR)/oovbaapi \
	-I$(OUTDIR)/idl \
))

$(eval $(call gb_UnoApiTarget_add_idlfiles_nohdl,oovbaapi,\
	oovbaapi/ooo/vba/excel/Globals \
	oovbaapi/ooo/vba/excel/Hyperlink \
	oovbaapi/ooo/vba/excel/Range \
	oovbaapi/ooo/vba/excel/TextFrame \
	oovbaapi/ooo/vba/excel/Window \
	oovbaapi/ooo/vba/excel/Workbook \
	oovbaapi/ooo/vba/excel/Worksheet \
))

$(eval $(call gb_UnoApiTarget_add_idlfiles_noheader,oovbaapi,\
	oovbaapi/ooo/vba/ControlProvider \
	oovbaapi/ooo/vba/msforms/MSFormReturnTypes \
	oovbaapi/ooo/vba/excel/SheetObjects \
))

$(eval $(call gb_UnoApiTarget_add_idlfiles,oovbaapi,\
	oovbaapi/ooo/vba/excel/XGraphicObjects \
	oovbaapi/ooo/vba/excel/XSheetObject \
	oovbaapi/ooo/vba/excel/XControlObject \
	oovbaapi/ooo/vba/excel/XButton \
	oovbaapi/ooo/vba/XApplicationBase \
	oovbaapi/ooo/vba/XAssistant \
	oovbaapi/ooo/vba/XCollection \
	oovbaapi/ooo/vba/XCollectionBase \
	oovbaapi/ooo/vba/XCommandBar \
	oovbaapi/ooo/vba/XCommandBarButton \
	oovbaapi/ooo/vba/XCommandBarControl \
	oovbaapi/ooo/vba/XCommandBarControls \
	oovbaapi/ooo/vba/XCommandBarPopup \
	oovbaapi/ooo/vba/XCommandBars \
	oovbaapi/ooo/vba/XControlProvider \
	oovbaapi/ooo/vba/XDialogBase \
	oovbaapi/ooo/vba/XDialogsBase \
	oovbaapi/ooo/vba/XDocumentBase \
	oovbaapi/ooo/vba/XDocumentProperties \
	oovbaapi/ooo/vba/XDocumentProperty \
	oovbaapi/ooo/vba/XDocumentsBase \
	oovbaapi/ooo/vba/XErrObject \
	oovbaapi/ooo/vba/XFileDialog \
	oovbaapi/ooo/vba/XFileDialogSelectedItems \
	oovbaapi/ooo/vba/XFileSearch \
	oovbaapi/ooo/vba/XFoundFiles \
	oovbaapi/ooo/vba/XFontBase \
	oovbaapi/ooo/vba/XGlobalsBase \
	oovbaapi/ooo/vba/XHelperInterface \
	oovbaapi/ooo/vba/XPageSetupBase \
	oovbaapi/ooo/vba/XPropValue \
	oovbaapi/ooo/vba/XVBAToOOEventDescGen \
	oovbaapi/ooo/vba/XWindowBase \
	oovbaapi/ooo/vba/excel/XApplication \
	oovbaapi/ooo/vba/excel/XAxes \
	oovbaapi/ooo/vba/excel/XAxis \
	oovbaapi/ooo/vba/excel/XAxisTitle \
	oovbaapi/ooo/vba/excel/XBorder \
	oovbaapi/ooo/vba/excel/XBorders \
	oovbaapi/ooo/vba/excel/XCharacters \
	oovbaapi/ooo/vba/excel/XChart \
	oovbaapi/ooo/vba/excel/XChartObject \
	oovbaapi/ooo/vba/excel/XChartObjects \
	oovbaapi/ooo/vba/excel/XChartTitle \
	oovbaapi/ooo/vba/excel/XCharts \
	oovbaapi/ooo/vba/excel/XComment \
	oovbaapi/ooo/vba/excel/XComments \
	oovbaapi/ooo/vba/excel/XDataLabel \
	oovbaapi/ooo/vba/excel/XDataLabels \
	oovbaapi/ooo/vba/excel/XDialog \
	oovbaapi/ooo/vba/excel/XDialogs \
	oovbaapi/ooo/vba/excel/XFont \
	oovbaapi/ooo/vba/excel/XFormat \
	oovbaapi/ooo/vba/excel/XFormatCondition \
	oovbaapi/ooo/vba/excel/XFormatConditions \
	oovbaapi/ooo/vba/excel/XGlobals \
	oovbaapi/ooo/vba/excel/XHPageBreak \
	oovbaapi/ooo/vba/excel/XHPageBreaks \
	oovbaapi/ooo/vba/excel/XHyperlink \
	oovbaapi/ooo/vba/excel/XHyperlinks \
	oovbaapi/ooo/vba/excel/XInterior \
	oovbaapi/ooo/vba/excel/XMenu \
	oovbaapi/ooo/vba/excel/XMenuBar \
	oovbaapi/ooo/vba/excel/XMenuBars \
	oovbaapi/ooo/vba/excel/XMenuItem \
	oovbaapi/ooo/vba/excel/XMenuItems \
	oovbaapi/ooo/vba/excel/XMenus \
	oovbaapi/ooo/vba/excel/XName \
	oovbaapi/ooo/vba/excel/XNames \
	oovbaapi/ooo/vba/excel/XOLEObject \
	oovbaapi/ooo/vba/excel/XOLEObjects \
	oovbaapi/ooo/vba/excel/XOutline \
	oovbaapi/ooo/vba/excel/XPageBreak \
	oovbaapi/ooo/vba/excel/XPageSetup \
	oovbaapi/ooo/vba/excel/XPane \
	oovbaapi/ooo/vba/excel/XPivotCache \
	oovbaapi/ooo/vba/excel/XPivotTable \
	oovbaapi/ooo/vba/excel/XPivotTables \
	oovbaapi/ooo/vba/excel/XQueryTable \
	oovbaapi/ooo/vba/excel/XRange \
	oovbaapi/ooo/vba/excel/XSeries \
	oovbaapi/ooo/vba/excel/XSeriesCollection \
	oovbaapi/ooo/vba/excel/XStyle \
	oovbaapi/ooo/vba/excel/XStyles \
	oovbaapi/ooo/vba/excel/XTextFrame \
	oovbaapi/ooo/vba/excel/XTitle \
	oovbaapi/ooo/vba/excel/XVPageBreak \
	oovbaapi/ooo/vba/excel/XVPageBreaks \
	oovbaapi/ooo/vba/excel/XValidation \
	oovbaapi/ooo/vba/excel/XWindow \
	oovbaapi/ooo/vba/excel/XWindows \
	oovbaapi/ooo/vba/excel/XWorkbook \
	oovbaapi/ooo/vba/excel/XWorkbooks \
	oovbaapi/ooo/vba/excel/XWorksheet \
	oovbaapi/ooo/vba/excel/XWorksheetFunction \
	oovbaapi/ooo/vba/excel/XWorksheets \
	oovbaapi/ooo/vba/excel/XlBuildInDialog \
	oovbaapi/ooo/vba/msforms/XButton \
	oovbaapi/ooo/vba/msforms/XCheckBox \
	oovbaapi/ooo/vba/msforms/XColorFormat \
	oovbaapi/ooo/vba/msforms/XComboBox \
	oovbaapi/ooo/vba/msforms/XCommandButton \
	oovbaapi/ooo/vba/msforms/XControl \
	oovbaapi/ooo/vba/msforms/XControls \
	oovbaapi/ooo/vba/msforms/XFillFormat \
	oovbaapi/ooo/vba/msforms/XFrame \
	oovbaapi/ooo/vba/msforms/XGroupBox \
	oovbaapi/ooo/vba/msforms/XImage \
	oovbaapi/ooo/vba/msforms/XLabel \
	oovbaapi/ooo/vba/msforms/XLineFormat \
	oovbaapi/ooo/vba/msforms/XListBox \
	oovbaapi/ooo/vba/msforms/XMultiPage \
	oovbaapi/ooo/vba/msforms/XNewFont \
	oovbaapi/ooo/vba/msforms/XPages \
	oovbaapi/ooo/vba/msforms/XPictureFormat \
	oovbaapi/ooo/vba/msforms/XProgressBar \
	oovbaapi/ooo/vba/msforms/XRadioButton \
	oovbaapi/ooo/vba/msforms/XScrollBar \
	oovbaapi/ooo/vba/msforms/XShape \
	oovbaapi/ooo/vba/msforms/XShapeRange \
	oovbaapi/ooo/vba/msforms/XShapes \
	oovbaapi/ooo/vba/msforms/XSpinButton \
	oovbaapi/ooo/vba/msforms/XTextBox \
	oovbaapi/ooo/vba/msforms/XTextBoxShape \
	oovbaapi/ooo/vba/msforms/XTextFrame \
	oovbaapi/ooo/vba/msforms/XToggleButton \
	oovbaapi/ooo/vba/msforms/XUserForm \
	oovbaapi/ooo/vba/word/XAddin \
	oovbaapi/ooo/vba/word/XAddins \
	oovbaapi/ooo/vba/word/XApplication \
	oovbaapi/ooo/vba/word/XAutoTextEntries \
	oovbaapi/ooo/vba/word/XAutoTextEntry \
	oovbaapi/ooo/vba/word/XBookmark \
	oovbaapi/ooo/vba/word/XBookmarks \
	oovbaapi/ooo/vba/word/XBorder \
	oovbaapi/ooo/vba/word/XBorders \
	oovbaapi/ooo/vba/word/XCell \
	oovbaapi/ooo/vba/word/XCells \
	oovbaapi/ooo/vba/word/XColumn \
	oovbaapi/ooo/vba/word/XColumns \
	oovbaapi/ooo/vba/word/XDialog \
	oovbaapi/ooo/vba/word/XDialogs \
	oovbaapi/ooo/vba/word/XDocument \
	oovbaapi/ooo/vba/word/XDocuments \
	oovbaapi/ooo/vba/word/XField \
	oovbaapi/ooo/vba/word/XFields \
	oovbaapi/ooo/vba/word/XFind \
	oovbaapi/ooo/vba/word/XFont \
	oovbaapi/ooo/vba/word/XFormField \
	oovbaapi/ooo/vba/word/XFormFields \
	oovbaapi/ooo/vba/word/XFrame \
	oovbaapi/ooo/vba/word/XFrames \
	oovbaapi/ooo/vba/word/XGlobals \
	oovbaapi/ooo/vba/word/XHeaderFooter \
	oovbaapi/ooo/vba/word/XHeadersFooters \
	oovbaapi/ooo/vba/word/XListFormat \
	oovbaapi/ooo/vba/word/XListGallery \
	oovbaapi/ooo/vba/word/XListGalleries \
	oovbaapi/ooo/vba/word/XListLevel \
	oovbaapi/ooo/vba/word/XListLevels \
	oovbaapi/ooo/vba/word/XListTemplate \
	oovbaapi/ooo/vba/word/XListTemplates \
	oovbaapi/ooo/vba/word/XOptions \
	oovbaapi/ooo/vba/word/XPageSetup \
	oovbaapi/ooo/vba/word/XPane \
	oovbaapi/ooo/vba/word/XPanes \
	oovbaapi/ooo/vba/word/XParagraph \
	oovbaapi/ooo/vba/word/XParagraphFormat \
	oovbaapi/ooo/vba/word/XParagraphs \
	oovbaapi/ooo/vba/word/XRange \
	oovbaapi/ooo/vba/word/XReplacement \
	oovbaapi/ooo/vba/word/XRevision \
	oovbaapi/ooo/vba/word/XRevisions \
	oovbaapi/ooo/vba/word/XRow \
	oovbaapi/ooo/vba/word/XRows \
	oovbaapi/ooo/vba/word/XSection \
	oovbaapi/ooo/vba/word/XSections \
	oovbaapi/ooo/vba/word/XSelection \
	oovbaapi/ooo/vba/word/XStyle \
	oovbaapi/ooo/vba/word/XStyles \
	oovbaapi/ooo/vba/word/XSystem \
	oovbaapi/ooo/vba/word/XTable \
	oovbaapi/ooo/vba/word/XTableOfContents \
	oovbaapi/ooo/vba/word/XTables \
	oovbaapi/ooo/vba/word/XTablesOfContents \
	oovbaapi/ooo/vba/word/XTabStop \
	oovbaapi/ooo/vba/word/XTabStops \
	oovbaapi/ooo/vba/word/XTemplate \
	oovbaapi/ooo/vba/word/XVariable \
	oovbaapi/ooo/vba/word/XVariables \
	oovbaapi/ooo/vba/word/XView \
	oovbaapi/ooo/vba/word/XWindow \
	oovbaapi/ooo/vba/word/XWrapFormat \
    oovbaapi/ooo/vba/FormShowConstants \
    oovbaapi/ooo/vba/VbAppWinStyle \
    oovbaapi/ooo/vba/VbCalendar \
    oovbaapi/ooo/vba/VbCallType \
    oovbaapi/ooo/vba/VbCompareMethod \
    oovbaapi/ooo/vba/VbDateTimeFormat \
    oovbaapi/ooo/vba/VbDayOfWeek \
    oovbaapi/ooo/vba/VbFileAttribute \
    oovbaapi/ooo/vba/VbFirstWeekOfYear \
    oovbaapi/ooo/vba/VbIMEStatus \
    oovbaapi/ooo/vba/VbMsgBoxResult \
    oovbaapi/ooo/vba/VbMsgBoxStyle \
    oovbaapi/ooo/vba/VbQueryClose \
    oovbaapi/ooo/vba/VbStrConv \
    oovbaapi/ooo/vba/VbTriState \
    oovbaapi/ooo/vba/VbVarType \
    oovbaapi/ooo/vba/access/AcCloseSave \
    oovbaapi/ooo/vba/access/AcColorIndex \
    oovbaapi/ooo/vba/access/AcCommand \
    oovbaapi/ooo/vba/access/AcControlType \
    oovbaapi/ooo/vba/access/AcCurrentView \
    oovbaapi/ooo/vba/access/AcDataAccessPageView \
    oovbaapi/ooo/vba/access/AcDataObjectType \
    oovbaapi/ooo/vba/access/AcDataTransferType \
    oovbaapi/ooo/vba/access/AcDefView \
    oovbaapi/ooo/vba/access/AcExportXMLEncoding \
    oovbaapi/ooo/vba/access/AcExportXMLObjectType \
    oovbaapi/ooo/vba/access/AcExportXMLOtherFlags \
    oovbaapi/ooo/vba/access/AcExportXMLSchemaFormat \
    oovbaapi/ooo/vba/access/AcFileFormat \
    oovbaapi/ooo/vba/access/AcFilterType \
    oovbaapi/ooo/vba/access/AcFindField \
    oovbaapi/ooo/vba/access/AcFindMatch \
    oovbaapi/ooo/vba/access/AcFormOpenDataMode \
    oovbaapi/ooo/vba/access/AcFormView \
    oovbaapi/ooo/vba/access/AcFormatConditionOperator \
    oovbaapi/ooo/vba/access/AcFormatConditionType \
    oovbaapi/ooo/vba/access/AcHyperlinkPart \
    oovbaapi/ooo/vba/access/AcImeMode \
    oovbaapi/ooo/vba/access/AcImeSentenceMode \
    oovbaapi/ooo/vba/access/AcImportXMLOption \
    oovbaapi/ooo/vba/access/AcModuleType \
    oovbaapi/ooo/vba/access/AcObjectType \
    oovbaapi/ooo/vba/access/AcOpenDataMode \
    oovbaapi/ooo/vba/access/AcOutputObjectType \
    oovbaapi/ooo/vba/access/AcPrintColor \
    oovbaapi/ooo/vba/access/AcPrintDuplex \
    oovbaapi/ooo/vba/access/AcPrintItemLayout \
    oovbaapi/ooo/vba/access/AcPrintObjQuality \
    oovbaapi/ooo/vba/access/AcPrintOrientation \
    oovbaapi/ooo/vba/access/AcPrintPaperBin \
    oovbaapi/ooo/vba/access/AcPrintPaperSize \
    oovbaapi/ooo/vba/access/AcPrintQuality \
    oovbaapi/ooo/vba/access/AcPrintRange \
    oovbaapi/ooo/vba/access/AcProjectType \
    oovbaapi/ooo/vba/access/AcQuitOption \
    oovbaapi/ooo/vba/access/AcRecord \
    oovbaapi/ooo/vba/access/AcSearchDirection \
    oovbaapi/ooo/vba/access/AcSection \
    oovbaapi/ooo/vba/access/AcSendObjectType \
    oovbaapi/ooo/vba/access/AcShowToolbar \
    oovbaapi/ooo/vba/access/AcSpreadSheetType \
    oovbaapi/ooo/vba/access/AcSysCmdAction \
    oovbaapi/ooo/vba/access/AcTextTransferType \
    oovbaapi/ooo/vba/access/AcTransformXMLScriptOption \
    oovbaapi/ooo/vba/access/AcView \
    oovbaapi/ooo/vba/access/AcWindowMode \
    oovbaapi/ooo/vba/access/ProcKind \
    oovbaapi/ooo/vba/access/RefKind \
    oovbaapi/ooo/vba/adodb/ADCPROP_ASYNCTHREADPRIORITY_ENUM \
    oovbaapi/ooo/vba/adodb/ADCPROP_AUTORECALC_ENUM \
    oovbaapi/ooo/vba/adodb/ADCPROP_UPDATECRITERIA_ENUM \
    oovbaapi/ooo/vba/adodb/AffectEnum \
    oovbaapi/ooo/vba/adodb/BookmarkEnum \
    oovbaapi/ooo/vba/adodb/CEResyncEnum \
    oovbaapi/ooo/vba/adodb/CommandTypeEnum \
    oovbaapi/ooo/vba/adodb/CompareEnum \
    oovbaapi/ooo/vba/adodb/ConnectModeEnum \
    oovbaapi/ooo/vba/adodb/ConnectOptionEnum \
    oovbaapi/ooo/vba/adodb/ConnectPromptEnum \
    oovbaapi/ooo/vba/adodb/CursorLocationEnum \
    oovbaapi/ooo/vba/adodb/CursorOptionEnum \
    oovbaapi/ooo/vba/adodb/CursorTypeEnum \
    oovbaapi/ooo/vba/adodb/ErrorValueEnum \
    oovbaapi/ooo/vba/adodb/EventReasonEnum \
    oovbaapi/ooo/vba/adodb/EventStatusEnum \
    oovbaapi/ooo/vba/adodb/ExecuteOptionEnum \
    oovbaapi/ooo/vba/adodb/FilterGroupEnum \
    oovbaapi/ooo/vba/adodb/GetRowsOptionEnum \
    oovbaapi/ooo/vba/adodb/IsolationLevelEnum \
    oovbaapi/ooo/vba/adodb/MarshalOptionsEnum \
    oovbaapi/ooo/vba/adodb/ObjectStateEnum \
    oovbaapi/ooo/vba/adodb/ParameterAttributesEnum \
    oovbaapi/ooo/vba/adodb/PersistFormatEnum \
    oovbaapi/ooo/vba/adodb/PositionEnum \
    oovbaapi/ooo/vba/adodb/PropertyAttributesEnum \
    oovbaapi/ooo/vba/adodb/ResyncEnum \
    oovbaapi/ooo/vba/adodb/SchemaEnum \
    oovbaapi/ooo/vba/adodb/SearchDirectionEnum \
    oovbaapi/ooo/vba/adodb/SeekEnum \
    oovbaapi/ooo/vba/adodb/StringFormatEnum \
    oovbaapi/ooo/vba/adodb/XactAttributeEnum \
    oovbaapi/ooo/vba/dao/CollatingOrderEnum \
    oovbaapi/ooo/vba/dao/CommitTransOptionsEnum \
    oovbaapi/ooo/vba/dao/CursorDriverEnum \
    oovbaapi/ooo/vba/dao/DataTypeEnum \
    oovbaapi/ooo/vba/dao/DatabaseTypeEnum \
    oovbaapi/ooo/vba/dao/DriverPromptEnum \
    oovbaapi/ooo/vba/dao/EditModeEnum \
    oovbaapi/ooo/vba/dao/FieldAttributeEnum \
    oovbaapi/ooo/vba/dao/IdleEnum \
    oovbaapi/ooo/vba/dao/LockTypeEnum \
    oovbaapi/ooo/vba/dao/ParameterDirectionEnum \
    oovbaapi/ooo/vba/dao/PermissionEnum \
    oovbaapi/ooo/vba/dao/QueryDefStateEnum \
    oovbaapi/ooo/vba/dao/QueryDefTypeEnum \
    oovbaapi/ooo/vba/dao/RecordStatusEnum \
    oovbaapi/ooo/vba/dao/RecordsetOptionEnum \
    oovbaapi/ooo/vba/dao/RecordsetTypeEnum \
    oovbaapi/ooo/vba/dao/RelationAttributeEnum \
    oovbaapi/ooo/vba/dao/ReplicaTypeEnum \
    oovbaapi/ooo/vba/dao/SetOptionEnum \
    oovbaapi/ooo/vba/dao/SynchronizeTypeEnum \
    oovbaapi/ooo/vba/dao/TableDefAttributeEnum \
    oovbaapi/ooo/vba/dao/UpdateCriteriaEnum \
    oovbaapi/ooo/vba/dao/UpdateTypeEnum \
    oovbaapi/ooo/vba/dao/WorkspaceTypeEnum \
    oovbaapi/ooo/vba/excel/Constants \
    oovbaapi/ooo/vba/excel/XlApplicationInternational \
    oovbaapi/ooo/vba/excel/XlApplyNamesOrder \
    oovbaapi/ooo/vba/excel/XlArabicModes \
    oovbaapi/ooo/vba/excel/XlArrangeStyle \
    oovbaapi/ooo/vba/excel/XlArrowHeadLength \
    oovbaapi/ooo/vba/excel/XlArrowHeadStyle \
    oovbaapi/ooo/vba/excel/XlArrowHeadWidth \
    oovbaapi/ooo/vba/excel/XlAutoFillType \
    oovbaapi/ooo/vba/excel/XlAutoFilterOperator \
    oovbaapi/ooo/vba/excel/XlAxisCrosses \
    oovbaapi/ooo/vba/excel/XlAxisGroup \
    oovbaapi/ooo/vba/excel/XlAxisType \
    oovbaapi/ooo/vba/excel/XlBackground \
    oovbaapi/ooo/vba/excel/XlBarShape \
    oovbaapi/ooo/vba/excel/XlBorderWeight \
    oovbaapi/ooo/vba/excel/XlBordersIndex \
    oovbaapi/ooo/vba/excel/XlBuiltInDialog \
    oovbaapi/ooo/vba/excel/XlCVError \
    oovbaapi/ooo/vba/excel/XlCalculatedMemberType \
    oovbaapi/ooo/vba/excel/XlCalculation \
    oovbaapi/ooo/vba/excel/XlCalculationInterruptKey \
    oovbaapi/ooo/vba/excel/XlCalculationState \
    oovbaapi/ooo/vba/excel/XlCategoryType \
    oovbaapi/ooo/vba/excel/XlCellInsertionMode \
    oovbaapi/ooo/vba/excel/XlCellType \
    oovbaapi/ooo/vba/excel/XlChartGallery \
    oovbaapi/ooo/vba/excel/XlChartItem \
    oovbaapi/ooo/vba/excel/XlChartLocation \
    oovbaapi/ooo/vba/excel/XlChartPicturePlacement \
    oovbaapi/ooo/vba/excel/XlChartPictureType \
    oovbaapi/ooo/vba/excel/XlChartSplitType \
    oovbaapi/ooo/vba/excel/XlChartType \
    oovbaapi/ooo/vba/excel/XlClipboardFormat \
    oovbaapi/ooo/vba/excel/XlCmdType \
    oovbaapi/ooo/vba/excel/XlColorIndex \
    oovbaapi/ooo/vba/excel/XlColumnDataType \
    oovbaapi/ooo/vba/excel/XlCommandUnderlines \
    oovbaapi/ooo/vba/excel/XlCommentDisplayMode \
    oovbaapi/ooo/vba/excel/XlConsolidationFunction \
    oovbaapi/ooo/vba/excel/XlCopyPictureFormat \
    oovbaapi/ooo/vba/excel/XlCorruptLoad \
    oovbaapi/ooo/vba/excel/XlCreator \
    oovbaapi/ooo/vba/excel/XlCubeFieldType \
    oovbaapi/ooo/vba/excel/XlCutCopyMode \
    oovbaapi/ooo/vba/excel/XlDVAlertStyle \
    oovbaapi/ooo/vba/excel/XlDVType \
    oovbaapi/ooo/vba/excel/XlDataLabelPosition \
    oovbaapi/ooo/vba/excel/XlDataLabelSeparator \
    oovbaapi/ooo/vba/excel/XlDataLabelsType \
    oovbaapi/ooo/vba/excel/XlDataSeriesDate \
    oovbaapi/ooo/vba/excel/XlDataSeriesType \
    oovbaapi/ooo/vba/excel/XlDeleteShiftDirection \
    oovbaapi/ooo/vba/excel/XlDirection \
    oovbaapi/ooo/vba/excel/XlDisplayBlanksAs \
    oovbaapi/ooo/vba/excel/XlDisplayDrawingObjects \
    oovbaapi/ooo/vba/excel/XlDisplayUnit \
    oovbaapi/ooo/vba/excel/XlEditionFormat \
    oovbaapi/ooo/vba/excel/XlEditionOptionsOption \
    oovbaapi/ooo/vba/excel/XlEditionType \
    oovbaapi/ooo/vba/excel/XlEnableCancelKey \
    oovbaapi/ooo/vba/excel/XlEnableSelection \
    oovbaapi/ooo/vba/excel/XlEndStyleCap \
    oovbaapi/ooo/vba/excel/XlErrorBarDirection \
    oovbaapi/ooo/vba/excel/XlErrorBarInclude \
    oovbaapi/ooo/vba/excel/XlErrorBarType \
    oovbaapi/ooo/vba/excel/XlErrorChecks \
    oovbaapi/ooo/vba/excel/XlFileAccess \
    oovbaapi/ooo/vba/excel/XlFileFormat \
    oovbaapi/ooo/vba/excel/XlFillWith \
    oovbaapi/ooo/vba/excel/XlFilterAction \
    oovbaapi/ooo/vba/excel/XlFindLookIn \
    oovbaapi/ooo/vba/excel/XlFormControl \
    oovbaapi/ooo/vba/excel/XlFormatConditionOperator \
    oovbaapi/ooo/vba/excel/XlFormatConditionType \
    oovbaapi/ooo/vba/excel/XlFormulaLabel \
    oovbaapi/ooo/vba/excel/XlHAlign \
    oovbaapi/ooo/vba/excel/XlHebrewModes \
    oovbaapi/ooo/vba/excel/XlHighlightChangesTime \
    oovbaapi/ooo/vba/excel/XlHtmlType \
    oovbaapi/ooo/vba/excel/XlIMEMode \
    oovbaapi/ooo/vba/excel/XlImportDataAs \
    oovbaapi/ooo/vba/excel/XlInsertFormatOrigin \
    oovbaapi/ooo/vba/excel/XlInsertShiftDirection \
    oovbaapi/ooo/vba/excel/XlLayoutFormType \
    oovbaapi/ooo/vba/excel/XlLegendPosition \
    oovbaapi/ooo/vba/excel/XlLineStyle \
    oovbaapi/ooo/vba/excel/XlLink \
    oovbaapi/ooo/vba/excel/XlLinkInfo \
    oovbaapi/ooo/vba/excel/XlLinkInfoType \
    oovbaapi/ooo/vba/excel/XlLinkStatus \
    oovbaapi/ooo/vba/excel/XlLinkType \
    oovbaapi/ooo/vba/excel/XlListConflict \
    oovbaapi/ooo/vba/excel/XlListDataType \
    oovbaapi/ooo/vba/excel/XlListObjectSourceType \
    oovbaapi/ooo/vba/excel/XlLocationInTable \
    oovbaapi/ooo/vba/excel/XlLookAt \
    oovbaapi/ooo/vba/excel/XlMSApplication \
    oovbaapi/ooo/vba/excel/XlMailSystem \
    oovbaapi/ooo/vba/excel/XlMarkerStyle \
    oovbaapi/ooo/vba/excel/XlMouseButton \
    oovbaapi/ooo/vba/excel/XlMousePointer \
    oovbaapi/ooo/vba/excel/XlOLEType \
    oovbaapi/ooo/vba/excel/XlOLEVerb \
    oovbaapi/ooo/vba/excel/XlObjectSize \
    oovbaapi/ooo/vba/excel/XlOrder \
    oovbaapi/ooo/vba/excel/XlOrientation \
    oovbaapi/ooo/vba/excel/XlPTSelectionMode \
    oovbaapi/ooo/vba/excel/XlPageBreak \
    oovbaapi/ooo/vba/excel/XlPageBreakExtent \
    oovbaapi/ooo/vba/excel/XlPageOrientation \
    oovbaapi/ooo/vba/excel/XlPaperSize \
    oovbaapi/ooo/vba/excel/XlParameterDataType \
    oovbaapi/ooo/vba/excel/XlParameterType \
    oovbaapi/ooo/vba/excel/XlPasteSpecialOperation \
    oovbaapi/ooo/vba/excel/XlPasteType \
    oovbaapi/ooo/vba/excel/XlPattern \
    oovbaapi/ooo/vba/excel/XlPhoneticAlignment \
    oovbaapi/ooo/vba/excel/XlPhoneticCharacterType \
    oovbaapi/ooo/vba/excel/XlPictureAppearance \
    oovbaapi/ooo/vba/excel/XlPictureConvertorType \
    oovbaapi/ooo/vba/excel/XlPivotCellType \
    oovbaapi/ooo/vba/excel/XlPivotFieldCalculation \
    oovbaapi/ooo/vba/excel/XlPivotFieldDataType \
    oovbaapi/ooo/vba/excel/XlPivotFieldOrientation \
    oovbaapi/ooo/vba/excel/XlPivotFormatType \
    oovbaapi/ooo/vba/excel/XlPivotTableMissingItems \
    oovbaapi/ooo/vba/excel/XlPivotTableSourceType \
    oovbaapi/ooo/vba/excel/XlPivotTableVersionList \
    oovbaapi/ooo/vba/excel/XlPlacement \
    oovbaapi/ooo/vba/excel/XlPlatform \
    oovbaapi/ooo/vba/excel/XlPrintErrors \
    oovbaapi/ooo/vba/excel/XlPrintLocation \
    oovbaapi/ooo/vba/excel/XlPriority \
    oovbaapi/ooo/vba/excel/XlQueryType \
    oovbaapi/ooo/vba/excel/XlRangeAutoFormat \
    oovbaapi/ooo/vba/excel/XlRangeValueDataType \
    oovbaapi/ooo/vba/excel/XlReferenceStyle \
    oovbaapi/ooo/vba/excel/XlReferenceType \
    oovbaapi/ooo/vba/excel/XlRobustConnect \
    oovbaapi/ooo/vba/excel/XlRoutingSlipDelivery \
    oovbaapi/ooo/vba/excel/XlRoutingSlipStatus \
    oovbaapi/ooo/vba/excel/XlRowCol \
    oovbaapi/ooo/vba/excel/XlRunAutoMacro \
    oovbaapi/ooo/vba/excel/XlSaveAction \
    oovbaapi/ooo/vba/excel/XlSaveAsAccessMode \
    oovbaapi/ooo/vba/excel/XlSaveConflictResolution \
    oovbaapi/ooo/vba/excel/XlScaleType \
    oovbaapi/ooo/vba/excel/XlSearchDirection \
    oovbaapi/ooo/vba/excel/XlSearchOrder \
    oovbaapi/ooo/vba/excel/XlSearchWithin \
    oovbaapi/ooo/vba/excel/XlSheetType \
    oovbaapi/ooo/vba/excel/XlSheetVisibility \
    oovbaapi/ooo/vba/excel/XlSizeRepresents \
    oovbaapi/ooo/vba/excel/XlSmartTagControlType \
    oovbaapi/ooo/vba/excel/XlSmartTagDisplayMode \
    oovbaapi/ooo/vba/excel/XlSortDataOption \
    oovbaapi/ooo/vba/excel/XlSortMethod \
    oovbaapi/ooo/vba/excel/XlSortMethodOld \
    oovbaapi/ooo/vba/excel/XlSortOrder \
    oovbaapi/ooo/vba/excel/XlSortOrientation \
    oovbaapi/ooo/vba/excel/XlSortType \
    oovbaapi/ooo/vba/excel/XlSourceType \
    oovbaapi/ooo/vba/excel/XlSpeakDirection \
    oovbaapi/ooo/vba/excel/XlSpecialCellsValue \
    oovbaapi/ooo/vba/excel/XlSubscribeToFormat \
    oovbaapi/ooo/vba/excel/XlSubtototalLocationType \
    oovbaapi/ooo/vba/excel/XlSummaryColumn \
    oovbaapi/ooo/vba/excel/XlSummaryReportType \
    oovbaapi/ooo/vba/excel/XlSummaryRow \
    oovbaapi/ooo/vba/excel/XlTabPosition \
    oovbaapi/ooo/vba/excel/XlTextParsingType \
    oovbaapi/ooo/vba/excel/XlTextQualifier \
    oovbaapi/ooo/vba/excel/XlTextVisualLayoutType \
    oovbaapi/ooo/vba/excel/XlTickLabelOrientation \
    oovbaapi/ooo/vba/excel/XlTickLabelPosition \
    oovbaapi/ooo/vba/excel/XlTickMark \
    oovbaapi/ooo/vba/excel/XlTimeUnit \
    oovbaapi/ooo/vba/excel/XlToolbarProtection \
    oovbaapi/ooo/vba/excel/XlTotalsCalculation \
    oovbaapi/ooo/vba/excel/XlTrendlineType \
    oovbaapi/ooo/vba/excel/XlUnderlineStyle \
    oovbaapi/ooo/vba/excel/XlUpdateLinks \
    oovbaapi/ooo/vba/excel/XlVAlign \
    oovbaapi/ooo/vba/excel/XlWBATemplate \
    oovbaapi/ooo/vba/excel/XlWebFormatting \
    oovbaapi/ooo/vba/excel/XlWebSelectionType \
    oovbaapi/ooo/vba/excel/XlWindowState \
    oovbaapi/ooo/vba/excel/XlWindowType \
    oovbaapi/ooo/vba/excel/XlWindowView \
    oovbaapi/ooo/vba/excel/XlXLMMacroType \
    oovbaapi/ooo/vba/excel/XlXmlExportResult \
    oovbaapi/ooo/vba/excel/XlXmlImportResult \
    oovbaapi/ooo/vba/excel/XlXmlLoadOption \
    oovbaapi/ooo/vba/excel/XlYesNoGuess \
    oovbaapi/ooo/vba/msforms/fmAction \
    oovbaapi/ooo/vba/msforms/fmAlignment \
    oovbaapi/ooo/vba/msforms/fmBackStyle \
    oovbaapi/ooo/vba/msforms/fmBorderStyle \
    oovbaapi/ooo/vba/msforms/fmBorders \
    oovbaapi/ooo/vba/msforms/fmButtonEffect \
    oovbaapi/ooo/vba/msforms/fmButtonStyle \
    oovbaapi/ooo/vba/msforms/fmCycle \
    oovbaapi/ooo/vba/msforms/fmDisplayStyle \
    oovbaapi/ooo/vba/msforms/fmDragBehavior \
    oovbaapi/ooo/vba/msforms/fmDragState \
    oovbaapi/ooo/vba/msforms/fmDropButtonStyle \
    oovbaapi/ooo/vba/msforms/fmDropEffect \
    oovbaapi/ooo/vba/msforms/fmEnterFieldBehavior \
    oovbaapi/ooo/vba/msforms/fmIMEMode \
    oovbaapi/ooo/vba/msforms/fmLayoutEffect \
    oovbaapi/ooo/vba/msforms/fmListStyle \
    oovbaapi/ooo/vba/msforms/fmMatchEntry \
    oovbaapi/ooo/vba/msforms/fmMode \
    oovbaapi/ooo/vba/msforms/fmMousePointer \
    oovbaapi/ooo/vba/msforms/fmMultiSelect \
    oovbaapi/ooo/vba/msforms/fmOrientation \
    oovbaapi/ooo/vba/msforms/fmPicPosition \
    oovbaapi/ooo/vba/msforms/fmPictureAlignment \
    oovbaapi/ooo/vba/msforms/fmPicturePosition \
    oovbaapi/ooo/vba/msforms/fmPictureSizeMode \
    oovbaapi/ooo/vba/msforms/fmScrollAction \
    oovbaapi/ooo/vba/msforms/fmScrollBars \
    oovbaapi/ooo/vba/msforms/fmShowDropButtonWhen \
    oovbaapi/ooo/vba/msforms/fmShowListWhen \
    oovbaapi/ooo/vba/msforms/fmSnapPoint \
    oovbaapi/ooo/vba/msforms/fmSpecialEffect \
    oovbaapi/ooo/vba/msforms/fmStyle \
    oovbaapi/ooo/vba/msforms/fmTabOrientation \
    oovbaapi/ooo/vba/msforms/fmTabStyle \
    oovbaapi/ooo/vba/msforms/fmTextAlign \
    oovbaapi/ooo/vba/msforms/fmTransitionEffect \
    oovbaapi/ooo/vba/msforms/fmVerticalScrollBarSide \
    oovbaapi/ooo/vba/msforms/fmZOrder \
    oovbaapi/ooo/vba/office/DocProperties \
    oovbaapi/ooo/vba/office/MailFormat \
    oovbaapi/ooo/vba/office/MsoAlertButtonType \
    oovbaapi/ooo/vba/office/MsoAlertCancelType \
    oovbaapi/ooo/vba/office/MsoAlertDefaultType \
    oovbaapi/ooo/vba/office/MsoAlertIconType \
    oovbaapi/ooo/vba/office/MsoAlignCmd \
    oovbaapi/ooo/vba/office/MsoAnimationType \
    oovbaapi/ooo/vba/office/MsoAppLanguageID \
    oovbaapi/ooo/vba/office/MsoArrowheadLength \
    oovbaapi/ooo/vba/office/MsoArrowheadStyle \
    oovbaapi/ooo/vba/office/MsoArrowheadWidth \
    oovbaapi/ooo/vba/office/MsoAutoShapeType \
    oovbaapi/ooo/vba/office/MsoAutomationSecurity \
    oovbaapi/ooo/vba/office/MsoBalloonButtonType \
    oovbaapi/ooo/vba/office/MsoBalloonErrorType \
    oovbaapi/ooo/vba/office/MsoBalloonType \
    oovbaapi/ooo/vba/office/MsoBarPosition \
    oovbaapi/ooo/vba/office/MsoBarProtection \
    oovbaapi/ooo/vba/office/MsoBarRow \
    oovbaapi/ooo/vba/office/MsoBarType \
    oovbaapi/ooo/vba/office/MsoBlackWhiteMode \
    oovbaapi/ooo/vba/office/MsoButtonSetType \
    oovbaapi/ooo/vba/office/MsoButtonState \
    oovbaapi/ooo/vba/office/MsoButtonStyle \
    oovbaapi/ooo/vba/office/MsoButtonStyleHidden \
    oovbaapi/ooo/vba/office/MsoCalloutAngleType \
    oovbaapi/ooo/vba/office/MsoCalloutDropType \
    oovbaapi/ooo/vba/office/MsoCalloutType \
    oovbaapi/ooo/vba/office/MsoCharacterSet \
    oovbaapi/ooo/vba/office/MsoColorType \
    oovbaapi/ooo/vba/office/MsoComboStyle \
    oovbaapi/ooo/vba/office/MsoCommandBarButtonHyperlinkType \
    oovbaapi/ooo/vba/office/MsoCondition \
    oovbaapi/ooo/vba/office/MsoConnector \
    oovbaapi/ooo/vba/office/MsoConnectorType \
    oovbaapi/ooo/vba/office/MsoControlOLEUsage \
    oovbaapi/ooo/vba/office/MsoControlType \
    oovbaapi/ooo/vba/office/MsoDiagramNodeType \
    oovbaapi/ooo/vba/office/MsoDiagramType \
    oovbaapi/ooo/vba/office/MsoDistributeCmd \
    oovbaapi/ooo/vba/office/MsoDocProperties \
    oovbaapi/ooo/vba/office/MsoEditingType \
    oovbaapi/ooo/vba/office/MsoEncoding \
    oovbaapi/ooo/vba/office/MsoExtraInfoMethod \
    oovbaapi/ooo/vba/office/MsoExtrusionColorType \
    oovbaapi/ooo/vba/office/MsoFarEastLineBreakLanguageID \
    oovbaapi/ooo/vba/office/MsoFeatureInstall \
    oovbaapi/ooo/vba/office/MsoFileDialogType \
    oovbaapi/ooo/vba/office/MsoFileDialogView \
    oovbaapi/ooo/vba/office/MsoFileFindListBy \
    oovbaapi/ooo/vba/office/MsoFileFindOptions \
    oovbaapi/ooo/vba/office/MsoFileFindSortBy \
    oovbaapi/ooo/vba/office/MsoFileFindView \
    oovbaapi/ooo/vba/office/MsoFileNewAction \
    oovbaapi/ooo/vba/office/MsoFileNewSection \
    oovbaapi/ooo/vba/office/MsoFileType \
    oovbaapi/ooo/vba/office/MsoFillType \
    oovbaapi/ooo/vba/office/MsoFilterComparison \
    oovbaapi/ooo/vba/office/MsoFilterConjunction \
    oovbaapi/ooo/vba/office/MsoFlipCmd \
    oovbaapi/ooo/vba/office/MsoGradientColorType \
    oovbaapi/ooo/vba/office/MsoGradientStyle \
    oovbaapi/ooo/vba/office/MsoHTMLProjectOpen \
    oovbaapi/ooo/vba/office/MsoHTMLProjectState \
    oovbaapi/ooo/vba/office/MsoHorizontalAnchor \
    oovbaapi/ooo/vba/office/MsoHyperlinkType \
    oovbaapi/ooo/vba/office/MsoIconType \
    oovbaapi/ooo/vba/office/MsoLanguageID \
    oovbaapi/ooo/vba/office/MsoLanguageIDHidden \
    oovbaapi/ooo/vba/office/MsoLastModified \
    oovbaapi/ooo/vba/office/MsoLineDashStyle \
    oovbaapi/ooo/vba/office/MsoLineStyle \
    oovbaapi/ooo/vba/office/MsoMenuAnimation \
    oovbaapi/ooo/vba/office/MsoMixedType \
    oovbaapi/ooo/vba/office/MsoModeType \
    oovbaapi/ooo/vba/office/MsoMoveRow \
    oovbaapi/ooo/vba/office/MsoOLEMenuGroup \
    oovbaapi/ooo/vba/office/MsoOrgChartLayoutType \
    oovbaapi/ooo/vba/office/MsoOrgChartOrientation \
    oovbaapi/ooo/vba/office/MsoOrientation \
    oovbaapi/ooo/vba/office/MsoPatternType \
    oovbaapi/ooo/vba/office/MsoPermission \
    oovbaapi/ooo/vba/office/MsoPictureColorType \
    oovbaapi/ooo/vba/office/MsoPresetExtrusionDirection \
    oovbaapi/ooo/vba/office/MsoPresetGradientType \
    oovbaapi/ooo/vba/office/MsoPresetLightingDirection \
    oovbaapi/ooo/vba/office/MsoPresetLightingSoftness \
    oovbaapi/ooo/vba/office/MsoPresetMaterial \
    oovbaapi/ooo/vba/office/MsoPresetTextEffect \
    oovbaapi/ooo/vba/office/MsoPresetTextEffectShape \
    oovbaapi/ooo/vba/office/MsoPresetTexture \
    oovbaapi/ooo/vba/office/MsoPresetThreeDFormat \
    oovbaapi/ooo/vba/office/MsoRelativeNodePosition \
    oovbaapi/ooo/vba/office/MsoScaleFrom \
    oovbaapi/ooo/vba/office/MsoScreenSize \
    oovbaapi/ooo/vba/office/MsoScriptLanguage \
    oovbaapi/ooo/vba/office/MsoScriptLocation \
    oovbaapi/ooo/vba/office/MsoSearchIn \
    oovbaapi/ooo/vba/office/MsoSegmentType \
    oovbaapi/ooo/vba/office/MsoShadowType \
    oovbaapi/ooo/vba/office/MsoShapeType \
    oovbaapi/ooo/vba/office/MsoSharedWorkspaceTaskPriority \
    oovbaapi/ooo/vba/office/MsoSharedWorkspaceTaskStatus \
    oovbaapi/ooo/vba/office/MsoSortBy \
    oovbaapi/ooo/vba/office/MsoSortOrder \
    oovbaapi/ooo/vba/office/MsoSyncAvailableType \
    oovbaapi/ooo/vba/office/MsoSyncCompareType \
    oovbaapi/ooo/vba/office/MsoSyncConflictResolutionType \
    oovbaapi/ooo/vba/office/MsoSyncErrorType \
    oovbaapi/ooo/vba/office/MsoSyncEventType \
    oovbaapi/ooo/vba/office/MsoSyncStatusType \
    oovbaapi/ooo/vba/office/MsoSyncVersionType \
    oovbaapi/ooo/vba/office/MsoTargetBrowser \
    oovbaapi/ooo/vba/office/MsoTextEffectAlignment \
    oovbaapi/ooo/vba/office/MsoTextOrientation \
    oovbaapi/ooo/vba/office/MsoTextureType \
    oovbaapi/ooo/vba/office/MsoTriState \
    oovbaapi/ooo/vba/office/MsoVerticalAnchor \
    oovbaapi/ooo/vba/office/MsoWizardActType \
    oovbaapi/ooo/vba/office/MsoWizardMsgType \
    oovbaapi/ooo/vba/office/MsoZOrderCmd \
    oovbaapi/ooo/vba/powerpoint/MsoAnimAccumulate \
    oovbaapi/ooo/vba/powerpoint/MsoAnimAdditive \
    oovbaapi/ooo/vba/powerpoint/MsoAnimAfterEffect \
    oovbaapi/ooo/vba/powerpoint/MsoAnimCommandType \
    oovbaapi/ooo/vba/powerpoint/MsoAnimDirection \
    oovbaapi/ooo/vba/powerpoint/MsoAnimEffect \
    oovbaapi/ooo/vba/powerpoint/MsoAnimEffectAfter \
    oovbaapi/ooo/vba/powerpoint/MsoAnimEffectRestart \
    oovbaapi/ooo/vba/powerpoint/MsoAnimFilterEffectSubtype \
    oovbaapi/ooo/vba/powerpoint/MsoAnimFilterEffectType \
    oovbaapi/ooo/vba/powerpoint/MsoAnimProperty \
    oovbaapi/ooo/vba/powerpoint/MsoAnimTextUnitEffect \
    oovbaapi/ooo/vba/powerpoint/MsoAnimTriggerType \
    oovbaapi/ooo/vba/powerpoint/MsoAnimType \
    oovbaapi/ooo/vba/powerpoint/MsoAnimateByLevel \
    oovbaapi/ooo/vba/powerpoint/PpActionType \
    oovbaapi/ooo/vba/powerpoint/PpAdvanceMode \
    oovbaapi/ooo/vba/powerpoint/PpAfterEffect \
    oovbaapi/ooo/vba/powerpoint/PpAlertLevel \
    oovbaapi/ooo/vba/powerpoint/PpArrangeStyle \
    oovbaapi/ooo/vba/powerpoint/PpAutoSize \
    oovbaapi/ooo/vba/powerpoint/PpBaselineAlignment \
    oovbaapi/ooo/vba/powerpoint/PpBorderType \
    oovbaapi/ooo/vba/powerpoint/PpBulletType \
    oovbaapi/ooo/vba/powerpoint/PpChangeCase \
    oovbaapi/ooo/vba/powerpoint/PpChartUnitEffect \
    oovbaapi/ooo/vba/powerpoint/PpColorSchemeIndex \
    oovbaapi/ooo/vba/powerpoint/PpDateTimeFormat \
    oovbaapi/ooo/vba/powerpoint/PpDirection \
    oovbaapi/ooo/vba/powerpoint/PpEntryEffect \
    oovbaapi/ooo/vba/powerpoint/PpExportMode \
    oovbaapi/ooo/vba/powerpoint/PpFarEastLineBreakLevel \
    oovbaapi/ooo/vba/powerpoint/PpFileDialogType \
    oovbaapi/ooo/vba/powerpoint/PpFollowColors \
    oovbaapi/ooo/vba/powerpoint/PpFrameColors \
    oovbaapi/ooo/vba/powerpoint/PpHTMLVersion \
    oovbaapi/ooo/vba/powerpoint/PpIndentControl \
    oovbaapi/ooo/vba/powerpoint/PpMediaType \
    oovbaapi/ooo/vba/powerpoint/PpMouseActivation \
    oovbaapi/ooo/vba/powerpoint/PpNumberedBulletStyle \
    oovbaapi/ooo/vba/powerpoint/PpParagraphAlignment \
    oovbaapi/ooo/vba/powerpoint/PpPasteDataType \
    oovbaapi/ooo/vba/powerpoint/PpPlaceholderType \
    oovbaapi/ooo/vba/powerpoint/PpPrintColorType \
    oovbaapi/ooo/vba/powerpoint/PpPrintHandoutOrder \
    oovbaapi/ooo/vba/powerpoint/PpPrintOutputType \
    oovbaapi/ooo/vba/powerpoint/PpPrintRangeType \
    oovbaapi/ooo/vba/powerpoint/PpPublishSourceType \
    oovbaapi/ooo/vba/powerpoint/PpRevisionInfo \
    oovbaapi/ooo/vba/powerpoint/PpSaveAsFileType \
    oovbaapi/ooo/vba/powerpoint/PpSelectionType \
    oovbaapi/ooo/vba/powerpoint/PpShapeFormat \
    oovbaapi/ooo/vba/powerpoint/PpSlideLayout \
    oovbaapi/ooo/vba/powerpoint/PpSlideShowAdvanceMode \
    oovbaapi/ooo/vba/powerpoint/PpSlideShowPointerType \
    oovbaapi/ooo/vba/powerpoint/PpSlideShowRangeType \
    oovbaapi/ooo/vba/powerpoint/PpSlideShowState \
    oovbaapi/ooo/vba/powerpoint/PpSlideShowType \
    oovbaapi/ooo/vba/powerpoint/PpSlideSizeType \
    oovbaapi/ooo/vba/powerpoint/PpSoundEffectType \
    oovbaapi/ooo/vba/powerpoint/PpSoundFormatType \
    oovbaapi/ooo/vba/powerpoint/PpTabStopType \
    oovbaapi/ooo/vba/powerpoint/PpTextLevelEffect \
    oovbaapi/ooo/vba/powerpoint/PpTextStyleType \
    oovbaapi/ooo/vba/powerpoint/PpTextUnitEffect \
    oovbaapi/ooo/vba/powerpoint/PpTransitionSpeed \
    oovbaapi/ooo/vba/powerpoint/PpUpdateOption \
    oovbaapi/ooo/vba/powerpoint/PpViewType \
    oovbaapi/ooo/vba/powerpoint/PpWindowState \
    oovbaapi/ooo/vba/stdole/LoadPictureConstants \
    oovbaapi/ooo/vba/stdole/OLE_TRISTATE \
    oovbaapi/ooo/vba/word/WdAlertLevel \
    oovbaapi/ooo/vba/word/WdAnimation \
    oovbaapi/ooo/vba/word/WdAraSpeller \
    oovbaapi/ooo/vba/word/WdArabicNumeral \
    oovbaapi/ooo/vba/word/WdArrangeStyle \
    oovbaapi/ooo/vba/word/WdAutoFitBehavior \
    oovbaapi/ooo/vba/word/WdAutoMacros \
    oovbaapi/ooo/vba/word/WdAutoVersions \
    oovbaapi/ooo/vba/word/WdBaselineAlignment \
    oovbaapi/ooo/vba/word/WdBookmarkSortBy \
    oovbaapi/ooo/vba/word/WdBorderDistanceFrom \
    oovbaapi/ooo/vba/word/WdBorderType \
    oovbaapi/ooo/vba/word/WdBorderTypeHID \
    oovbaapi/ooo/vba/word/WdBreakType \
    oovbaapi/ooo/vba/word/WdBrowseTarget \
    oovbaapi/ooo/vba/word/WdBrowserLevel \
    oovbaapi/ooo/vba/word/WdBuiltInProperty \
    oovbaapi/ooo/vba/word/WdBuiltinStyle \
    oovbaapi/ooo/vba/word/WdCalendarType \
    oovbaapi/ooo/vba/word/WdCalendarTypeBi \
    oovbaapi/ooo/vba/word/WdCaptionLabelID \
    oovbaapi/ooo/vba/word/WdCaptionNumberStyle \
    oovbaapi/ooo/vba/word/WdCaptionNumberStyleHID \
    oovbaapi/ooo/vba/word/WdCaptionPosition \
    oovbaapi/ooo/vba/word/WdCellVerticalAlignment \
    oovbaapi/ooo/vba/word/WdCharacterCase \
    oovbaapi/ooo/vba/word/WdCharacterCaseHID \
    oovbaapi/ooo/vba/word/WdCharacterWidth \
    oovbaapi/ooo/vba/word/WdChevronConvertRule \
    oovbaapi/ooo/vba/word/WdCollapseDirection \
    oovbaapi/ooo/vba/word/WdColor \
    oovbaapi/ooo/vba/word/WdColorIndex \
    oovbaapi/ooo/vba/word/WdCompareTarget \
    oovbaapi/ooo/vba/word/WdCompatibility \
    oovbaapi/ooo/vba/word/WdConditionCode \
    oovbaapi/ooo/vba/word/WdConstants \
    oovbaapi/ooo/vba/word/WdContinue \
    oovbaapi/ooo/vba/word/WdCountry \
    oovbaapi/ooo/vba/word/WdCursorMovement \
    oovbaapi/ooo/vba/word/WdCursorType \
    oovbaapi/ooo/vba/word/WdCustomLabelPageSize \
    oovbaapi/ooo/vba/word/WdDateLanguage \
    oovbaapi/ooo/vba/word/WdDefaultFilePath \
    oovbaapi/ooo/vba/word/WdDefaultListBehavior \
    oovbaapi/ooo/vba/word/WdDefaultTableBehavior \
    oovbaapi/ooo/vba/word/WdDeleteCells \
    oovbaapi/ooo/vba/word/WdDeletedTextMark \
    oovbaapi/ooo/vba/word/WdDiacriticColor \
    oovbaapi/ooo/vba/word/WdDictionaryType \
    oovbaapi/ooo/vba/word/WdDictionaryTypeHID \
    oovbaapi/ooo/vba/word/WdDisableFeaturesIntroducedAfter \
    oovbaapi/ooo/vba/word/WdDocumentDirection \
    oovbaapi/ooo/vba/word/WdDocumentKind \
    oovbaapi/ooo/vba/word/WdDocumentMedium \
    oovbaapi/ooo/vba/word/WdDocumentType \
    oovbaapi/ooo/vba/word/WdDocumentViewDirection \
    oovbaapi/ooo/vba/word/WdDropPosition \
    oovbaapi/ooo/vba/word/WdEditionOption \
    oovbaapi/ooo/vba/word/WdEditionType \
    oovbaapi/ooo/vba/word/WdEditorType \
    oovbaapi/ooo/vba/word/WdEmailHTMLFidelity \
    oovbaapi/ooo/vba/word/WdEmphasisMark \
    oovbaapi/ooo/vba/word/WdEnableCancelKey \
    oovbaapi/ooo/vba/word/WdEncloseStyle \
    oovbaapi/ooo/vba/word/WdEnclosureType \
    oovbaapi/ooo/vba/word/WdEndnoteLocation \
    oovbaapi/ooo/vba/word/WdEnvelopeOrientation \
    oovbaapi/ooo/vba/word/WdFarEastLineBreakLanguageID \
    oovbaapi/ooo/vba/word/WdFarEastLineBreakLevel \
    oovbaapi/ooo/vba/word/WdFieldKind \
    oovbaapi/ooo/vba/word/WdFieldShading \
    oovbaapi/ooo/vba/word/WdFieldType \
    oovbaapi/ooo/vba/word/WdFindMatch \
    oovbaapi/ooo/vba/word/WdFindWrap \
    oovbaapi/ooo/vba/word/WdFlowDirection \
    oovbaapi/ooo/vba/word/WdFontBias \
    oovbaapi/ooo/vba/word/WdFootnoteLocation \
    oovbaapi/ooo/vba/word/WdFramePosition \
    oovbaapi/ooo/vba/word/WdFrameSizeRule \
    oovbaapi/ooo/vba/word/WdFramesetNewFrameLocation \
    oovbaapi/ooo/vba/word/WdFramesetSizeType \
    oovbaapi/ooo/vba/word/WdFramesetType \
    oovbaapi/ooo/vba/word/WdGoToDirection \
    oovbaapi/ooo/vba/word/WdGoToItem \
    oovbaapi/ooo/vba/word/WdGutterStyle \
    oovbaapi/ooo/vba/word/WdGutterStyleOld \
    oovbaapi/ooo/vba/word/WdHeaderFooterIndex \
    oovbaapi/ooo/vba/word/WdHeadingSeparator \
    oovbaapi/ooo/vba/word/WdHebSpellStart \
    oovbaapi/ooo/vba/word/WdHelpType \
    oovbaapi/ooo/vba/word/WdHelpTypeHID \
    oovbaapi/ooo/vba/word/WdHighAnsiText \
    oovbaapi/ooo/vba/word/WdHorizontalInVerticalType \
    oovbaapi/ooo/vba/word/WdHorizontalLineAlignment \
    oovbaapi/ooo/vba/word/WdHorizontalLineWidthType \
    oovbaapi/ooo/vba/word/WdIMEMode \
    oovbaapi/ooo/vba/word/WdIndexFilter \
    oovbaapi/ooo/vba/word/WdIndexFormat \
    oovbaapi/ooo/vba/word/WdIndexSortBy \
    oovbaapi/ooo/vba/word/WdIndexType \
    oovbaapi/ooo/vba/word/WdInformation \
    oovbaapi/ooo/vba/word/WdInlineShapeType \
    oovbaapi/ooo/vba/word/WdInsertCells \
    oovbaapi/ooo/vba/word/WdInsertedTextMark \
    oovbaapi/ooo/vba/word/WdInternationalIndex \
    oovbaapi/ooo/vba/word/WdJustificationMode \
    oovbaapi/ooo/vba/word/WdKana \
    oovbaapi/ooo/vba/word/WdKey \
    oovbaapi/ooo/vba/word/WdKeyCategory \
    oovbaapi/ooo/vba/word/WdLanguageID \
    oovbaapi/ooo/vba/word/WdLanguageID2000 \
    oovbaapi/ooo/vba/word/WdLayoutMode \
    oovbaapi/ooo/vba/word/WdLetterStyle \
    oovbaapi/ooo/vba/word/WdLetterheadLocation \
    oovbaapi/ooo/vba/word/WdLineEndingType \
    oovbaapi/ooo/vba/word/WdLineSpacing \
    oovbaapi/ooo/vba/word/WdLineStyle \
    oovbaapi/ooo/vba/word/WdLineType \
    oovbaapi/ooo/vba/word/WdLineWidth \
    oovbaapi/ooo/vba/word/WdLinkType \
    oovbaapi/ooo/vba/word/WdListApplyTo \
    oovbaapi/ooo/vba/word/WdListGalleryType \
    oovbaapi/ooo/vba/word/WdListLevelAlignment \
    oovbaapi/ooo/vba/word/WdListNumberStyle \
    oovbaapi/ooo/vba/word/WdListNumberStyleHID \
    oovbaapi/ooo/vba/word/WdListType \
    oovbaapi/ooo/vba/word/WdMailMergeActiveRecord \
    oovbaapi/ooo/vba/word/WdMailMergeComparison \
    oovbaapi/ooo/vba/word/WdMailMergeDataSource \
    oovbaapi/ooo/vba/word/WdMailMergeDefaultRecord \
    oovbaapi/ooo/vba/word/WdMailMergeDestination \
    oovbaapi/ooo/vba/word/WdMailMergeMailFormat \
    oovbaapi/ooo/vba/word/WdMailMergeMainDocType \
    oovbaapi/ooo/vba/word/WdMailMergeState \
    oovbaapi/ooo/vba/word/WdMailSystem \
    oovbaapi/ooo/vba/word/WdMailerPriority \
    oovbaapi/ooo/vba/word/WdMappedDataFields \
    oovbaapi/ooo/vba/word/WdMeasurementUnits \
    oovbaapi/ooo/vba/word/WdMeasurementUnitsHID \
    oovbaapi/ooo/vba/word/WdMergeSubType \
    oovbaapi/ooo/vba/word/WdMergeTarget \
    oovbaapi/ooo/vba/word/WdMonthNames \
    oovbaapi/ooo/vba/word/WdMovementType \
    oovbaapi/ooo/vba/word/WdMultipleWordConversionsMode \
    oovbaapi/ooo/vba/word/WdNewDocumentType \
    oovbaapi/ooo/vba/word/WdNoteNumberStyle \
    oovbaapi/ooo/vba/word/WdNoteNumberStyleHID \
    oovbaapi/ooo/vba/word/WdNumberStyleWordBasicBiDi \
    oovbaapi/ooo/vba/word/WdNumberType \
    oovbaapi/ooo/vba/word/WdNumberingRule \
    oovbaapi/ooo/vba/word/WdOLEPlacement \
    oovbaapi/ooo/vba/word/WdOLEType \
    oovbaapi/ooo/vba/word/WdOLEVerb \
    oovbaapi/ooo/vba/word/WdOpenFormat \
    oovbaapi/ooo/vba/word/WdOrganizerObject \
    oovbaapi/ooo/vba/word/WdOrientation \
    oovbaapi/ooo/vba/word/WdOriginalFormat \
    oovbaapi/ooo/vba/word/WdOutlineLevel \
    oovbaapi/ooo/vba/word/WdPageBorderArt \
    oovbaapi/ooo/vba/word/WdPageFit \
    oovbaapi/ooo/vba/word/WdPageNumberAlignment \
    oovbaapi/ooo/vba/word/WdPageNumberStyle \
    oovbaapi/ooo/vba/word/WdPageNumberStyleHID \
    oovbaapi/ooo/vba/word/WdPaperSize \
    oovbaapi/ooo/vba/word/WdPaperTray \
    oovbaapi/ooo/vba/word/WdParagraphAlignment \
    oovbaapi/ooo/vba/word/WdParagraphAlignmentHID \
    oovbaapi/ooo/vba/word/WdPartOfSpeech \
    oovbaapi/ooo/vba/word/WdPasteDataType \
    oovbaapi/ooo/vba/word/WdPhoneticGuideAlignmentType \
    oovbaapi/ooo/vba/word/WdPictureLinkType \
    oovbaapi/ooo/vba/word/WdPreferredWidthType \
    oovbaapi/ooo/vba/word/WdPrintOutItem \
    oovbaapi/ooo/vba/word/WdPrintOutPages \
    oovbaapi/ooo/vba/word/WdPrintOutRange \
    oovbaapi/ooo/vba/word/WdProofreadingErrorType \
    oovbaapi/ooo/vba/word/WdProtectionType \
    oovbaapi/ooo/vba/word/WdReadingOrder \
    oovbaapi/ooo/vba/word/WdRecoveryType \
    oovbaapi/ooo/vba/word/WdRectangleType \
    oovbaapi/ooo/vba/word/WdReferenceKind \
    oovbaapi/ooo/vba/word/WdReferenceType \
    oovbaapi/ooo/vba/word/WdRelativeHorizontalPosition \
    oovbaapi/ooo/vba/word/WdRelativeVerticalPosition \
    oovbaapi/ooo/vba/word/WdRelocate \
    oovbaapi/ooo/vba/word/WdReplace \
    oovbaapi/ooo/vba/word/WdRevisedLinesMark \
    oovbaapi/ooo/vba/word/WdRevisedPropertiesMark \
    oovbaapi/ooo/vba/word/WdRevisionType \
    oovbaapi/ooo/vba/word/WdRevisionsBalloonMargin \
    oovbaapi/ooo/vba/word/WdRevisionsBalloonPrintOrientation \
    oovbaapi/ooo/vba/word/WdRevisionsBalloonWidthType \
    oovbaapi/ooo/vba/word/WdRevisionsMode \
    oovbaapi/ooo/vba/word/WdRevisionsView \
    oovbaapi/ooo/vba/word/WdRevisionsWrap \
    oovbaapi/ooo/vba/word/WdRoutingSlipDelivery \
    oovbaapi/ooo/vba/word/WdRoutingSlipStatus \
    oovbaapi/ooo/vba/word/WdRowAlignment \
    oovbaapi/ooo/vba/word/WdRowHeightRule \
    oovbaapi/ooo/vba/word/WdRulerStyle \
    oovbaapi/ooo/vba/word/WdSalutationGender \
    oovbaapi/ooo/vba/word/WdSalutationType \
    oovbaapi/ooo/vba/word/WdSaveFormat \
    oovbaapi/ooo/vba/word/WdSaveOptions \
    oovbaapi/ooo/vba/word/WdScrollbarType \
    oovbaapi/ooo/vba/word/WdSectionDirection \
    oovbaapi/ooo/vba/word/WdSectionStart \
    oovbaapi/ooo/vba/word/WdSeekView \
    oovbaapi/ooo/vba/word/WdSelectionFlags \
    oovbaapi/ooo/vba/word/WdSelectionType \
    oovbaapi/ooo/vba/word/WdSeparatorType \
    oovbaapi/ooo/vba/word/WdShapePosition \
    oovbaapi/ooo/vba/word/WdShowFilter \
    oovbaapi/ooo/vba/word/WdSmartTagControlType \
    oovbaapi/ooo/vba/word/WdSortFieldType \
    oovbaapi/ooo/vba/word/WdSortFieldTypeHID \
    oovbaapi/ooo/vba/word/WdSortOrder \
    oovbaapi/ooo/vba/word/WdSortSeparator \
    oovbaapi/ooo/vba/word/WdSpecialPane \
    oovbaapi/ooo/vba/word/WdSpellingErrorType \
    oovbaapi/ooo/vba/word/WdSpellingWordType \
    oovbaapi/ooo/vba/word/WdStatistic \
    oovbaapi/ooo/vba/word/WdStatisticHID \
    oovbaapi/ooo/vba/word/WdStoryType \
    oovbaapi/ooo/vba/word/WdStyleSheetLinkType \
    oovbaapi/ooo/vba/word/WdStyleSheetPrecedence \
    oovbaapi/ooo/vba/word/WdStyleType \
    oovbaapi/ooo/vba/word/WdSubscriberFormats \
    oovbaapi/ooo/vba/word/WdSummaryLength \
    oovbaapi/ooo/vba/word/WdSummaryMode \
    oovbaapi/ooo/vba/word/WdTCSCConverterDirection \
    oovbaapi/ooo/vba/word/WdTabAlignment \
    oovbaapi/ooo/vba/word/WdTabLeader \
    oovbaapi/ooo/vba/word/WdTabLeaderHID \
    oovbaapi/ooo/vba/word/WdTableDirection \
    oovbaapi/ooo/vba/word/WdTableFieldSeparator \
    oovbaapi/ooo/vba/word/WdTableFormat \
    oovbaapi/ooo/vba/word/WdTableFormatApply \
    oovbaapi/ooo/vba/word/WdTablePosition \
    oovbaapi/ooo/vba/word/WdTaskPanes \
    oovbaapi/ooo/vba/word/WdTemplateType \
    oovbaapi/ooo/vba/word/WdTextFormFieldType \
    oovbaapi/ooo/vba/word/WdTextOrientation \
    oovbaapi/ooo/vba/word/WdTextOrientationHID \
    oovbaapi/ooo/vba/word/WdTextureIndex \
    oovbaapi/ooo/vba/word/WdToaFormat \
    oovbaapi/ooo/vba/word/WdTocFormat \
    oovbaapi/ooo/vba/word/WdTofFormat \
    oovbaapi/ooo/vba/word/WdTrailingCharacter \
    oovbaapi/ooo/vba/word/WdTwoLinesInOneType \
    oovbaapi/ooo/vba/word/WdUnderline \
    oovbaapi/ooo/vba/word/WdUnits \
    oovbaapi/ooo/vba/word/WdUseFormattingFrom \
    oovbaapi/ooo/vba/word/WdVerticalAlignment \
    oovbaapi/ooo/vba/word/WdViewType \
    oovbaapi/ooo/vba/word/WdViewTypeOld \
    oovbaapi/ooo/vba/word/WdVisualSelection \
    oovbaapi/ooo/vba/word/WdWindowState \
    oovbaapi/ooo/vba/word/WdWindowType \
    oovbaapi/ooo/vba/word/WdWordDialog \
    oovbaapi/ooo/vba/word/WdWordDialogHID \
    oovbaapi/ooo/vba/word/WdWordDialogTab \
    oovbaapi/ooo/vba/word/WdWordDialogTabHID \
    oovbaapi/ooo/vba/word/WdWrapSideType \
    oovbaapi/ooo/vba/word/WdWrapType \
    oovbaapi/ooo/vba/word/WdWrapTypeMerged \
    oovbaapi/ooo/vba/word/WdXMLNodeLevel \
    oovbaapi/ooo/vba/word/WdXMLNodeType \
    oovbaapi/ooo/vba/word/WdXMLSelectionChangeReason \
    oovbaapi/ooo/vba/word/WdXMLValidationStatus \
))


# vim: set noet sw=4 ts=4:
