/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */
/*
 * This file is part of the LibreOffice project.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This file incorporates work covered by the following license notice:
 *
 *   Licensed to the Apache Software Foundation (ASF) under one or more
 *   contributor license agreements. See the NOTICE file distributed
 *   with this work for additional information regarding copyright
 *   ownership. The ASF licenses this file to you under the Apache
 *   License, Version 2.0 (the "License"); you may not use this file
 *   except in compliance with the License. You may obtain a copy of
 *   the License at http://www.apache.org/licenses/LICENSE-2.0 .
 */
#ifndef __com_sun_star_drawing_DrawPage_idl__
#define __com_sun_star_drawing_DrawPage_idl__

#include <com/sun/star/drawing/GenericDrawPage.idl>

#include <com/sun/star/drawing/XMasterPageTarget.idl>
#include <com/sun/star/form/XFormsSupplier.idl>



 module com {  module sun {  module star {  module drawing {


// DocMerge from xml: service com::sun::star::drawing::DrawPage
/** This service specifies a page for the actual draw pages to contain
    the drawings.
    @see    GenericDrawPage
    @see    DrawPages
 */
published service DrawPage
{


    // DocMerge from xml: service com::sun::star::drawing::DrawPage: service com::sun::star::drawing::GenericDrawPage
    /** This service describes the base functionality that every
                draw/master page has.
     */
    service com::sun::star::drawing::GenericDrawPage;


    // DocMerge from xml: service com::sun::star::drawing::DrawPage: interface com::sun::star::drawing::XMasterPageTarget
    /** provides the link to a <type>MasterPage</type>.
     */
    interface com::sun::star::drawing::XMasterPageTarget;

    /** provides access to the hierarchy of form components belonging to the draw page.

        <p>Every draw page may contain a form layer - that is, a hierarchy of form elements. The layer can be
        accessed using this interface.</p>

        @see com.sun.star.form.FormComponent
        @see com.sun.star.form.FormComponents
        @see com.sun.star.form.Forms
    */
    [optional] interface com::sun::star::form::XFormsSupplier;
};


}; }; }; };

#endif

/* vim:set shiftwidth=4 softtabstop=4 expandtab: */
