/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_drawing_LineEndType_idl__
#define __com_sun_star_drawing_LineEndType_idl__


//=============================================================================

 module com {  module sun {  module star {  module drawing {

//=============================================================================

// DocMerge from xml: enum com::sun::star::drawing::LineEndType
/** The <type>LineEndType</type> specifies the appearance of the bullet at the
    end of a line.

    @deprecated
 */
published enum LineEndType
{
    //-------------------------------------------------------------------------
    // DOCUMENTATION OMITTED FOR LineEndType::  NONE,

    // DocMerge from xml: value com::sun::star::drawing::LineEndType::NONE
    /** the line has no special end.
     */
    NONE,

    //-------------------------------------------------------------------------
    // DOCUMENTATION OMITTED FOR LineEndType::  ARROW,

    // DocMerge from xml: value com::sun::star::drawing::LineEndType::ARROW
    /** the line uses an arrow for the line end.
     */
    ARROW,

    //-------------------------------------------------------------------------
    // DOCUMENTATION OMITTED FOR LineEndType::  CIRCLE,

    // DocMerge from xml: value com::sun::star::drawing::LineEndType::CIRCLE
    /** the line uses a circle for the line end.
     */
    CIRCLE,

    //-------------------------------------------------------------------------
    // DOCUMENTATION OMITTED FOR LineEndType::  SQUARE,

    // DocMerge from xml: value com::sun::star::drawing::LineEndType::SQUARE
    /** the line uses a square for the line end.
     */
    SQUARE,

    //-------------------------------------------------------------------------
    // DOCUMENTATION OMITTED FOR LineEndType::  SPECIAL

    // DocMerge from xml: value com::sun::star::drawing::LineEndType::SPECIAL
    /** deprecated
     */
    SPECIAL

};

//=============================================================================

}; }; }; };

#endif

