/**************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *************************************************************/


#ifndef __com_sun_star_drawing_XShapeGrouper_idl__
#define __com_sun_star_drawing_XShapeGrouper_idl__

#ifndef __com_sun_star_uno_XInterface_idl__
#include <com/sun/star/uno/XInterface.idl>
#endif

#ifndef __com_sun_star_drawing_XShapeGroup_idl__
#include <com/sun/star/drawing/XShapeGroup.idl>
#endif

#ifndef __com_sun_star_drawing_XShapes_idl__
#include <com/sun/star/drawing/XShapes.idl>
#endif


//=============================================================================

 module com {  module sun {  module star {  module drawing {

//=============================================================================

/** specifies the group/ungroup functionality.
 */
published interface XShapeGrouper: com::sun::star::uno::XInterface
{
    //-------------------------------------------------------------------------

    /** groups the <type>Shape</type>s inside a collection.

        <p>Grouping of objects in text documents works only if none
        of the objects has an anchor of type
        <member scope="com::sun::star::text::TextContentAnchorType">AS_CHARACTER</member>
        </p>.

        @param xShapes
            the <type>Shape</type>s that will be grouped. They
            must all be inserted into the same <type>GenericDrawPage</type>.

        @returns
            a newly created <type>GroupShape</type> that contains all
            <type>Shape</type>s from xShapes and is also added to the
            <type>GenericDrawPage</type> of the <type>Shape</type>s
            in xShapes.
     */
    com::sun::star::drawing::XShapeGroup group( [in] com::sun::star::drawing::XShapes xShapes );

    //-------------------------------------------------------------------------

    /** ungroups a given <type>GroupShape</type>.

        @param aGroup
            moves all <type>Shape</type>s from this <type>GroupShape</type>
            to the parent <type>XShapes</type> of the <type>GroupShape</type>.
            The <type>GroupShape</type> is than removed from the
            <type>GenericDrawPage</type> and disposed.
     */
    void ungroup( [in] com::sun::star::drawing::XShapeGroup aGroup );

};

//=============================================================================

}; }; }; };

#endif

