# -*- Mode: makefile-gmake; tab-width: 4; indent-tabs-mode: t -*-
#
# This file is part of the LibreOffice project.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

$(eval $(call gb_AllLangZip_AllLangZip,tplwizfax,$(SRCDIR)/extras/source/templates/wizard/fax/lang))

$(eval $(call gb_AllLangZip_add_files,tplwizfax,\
	bg/bus-classic_f.ott \
	bg/bus-classic-pri_f.ott \
	bg/bus-modern_f.ott \
	bg/bus-modern-pri_f.ott \
	bg/pri-bottle_f.ott \
	bg/pri-fax_f.ott \
	bg/pri-lines_f.ott \
	bg/pri-marine_f.ott \
	cs/bus-classic_f.ott \
	cs/bus-classic-pri_f.ott \
	cs/bus-modern_f.ott \
	cs/bus-modern-pri_f.ott \
	cs/pri-bottle_f.ott \
	cs/pri-fax_f.ott \
	cs/pri-lines_f.ott \
	cs/pri-marine_f.ott \
	da/bus-classic_f.ott \
	da/bus-classic-pri_f.ott \
	da/bus-modern_f.ott \
	da/bus-modern-pri_f.ott \
	da/pri-bottle_f.ott \
	da/pri-fax_f.ott \
	da/pri-lines_f.ott \
	da/pri-marine_f.ott \
	de/bus-classic_f.ott \
	de/bus-classic-pri_f.ott \
	de/bus-modern_f.ott \
	de/bus-modern-pri_f.ott \
	de/pri-bottle_f.ott \
	de/pri-fax_f.ott \
	de/pri-lines_f.ott \
	de/pri-marine_f.ott \
	en-GB/bus-classic_f.ott \
	en-GB/bus-classic-pri_f.ott \
	en-GB/bus-modern_f.ott \
	en-GB/bus-modern-pri_f.ott \
	en-GB/pri-bottle_f.ott \
	en-GB/pri-fax_f.ott \
	en-GB/pri-lines_f.ott \
	en-GB/pri-marine_f.ott \
	en-US/bus-classic_f.ott \
	en-US/bus-classic-pri_f.ott \
	en-US/bus-modern_f.ott \
	en-US/bus-modern-pri_f.ott \
	en-US/pri-bottle_f.ott \
	en-US/pri-fax_f.ott \
	en-US/pri-lines_f.ott \
	en-US/pri-marine_f.ott \
	es/bus-classic_f.ott \
	es/bus-classic-pri_f.ott \
	es/bus-modern_f.ott \
	es/bus-modern-pri_f.ott \
	es/pri-bottle_f.ott \
	es/pri-fax_f.ott \
	es/pri-lines_f.ott \
	es/pri-marine_f.ott \
	eu/bus-classic_f.ott \
	eu/bus-classic-pri_f.ott \
	eu/bus-modern_f.ott \
	eu/bus-modern-pri_f.ott \
	eu/pri-bottle_f.ott \
	eu/pri-fax_f.ott \
	eu/pri-lines_f.ott \
	eu/pri-marine_f.ott \
	fr/bus-classic_f.ott \
	fr/bus-classic-pri_f.ott \
	fr/bus-modern_f.ott \
	fr/bus-modern-pri_f.ott \
	fr/pri-bottle_f.ott \
	fr/pri-fax_f.ott \
	fr/pri-lines_f.ott \
	fr/pri-marine_f.ott \
	hu/bus-classic_f.ott \
	hu/bus-classic-pri_f.ott \
	hu/bus-modern_f.ott \
	hu/bus-modern-pri_f.ott \
	hu/pri-bottle_f.ott \
	hu/pri-fax_f.ott \
	hu/pri-lines_f.ott \
	hu/pri-marine_f.ott \
	it/bus-classic_f.ott \
	it/bus-classic-pri_f.ott \
	it/bus-modern_f.ott \
	it/bus-modern-pri_f.ott \
	it/pri-bottle_f.ott \
	it/pri-fax_f.ott \
	it/pri-lines_f.ott \
	it/pri-marine_f.ott \
	ja/bus-classic_f.ott \
	ja/bus-classic-pri_f.ott \
	ja/bus-modern_f.ott \
	ja/bus-modern-pri_f.ott \
	ja/pri-bottle_f.ott \
	ja/pri-fax_f.ott \
	ja/pri-lines_f.ott \
	ja/pri-marine_f.ott \
	km/bus-classic_f.ott \
	km/bus-classic-pri_f.ott \
	km/bus-modern_f.ott \
	km/bus-modern-pri_f.ott \
	km/pri-bottle_f.ott \
	km/pri-fax_f.ott \
	km/pri-lines_f.ott \
	km/pri-marine_f.ott \
	ko/bus-classic_f.ott \
	ko/bus-classic-pri_f.ott \
	ko/bus-modern_f.ott \
	ko/bus-modern-pri_f.ott \
	ko/pri-bottle_f.ott \
	ko/pri-fax_f.ott \
	ko/pri-lines_f.ott \
	ko/pri-marine_f.ott \
	nl/bus-classic_f.ott \
	nl/bus-classic-pri_f.ott \
	nl/bus-modern_f.ott \
	nl/bus-modern-pri_f.ott \
	nl/pri-bottle_f.ott \
	nl/pri-fax_f.ott \
	nl/pri-lines_f.ott \
	nl/pri-marine_f.ott \
	pl/bus-classic_f.ott \
	pl/bus-classic-pri_f.ott \
	pl/bus-modern_f.ott \
	pl/bus-modern-pri_f.ott \
	pl/pri-bottle_f.ott \
	pl/pri-fax_f.ott \
	pl/pri-lines_f.ott \
	pl/pri-marine_f.ott \
	pt-BR/bus-classic_f.ott \
	pt-BR/bus-classic-pri_f.ott \
	pt-BR/bus-modern_f.ott \
	pt-BR/bus-modern-pri_f.ott \
	pt-BR/pri-bottle_f.ott \
	pt-BR/pri-fax_f.ott \
	pt-BR/pri-lines_f.ott \
	pt-BR/pri-marine_f.ott \
	pt/bus-classic_f.ott \
	pt/bus-classic-pri_f.ott \
	pt/bus-modern_f.ott \
	pt/bus-modern-pri_f.ott \
	pt/pri-bottle_f.ott \
	pt/pri-fax_f.ott \
	pt/pri-lines_f.ott \
	pt/pri-marine_f.ott \
	ru/bus-classic_f.ott \
	ru/bus-classic-pri_f.ott \
	ru/bus-modern_f.ott \
	ru/bus-modern-pri_f.ott \
	ru/pri-bottle_f.ott \
	ru/pri-fax_f.ott \
	ru/pri-lines_f.ott \
	ru/pri-marine_f.ott \
	sk/bus-classic_f.ott \
	sk/bus-classic-pri_f.ott \
	sk/bus-modern_f.ott \
	sk/bus-modern-pri_f.ott \
	sk/pri-bottle_f.ott \
	sk/pri-fax_f.ott \
	sk/pri-lines_f.ott \
	sk/pri-marine_f.ott \
	sl/bus-classic_f.ott \
	sl/bus-classic-pri_f.ott \
	sl/bus-modern_f.ott \
	sl/bus-modern-pri_f.ott \
	sl/pri-bottle_f.ott \
	sl/pri-fax_f.ott \
	sl/pri-lines_f.ott \
	sl/pri-marine_f.ott \
	sv/bus-classic_f.ott \
	sv/bus-classic-pri_f.ott \
	sv/bus-modern_f.ott \
	sv/bus-modern-pri_f.ott \
	sv/pri-bottle_f.ott \
	sv/pri-fax_f.ott \
	sv/pri-lines_f.ott \
	sv/pri-marine_f.ott \
	tr/bus-classic_f.ott \
	tr/bus-classic-pri_f.ott \
	tr/bus-modern_f.ott \
	tr/bus-modern-pri_f.ott \
	tr/pri-bottle_f.ott \
	tr/pri-fax_f.ott \
	tr/pri-lines_f.ott \
	tr/pri-marine_f.ott \
	vi/bus-classic_f.ott \
	vi/bus-classic-pri_f.ott \
	vi/bus-modern_f.ott \
	vi/bus-modern-pri_f.ott \
	vi/pri-bottle_f.ott \
	vi/pri-fax_f.ott \
	vi/pri-lines_f.ott \
	vi/pri-marine_f.ott \
	zh-CN/bus-classic_f.ott \
	zh-CN/bus-classic-pri_f.ott \
	zh-CN/bus-modern_f.ott \
	zh-CN/bus-modern-pri_f.ott \
	zh-CN/pri-bottle_f.ott \
	zh-CN/pri-fax_f.ott \
	zh-CN/pri-lines_f.ott \
	zh-CN/pri-marine_f.ott \
	zh-TW/bus-classic_f.ott \
	zh-TW/bus-classic-pri_f.ott \
	zh-TW/bus-modern_f.ott \
	zh-TW/bus-modern-pri_f.ott \
	zh-TW/pri-bottle_f.ott \
	zh-TW/pri-fax_f.ott \
	zh-TW/pri-lines_f.ott \
	zh-TW/pri-marine_f.ott \
))

# vim: set noet sw=4 ts=4:
