# -*- Mode: makefile-gmake; tab-width: 4; indent-tabs-mode: t -*-
#
# This file is part of the LibreOffice project.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

$(eval $(call gb_AllLangZip_AllLangZip,tplwizagenda,$(SRCDIR)/extras/source/templates/wizard/agenda/lang))

$(eval $(call gb_AllLangZip_add_files,tplwizagenda,\
	bg/10grey.ott \
	bg/1simple.ott \
	bg/2elegant.ott \
	bg/3modern.ott \
	bg/4classic.ott \
	bg/5blue.ott \
	bg/6orange.ott \
	bg/7red.ott \
	bg/8green.ott \
	bg/9colorful.ott \
	bg/aw-10grey.ott \
	bg/aw-1simple.ott \
	bg/aw-2elegant.ott \
	bg/aw-3modern.ott \
	bg/aw-4classic.ott \
	bg/aw-5blue.ott \
	bg/aw-6orange.ott \
	bg/aw-7red.ott \
	bg/aw-8green.ott \
	bg/aw-9colorful.ott \
	cs/10grey.ott \
	cs/1simple.ott \
	cs/2elegant.ott \
	cs/3modern.ott \
	cs/4classic.ott \
	cs/5blue.ott \
	cs/6orange.ott \
	cs/7red.ott \
	cs/8green.ott \
	cs/9colorful.ott \
	cs/aw-10grey.ott \
	cs/aw-1simple.ott \
	cs/aw-2elegant.ott \
	cs/aw-3modern.ott \
	cs/aw-4classic.ott \
	cs/aw-5blue.ott \
	cs/aw-6orange.ott \
	cs/aw-7red.ott \
	cs/aw-8green.ott \
	cs/aw-9colorful.ott \
	da/10grey.ott \
	da/1simple.ott \
	da/2elegant.ott \
	da/3modern.ott \
	da/4classic.ott \
	da/5blue.ott \
	da/6orange.ott \
	da/7red.ott \
	da/8green.ott \
	da/9colorful.ott \
	da/aw-10grey.ott \
	da/aw-1simple.ott \
	da/aw-2elegant.ott \
	da/aw-3modern.ott \
	da/aw-4classic.ott \
	da/aw-5blue.ott \
	da/aw-6orange.ott \
	da/aw-7red.ott \
	da/aw-8green.ott \
	da/aw-9colorful.ott \
	de/10grey.ott \
	de/1simple.ott \
	de/2elegant.ott \
	de/3modern.ott \
	de/4classic.ott \
	de/5blue.ott \
	de/6orange.ott \
	de/7red.ott \
	de/8green.ott \
	de/9colorful.ott \
	de/aw-10grey.ott \
	de/aw-1simple.ott \
	de/aw-2elegant.ott \
	de/aw-3modern.ott \
	de/aw-4classic.ott \
	de/aw-5blue.ott \
	de/aw-6orange.ott \
	de/aw-7red.ott \
	de/aw-8green.ott \
	de/aw-9colorful.ott \
	en-GB/10grey.ott \
	en-GB/1simple.ott \
	en-GB/2elegant.ott \
	en-GB/3modern.ott \
	en-GB/4classic.ott \
	en-GB/5blue.ott \
	en-GB/6orange.ott \
	en-GB/7red.ott \
	en-GB/8green.ott \
	en-GB/9colorful.ott \
	en-GB/aw-10grey.ott \
	en-GB/aw-1simple.ott \
	en-GB/aw-2elegant.ott \
	en-GB/aw-3modern.ott \
	en-GB/aw-4classic.ott \
	en-GB/aw-5blue.ott \
	en-GB/aw-6orange.ott \
	en-GB/aw-7red.ott \
	en-GB/aw-8green.ott \
	en-GB/aw-9colorful.ott \
	en-US/10grey.ott \
	en-US/1simple.ott \
	en-US/2elegant.ott \
	en-US/3modern.ott \
	en-US/4classic.ott \
	en-US/5blue.ott \
	en-US/6orange.ott \
	en-US/7red.ott \
	en-US/8green.ott \
	en-US/9colorful.ott \
	en-US/aw-10grey.ott \
	en-US/aw-1simple.ott \
	en-US/aw-2elegant.ott \
	en-US/aw-3modern.ott \
	en-US/aw-4classic.ott \
	en-US/aw-5blue.ott \
	en-US/aw-6orange.ott \
	en-US/aw-7red.ott \
	en-US/aw-8green.ott \
	en-US/aw-9colorful.ott \
	es/10grey.ott \
	es/1simple.ott \
	es/2elegant.ott \
	es/3modern.ott \
	es/4classic.ott \
	es/5blue.ott \
	es/6orange.ott \
	es/7red.ott \
	es/8green.ott \
	es/9colorful.ott \
	es/aw-10grey.ott \
	es/aw-1simple.ott \
	es/aw-2elegant.ott \
	es/aw-3modern.ott \
	es/aw-4classic.ott \
	es/aw-5blue.ott \
	es/aw-6orange.ott \
	es/aw-7red.ott \
	es/aw-8green.ott \
	es/aw-9colorful.ott \
	eu/10grey.ott \
	eu/1simple.ott \
	eu/2elegant.ott \
	eu/3modern.ott \
	eu/4classic.ott \
	eu/5blue.ott \
	eu/6orange.ott \
	eu/7red.ott \
	eu/8green.ott \
	eu/9colorful.ott \
	eu/aw-10grey.ott \
	eu/aw-1simple.ott \
	eu/aw-2elegant.ott \
	eu/aw-3modern.ott \
	eu/aw-4classic.ott \
	eu/aw-5blue.ott \
	eu/aw-6orange.ott \
	eu/aw-7red.ott \
	eu/aw-8green.ott \
	eu/aw-9colorful.ott \
	fr/10grey.ott \
	fr/1simple.ott \
	fr/2elegant.ott \
	fr/3modern.ott \
	fr/4classic.ott \
	fr/5blue.ott \
	fr/6orange.ott \
	fr/7red.ott \
	fr/8green.ott \
	fr/9colorful.ott \
	fr/aw-10grey.ott \
	fr/aw-1simple.ott \
	fr/aw-2elegant.ott \
	fr/aw-3modern.ott \
	fr/aw-4classic.ott \
	fr/aw-5blue.ott \
	fr/aw-6orange.ott \
	fr/aw-7red.ott \
	fr/aw-8green.ott \
	fr/aw-9colorful.ott \
	hu/10grey.ott \
	hu/1simple.ott \
	hu/2elegant.ott \
	hu/3modern.ott \
	hu/4classic.ott \
	hu/5blue.ott \
	hu/6orange.ott \
	hu/7red.ott \
	hu/8green.ott \
	hu/9colorful.ott \
	hu/aw-10grey.ott \
	hu/aw-1simple.ott \
	hu/aw-2elegant.ott \
	hu/aw-3modern.ott \
	hu/aw-4classic.ott \
	hu/aw-5blue.ott \
	hu/aw-6orange.ott \
	hu/aw-7red.ott \
	hu/aw-8green.ott \
	hu/aw-9colorful.ott \
	it/10grey.ott \
	it/1simple.ott \
	it/2elegant.ott \
	it/3modern.ott \
	it/4classic.ott \
	it/5blue.ott \
	it/6orange.ott \
	it/7red.ott \
	it/8green.ott \
	it/9colorful.ott \
	it/aw-10grey.ott \
	it/aw-1simple.ott \
	it/aw-2elegant.ott \
	it/aw-3modern.ott \
	it/aw-4classic.ott \
	it/aw-5blue.ott \
	it/aw-6orange.ott \
	it/aw-7red.ott \
	it/aw-8green.ott \
	it/aw-9colorful.ott \
	ja/10grey.ott \
	ja/1simple.ott \
	ja/2elegant.ott \
	ja/3modern.ott \
	ja/4classic.ott \
	ja/5blue.ott \
	ja/6orange.ott \
	ja/7red.ott \
	ja/8green.ott \
	ja/9colorful.ott \
	ja/aw-10grey.ott \
	ja/aw-1simple.ott \
	ja/aw-2elegant.ott \
	ja/aw-3modern.ott \
	ja/aw-4classic.ott \
	ja/aw-5blue.ott \
	ja/aw-6orange.ott \
	ja/aw-7red.ott \
	ja/aw-8green.ott \
	ja/aw-9colorful.ott \
	km/10grey.ott \
	km/1simple.ott \
	km/2elegant.ott \
	km/3modern.ott \
	km/4classic.ott \
	km/5blue.ott \
	km/6orange.ott \
	km/7red.ott \
	km/8green.ott \
	km/9colorful.ott \
	km/aw-10grey.ott \
	km/aw-1simple.ott \
	km/aw-2elegant.ott \
	km/aw-3modern.ott \
	km/aw-4classic.ott \
	km/aw-5blue.ott \
	km/aw-6orange.ott \
	km/aw-7red.ott \
	km/aw-8green.ott \
	km/aw-9colorful.ott \
	ko/10grey.ott \
	ko/1simple.ott \
	ko/2elegant.ott \
	ko/3modern.ott \
	ko/4classic.ott \
	ko/5blue.ott \
	ko/6orange.ott \
	ko/7red.ott \
	ko/8green.ott \
	ko/9colorful.ott \
	ko/aw-10grey.ott \
	ko/aw-1simple.ott \
	ko/aw-2elegant.ott \
	ko/aw-3modern.ott \
	ko/aw-4classic.ott \
	ko/aw-5blue.ott \
	ko/aw-6orange.ott \
	ko/aw-7red.ott \
	ko/aw-8green.ott \
	ko/aw-9colorful.ott \
	nl/10grey.ott \
	nl/1simple.ott \
	nl/2elegant.ott \
	nl/3modern.ott \
	nl/4classic.ott \
	nl/5blue.ott \
	nl/6orange.ott \
	nl/7red.ott \
	nl/8green.ott \
	nl/9colorful.ott \
	nl/aw-10grey.ott \
	nl/aw-1simple.ott \
	nl/aw-2elegant.ott \
	nl/aw-3modern.ott \
	nl/aw-4classic.ott \
	nl/aw-5blue.ott \
	nl/aw-6orange.ott \
	nl/aw-7red.ott \
	nl/aw-8green.ott \
	nl/aw-9colorful.ott \
	pl/10grey.ott \
	pl/1simple.ott \
	pl/2elegant.ott \
	pl/3modern.ott \
	pl/4classic.ott \
	pl/5blue.ott \
	pl/6orange.ott \
	pl/7red.ott \
	pl/8green.ott \
	pl/9colorful.ott \
	pl/aw-10grey.ott \
	pl/aw-1simple.ott \
	pl/aw-2elegant.ott \
	pl/aw-3modern.ott \
	pl/aw-4classic.ott \
	pl/aw-5blue.ott \
	pl/aw-6orange.ott \
	pl/aw-7red.ott \
	pl/aw-8green.ott \
	pl/aw-9colorful.ott \
	pt/10grey.ott \
	pt/1simple.ott \
	pt/2elegant.ott \
	pt/3modern.ott \
	pt/4classic.ott \
	pt/5blue.ott \
	pt/6orange.ott \
	pt/7red.ott \
	pt/8green.ott \
	pt/9colorful.ott \
	pt/aw-10grey.ott \
	pt/aw-1simple.ott \
	pt/aw-2elegant.ott \
	pt/aw-3modern.ott \
	pt/aw-4classic.ott \
	pt/aw-5blue.ott \
	pt/aw-6orange.ott \
	pt/aw-7red.ott \
	pt/aw-8green.ott \
	pt/aw-9colorful.ott \
	pt-BR/10grey.ott \
	pt-BR/1simple.ott \
	pt-BR/2elegant.ott \
	pt-BR/3modern.ott \
	pt-BR/4classic.ott \
	pt-BR/5blue.ott \
	pt-BR/6orange.ott \
	pt-BR/7red.ott \
	pt-BR/8green.ott \
	pt-BR/9colorful.ott \
	pt-BR/aw-10grey.ott \
	pt-BR/aw-1simple.ott \
	pt-BR/aw-2elegant.ott \
	pt-BR/aw-3modern.ott \
	pt-BR/aw-4classic.ott \
	pt-BR/aw-5blue.ott \
	pt-BR/aw-6orange.ott \
	pt-BR/aw-7red.ott \
	pt-BR/aw-8green.ott \
	pt-BR/aw-9colorful.ott \
	ru/10grey.ott \
	ru/1simple.ott \
	ru/2elegant.ott \
	ru/3modern.ott \
	ru/4classic.ott \
	ru/5blue.ott \
	ru/6orange.ott \
	ru/7red.ott \
	ru/8green.ott \
	ru/9colorful.ott \
	ru/aw-10grey.ott \
	ru/aw-1simple.ott \
	ru/aw-2elegant.ott \
	ru/aw-3modern.ott \
	ru/aw-4classic.ott \
	ru/aw-5blue.ott \
	ru/aw-6orange.ott \
	ru/aw-7red.ott \
	ru/aw-8green.ott \
	ru/aw-9colorful.ott \
	sk/10grey.ott \
	sk/1simple.ott \
	sk/2elegant.ott \
	sk/3modern.ott \
	sk/4classic.ott \
	sk/5blue.ott \
	sk/6orange.ott \
	sk/7red.ott \
	sk/8green.ott \
	sk/9colorful.ott \
	sk/aw-10grey.ott \
	sk/aw-1simple.ott \
	sk/aw-2elegant.ott \
	sk/aw-3modern.ott \
	sk/aw-4classic.ott \
	sk/aw-5blue.ott \
	sk/aw-6orange.ott \
	sk/aw-7red.ott \
	sk/aw-8green.ott \
	sk/aw-9colorful.ott \
	sl/10grey.ott \
	sl/1simple.ott \
	sl/2elegant.ott \
	sl/3modern.ott \
	sl/4classic.ott \
	sl/5blue.ott \
	sl/6orange.ott \
	sl/7red.ott \
	sl/8green.ott \
	sl/9colorful.ott \
	sl/aw-10grey.ott \
	sl/aw-1simple.ott \
	sl/aw-2elegant.ott \
	sl/aw-3modern.ott \
	sl/aw-4classic.ott \
	sl/aw-5blue.ott \
	sl/aw-6orange.ott \
	sl/aw-7red.ott \
	sl/aw-8green.ott \
	sl/aw-9colorful.ott \
	sv/10grey.ott \
	sv/1simple.ott \
	sv/2elegant.ott \
	sv/3modern.ott \
	sv/4classic.ott \
	sv/5blue.ott \
	sv/6orange.ott \
	sv/7red.ott \
	sv/8green.ott \
	sv/9colorful.ott \
	sv/aw-10grey.ott \
	sv/aw-1simple.ott \
	sv/aw-2elegant.ott \
	sv/aw-3modern.ott \
	sv/aw-4classic.ott \
	sv/aw-5blue.ott \
	sv/aw-6orange.ott \
	sv/aw-7red.ott \
	sv/aw-8green.ott \
	sv/aw-9colorful.ott \
	tr/10grey.ott \
	tr/1simple.ott \
	tr/2elegant.ott \
	tr/3modern.ott \
	tr/4classic.ott \
	tr/5blue.ott \
	tr/6orange.ott \
	tr/7red.ott \
	tr/8green.ott \
	tr/9colorful.ott \
	tr/aw-10grey.ott \
	tr/aw-1simple.ott \
	tr/aw-2elegant.ott \
	tr/aw-3modern.ott \
	tr/aw-4classic.ott \
	tr/aw-5blue.ott \
	tr/aw-6orange.ott \
	tr/aw-7red.ott \
	tr/aw-8green.ott \
	tr/aw-9colorful.ott \
	vi/10grey.ott \
	vi/1simple.ott \
	vi/2elegant.ott \
	vi/3modern.ott \
	vi/4classic.ott \
	vi/5blue.ott \
	vi/6orange.ott \
	vi/7red.ott \
	vi/8green.ott \
	vi/9colorful.ott \
	vi/aw-10grey.ott \
	vi/aw-1simple.ott \
	vi/aw-2elegant.ott \
	vi/aw-3modern.ott \
	vi/aw-4classic.ott \
	vi/aw-5blue.ott \
	vi/aw-6orange.ott \
	vi/aw-7red.ott \
	vi/aw-8green.ott \
	vi/aw-9colorful.ott \
	zh-CN/10grey.ott \
	zh-CN/1simple.ott \
	zh-CN/2elegant.ott \
	zh-CN/3modern.ott \
	zh-CN/4classic.ott \
	zh-CN/5blue.ott \
	zh-CN/6orange.ott \
	zh-CN/7red.ott \
	zh-CN/8green.ott \
	zh-CN/9colorful.ott \
	zh-CN/aw-10grey.ott \
	zh-CN/aw-1simple.ott \
	zh-CN/aw-2elegant.ott \
	zh-CN/aw-3modern.ott \
	zh-CN/aw-4classic.ott \
	zh-CN/aw-5blue.ott \
	zh-CN/aw-6orange.ott \
	zh-CN/aw-7red.ott \
	zh-CN/aw-8green.ott \
	zh-CN/aw-9colorful.ott \
	zh-TW/10grey.ott \
	zh-TW/1simple.ott \
	zh-TW/2elegant.ott \
	zh-TW/3modern.ott \
	zh-TW/4classic.ott \
	zh-TW/5blue.ott \
	zh-TW/6orange.ott \
	zh-TW/7red.ott \
	zh-TW/8green.ott \
	zh-TW/9colorful.ott \
	zh-TW/aw-10grey.ott \
	zh-TW/aw-1simple.ott \
	zh-TW/aw-2elegant.ott \
	zh-TW/aw-3modern.ott \
	zh-TW/aw-4classic.ott \
	zh-TW/aw-5blue.ott \
	zh-TW/aw-6orange.ott \
	zh-TW/aw-7red.ott \
	zh-TW/aw-8green.ott \
	zh-TW/aw-9colorful.ott \
))

# vim: set noet sw=4 ts=4:
