# -*- Mode: makefile-gmake; tab-width: 4; indent-tabs-mode: t -*-
#
# This file is part of the LibreOffice project.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

$(eval $(call gb_ExternalPackage_ExternalPackage,extras_accessoriesgalleryelementsbullets2,gallery-pack))

$(eval $(call gb_ExternalPackage_set_outdir,extras_accessoriesgalleryelementsbullets2,$(gb_INSTROOT)))

$(eval $(call gb_ExternalPackage_add_unpacked_files,extras_accessoriesgalleryelementsbullets2,$(LIBO_SHARE_FOLDER)/gallery/Elements/Bullets2,\
	accessories/Elements/Bullets2/amethyst.arrow.png \
	accessories/Elements/Bullets2/amethyst.asterisk.png \
	accessories/Elements/Bullets2/amethyst.circle-light.png \
	accessories/Elements/Bullets2/amethyst.circle.png \
	accessories/Elements/Bullets2/amethyst.cross1.png \
	accessories/Elements/Bullets2/amethyst.cross2.png \
	accessories/Elements/Bullets2/amethyst.dash.png \
	accessories/Elements/Bullets2/amethyst.diamond-light.png \
	accessories/Elements/Bullets2/amethyst.diamond.png \
	accessories/Elements/Bullets2/amethyst.minus.png \
	accessories/Elements/Bullets2/amethyst.plus.png \
	accessories/Elements/Bullets2/amethyst.smiley.png \
	accessories/Elements/Bullets2/amethyst.square-light.png \
	accessories/Elements/Bullets2/amethyst.square.png \
	accessories/Elements/Bullets2/amethyst.star.png \
	accessories/Elements/Bullets2/amethyst.tick.png \
	accessories/Elements/Bullets2/amethyst.triangle1-light.png \
	accessories/Elements/Bullets2/amethyst.triangle1.png \
	accessories/Elements/Bullets2/amethyst.triangle2-light.png \
	accessories/Elements/Bullets2/amethyst.triangle2.png \
	accessories/Elements/Bullets2/citrine.arrow.png \
	accessories/Elements/Bullets2/citrine.asterisk.png \
	accessories/Elements/Bullets2/citrine.circle-light.png \
	accessories/Elements/Bullets2/citrine.circle.png \
	accessories/Elements/Bullets2/citrine.cross1.png \
	accessories/Elements/Bullets2/citrine.cross2.png \
	accessories/Elements/Bullets2/citrine.dash.png \
	accessories/Elements/Bullets2/citrine.diamond-light.png \
	accessories/Elements/Bullets2/citrine.diamond.png \
	accessories/Elements/Bullets2/citrine.minus.png \
	accessories/Elements/Bullets2/citrine.plus.png \
	accessories/Elements/Bullets2/citrine.smiley.png \
	accessories/Elements/Bullets2/citrine.square-light.png \
	accessories/Elements/Bullets2/citrine.square.png \
	accessories/Elements/Bullets2/citrine.star.png \
	accessories/Elements/Bullets2/citrine.tick.png \
	accessories/Elements/Bullets2/citrine.triangle1-light.png \
	accessories/Elements/Bullets2/citrine.triangle1.png \
	accessories/Elements/Bullets2/citrine.triangle2-light.png \
	accessories/Elements/Bullets2/citrine.triangle2.png \
	accessories/Elements/Bullets2/emerald.arrow.png \
	accessories/Elements/Bullets2/emerald.asterisk.png \
	accessories/Elements/Bullets2/emerald.circle-light.png \
	accessories/Elements/Bullets2/emerald.circle.png \
	accessories/Elements/Bullets2/emerald.cross1.png \
	accessories/Elements/Bullets2/emerald.cross2.png \
	accessories/Elements/Bullets2/emerald.dash.png \
	accessories/Elements/Bullets2/emerald.diamond-light.png \
	accessories/Elements/Bullets2/emerald.diamond.png \
	accessories/Elements/Bullets2/emerald.minus.png \
	accessories/Elements/Bullets2/emerald.plus.png \
	accessories/Elements/Bullets2/emerald.smiley.png \
	accessories/Elements/Bullets2/emerald.square-light.png \
	accessories/Elements/Bullets2/emerald.square.png \
	accessories/Elements/Bullets2/emerald.star.png \
	accessories/Elements/Bullets2/emerald.tick.png \
	accessories/Elements/Bullets2/emerald.triangle1-light.png \
	accessories/Elements/Bullets2/emerald.triangle1.png \
	accessories/Elements/Bullets2/emerald.triangle2-light.png \
	accessories/Elements/Bullets2/emerald.triangle2.png \
	accessories/Elements/Bullets2/glass.arrow.png \
	accessories/Elements/Bullets2/glass.asterisk.png \
	accessories/Elements/Bullets2/glass.circle-light.png \
	accessories/Elements/Bullets2/glass.circle.png \
	accessories/Elements/Bullets2/glass.cross1.png \
	accessories/Elements/Bullets2/glass.cross2.png \
	accessories/Elements/Bullets2/glass.dash.png \
	accessories/Elements/Bullets2/glass.diamond-light.png \
	accessories/Elements/Bullets2/glass.diamond.png \
	accessories/Elements/Bullets2/glass.minus.png \
	accessories/Elements/Bullets2/glass.plus.png \
	accessories/Elements/Bullets2/glass.smiley.png \
	accessories/Elements/Bullets2/glass.square-light.png \
	accessories/Elements/Bullets2/glass.square.png \
	accessories/Elements/Bullets2/glass.star.png \
	accessories/Elements/Bullets2/glass.tick.png \
	accessories/Elements/Bullets2/glass.triangle1-light.png \
	accessories/Elements/Bullets2/glass.triangle1.png \
	accessories/Elements/Bullets2/glass.triangle2-light.png \
	accessories/Elements/Bullets2/glass.triangle2.png \
	accessories/Elements/Bullets2/mono.arrow.png \
	accessories/Elements/Bullets2/mono.asterisk.png \
	accessories/Elements/Bullets2/mono.circle-light.png \
	accessories/Elements/Bullets2/mono.circle.png \
	accessories/Elements/Bullets2/mono.circle-semi1.png \
	accessories/Elements/Bullets2/mono.circle-semi2.png \
	accessories/Elements/Bullets2/mono.cross1.png \
	accessories/Elements/Bullets2/mono.cross2.png \
	accessories/Elements/Bullets2/mono.dash.png \
	accessories/Elements/Bullets2/mono.diamond-light.png \
	accessories/Elements/Bullets2/mono.diamond.png \
	accessories/Elements/Bullets2/mono.diamond-semi1.png \
	accessories/Elements/Bullets2/mono.diamond-semi2.png \
	accessories/Elements/Bullets2/mono.minus.png \
	accessories/Elements/Bullets2/mono.plus.png \
	accessories/Elements/Bullets2/mono.smiley.png \
	accessories/Elements/Bullets2/mono.square-light.png \
	accessories/Elements/Bullets2/mono.square.png \
	accessories/Elements/Bullets2/mono.square-semi1.png \
	accessories/Elements/Bullets2/mono.square-semi2.png \
	accessories/Elements/Bullets2/mono.star.png \
	accessories/Elements/Bullets2/mono.tick.png \
	accessories/Elements/Bullets2/mono.triangle1-light.png \
	accessories/Elements/Bullets2/mono.triangle1.png \
	accessories/Elements/Bullets2/mono.triangle1-semi.png \
	accessories/Elements/Bullets2/mono.triangle2-light.png \
	accessories/Elements/Bullets2/mono.triangle2.png \
	accessories/Elements/Bullets2/mono.triangle2-semi.png \
	accessories/Elements/Bullets2/mono.triangle3-light.png \
	accessories/Elements/Bullets2/mono.triangle3.png \
	accessories/Elements/Bullets2/mono.triangle3-semi.png \
	accessories/Elements/Bullets2/mono.triangle4-light.png \
	accessories/Elements/Bullets2/mono.triangle4.png \
	accessories/Elements/Bullets2/mono.triangle4-semi.png \
	accessories/Elements/Bullets2/obsidian.arrow.png \
	accessories/Elements/Bullets2/obsidian.asterisk.png \
	accessories/Elements/Bullets2/obsidian.circle-light.png \
	accessories/Elements/Bullets2/obsidian.circle.png \
	accessories/Elements/Bullets2/obsidian.cross1.png \
	accessories/Elements/Bullets2/obsidian.cross2.png \
	accessories/Elements/Bullets2/obsidian.dash.png \
	accessories/Elements/Bullets2/obsidian.diamond-light.png \
	accessories/Elements/Bullets2/obsidian.diamond.png \
	accessories/Elements/Bullets2/obsidian.minus.png \
	accessories/Elements/Bullets2/obsidian.plus.png \
	accessories/Elements/Bullets2/obsidian.smiley.png \
	accessories/Elements/Bullets2/obsidian.square-light.png \
	accessories/Elements/Bullets2/obsidian.square.png \
	accessories/Elements/Bullets2/obsidian.star.png \
	accessories/Elements/Bullets2/obsidian.tick.png \
	accessories/Elements/Bullets2/obsidian.triangle1-light.png \
	accessories/Elements/Bullets2/obsidian.triangle1.png \
	accessories/Elements/Bullets2/obsidian.triangle2-light.png \
	accessories/Elements/Bullets2/obsidian.triangle2.png \
	accessories/Elements/Bullets2/ruby.arrow.png \
	accessories/Elements/Bullets2/ruby.asterisk.png \
	accessories/Elements/Bullets2/ruby.circle-light.png \
	accessories/Elements/Bullets2/ruby.circle.png \
	accessories/Elements/Bullets2/ruby.cross1.png \
	accessories/Elements/Bullets2/ruby.cross2.png \
	accessories/Elements/Bullets2/ruby.dash.png \
	accessories/Elements/Bullets2/ruby.diamond-light.png \
	accessories/Elements/Bullets2/ruby.diamond.png \
	accessories/Elements/Bullets2/ruby.minus.png \
	accessories/Elements/Bullets2/ruby.plus.png \
	accessories/Elements/Bullets2/ruby.smiley.png \
	accessories/Elements/Bullets2/ruby.square-light.png \
	accessories/Elements/Bullets2/ruby.square.png \
	accessories/Elements/Bullets2/ruby.star.png \
	accessories/Elements/Bullets2/ruby.tick.png \
	accessories/Elements/Bullets2/ruby.triangle1-light.png \
	accessories/Elements/Bullets2/ruby.triangle1.png \
	accessories/Elements/Bullets2/ruby.triangle2-light.png \
	accessories/Elements/Bullets2/ruby.triangle2.png \
	accessories/Elements/Bullets2/sapphire.arrow.png \
	accessories/Elements/Bullets2/sapphire.asterisk.png \
	accessories/Elements/Bullets2/sapphire.circle-light.png \
	accessories/Elements/Bullets2/sapphire.circle.png \
	accessories/Elements/Bullets2/sapphire.cross1.png \
	accessories/Elements/Bullets2/sapphire.cross2.png \
	accessories/Elements/Bullets2/sapphire.dash.png \
	accessories/Elements/Bullets2/sapphire.diamond-light.png \
	accessories/Elements/Bullets2/sapphire.diamond.png \
	accessories/Elements/Bullets2/sapphire.minus.png \
	accessories/Elements/Bullets2/sapphire.plus.png \
	accessories/Elements/Bullets2/sapphire.smiley.png \
	accessories/Elements/Bullets2/sapphire.square-light.png \
	accessories/Elements/Bullets2/sapphire.square.png \
	accessories/Elements/Bullets2/sapphire.star.png \
	accessories/Elements/Bullets2/sapphire.tick.png \
	accessories/Elements/Bullets2/sapphire.triangle1-light.png \
	accessories/Elements/Bullets2/sapphire.triangle1.png \
	accessories/Elements/Bullets2/sapphire.triangle2-light.png \
	accessories/Elements/Bullets2/sapphire.triangle2.png \
))

# vim: set noet sw=4 ts=4:
