# -*- Mode: makefile-gmake; tab-width: 4; indent-tabs-mode: t -*-
#
# This file is part of the LibreOffice project.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

$(eval $(call gb_ExternalPackage_ExternalPackage,extras_accessoriestemplatescommonlayout,templates-pack))

$(eval $(call gb_ExternalPackage_set_outdir,extras_accessoriestemplatescommonlayout,$(gb_INSTROOT)))

$(eval $(call gb_ExternalPackage_add_unpacked_files,extras_accessoriestemplatescommonlayout,$(LIBO_SHARE_FOLDER)/template/common/layout,\
	templates/common/layout/31407-squares.otp \
	templates/common/layout/abstract-015_1.jpg.otp \
	templates/common/layout/abstract-015_2.jpg.otp \
	templates/common/layout/abstract-015_3.jpg.otp \
	templates/common/layout/abstract-015p_1.jpg.otp \
	templates/common/layout/abstract-015p_2.jpg.otp \
	templates/common/layout/abstract-015p_3.jpg.otp \
	templates/common/layout/abstract-015t_1.jpg.otp \
	templates/common/layout/abstract-015t_2.jpg.otp \
	templates/common/layout/abstract-015t_3.jpg.otp \
	templates/common/layout/abstract-032_1.jpg.otp \
	templates/common/layout/abstract-032_2.jpg.otp \
	templates/common/layout/abstract-032_3.jpg.otp \
	templates/common/layout/abstract-032p_1.jpg.otp \
	templates/common/layout/abstract-032p_2.jpg.otp \
	templates/common/layout/abstract-032p_3.jpg.otp \
	templates/common/layout/abstract-032t_1.jpg.otp \
	templates/common/layout/abstract-032t_2.jpg.otp \
	templates/common/layout/abstract-032t_3.jpg.otp \
	templates/common/layout/abstract-078_1.jpg.otp \
	templates/common/layout/abstract-078_2.jpg.otp \
	templates/common/layout/abstract-078_3.jpg.otp \
	templates/common/layout/abstract-078p_1.jpg.otp \
	templates/common/layout/abstract-078p_2.jpg.otp \
	templates/common/layout/abstract-078p_3.jpg.otp \
	templates/common/layout/abstract-078t_1.jpg.otp \
	templates/common/layout/abstract-078t_2.jpg.otp \
	templates/common/layout/abstract-078t_3.jpg.otp \
	templates/common/layout/abstract-138_1.jpg.otp \
	templates/common/layout/abstract-138_2.jpg.otp \
	templates/common/layout/abstract-138_3.jpg.otp \
	templates/common/layout/abstract-138p_1.jpg.otp \
	templates/common/layout/abstract-138p_2.jpg.otp \
	templates/common/layout/abstract-138p_3.jpg.otp \
	templates/common/layout/abstract-138t_1.jpg.otp \
	templates/common/layout/abstract-138t_2.jpg.otp \
	templates/common/layout/abstract-138t_3.jpg.otp \
	templates/common/layout/aquarius.otp \
	templates/common/layout/blau.otp \
	templates/common/layout/Blue_2.otp \
	templates/common/layout/Blue_Boxes.otp \
	templates/common/layout/Blue_Circles.otp \
	templates/common/layout/blue-elegance.otp \
	templates/common/layout/Blue_Lines.otp \
	templates/common/layout/blue.otp \
	templates/common/layout/Blue_Silver.otp \
	templates/common/layout/Blue_Squares.otp \
	templates/common/layout/Blue_Waves.otp \
	templates/common/layout/carton.otp \
	templates/common/layout/chalkboard_2.otp \
	templates/common/layout/chalkboard.otp \
	templates/common/layout/circulos_clasicos.otp \
	templates/common/layout/circulos_originales.otp \
	templates/common/layout/citrus-e.otp \
	templates/common/layout/compladients.otp \
	templates/common/layout/Cool_Space.otp \
	templates/common/layout/cross_color.otp \
	templates/common/layout/cross_gray.otp \
	templates/common/layout/cross_green.otp \
	templates/common/layout/cross_orange.otp \
	templates/common/layout/cross_white.otp \
	templates/common/layout/cross_yellow.otp \
	templates/common/layout/Cubes.otp \
	templates/common/layout/Doppellinie-blau.otp \
	templates/common/layout/EarthLight.otp \
	templates/common/layout/edge-005_1.jpg.otp \
	templates/common/layout/edge-005_2.jpg.otp \
	templates/common/layout/edge-005_3.jpg.otp \
	templates/common/layout/edge-005p_1.jpg.otp \
	templates/common/layout/edge-005p_2.jpg.otp \
	templates/common/layout/edge-005p_3.jpg.otp \
	templates/common/layout/edge-005t_1.jpg.otp \
	templates/common/layout/edge-005t_2.jpg.otp \
	templates/common/layout/edge-005t_3.jpg.otp \
	templates/common/layout/edge-013_1.jpg.otp \
	templates/common/layout/edge-013_2.jpg.otp \
	templates/common/layout/edge-013_3.jpg.otp \
	templates/common/layout/edge-013p_1.jpg.otp \
	templates/common/layout/edge-013p_2.jpg.otp \
	templates/common/layout/edge-013p_3.jpg.otp \
	templates/common/layout/edge-013t_1.jpg.otp \
	templates/common/layout/edge-013t_2.jpg.otp \
	templates/common/layout/edge-013t_3.jpg.otp \
	templates/common/layout/edge-046_1.jpg.otp \
	templates/common/layout/edge-046_2.jpg.otp \
	templates/common/layout/edge-046_3.jpg.otp \
	templates/common/layout/edge-046p_1.jpg.otp \
	templates/common/layout/edge-046p_2.jpg.otp \
	templates/common/layout/edge-046p_3.jpg.otp \
	templates/common/layout/edge-046t_1.jpg.otp \
	templates/common/layout/edge-046t_2.jpg.otp \
	templates/common/layout/edge-046t_3.jpg.otp \
	templates/common/layout/edge-048_1.jpg.otp \
	templates/common/layout/edge-048_2.jpg.otp \
	templates/common/layout/edge-048_3.jpg.otp \
	templates/common/layout/edge-048p_1.jpg.otp \
	templates/common/layout/edge-048p_2.jpg.otp \
	templates/common/layout/edge-048p_3.jpg.otp \
	templates/common/layout/edge-048t_1.jpg.otp \
	templates/common/layout/edge-048t_2.jpg.otp \
	templates/common/layout/edge-048t_3.jpg.otp \
	templates/common/layout/edge-058_1.jpg.otp \
	templates/common/layout/edge-058_2.jpg.otp \
	templates/common/layout/edge-058_3.jpg.otp \
	templates/common/layout/edge-058p_1.jpg.otp \
	templates/common/layout/edge-058p_2.jpg.otp \
	templates/common/layout/edge-058p_3.jpg.otp \
	templates/common/layout/edge-058t_1.jpg.otp \
	templates/common/layout/edge-058t_2.jpg.otp \
	templates/common/layout/edge-058t_3.jpg.otp \
	templates/common/layout/edge-077_1.jpg.otp \
	templates/common/layout/edge-077_2.jpg.otp \
	templates/common/layout/edge-077_3.jpg.otp \
	templates/common/layout/edge-077p_1.jpg.otp \
	templates/common/layout/edge-077p_2.jpg.otp \
	templates/common/layout/edge-077p_3.jpg.otp \
	templates/common/layout/edge-077t_1.jpg.otp \
	templates/common/layout/edge-077t_2.jpg.otp \
	templates/common/layout/edge-077t_3.jpg.otp \
	templates/common/layout/edge-084_1.jpg.otp \
	templates/common/layout/edge-084_2.jpg.otp \
	templates/common/layout/edge-084_3.jpg.otp \
	templates/common/layout/edge-084p_1.jpg.otp \
	templates/common/layout/edge-084p_2.jpg.otp \
	templates/common/layout/edge-084p_3.jpg.otp \
	templates/common/layout/edge-084t_1.jpg.otp \
	templates/common/layout/edge-084t_2.jpg.otp \
	templates/common/layout/edge-084t_3.jpg.otp \
	templates/common/layout/edge-091_1.jpg.otp \
	templates/common/layout/edge-091_2.jpg.otp \
	templates/common/layout/edge-091_3.jpg.otp \
	templates/common/layout/edge-091p_1.jpg.otp \
	templates/common/layout/edge-091p_2.jpg.otp \
	templates/common/layout/edge-091p_3.jpg.otp \
	templates/common/layout/edge-091t_1.jpg.otp \
	templates/common/layout/edge-091t_2.jpg.otp \
	templates/common/layout/edge-091t_3.jpg.otp \
	templates/common/layout/edge-092_1.jpg.otp \
	templates/common/layout/edge-092_2.jpg.otp \
	templates/common/layout/edge-092_3.jpg.otp \
	templates/common/layout/edge-092p_1.jpg.otp \
	templates/common/layout/edge-092p_2.jpg.otp \
	templates/common/layout/edge-092p_3.jpg.otp \
	templates/common/layout/edge-092t_1.jpg.otp \
	templates/common/layout/edge-092t_2.jpg.otp \
	templates/common/layout/edge-092t_3.jpg.otp \
	templates/common/layout/edge-104_1.jpg.otp \
	templates/common/layout/edge-104_2.jpg.otp \
	templates/common/layout/edge-104_3.jpg.otp \
	templates/common/layout/edge-104p_1.jpg.otp \
	templates/common/layout/edge-104p_2.jpg.otp \
	templates/common/layout/edge-104p_3.jpg.otp \
	templates/common/layout/edge-109_1.jpg.otp \
	templates/common/layout/edge-109_2.jpg.otp \
	templates/common/layout/edge-109_3.jpg.otp \
	templates/common/layout/edge-109p_1.jpg.otp \
	templates/common/layout/edge-109p_2.jpg.otp \
	templates/common/layout/edge-109p_3.jpg.otp \
	templates/common/layout/edge-109t_1.jpg.otp \
	templates/common/layout/edge-109t_2.jpg.otp \
	templates/common/layout/edge-109t_3.jpg.otp \
	templates/common/layout/edge-117_1.jpg.otp \
	templates/common/layout/edge-117_2.jpg.otp \
	templates/common/layout/edge-117_3.jpg.otp \
	templates/common/layout/edge-117p_1.jpg.otp \
	templates/common/layout/edge-117p_2.jpg.otp \
	templates/common/layout/edge-117p_3.jpg.otp \
	templates/common/layout/edge-117t_1.jpg.otp \
	templates/common/layout/edge-117t_2.jpg.otp \
	templates/common/layout/edge-117t_3.jpg.otp \
	templates/common/layout/edge-122_1.jpg.otp \
	templates/common/layout/edge-122_2.jpg.otp \
	templates/common/layout/edge-122_3.jpg.otp \
	templates/common/layout/edge-122p_1.jpg.otp \
	templates/common/layout/edge-122p_2.jpg.otp \
	templates/common/layout/edge-122p_3.jpg.otp \
	templates/common/layout/edge-122t_1.jpg.otp \
	templates/common/layout/edge-122t_2.jpg.otp \
	templates/common/layout/edge-122t_3.jpg.otp \
	templates/common/layout/edge-138_1.jpg.otp \
	templates/common/layout/edge-138_2.jpg.otp \
	templates/common/layout/edge-138_3.jpg.otp \
	templates/common/layout/edge-138p_1.jpg.otp \
	templates/common/layout/edge-138p_2.jpg.otp \
	templates/common/layout/edge-138p_3.jpg.otp \
	templates/common/layout/edge-138t_1.jpg.otp \
	templates/common/layout/edge-138t_2.jpg.otp \
	templates/common/layout/edge-138t_3.jpg.otp \
	templates/common/layout/edge-163_1.jpg.otp \
	templates/common/layout/edge-163_2.jpg.otp \
	templates/common/layout/edge-163_3.jpg.otp \
	templates/common/layout/edge-163p_1.jpg.otp \
	templates/common/layout/edge-163p_2.jpg.otp \
	templates/common/layout/edge-163p_3.jpg.otp \
	templates/common/layout/edge-163t_1.jpg.otp \
	templates/common/layout/edge-163t_2.jpg.otp \
	templates/common/layout/edge-163t_3.jpg.otp \
	templates/common/layout/edge-199_1.jpg.otp \
	templates/common/layout/edge-199_2.jpg.otp \
	templates/common/layout/edge-199_3.jpg.otp \
	templates/common/layout/edge-199p_1.jpg.otp \
	templates/common/layout/edge-199p_2.jpg.otp \
	templates/common/layout/edge-199p_3.jpg.otp \
	templates/common/layout/edge-199t_1.jpg.otp \
	templates/common/layout/edge-199t_2.jpg.otp \
	templates/common/layout/edge-199t_3.jpg.otp \
	templates/common/layout/education-116a.jpg.otp \
	templates/common/layout/education-116b.jpg.otp \
	templates/common/layout/education-116c.jpg.otp \
	templates/common/layout/education-116d.jpg.otp \
	templates/common/layout/education-116e.jpg.otp \
	templates/common/layout/emotion2.otp \
	templates/common/layout/emotion.otp \
	templates/common/layout/eos.otp \
	templates/common/layout/exec-au.otp \
	templates/common/layout/exec-br.otp \
	templates/common/layout/exec-eh.otp \
	templates/common/layout/exec-eu.otp \
	templates/common/layout/exec-in.otp \
	templates/common/layout/exec-jp.otp \
	templates/common/layout/exec-nz.otp \
	templates/common/layout/exec-us.otp \
	templates/common/layout/exec-za.otp \
	templates/common/layout/fields-of-peace.otp \
	templates/common/layout/fresh-morning.otp \
	templates/common/layout/Girasoles.otp \
	templates/common/layout/Glossy.otp \
	templates/common/layout/glowing-rectangles.otp \
	templates/common/layout/golthia.otp \
	templates/common/layout/green-concentration.otp \
	templates/common/layout/greenish-wallpaper.otp \
	templates/common/layout/Green.otp \
	templates/common/layout/Grey.otp \
	templates/common/layout/Hatch.otp \
	templates/common/layout/holiday-030a.jpg.otp \
	templates/common/layout/holiday-030b.jpg.otp \
	templates/common/layout/holiday-032a.jpg.otp \
	templates/common/layout/holiday-032b.jpg.otp \
	templates/common/layout/humanist_presentation.otp \
	templates/common/layout/Human.otp \
	templates/common/layout/Infantil.otp \
	templates/common/layout/inspire-001a.jpg.otp \
	templates/common/layout/inspire-001b.jpg.otp \
	templates/common/layout/inspire-001c.jpg.otp \
	templates/common/layout/inspire-011a.jpg.otp \
	templates/common/layout/inspire-011b.jpg.otp \
	templates/common/layout/inspire-024a.jpg.otp \
	templates/common/layout/inspire-024b.jpg.otp \
	templates/common/layout/inspire-073a.jpg.otp \
	templates/common/layout/inspire-073b.jpg.otp \
	templates/common/layout/inspire-073c.jpg.otp \
	templates/common/layout/inspire-130a.jpg.otp \
	templates/common/layout/inspire-130b.jpg.otp \
	templates/common/layout/inspire-166c.jpg.otp \
	templates/common/layout/kde.otp \
	templates/common/layout/keynote.otp \
	templates/common/layout/Lamp.otp \
	templates/common/layout/Lay_grafity.otp \
	templates/common/layout/Lay_wood.otp \
	templates/common/layout/letterpress.otp \
	templates/common/layout/line_blue.otp \
	templates/common/layout/line_green.otp \
	templates/common/layout/line_orange.otp \
	templates/common/layout/line_red.otp \
	templates/common/layout/line_white.otp \
	templates/common/layout/line_yellow.otp \
	templates/common/layout/list.txt \
	templates/common/layout/macos103.otp \
	templates/common/layout/Marble.otp \
	templates/common/layout/MediaStyle.otp \
	templates/common/layout/moebius-strip.otp \
	templates/common/layout/Mondo_Cyan.otp \
	templates/common/layout/Mondo_Green.otp \
	templates/common/layout/Mondo_Yellow.otp \
	templates/common/layout/more-green.otp \
	templates/common/layout/Movie.otp \
	templates/common/layout/NavyBlue.otp \
	templates/common/layout/Notepad.otp \
	templates/common/layout/ooo2.otp \
	templates/common/layout/ooo2_spot.otp \
	templates/common/layout/Openblue.otp \
	templates/common/layout/openoffice.org_gulls.otp \
	templates/common/layout/Orange.otp \
	templates/common/layout/perspective-020_1.jpg.otp \
	templates/common/layout/perspective-020_2.jpg.otp \
	templates/common/layout/perspective-020_3.jpg.otp \
	templates/common/layout/perspective-020p_1.jpg.otp \
	templates/common/layout/perspective-020p_2.jpg.otp \
	templates/common/layout/perspective-020p_3.jpg.otp \
	templates/common/layout/perspective-020t_1.jpg.otp \
	templates/common/layout/perspective-020t_2.jpg.otp \
	templates/common/layout/perspective-020t_3.jpg.otp \
	templates/common/layout/perspective-023_1.jpg.otp \
	templates/common/layout/perspective-023_2.jpg.otp \
	templates/common/layout/perspective-023_3.jpg.otp \
	templates/common/layout/perspective-023p_1.jpg.otp \
	templates/common/layout/perspective-023p_2.jpg.otp \
	templates/common/layout/perspective-023p_3.jpg.otp \
	templates/common/layout/perspective-023t_1.jpg.otp \
	templates/common/layout/perspective-023t_2.jpg.otp \
	templates/common/layout/perspective-023t_3.jpg.otp \
	templates/common/layout/perspective-038_1.jpg.otp \
	templates/common/layout/perspective-038_2.jpg.otp \
	templates/common/layout/perspective-038_3.jpg.otp \
	templates/common/layout/perspective-038p_1.jpg.otp \
	templates/common/layout/perspective-038p_2.jpg.otp \
	templates/common/layout/perspective-038p_3.jpg.otp \
	templates/common/layout/perspective-038t_1.jpg.otp \
	templates/common/layout/perspective-038t_2.jpg.otp \
	templates/common/layout/perspective-038t_3.jpg.otp \
	templates/common/layout/perspective-059_1.jpg.otp \
	templates/common/layout/perspective-059_2.jpg.otp \
	templates/common/layout/perspective-059_3.jpg.otp \
	templates/common/layout/perspective-059p_1.jpg.otp \
	templates/common/layout/perspective-059p_2.jpg.otp \
	templates/common/layout/perspective-059p_3.jpg.otp \
	templates/common/layout/perspective-059t_1.jpg.otp \
	templates/common/layout/perspective-059t_2.jpg.otp \
	templates/common/layout/perspective-059t_3.jpg.otp \
	templates/common/layout/perspective-060_1.jpg.otp \
	templates/common/layout/perspective-060_2.jpg.otp \
	templates/common/layout/perspective-060_3.jpg.otp \
	templates/common/layout/perspective-060p_1.jpg.otp \
	templates/common/layout/perspective-060p_2.jpg.otp \
	templates/common/layout/perspective-060p_3.jpg.otp \
	templates/common/layout/perspective-060t_1.jpg.otp \
	templates/common/layout/perspective-060t_2.jpg.otp \
	templates/common/layout/perspective-060t_3.jpg.otp \
	templates/common/layout/perspective-091_1.jpg.otp \
	templates/common/layout/perspective-091_2.jpg.otp \
	templates/common/layout/perspective-091_3.jpg.otp \
	templates/common/layout/perspective-091p_1.jpg.otp \
	templates/common/layout/perspective-091p_2.jpg.otp \
	templates/common/layout/perspective-091p_3.jpg.otp \
	templates/common/layout/perspective-091t_1.jpg.otp \
	templates/common/layout/perspective-091t_2.jpg.otp \
	templates/common/layout/perspective-091t_3.jpg.otp \
	templates/common/layout/perspective-100_1.jpg.otp \
	templates/common/layout/perspective-100_2.jpg.otp \
	templates/common/layout/perspective-100_3.jpg.otp \
	templates/common/layout/perspective-100p_1.jpg.otp \
	templates/common/layout/perspective-100p_2.jpg.otp \
	templates/common/layout/perspective-100p_3.jpg.otp \
	templates/common/layout/perspective-100t_1.jpg.otp \
	templates/common/layout/perspective-100t_2.jpg.otp \
	templates/common/layout/perspective-100t_3.jpg.otp \
	templates/common/layout/perspective-105_1.jpg.otp \
	templates/common/layout/perspective-105_2.jpg.otp \
	templates/common/layout/perspective-105_3.jpg.otp \
	templates/common/layout/perspective-105p_1.jpg.otp \
	templates/common/layout/perspective-105p_2.jpg.otp \
	templates/common/layout/perspective-105p_3.jpg.otp \
	templates/common/layout/perspective-105t_1.jpg.otp \
	templates/common/layout/perspective-105t_2.jpg.otp \
	templates/common/layout/perspective-105t_3.jpg.otp \
	templates/common/layout/perspective-115_1.jpg.otp \
	templates/common/layout/perspective-115_2.jpg.otp \
	templates/common/layout/perspective-115_3.jpg.otp \
	templates/common/layout/perspective-115p_1.jpg.otp \
	templates/common/layout/perspective-115p_2.jpg.otp \
	templates/common/layout/perspective-115p_3.jpg.otp \
	templates/common/layout/perspective-115t_1.jpg.otp \
	templates/common/layout/perspective-115t_2.jpg.otp \
	templates/common/layout/perspective-115t_3.jpg.otp \
	templates/common/layout/perspective-128_1.jpg.otp \
	templates/common/layout/perspective-128_2.jpg.otp \
	templates/common/layout/perspective-128_3.jpg.otp \
	templates/common/layout/perspective-128p_1.jpg.otp \
	templates/common/layout/perspective-128p_2.jpg.otp \
	templates/common/layout/perspective-128p_3.jpg.otp \
	templates/common/layout/perspective-128t_1.jpg.otp \
	templates/common/layout/perspective-128t_2.jpg.otp \
	templates/common/layout/perspective-128t_3.jpg.otp \
	templates/common/layout/perspective-167_1.jpg.otp \
	templates/common/layout/perspective-167_2.jpg.otp \
	templates/common/layout/perspective-167_3.jpg.otp \
	templates/common/layout/perspective-167p_1.jpg.otp \
	templates/common/layout/perspective-167p_2.jpg.otp \
	templates/common/layout/perspective-167p_3.jpg.otp \
	templates/common/layout/perspective-167t_1.jpg.otp \
	templates/common/layout/perspective-167t_2.jpg.otp \
	templates/common/layout/perspective-167t_3.jpg.otp \
	templates/common/layout/perspective-172_1.jpg.otp \
	templates/common/layout/perspective-172_2.jpg.otp \
	templates/common/layout/perspective-172_3.jpg.otp \
	templates/common/layout/perspective-172p_1.jpg.otp \
	templates/common/layout/perspective-172p_2.jpg.otp \
	templates/common/layout/perspective-172p_3.jpg.otp \
	templates/common/layout/perspective-172t_1.jpg.otp \
	templates/common/layout/perspective-172t_2.jpg.otp \
	templates/common/layout/perspective-172t_3.jpg.otp \
	templates/common/layout/perspective-186_1.jpg.otp \
	templates/common/layout/perspective-186_2.jpg.otp \
	templates/common/layout/perspective-186_3.jpg.otp \
	templates/common/layout/perspective-186p_1.jpg.otp \
	templates/common/layout/perspective-186p_2.jpg.otp \
	templates/common/layout/perspective-186p_3.jpg.otp \
	templates/common/layout/perspective-186t_1.jpg.otp \
	templates/common/layout/perspective-186t_2.jpg.otp \
	templates/common/layout/perspective-186t_3.jpg.otp \
	templates/common/layout/PhotoFrame.otp \
	templates/common/layout/Plantillafiesta.otp \
	templates/common/layout/Praesentation_Radial_Blau.otp \
	templates/common/layout/Praesentation_Radial_Braun.otp \
	templates/common/layout/Praesentation_Radial_Grau.otp \
	templates/common/layout/Praesentation_Radial_Gruen.otp \
	templates/common/layout/Praesentation_Radial_Magenta.otp \
	templates/common/layout/Praesentation_Radial_Orange.otp \
	templates/common/layout/Praesentation_Radial_Rot.otp \
	templates/common/layout/Praesentation_Radial_SUN.otp \
	templates/common/layout/Praesentation_Radial_Tuerkis.otp \
	templates/common/layout/QuadratischBlau.otp \
	templates/common/layout/QuadratischBraun.otp \
	templates/common/layout/QuadratischGrau.otp \
	templates/common/layout/QuadratischGruen.otp \
	templates/common/layout/QuadratischMagenta.otp \
	templates/common/layout/QuadratischOrange.otp \
	templates/common/layout/QuadratischRot.otp \
	templates/common/layout/QuadratischSUN.otp \
	templates/common/layout/RedStar.otp \
	templates/common/layout/reo-veo10.otp \
	templates/common/layout/reo-veo11.otp \
	templates/common/layout/reo-veo12.otp \
	templates/common/layout/reo-veo1.otp \
	templates/common/layout/reo-veo2.otp \
	templates/common/layout/reo-veo3.otp \
	templates/common/layout/reo-veo4.otp \
	templates/common/layout/reo-veo5.otp \
	templates/common/layout/reo-veo6.otp \
	templates/common/layout/reo-veo7.otp \
	templates/common/layout/reo-veo8.otp \
	templates/common/layout/reo-veo9.otp \
	templates/common/layout/schatten_blau.otp \
	templates/common/layout/schatten_gelb.otp \
	templates/common/layout/schatten_gruen.otp \
	templates/common/layout/schatten_magenta.otp \
	templates/common/layout/schatten_orange.otp \
	templates/common/layout/schatten_rot.otp \
	templates/common/layout/schatten_tuerkis.otp \
	templates/common/layout/science-002a.jpg.otp \
	templates/common/layout/science-002b.jpg.otp \
	templates/common/layout/science-014a.jpg.otp \
	templates/common/layout/science-014b.jpg.otp \
	templates/common/layout/science-014c.jpg.otp \
	templates/common/layout/science-014d.jpg.otp \
	templates/common/layout/science-108a.jpg.otp \
	templates/common/layout/science-108b.jpg.otp \
	templates/common/layout/science-108c.jpg.otp \
	templates/common/layout/science-108d.jpg.otp \
	templates/common/layout/sedi.otp \
	templates/common/layout/Sidepanel_Blue.otp \
	templates/common/layout/Sidepanel_Cloud.otp \
	templates/common/layout/Sidepanel_Green.otp \
	templates/common/layout/Sidepanel_Red.otp \
	templates/common/layout/Solar.otp \
	templates/common/layout/Soleil.otp \
	templates/common/layout/standard-blau-gelb.otp \
	templates/common/layout/standard-dunkel.otp \
	templates/common/layout/standard-rot-gruen.otp \
	templates/common/layout/Sunburst.otp \
	templates/common/layout/sun.otp \
	templates/common/layout/texture-003_1.jpg.otp \
	templates/common/layout/texture-003_2.jpg.otp \
	templates/common/layout/texture-003_3.jpg.otp \
	templates/common/layout/texture-003p_1.jpg.otp \
	templates/common/layout/texture-003p_2.jpg.otp \
	templates/common/layout/texture-003p_3.jpg.otp \
	templates/common/layout/texture-003t_1.jpg.otp \
	templates/common/layout/texture-003t_2.jpg.otp \
	templates/common/layout/texture-003t_3.jpg.otp \
	templates/common/layout/texture-004_1.jpg.otp \
	templates/common/layout/texture-004_2.jpg.otp \
	templates/common/layout/texture-004_3.jpg.otp \
	templates/common/layout/texture-004p_1.jpg.otp \
	templates/common/layout/texture-004p_2.jpg.otp \
	templates/common/layout/texture-004p_3.jpg.otp \
	templates/common/layout/texture-004t_1.jpg.otp \
	templates/common/layout/texture-004t_2.jpg.otp \
	templates/common/layout/texture-004t_3.jpg.otp \
	templates/common/layout/texture-007_1.jpg.otp \
	templates/common/layout/texture-007_2.jpg.otp \
	templates/common/layout/texture-007_3.jpg.otp \
	templates/common/layout/texture-007p_1.jpg.otp \
	templates/common/layout/texture-007p_2.jpg.otp \
	templates/common/layout/texture-007p_3.jpg.otp \
	templates/common/layout/texture-007t_1.jpg.otp \
	templates/common/layout/texture-007t_2.jpg.otp \
	templates/common/layout/texture-007t_3.jpg.otp \
	templates/common/layout/texture-045_1.jpg.otp \
	templates/common/layout/texture-045_2.jpg.otp \
	templates/common/layout/texture-045_3.jpg.otp \
	templates/common/layout/texture-045p_1.jpg.otp \
	templates/common/layout/texture-045p_2.jpg.otp \
	templates/common/layout/texture-045p_3.jpg.otp \
	templates/common/layout/texture-045t_1.jpg.otp \
	templates/common/layout/texture-045t_2.jpg.otp \
	templates/common/layout/texture-045t_3.jpg.otp \
	templates/common/layout/texture-110_1.jpg.otp \
	templates/common/layout/texture-110_2.jpg.otp \
	templates/common/layout/texture-110_3.jpg.otp \
	templates/common/layout/texture-110p_1.jpg.otp \
	templates/common/layout/texture-110p_2.jpg.otp \
	templates/common/layout/texture-110p_3.jpg.otp \
	templates/common/layout/texture-110t_1.jpg.otp \
	templates/common/layout/texture-110t_2.jpg.otp \
	templates/common/layout/texture-110t_3.jpg.otp \
	templates/common/layout/texture-158_1.jpg.otp \
	templates/common/layout/texture-158_2.jpg.otp \
	templates/common/layout/texture-158_3.jpg.otp \
	templates/common/layout/texture-158p_1.jpg.otp \
	templates/common/layout/texture-158p_2.jpg.otp \
	templates/common/layout/texture-158p_3.jpg.otp \
	templates/common/layout/texture-158t_1.jpg.otp \
	templates/common/layout/texture-158t_2.jpg.otp \
	templates/common/layout/texture-158t_3.jpg.otp \
	templates/common/layout/texture-191_1.jpg.otp \
	templates/common/layout/texture-191_2.jpg.otp \
	templates/common/layout/texture-191_3.jpg.otp \
	templates/common/layout/texture-191p_1.jpg.otp \
	templates/common/layout/texture-191p_2.jpg.otp \
	templates/common/layout/texture-191p_3.jpg.otp \
	templates/common/layout/texture-191t_1.jpg.otp \
	templates/common/layout/texture-191t_2.jpg.otp \
	templates/common/layout/texture-191t_3.jpg.otp \
	templates/common/layout/vortrag_gelb.otp \
	templates/common/layout/vortrag_gruen.otp \
	templates/common/layout/vortrag_rot.otp \
	templates/common/layout/vortrag_schwarz.otp \
	templates/common/layout/vortrag_weiss.otp \
	templates/common/layout/Worldwide_-_Artisticblue.otp \
	templates/common/layout/Worldwide_-_ArtisticbluePencil.otp \
	templates/common/layout/Worldwide_-_Deluxegreen.otp \
	templates/common/layout/Worldwide_-_Lightgray.otp \
))

# vim: set noet sw=4 ts=4:
