# This is a basic workflow to test building for android in a linux environment.

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Android NDK
        uses: android-actions/setup-ndk@v2 # Or amyu/setup-android@v4 for SDK and NDK
        with:
          ndk-version: '25.2.9519653' # Specify your desired NDK version

      # Start LibreOffice Build
      - name: Announce staret of build
        run: echo Start Build for LibreOffice Binaries (Android)

      # Runs a single command using the runners shell
      - name: Create setup file for build
        run: echo "--with-distro=LibreOfficeAndroid\n--with-android-sdk=$HOME/Android/Sdk\n--with-android-ndk=$HOME/Android/Sdk/ndk/27.2.12479018\n" >> autogen.input

      # Runs a single command using the runners shell
      - name: Execute Make Script
        run: |
          #Execute run scripts
          ./autogen
          make


      #- name: Build Android NDK project
      #  run: |
      #    # Example native build
      #    ./gradlew build


