name: Run command in Docker and save artifact

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-libreoffice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build libreoffice-core in container
        run: |
          docker compose -f compose.yml up --build
          ls -lah ./build

      - name: save libreoffice as artifact
        uses: actions/upload-artifact@v4
        with:
          name: libreoffice-build
          path: ./build